### ISSUE TITLE
(M2C) perf of moab to catalog existence check

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#101]
Do another round of more realistic perf testing with real db updates generated by real storage root traversal

IFF this indicates performance issues, we may want to profile and split out db perf from storage root traversal perf.

Acceptable performance:  we want to be able to traverse a storage root on the order of 2-6 hours (so we can traverse all of them in 24 hours, using parallelization if needed)

**Comment by SaravShah** [comment]
I, [2017-10-10T18:10:57.560078 #22802]  INFO -- : It took 11780.047041534912 seconds to check the database w/ online moab s12 update

**Comment by ndushay** [comment]
thanks for putting the info. in https://github.com/sul-dlss/preservation_core_catalog/wiki/Stats.   I think perf is currently seeming acceptable.
