### ISSUE TITLE
ZippedMoabVersion#preserved_object association has useless `dependent` option

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1014]
https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_one
> Note that :dependent option is ignored when using :through option.

IIRC, i added that flag because rubocop complains if you specify a `has_one` without a `dependent` option.  if that's not actually the case, and rubocop didn't complain, we should just get rid of that option on that association.  otherwise, maybe we should make a rubocop exception?

but this is basically a small bit of harmless clutter as is.

**Comment by SaravShah** [comment]
are you pretty much saying, when the associated object (PreservedObject) is destroyed, we dont want an exception to be raised?

**Comment by jmartin-sul** [comment]
vice versa:  i think the intent is that the `:dependent` option would prevent cascading deletion of the associated `PreservedObject` for a destroyed `ZMV`.  but since that relationship is a `has_one ... through:`, the `:dependent` option is ignored according to the rails docs, and the default behavior is that this sort of deletion will not cascade over to the relationship that's a level out (`PreservedObject` being related to `ZippedMoabVersion` by way of `CompleteMoab`).
