### ISSUE TITLE
(R) tag v1.0.0, deploy to stage and prod, monitor to make sure auto-replication is working

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1021]
now that #1018 is merged, auto-replication should be code complete and ready for testing.

- [x] cut v 1.0.0 (this feels like a significant enough change to warrant a major version bump, and implements what was the last big missing chunk of functionality for this work cycle.  if it needs to be rationalized as a breaking change, i'd say it breaks the expectation that we won't automatically be shipping stuff to the cloud =) )
- [x] deploy to stage
  - [x] confirm that newly accessioned and versioned moabs are being replicated on stage
- [x] deploy to prod
  - [x] confirm that newly accessioned and versioned moabs are being replicated on prod

**Comment by jmartin-sul** [comment]
latest release as of this comment is v0.12.0:
https://github.com/sul-dlss/preservation_catalog/compare/v0.12.0...master

**Comment by SaravShah** [comment]
~ ⚡  aws s3 ls s3://sul-sdr-aws-us-west-2-archive/mj/017/zz/7129/mj017zz7129.v0001.zip
2018-07-26 16:36:34  191645352 mj017zz7129.v0001.zip
