### ISSUE TITLE
(R) implement cache expiry in zip transfers volume

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1032]
can be a simple script, e.g. rake task or bash script.

schedule using `whenever` gem from pres cat?

**Comment by atz** [comment]
Can be a rails runner also.  Behavior should be to check the `.zip` file, but purge all related files (`.z02`, `.z03`, `.z02.md5`, etc.) on expiry.

**Comment by atz** [comment]
Documented how to use `find -exec` to do this:
https://github.com/sul-dlss/preservation_catalog/wiki/Zip-Storage-Cache-Cleaning
