### ISSUE TITLE
Deadlock issue in workers

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#1037]
Apparently stuck resque workers was a known issue of conflict w/ newrelic between 8 years ago and 2017, at least:
https://github.com/resque/resque/issues/180
https://github.com/resque/resque/issues/1101

We still have newrelic in our build, but I don’t think we are actually using it?

I attempted to debug a stalled thread (22840) as those issues advise, using the new relic debugger `nrdebug`, but we don't seem to have the required dependencies on production:
```
nrdebug 22840
Could not find gdb, please ensure it is installed and in your PATH
```

Recommend we remove newrelic unless actively needed right now.

**Comment by julianmorley** [comment]
+1 on removing newrelic until we actually need it

**Comment by atz** [comment]
Yeah, if this resolves our hung workers, and we come back around to wanting newrelic again, we would want to be more judicious about where it was included/enabled (i.e. not where workers are).
