### ISSUE TITLE
make MoabValidationHandler more understandable: refactor, or unit tests

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#1058]
Module is not tested directly.  

Because it has such strong expectations about variable names and other characteristics of its "includers", it probably should be converted to a superclass rather than stay a module mix-in.

But in any case, it should be tested.

**Comment by jmartin-sul** [comment]
i think we want to leave this tech debt ticket open, but an alternative approach to testing the module might be to get out of using a mixin, and to turn the module into e.g. a regular class that other classes inherit from, or a utility class that's called by other classes, or something.

**Comment by jmartin-sul** [comment]
closing, as `MoabValidationHandler` has been refactored, and is no longer with us
