### ISSUE TITLE
Document design decisions and potential pitfalls/complexities

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#1063]
Including:
### Zip
- We use system `zip` binary: why?
  - Discuss threat model of `zip` changing underneath application
- We segment zips into `~10BGB` chunks: why?
- Tracking of part counts and metadata related to parts: what for?
- We don't intend to "update" previously uploaded files
- Our future selves should strongly consider deleting and reposting ALL parts for a zip if they ever have to replace just one, since we would be creating (e.g.) all 52 parts just to get the 13th anyway.  And the ability to reconstitute the whole is dependent on the parts being exactly of the same cohort.  

### TODO: Retrieval
- Glacier-shifted objects will not be retrievable via regular `S3` calls.  Instead an additional dependency, `aws-sdk-glacier`, will be required.  Only the metadata can be retrieved from S3 in realtime.

### BLOCKED: Deletion
- The application's credentials do not even have access to delete objects, by design.  

### ???

**Comment by julianmorley** [comment]
I don't think we need the aws-sdk-glacier SDK - an object can be called back from Glacier via regular S3 calls (transition storage). The Ruby SDK documents this here: https://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html#restore_object-instance_method

**Comment by atz** [comment]
Added multiple wiki pages.
- https://github.com/sul-dlss/preservation_catalog/wiki/Zip-Creation
- https://github.com/sul-dlss/preservation_catalog/wiki/S3-Deletions,-Updates

And notes on others that cover all enumerated points.
