### ISSUE TITLE
(PC) ReST call for preserved_object/_copy CREATE methods

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#109]
no yet clear if online Moab vs. archived object is an argument or a rest endpoint, as args may be slightly different.

See

https://docs.google.com/document/d/1_ejJE0Ve1gEezQWFnqJAsl1FI4rpREW9lSL0ZSbD62U

**Comment by jmartin-sul** [comment]
would be used by both on VM inventory and by REST.

see #113
