### ISSUE TITLE
Completed zips not being consistently uploaded / passed to S3 Delivery workers

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1096]
I've had several zips that are correctly made in /sdr-transfers but then apparently don't get handed off to S3 Delivery, resulting in a failed upload.
Examples:
```
 fm813sn1247 version 4 
ny636zx6277 version 5
td620dk8078 version 2
kf921gd3855 version 4
```
Already has a ZMV record, zipmaker successfully makes a zip and md5, but it never shows up in the S3 Delivery queue. /sdr-transfer cleanup is currently disabled, so it didn't have any files deleted out from underneath it.

**How can we catch these failures?**  and **how can we remediate them?** One of these (kf921gd3855) is really big (1.7TB) so re-processing zipmaker is less than ideal.

Of other concern; I had 47 of these errors on a recent batch of 827 druid-version uploads. That's a really high failure rate, and if that's been common across all the uploads it would explain why when I was 'done' I found tens of thousands of druid-versions missing from the S3 bucket.

**Comment by julianmorley** [comment]
I *think* this is caused by either the Robots workflow or M2C not correctly detecting a new or updated version of a druid. I'm not sure if it's happening all the time, or just some of the time (which would be worse).

**Comment by jmartin-sul** [comment]
update from robots or workflow getting dropped seems less bad than M2C not correctly detecting changes and missed updates, since the former is expected, and the latter is designed in part as protection against that.

regardless, let's see how things are looking after #1097 has been in prod for a bit, and after we've looked into #1095 and #1094 a bit more.

**Comment by jmartin-sul** [comment]
@julianmorley, scopes you might also enjoy:
```ruby
CompleteMoab.by_druid(druid) # same as the join you're doing, but canned query that's a little more terse because it's commonly used
```

https://github.com/sul-dlss/preservation_catalog/blob/122a10466c42886baa060f6ccd0f4cdbc7820e2b/app/models/complete_moab.rb#L29-L31

**Comment by jmartin-sul** [comment]
i suspect that the incidents where there was no catalog entry (no `preserved_objects` or `complete_moabs` rows) were related to #1094.

i suspect that instances where there were ZMVs and zips on disk are a different issue (and are the scope of this ticket).

do we have examples like that besides `kf921gd3855`?  what state is that one in ATM?

**Comment by SaravShah** [comment]
```
[15] pry(main)> CompleteMoab.by_druid("kf921gd3855")
=> [#<CompleteMoab:0x0000000005d4c560
  id: 1415217,
  version: 5,
  preserved_object_id: 1415209,
  moab_storage_root_id: 14,
  created_at: Wed, 05 Sep 2018 02:39:49 UTC +00:00,
  updated_at: Thu, 04 Oct 2018 22:48:47 UTC +00:00,
  last_moab_validation: Tue, 18 Sep 2018 20:04:16 UTC +00:00,
  last_checksum_validation: Wed, 05 Sep 2018 02:39:50 UTC +00:00,
  size: 108335,
  status: "ok",
  last_version_audit: Tue, 02 Oct 2018 20:28:19 UTC +00:00,
  last_archive_audit: nil>]
[16] pry(main)> CompleteMoab.by_druid("kf921gd3855").first.zipped_moab_versions
=> [#<ZippedMoabVersion:0x0000000005dc2440 id: 8201979, version: 5, complete_moab_id: 1415217, zip_endpoint_id: 1, created_at: Thu, 04 Oct 2018 22:48:47 UTC +00:00, updated_at: Thu, 04 Oct 2018 22:48:47 UTC +00:00>,
 #<ZippedMoabVersion:0x0000000005dc2260 id: 8201977, version: 4, complete_moab_id: 1415217, zip_endpoint_id: 1, created_at: Thu, 04 Oct 2018 22:41:53 UTC +00:00, updated_at: Thu, 04 Oct 2018 22:41:53 UTC +00:00>,
 #<ZippedMoabVersion:0x0000000005dc2080 id: 8099326, version: 3, complete_moab_id: 1415217, zip_endpoint_id: 1, created_at: Tue, 18 Sep 2018 20:04:16 UTC +00:00, updated_at: Tue, 18 Sep 2018 20:04:16 UTC +00:00>,
 #<ZippedMoabVersion:0x0000000005dc1ea0 id: 8099318, version: 2, complete_moab_id: 1415217, zip_endpoint_id: 1, created_at: Tue, 18 Sep 2018 20:04:16 UTC +00:00, updated_at: Tue, 18 Sep 2018 20:04:16 UTC +00:00>,
 #<ZippedMoabVersion:0x0000000005dc1cc0 id: 7859483, version: 1, complete_moab_id: 1415217, zip_endpoint_id: 1, created_at: Wed, 05 Sep 2018 02:39:49 UTC +00:00, updated_at: Wed, 05 Sep 2018 02:39:49 UTC +00:00>]
[17] pry(main)> 
```

**Comment by SaravShah** [comment]
Probably an just keep an eye on honeybadger and audit results errors for now.

**Comment by jmartin-sul** [comment]
for `kf921gd3855`, the really big version (0004) also had the zip parts i'd have expected when i glanced at it, and all appeared to be ok:
```ruby
[10] pry(main)> ZippedMoabVersion.by_druid('kf921gd3855').find_by(version: 4).zip_parts.group(:status).count
=> {"ok"=>189}
```
