### ISSUE TITLE
identify any uploaded data that is incorrect, remediate if needed

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1098]
it seems the issue fixed by #1097 only manifests itself in the audit code.  if it doesn't cause replication problems, there's nothing on S3 to remediate.

we'll wait for the seemingly fixed audit check to hit everything in the catalog, and we'll investigate any errors it finds.  we can also spot check some objects that seemed to be in a bad state in our cloud archive (see #1095).

see also #1088

~~we are inclined to delete everything where the complete moab has more than one version (or maybe just everything), and then re-replicate it all.~~

~~the thinking is that it would take a lot of work to figure out how to remediate all the bad metadata on all the content we've pushed, and that it'd be cheaper and more confidence inspiring to just re-push everything using the fixed machinery.  we can discuss in person and make more of a case for that if others disagree.~~

**Comment by atz** [comment]
After review and debugging, it now seems possible that no uploaded data is incorrect.  So I would close this ticket or repurpose like "identify any uploaded data that is incorrect".
