### ISSUE TITLE
deploy zp_s3key_correct_version and replicate a few objects

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#1099]
replicate objects that have current_version > 1 and make sure the s3 zip parts have the correct name

connects #1088

**Comment by jmartin-sul** [comment]
we should do a number of small multi-version objects to make sure all is well on that front, and we should also do some large objects that will be split into multi-part zips, to make sure that works as expected.

**Comment by SaravShah** [comment]
yup - closing
