### ISSUE TITLE
test recovery from preservation

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1103]
i don't think we've actually done this yet?  but this is an important end-to-end test, and should not be too difficult (though likely a little time-consuming).

- [ ] identify some test objects for recovery.  worthwhile categories i can think of are:
  - [ ] single version object
  - [ ] multi-version object
  - [ ] large multi-version object where at least one version is a multi-part zip

the things to do when testing for a given object are:
* identify the object to reconstitute
* retrieve the corresponding zip files for all versions of the object from the production cloud archive.
* confirm that unzipping the content is successful, and that checksum validation passes on the reconstituted objects.

this is just an initial manual version of what will hopefully become the automated spot check described in #1076.

**Comment by julianmorley** [comment]
I'd add an intermediate step of 'check downloaded zip part MD5 against stored MD5 value'

**Comment by jmartin-sul** [comment]
here's a bit of example console scripting to find a random druid between a given upper and lower size bound:
```ruby
[1] pry(main)> lower_size = 0
=> 0
[2] pry(main)> upper_size = 10000000000 # ~ 10 GB
=> 10000000000
[9] pry(main)> 
[10] pry(main)> total_count = CompleteMoab.where(size: (lower_size..upper_size)).count
=> 1312940
[11] pry(main)> random_cm_index = Random.rand(total_count)
=> 703323
[12] pry(main)> cm = CompleteMoab.where(size: (lower_size..upper_size)).offset(random_cm_index).limit(1).first
=> #<CompleteMoab:0x0000000006e30570
 id: 705363,
 version: 5,
 preserved_object_id: 705363,
 moab_storage_root_id: 6,
 created_at: Mon, 22 Jan 2018 04:39:35 UTC +00:00,
 updated_at: Sat, 13 Oct 2018 06:46:50 UTC +00:00,
 last_moab_validation: Thu, 09 Aug 2018 08:42:25 UTC +00:00,
 last_checksum_validation: Thu, 09 Aug 2018 08:42:25 UTC +00:00,
 size: 21375851,
 status: "ok",
 last_version_audit: Sat, 13 Oct 2018 06:46:50 UTC +00:00,
 last_archive_audit: nil>
[13] pry(main)> cm.preserved_object.druid
=> "vq236kj2965"
[14] pry(main)> 
[15] pry(main)> 
[16] pry(main)> 
[17] pry(main)> lower_size = 10000000000
=> 10000000000
[18] pry(main)> upper_size = 50000000000
=> 50000000000
[19] pry(main)> total_count = CompleteMoab.where(size: (lower_size..upper_size)).count
=> 4097
[20] pry(main)> random_cm_index = Random.rand(total_count)
=> 758
[21] pry(main)> cm = CompleteMoab.where(size: (lower_size..upper_size)).offset(random_cm_index).limit(1).first
=> #<CompleteMoab:0x0000000007098588
 id: 441646,
 version: 4,
 preserved_object_id: 441646,
 moab_storage_root_id: 4,
 created_at: Sun, 21 Jan 2018 03:38:13 UTC +00:00,
 updated_at: Sat, 13 Oct 2018 03:04:15 UTC +00:00,
 last_moab_validation: Tue, 07 Aug 2018 19:19:40 UTC +00:00,
 last_checksum_validation: Tue, 07 Aug 2018 19:19:39 UTC +00:00,
 size: 11619221710,
 status: "ok",
 last_version_audit: Sat, 13 Oct 2018 03:04:15 UTC +00:00,
 last_archive_audit: nil>
[22] pry(main)> cm.preserved_object.druid
=> "md506kt8712"
[23] pry(main)> 
```

**Comment by jmartin-sul** [comment]
@julianmorley will find a bunch of random druids that he'd like to spot check (using the above script).  he'll pull them down and attempt to reconstitute the archive zips into an exploded moab.  he'll also compare the checksums we have for the zip parts in the catalog against the checksums of the retrieved zip files.

in the meantime, i'll see if i can get a slightly modified version of `ChecksumValidator` to give us the sort of checksum validation pres cat does (not provided out the box by MoabVersioning gem), but on a random directory for a moab that's not in the catalog.  if that works out, julian can use that to do validation using the internal signature catalog etc contained in the moab.

**Comment by jmartin-sul** [comment]
can this be closed?  we think we've done this as initial manual smoke testing?  is there a process to be documented?

see also the automated audit version of this: #1076

**Comment by edsu** [comment]
Was the idea on this to routinely do some kind of automated spot checking?

**Comment by jmartin-sul** [comment]
> Was the idea on this to routinely do some kind of automated spot checking?

giving this a quick re-read, i think automated spot checking is what #1076 was filed for, and this one was just about some initial manual testing right after the work cycle ended.

**Comment by edsu** [comment]
+1 for closing then
