### ISSUE TITLE
Managing preservation audit errors in Argo/workflow grid

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/preservation_catalog#1110]
We currently have over 200K objects showing an error state in Argo: https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=preservationAuditWF%3Apreservation-audit%3Aerror

This is causing user confusion.

Need to know:
* are these "real" errors
* if "real" how to clear/reset/rerun
* if "not real" how to clear

From there, I can handle messaging to users beyond "please ignore".

**Comment by ndushay** [comment]
See also #1249

**Comment by ndushay** [comment]
I'm closing this as we are addressing existing pres audit errors now via #1324 and #1325, etc.
