### ISSUE TITLE
scheduled checksum validation should call a method that exists

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1116]
currently, the schedule.rb used by whenever has:

```
every :sunday, at: '1am', roles: [:queue_populator] do
  set :output, standard: nil, error: 'log/cv-err.log'
  runner 'Audit::Checksum.validate_disk_all_storage_roots'
end
```

unfortunately, `Audit::Checksum.validate_disk_all_storage_roots` is not a method that exists in our codebase anymore.

luckily, things are getting CVed at the moment, because there's a hook on `CompleteMoab` that triggers it if the object is updated and status goes to `unknown`:
```
after_save :validate_checksums!, if: proc { |cm| cm.saved_change_to_status? && cm.validity_unknown? }
```

we could just switch the whenever task to be something like:
```
every :sunday, at: '1am', roles: [:queue_populator] do
  set :output, standard: nil, error: 'log/cv-err.log'
  runner 'CompleteMoab.fixity_check_expired.find_each(&:validate_checksums!)'
end
```

similar to the way that we now schedule other audits (M2C, C2M, C2A).

**Comment by atz** [comment]
That's a lot of description for a one-line diff!
