### ISSUE TITLE
resque-pool fails to restart cleanly on deploy

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#1122]
Example:
```
[pres@preservation-catalog-prod-02 ~]$ ps -ef |grep resque-pool-master
pres      1394     1  0 Oct09 ?        00:02:53 resque-pool-master[20181009223444]: managing [22657, 22697, 22932, 22965, 23032, 23041, 22652, 22689, 23057, 23066, 23084, 23201]                                                                                                                                                              
pres      6320     1  0 16:20 ?        00:00:04 resque-pool-master[20181016231916]: managing [6752, 6755, 6758, 6762, 6766, 6775, 6780, 6787, 6796, 6818, 6827, 6831, 6835, 6838, 6842, 6852, 6857, 6863, 6867, 6870, 6875, 6885, 6913, 6922, 6929, 6949, 6956, 6959, 6968, 6973, 6976, 6986, 6991, 6999, 7004, 7024, 7029, 7034, 7042, 7053, 7055, 7068, 7074, 7079, 7082]
pres      6419     1  0 16:20 ?        00:00:04 resque-pool-master[20181016231916]: managing [7112, 7115, 7118, 7123, 7127, 7131]     
```

Two of those processes belong there (one for West, one for general workers), the other does not (the one that is a week old from `Oct09`).  

In `capistrano-resque-pool.rake`, the task `resque:pool:stop` is supposed to handle the shutdown.  But because no pid file references `1394` anymore, it cannot target it.  It can only hit what the pid files reference.

It is possible that the capistrano integration is OK, but the "extra" resque pools are from manually starting `rake resque:work` on the command line, or by manually deleting a PID file.  Both are to be avoided.

**Comment by atz** [comment]
We could add `monit` or other system level tools to detect this, but this problem is better addressed by not leaving unwanted processes running than by monitoring.

**Comment by atz** [comment]
See: #1120

**Comment by tallenaz** [comment]
I looked into `resque-pool`'s `hot-swap` option, which works great when there is only one pool of workers, and would be a good option for projects like `common-accessioning`, where there is only ever a single pool. But on worker nodes with > 1 pool, (prescat worker nodes for multiple cloud endpoints, for example) the hot swap does not know to preserve adjacent pools.

**Comment by jmartin-sul** [comment]
### post standup discussion today

#### we have this issue because we can't use resque pool hotswap with preservation.  we can't use resque pool hotswap with preservation because:
1. resque pool hotswap expects only one instance of resque pool on the box.  if there is more than one, it'll kill all pools, and then will only reload one of them.
2. we have multiple pools on each of our 3 worker VMs.  this is because the pools do the work of talking to our S3 endpoints, and the AWS S3 SDK, at least as we use it, determines which endpoint to talk to by looking at environment variables.  thus, we provision our S3 credentials by passing env vars to the resque pools that we start.  each worker VM has one resque pool for general use (no S3 credentials, e.g. checksum audit, zipmaking, etc).  each worker VM also has one resque pool for each of the three S3 endpoints we use (thus, each worker VM runs four instances of resque pool in total).

#### possible solutions
1. explore using the S3 SDK in such a way that we can provision credentials via parameters (from shared_cofigs) when instantiating the client, instead of via env vars that come from puppet.  this would let us collapse our 4 resque pool instances to 1 on each worker box, since there would no longer be a reason to provide 3 different sets of env vars to resque pool.  then, we could use resque pool hotswap as we do with other applications.
2. figure out what changes resque pool hotswap would need to cope with multiple pools on one VM.  fork the gem, make the changes, PR to push them back upstream.
3. explore splitting our resque pool usage so that we have one box for each S3 endpoint.  this would lead to more worker VMs, which isn't terrible in and of itself, but it'd also pull us farther away from the goal of being able to run all the pres cat workers from one VM, which is likely desirable/necessary for our move towards #1190.

we may start working on option 1, without necessarily expecting to complete and deploy it before winter break (which starts once this week ends).

**Comment by jmartin-sul** [comment]
relevant (abridged and lightly edited for clarity) [slack discussion](https://stanfordlib.slack.com/archives/G6K8R3VBK/p1575917653070600):


> @jcoyne Dec 9th at 10:54
> > @jmartin-sul I'd like to know why we can't just do this;
> > s3 = Aws::S3::Client.new(
> >   access_key_id: 'your_access_key_id',
> >   secret_access_key: 'your_secret_access_key'
> > )
> > 
> @tallenaz  7 days ago
> > Looking back over the code, it looks like we made the choice to use Aws::S3::Resource over Aws::S3::Client but I can’t recall the reason.
> > 
> @julianmorley  7 days ago
> > There was some functionality that wasn’t available with the then-current implementation of S3::Client that we needed.
> > 
> @jmartin-sul  7 days ago
> > ah, that would explain it
> > 
> @julianmorley  7 days ago
> > We started this off with the v2 Ruby API, which was … less smooth … than v3
> > 
> @jmartin-sul  7 days ago
> > any idea whether that functionality we want is there now, and whether we might be able to switch over?  if so, this might be a good thing to ticket and investigate (and maybe fix) during these two weeks.  would want a few days to watch it in prod before winter break if we did make changes, but it sounds like if we could switch, it would make our lives easier on the resque-pool management front (because, i'm assuming from what i've heard, that we could consolidate to one pool per box and then use resque pool hotswap).
> > 
> @julianmorley  7 days ago
> > The new SDR storage architecture precludes going to one pool per box, I’m afraid.
> > 
> @julianmorley  7 days ago
> > 1 box must be able to run all pools.
> > 
> @jmartin-sul  7 days ago
> > currently, each of boxes 02 - 04 runs all pools, correct?  i guess what i'm saying is, if we didn't have to provision credentials via env vars, with one set of AWS creds per pool, couldn't we then consolidate such that there is only one pool per box?
> > these all have the resque role:  https://github.com/sul-dlss/preservation_catalog/blob/master/config/deploy/prod.rb#L4-L6 (edited) 
> > 
> @jmartin-sul  7 days ago
> > currently, i believe we run four pools on each of the 3 VMs that host workers (one general pool for non-cloud stuff, and one pool for each cloud endpoint, with each of those pools managing workers for both delivery and audit).
> > 
> @jmartin-sul  7 days ago
> > it's possible that i'm mis-remembering/mis-understanding our current setup, in which case, corrections welcome
> > 
> @jmartin-sul  7 days ago
> > ah, i'm re-reading, and i see where i used some confusing wording:  what i meant by "because, i'm assuming from what i've heard, that we could consolidate to one pool per box and then use resque pool hotswap" is that we could consolidate what are multiple pools on each box into one pool doing all the same work on each box, not that we'd separate by type of pool so that e.g. all the AWS east workers were on one box, all the IBM on another, etc.  definitely wasn't proposing that.
> > 
> > since the impression i get is that resque pool hotswap works fine if there's one pool on the box, but not if the box hosts multiple pools, which each box does at the moment.

**Comment by jmartin-sul** [comment]
see also #1227

**Comment by mjgiarlo** [comment]
Open questions:

* Do we want to continue running resque-pool on one box in stage and three boxes in prod?
* How many of the different workers do we want running on each box? Here's what we have currently (the result of `cat`ing the region-specific resque-pool configs into the main resque-pool config):
  * ```yaml
c2m: 6
checksum_validation: 6
ibm_us_south_delivery: 6
m2c: 6
moab_replication_audit: 3
part_audit_aws_s3_east_1: 3
part_audit_aws_s3_west_2: 3
part_audit_ibm_us_south: 3
results_recorder: 6
s3_us_east_1_delivery: 6
s3_us_west_2_delivery: 6
zip_endpoint_events: 6
zipmaker: 6
zips_made: 6
```
* Is `zip_endpoints` an appropriate spot in the config to store provider-specific values (region, access key, secret, endpoint URL)? See https://github.com/sul-dlss/shared_configs/pull/1142/files#diff-b2b4310d1a2ee6c5549424c06c2893beR13-R37.

**Comment by mjgiarlo** [comment]
Requirements for this work:

- [ ] Deploy to stage (per order/plan identified in prior comment)
- [ ] Deploy to prod (per order/plan identified in prior comment)
- [ ] Remove unused `preservation_worker` role from puppet (HT: @tallenaz)

**Comment by jmartin-sul** [comment]
@mjgiarlo said:
> Open questions:
> 
>     * Do we want to continue running `resque-pool` on one box in stage and three boxes in prod?
> 

i personally have no opinion on this.  @julianmorley?  but fwiw, not including the redis box, stage has 2 VMs, and prod has 4, and each env runs resque pool on N-1 of its VMs, so there is some consistency in that sense.

>     * Is `zip_endpoints` an appropriate spot in the config to store provider-specific values (region, access key, secret, endpoint URL)? See https://github.com/sul-dlss/shared_configs/pull/1142/files#diff-b2b4310d1a2ee6c5549424c06c2893beR13-R37
> 

that's where i'd put it, i think.

>     * Given that 1) making this change requires coordination between puppet, shared_configs, and prescat, and 2) prescat workers tend to run long and thus complicate deployment, what is a sensible plan for pulling this off in production? (This is the process I'd use/test in stage first.)
> 

_something something something_ after we get back from winter break.

>     * How many of the different workers do we want running on each box? Here's what we have currently (the result of `cat`ing the region-specific `resque-pool` configs into the main `resque-pool` config):
> 
> 
> ```yaml
> c2m: 6
> checksum_validation: 6
> ibm_us_south_delivery: 6
> m2c: 6
> moab_replication_audit: 3
> part_audit_aws_s3_east_1: 3
> part_audit_aws_s3_west_2: 3
> part_audit_ibm_us_south: 3
> results_recorder: 6
> s3_us_east_1_delivery: 6
> s3_us_west_2_delivery: 6
> zip_endpoint_events: 6
> zipmaker: 6
> zips_made: 6
> ```

i have no objection to this config, and can't think of a specific thing i know we should change.  i can imagine maybe having the cloud endpoint audit and delivery workers not be so specifically assigned (e.g. `part_audit_aws_s3_west_2,s3_us_west_2_delivery: 9`), but that's not really a thing i've thought through much, just a random "what if" that's popped into my head a couple times.

**Comment by tallenaz** [comment]
Rough idea of a plan to deploy these changes:
- shut down resque-pool on worker nodes
- merge/deploy puppet PR (and verify the single pool responds to new init script)
- merge shared_configs/prescat PRs
- cap deploy prescat

**Comment by mjgiarlo** [comment]
@tallenaz ok, thanks! Given that, should I whip up draft prod shared_configs/puppet PRs as well, so there's not a period during which the prescat code can't be deployed to prod? cc: @jmartin-sul

**Comment by tallenaz** [comment]
I think having drafts of PRs in the 3 repos ready is a great idea, especially if we're un-drafting things after the break.

**Comment by mjgiarlo** [comment]
@tallenaz :speech_balloon: 
> I think having drafts of PRs in the 3 repos ready is a great idea, especially if we're un-drafting things after the break.

Here we go:

* [puppet (prod & stage)](https://github.com/sul-dlss/puppet/pull/4689)
* [shared_configs (stage)](https://github.com/sul-dlss/shared_configs/pull/1142)
* [shared_configs (prod)](https://github.com/sul-dlss/shared_configs/pull/1143)
* [preservation_catalog (prod & stage)](https://github.com/sul-dlss/preservation_catalog/pull/1278)
