### ISSUE TITLE
investigate replication audit errors

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1149]
honeybadger indicates an unusually high number of replication audit errors, especially mismatches between the expected number of zip parts (as indicated by part count column) and the number of zip part rows in the db for a given object.  e.g.:

https://app.honeybadger.io/projects/54415/faults/39235659?at=2019-04-18T10:00:00-07:00
`PartReplicationAuditJob(ty289vb4415, services-disk12) 1 on aws_s3_west_2: ZippedMoabVersion stated parts count (1) doesn't match actual number of zip parts rows (2)`

@julianmorley manually checked some of the reported druids, and all seemed fine in AWS.

we somewhat suspect that there's an audit query which is incorrectly scoped, and which isn't taking into account multiple endpoints when counting the number of rows for a replicated part.  @jmartin-sul wonders why we wouldn't have seen this error earlier in prod, since we've been replicating to two endpoints for a bit (or why it never came up in stage testing).

so, we should probably investigate this soon (it's preservation, we need to make sure it's working properly).  but since cursory investigation is reassuring, it can maybe wait a couple days if it has to.

even if things are being replicated correctly, pres cat should give high quality alerts, and spurious audit errors run counter to that goal.

**Comment by ndushay** [comment]
close in favor of #1166?

**Comment by jmartin-sul** [comment]
closing in favor of #1733, which deals with remaining known instances of cloud replication issues
