### ISSUE TITLE
if we adopt ADRs as a pattern, consider turning the pres cat architecture chat into one

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1157]
this may not be worth the effort, and we may not even adopt [Architecture Decision Records](https://github.com/sul-dlss-labs/infrastructure-adrs).  but if we do start using ADRs, we might consider turning this architecture review chat transcript into one:  https://github.com/sul-dlss/preservation_catalog/wiki/Architecture-Review

spawned by #1150

**Comment by ndushay** [comment]
closing in favor of upcoming ADR for many cats for storage root migration to shiny new big storage
