### ISSUE TITLE
[BLOCKED] Support same druid on multiple storage_roots

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1159]
We'll need this when we start migrating content off the NetApp / onto CHAOS; the same exploded Moab will exist on two NFS filesystems simultaneously, potentially with different current_versions. Possibly related to #1139

**Comment by jmartin-sul** [comment]
we already support this _in theory_ (e.g. schema allows for it), but have not tested it at all.

**Comment by julianmorley** [comment]
This functionality is looking like it's critical for seamless migration of content from existing services-disks to new sdr storage bricks, if we are to keep the same, single database for all storage roots.

**Comment by jmartin-sul** [comment]
In the context of the december 2019 maintenance sprint:  it's fine if this gets picked up so that we can start investigating and writing tests, without necessarily finishing before winter break.  It seems very likely that we'll pick this back up in January, so notes for when we come back, or a WIP branch with tests that exercise the desired functionality would be a fine start.

I can imagine that this might involve changes to preservation_catalog application code as well as moab-versioning code.

**Comment by justinlittman** [comment]
What would the logic be here?
* If there are multiple instances of a moab, will each instance have every version have up to its own current version? (So, for example, if the current version of a moab instance is 3, it will always have version 1, 2, and 3).
* If there are multiple instances of a moab with the same current version, does it matter which is used?
* If the catalog believes that there are multiple instances of a moab on different storage roots and auditing finds one of those missing, is this an error? Or should the missing instance just be removed from the catalog?

**Comment by julianmorley** [comment]
I think the biggest issue is version mismatches between storage roots; if M2C finds the same Druid on multiple roots, all discovered instances of that Druid should be complete (contiguous version directories) and match the expected current_version value. I'd vote for a meaningful/trackable alert if that's not the case.

If C2M discovers that one of several Druid instances is completely missing, that's fine, not an error, and the Druid instance can be safely removed from the catalog. It's only a problem / five alarm fire if the missing instance is the *last* known instance of that druid on local disk.

**Comment by justinlittman** [comment]
If a complete moab goes missing (and is not the last for that preserved object), do we want to delete it from the db or somehow mark it as gone (without deleting it)?

**Comment by justinlittman** [comment]
Declaring bankruptcy on this and #1139 as (1) relationship between complete_moab and zipped_moab_versions needs to be considered (viz., what happens to the zipped_moab_versions when a complete_moab is moved or deleted) and (2) how all of this relates to the proposal to run multiple instances of pres cat on multiple storage roots.

**Comment by julianmorley** [comment]
I agree with Justin that the current schema does not easily support this. I'd argue that our naming convention (complete_moab and z_m_v) has led to some constrained thinking here. It'd be easier if we spoke of 'moabs' and 'moab versions', with whether or not any particular moab version was a zip or a directory, and on an archive endpoint or on local disk being facets of the moab version model.

**Comment by jmartin-sul** [comment]
one note:  the `complete_moabs` to `zipped_moab_versions` relationship was only intended to indicate from which moab on disk an archive copy was created.  it's not meant to indicate that the ZMV is the only ZMV for the druid.  iirc, it was a bit of a tossup at the time as to whether the ZMV should be tied to the `CompleteMoab` or the `PreservedObject`.  the current schema allows easy association back to the `druid`/`PreservedObject` while also indicating with more specificity how the ZMV was created.  if we were to allow multiple `CompleteMoab`s for a given druid, we could keep the schema as-is under the reasoning described in this comment, or we could pretty easily switch the association to be to `preserved_objects` if that'd be more practical.  that would be a pretty straight-forward migration, i think.

there are some other questions i have in my notes, which i'll write up and schedule a meeting to hopefully iron out (hence marking the `[BLOCKED]`).

**Comment by jmartin-sul** [comment]
re @justinlittman's question:
> what happens to the zipped_moab_versions when a complete_moab is moved or deleted

i propose that the association be severed in that case, as the bits from which the archive copy was created no longer exist.  that would require making `zipped_moab_versions.complete_moab_id` nullable.  or maybe this is an argument for switching the association to point to a `PreservedObject`.

**Comment by jmartin-sul** [comment]
Closing this, as we were able to do the above described storage migration by incurring some downtime and updating database records. We also did get a good data model refactor out of this:  re-parenting `ZippedMoabVersion` to hang off of `PreservedObject` (the master record for the druid) instead of `CompleteMoab` (the record for the on prem exploded moab).  We've also undone the work we started on to fully support having the same druid on multiple storage roots, as the other goal, redundant local storage, was addressed below the POSIX file system level by the storage technologoy we migrated to (Ceph).

See also:
#1589
#1891
#1892
