### ISSUE TITLE
Support priority queues in ZipMaker

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1161]
Endpoint backfill operations frequently suck all the oxygen from the system, with all ZipMaker workers busy making a 2nd or 3rd copy of a Moab whilst new-to-prescat Moab-versions languish at the end of the queue, leaving new data completely unreplicated for an unacceptably long time.

Consider implementing a Low/Med/High priority queuing system for ZipMaker jobs, so backfill requests (where at least one ZMV already exists somewhere) happen in a way that allows jobs for Moab-versions that do not already have a successful ZMV uploaded can be processed with a higher priority.

Consider implementing some workers that never process low priority jobs, reserving some capacity for these uploads. Likewise, consider implementing a handful of workers that only process low priority jobs, and reserve this capacity for backfilling (a ZMV already exists somewhere) of very large archive ( > 10GB ) zips.

**Comment by julianmorley** [comment]
Moab-version is new to Pres-cat:   High
Moab-version already has > 1 ZMV:   Medium
Moab-version already has > 1 ZMV and is > 10GB: Low

**Comment by ndushay** [comment]
This ticket is 3 years old;  we have ironed out our concerns with balancing ingesting new moabs into prescat vs replicating stuff in prescat to the cloud.  And if we hit such a problem again, no one will remember this ticket exists - they will make a new one.
