### ISSUE TITLE
API endpoints should be versioned

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/preservation_catalog#1206]
We should use versioning in the API endpoints to allow for backwards compatibility when updating.

dor-services-app is one example (using scoped routes), but there may be other better ways of doing it.

**Comment by ndushay** [comment]
See https://github.com/sul-dlss/repository-api/blob/master/config/routes.rb as an example?

**Comment by ndushay** [comment]
Note that a small tweak will also be required for preservation-client, and a new release of that gem, and bundle update of that gem on its 3 consumers:  argo, common-accessioning, and dor-services-app
