### ISSUE TITLE
/objects/checksums should allow POST in addition to GET

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1212]
as @peetucket worried, a recent honeybadger alert shows that people will exceed the allowable size for a `GET` request:
```
Call to preservation_catalog_api failed: 414 Request-URI Too Large: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>414 Request-URI Too Large</title>
</head><body>
<h1>Request-URI Too Large</h1>
<p>The requested URL's length exceeds the capacity
limit for this server.<br />
</p>
</body></html>
```

https://app.honeybadger.io/projects/49894/faults/55032532 (alert is from argo, which got the 414)

as @ndushay pointed out, this is technically a violation of `POST` semantics (since this request isn't really modifying server side data).  but i can't think of anything better, and this violation is common enough that wiki [mentions it specifically](https://en.wikipedia.org/wiki/POST_(HTTP)#Affecting_server_state):
> However, there are reasons why POST is used even for idempotent requests, notably if the request is very long. Due to restrictions on URLs, the query string the GET method generates may become very long, especially due to percent-encoding.

i assume this only requires modifying the routes file and adding to the request spec.

**Comment by jmartin-sul** [comment]
the request in question had 311 druids

**Comment by peetucket** [comment]
Yes, I think:

1. we modify the routes.rb to make this a POST (could do it for only the multiple druid endpoint)
2. modify the spec to match
3. modify the argo job to make a post call instead of a get
