### ISSUE TITLE
add openapi documentation

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1216]
at the time of filing this ticket, the ReST API is still small, as most non-scheduled/non-automated functionality is handled from the rails console.

once done, update the PR template to mention the openapi doc along with the other documentation to possibly update.

**Comment by jmartin-sul** [comment]
fwiw, there is now API documentation in the README.  would this be duplicative?  i think this is probably a good thing to do since we're moving toward openapi documentation in general as a team, but i also don't know that it's super high priority since we already have thorough documentation of another sort on this front.

**Comment by mjgiarlo** [comment]
@jmartin-sul Open to specifying the API in YAML instead of JSON? I believe we've found YAML to be both easier to read and easier to write.

**Comment by jmartin-sul** [comment]
@mjgiarlo asked:
> Open to specifying the API in YAML instead of JSON? I believe we've found YAML to be both easier to read and easier to write.

no objection at all!
