### ISSUE TITLE
nagios check for worker count fails on re-deployment

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#1227]
At 9:36am, prescat was deployed, the okcomputer check for the number of workers failed. Currently, the resque console shows the following:

prescat-prod-02: (16 workers total)
PART_AUDIT_AWS_S3_WEST_2: 3 workers waiting
IBM_US_SOUTH_DELIVERY: 6 workers waiting
S3_US_WEST_2_DELIVERY: 3 workers waiting
ZIPMAKER: 5 workers active

prescat-prod-03: (20 workers total)
S3_US_EAST_1_DELIVERY: 3 workers waiting
S3_US_WEST_2_DELIVERY: 3 workers waiting
PART_AUDIT_AWS_S3_WEST_2: 3 workers waiting
IBM_US_SOUTH_DELIVERY: 6 workers waiting
ZIPMAKER: 5 workers active

prescat-prod-04: (18 workers total)
PART_AUDIT_AWS_S3_WEST_2: 3 workers waiting
S3_US_WEST_2_DELIVERY: 3 workers waiting
S3_US_EAST_1_DELIVERY: 3 workers waiting
IBM_US_SOUTH_DELIVERY: 6 workers waiting
ZIPMAKER: 3 workers active

53 total workers, when we expect 180.

Breakout of total workers expected per worker machine, from resque-pool yml files: (60 per worker machine)
checksum_validation: 6
c2m: 6
m2c: 6
moab_replication_audit: 3
results_recorder: 6
zipmaker: 6
zips_made: 6
zip_endpoint_events: 6
s3_us_east_1_delivery: 3
ibm_us_south_delivery: 6
part_audit_aws_s3_west_2: 3
s3_us_west_2_delivery: 3

**Comment by tallenaz** [comment]
In this case, it looks like there are some long running ZipmakerJobs that hold up a resque-pool shut down. on prescat-prod-02, at least.

**Comment by tallenaz** [comment]
I issued a `kill -s QUIT` to each pool containing long running jobs, which shut down the workers once they were done, and then the master. After that, I could `service resque-pool start` to bring all workers up.

We could try using `hot-swap` https://github.com/nevans/resque-pool#zero-downtime-code-deploys but we'd have to enforce a "one zip endpoint per worker machine" rule.

**Comment by ndushay** [comment]
this is a symptom of #1122

**Comment by tallenaz** [comment]
Redeployment with hot swap keeps the same worker count for nagios to check now.
