### ISSUE TITLE
ObjectsController#checksums 404 error is unhelpful -- need druid supplied.  

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1229]
Currently, will 404 the whole batch if there's one missing druid.  We need at a minimum a more specific error message (including the missing druid(s));  ideally better error handling would be nice (return results for all present druids, indicate which ones are missing?)

![image](https://user-images.githubusercontent.com/96775/67701339-fb55d000-f96c-11e9-901f-b911b1db40f4.png)

we were aware of this limitation when we implemented the endpoint, but we were fitting the work in with a bunch of other stuff during one week of maintenance, so MVP 🤷‍♂

**Comment by jcoyne** [comment]
I would also argue that changing the response from 404 is warranted.  404 means "nothing here", but what we want to say is probably: "409: The request could not be completed due to a conflict with the current state of the target resource"

**Comment by jmartin-sul** [comment]
huh... is 409 idiomatic as a response code for "one of the things in this batch is missing?"

for the one or more missing druids (e.g. if they were requested individually), that does seem like it'd be a 404, because from pres cat's perspective, the thing doesn't exist yet.  but i'd agree that for the batch as a whole, it's not really a 404.  not sure what the expectation would be for most clients.

**Comment by ndushay** [comment]
I think 404 text is coming from app/controllers/application_controller.rb;  wondering if checksum_report_job should override that so as to provide a druid for missing object.  The current error experience is sucky.  I don't care if it's a 404 or 409, I am more concerned with getting useful information from the error.

https://github.com/sul-dlss/preservation_catalog/blob/master/app/controllers/objects_controller.rb#L26 is another opportunity to say more when throwing an error - like "expect druid list" or something like that, with an example, even.

**Comment by jmartin-sul** [comment]
> I think 404 text is coming from app/controllers/application_controller.rb; wondering if checksum_report_job should override that so as to provide a druid for missing object.

so the application_controller.rb handling logic was just put there so that there's be generic handling of something that seemed 404-ish.  if we want something specific for the `ObjectsController#checksums` etc methods, i'd propose just removing the error handling in `ApplicationController`, and just doing a custom response in `ObjectsController`.  the 404 genercization didn't seem to have an effect one way or the other on the existing `CatalogController` methods, which render their own error messages.

honestly i think i just put that error handling in `ApplicationController` because i thought it was more idiomatic rails to have the controller _not_ do custom error handling, and to instead let the error get raised, and then presented by the controller.  but as seen here, that's not the easiest to trace through or the most informative in terms of error messaging, so i'm more than happy to ditch that approach for something specific to `ObjectsController`.

**Comment by mjgiarlo** [comment]
if anyone stumbles upon where that `preservation_catalog_api` string is coming from... I will be super excited to hear about it.
