### ISSUE TITLE
[BLOCKED by 1249] programmatically report on all objects with audit failures

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1261]
Before #1249 (ReST endpoint for audit details), this would merely give out druids for objects with not "ok" status, so perhaps not useful until #1249 is done.

Idea:  *someone* should be concerned with failing audit checks;  being able to generate a report of all objects failing audits, and the audit failure details, would be super helpful in trying to figure out what to do.

This could be an "on demand" thing, or run by a cron job.

We would also need to know WHO would be getting this and treating it as actionable rather than noise.

**Comment by jmartin-sul** [comment]
@ndushay, assigning this to you just so someone doesn't pick it up if you're already working on it (i got the impression intended to tackle this along with #1249.  if that's a mistake (like if i was the one that pulled it into the "In Progress" column but i forgot), feel free to unassign and move back to "Ready".

**Comment by jmartin-sul** [comment]
discussed F2F, un-assigning since naomi's not working on this _right now_, but marking blocked since we prob want #1249 to be done before this is started.  naomi may or may not pick that up next.

**Comment by ndushay** [comment]
this is probably going to be addressed via #1324 and #1363
