### ISSUE TITLE
Refactor `MoabValidationHandler`

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/preservation_catalog#1276]
The `MoabValidationHandler` mixin and its interactions with the classes in which it is `include`d are long and complex and, arguably, messy.

1) The mixin provides a bunch of public methods, so there are numerous interaction points and, thus, different "flows" through the mixin, which means there may be time-sensitive data points;
2) The mixin is not self-contained, requiring its containing classes to respond to certain messages, and there is no good way to enforce that contract;
3) Containing classes use only bits and pieces of the mixin; and
4) One containing class overrides the behavior of the mixin.

Overall, this suggests `MoabValidationHandler` is a "kitchen sink" abstraction, and given the length and complexity of this module and its containing classes and the sheer amount of shameless :green_apple: code, makes it difficult to reason about and difficult to work with.

I have attempted (twice) to extract a `MoabValidator` class out of the mixin  and each time walked it back due to not having enough time to sufficiently disentangle the code and touch/update all affected tests. In _lieu_ of trying to refactor it again, I have instead done a small bit of analysis which I will share here (knowing, of course, that it will age poorly):

# `MoabValidationHandler` public methods

## `object_dir`

Depends on `druid` and `storage_location` (the latter of which depends on `complete_moab`).

## `moab`

Depends on `druid` and `object_dir`.

## `can_validate_checksums?`

No dependencies.

## `can_validate_current_comp_moab_status?`

Depends on `can_validate_checksums?`, `complete_moab`, and `results`

## `moab_validation_errors`

Depends on `moab` and `ran_moab_validation!`

## `ran_moab_validation!`

No dependencies.

## `ran_moab_validation?`

No dependencies.

## `update_status`

Depends on `complete_moab` and `results`

## `set_status_as_seen_on_disk`

Depends on `update_status`, `moab_validation_errors`, `results`, and `complete_moab`

# `PreservedObjectHandler`

Uses the following methods from `MoabValidationHandler`:

* `can_validate_current_comp_moab_status?`
* `moab_validation_errors`
* `ran_moab_validation?`
* `ran_moab_validation!`
* `update_status`
* `set_status_as_seen_on_disk`

# `CatalogToMoab`

Uses the following methods from `MoabValidationHandler`:

* `moab`
* `can_validate_current_comp_moab_status?`
* `ran_moab_validation?`
* `update_status`
* `set_status_as_seen_on_disk`

# `ChecksumValidator`

Uses the following methods from `MoabValidationHandler`:

* `object_dir`
* `moab`
* `can_validate_checksums?`
* `update_status`
* `set_status_as_seen_on_disk`

**Comment by mjgiarlo** [comment]
Note that my second refactoring attempt went like this:

1. Copy `MoabValidationHandler` to a new `MoabValidator` class, and make it a class with three required initialization args & `attr_reader`s: `druid`, `audit_results`, and `complete_moab`
2. In `PreservedObjectHandler`, add a new initialization ivar and `attr_reader` called `validator` and set it to a new instance of the new extracted class, initialized with required values.
3. Change calls to mixin methods in `PreservedObjectHandler` to calls on the new validator instance, _e.g._, change `update_status` to `validator.update_status`

So far, so good. Except this caused > 160 test failures. Some of which are probably due to test setup, which is expceted. Not convinced all of these failures are due to that. FYI!

**Comment by jmartin-sul** [comment]
see also #1494 (forgot this one already existed, sorry for the duplicate).

i'd suggest that whoever picks this up pick up the other one too, and close whichever ticket seems less useful/informative as a dupe.

**Comment by aaron-collier** [comment]
Copying @jmartin-sul comment from #1494

per #1487
> Everyone seems to find this difficult to work with, myself included sometimes, and I was the one who originally refactored code into this module. I don't want to copy this logic back out into the various consumers, but feedback seems to be that a more traditional inheritance relationship, or some other form of composition, would be more intelligible than the module mixin.


some possible approaches:
* turn it into a parent class that takes needed things in constructor, modify the classes that currently `include` it extend it instead.
  * along those lines: turn it into a class where subclass is expected to define some methods, and the default method implementations raise error if unimplemented.  this feels a little too java-ish and a little too close to the current (confusing) implementation, but it's a possibility to consider.
* service object that takes needed things in constructor, classes that currently `include` the module would have an instance of the service class instead
* other ideas?

i think i'm leaning toward the parent class idea, but would love to hear other ideas or discuss further if someone else wants to pick this up.  the service class thing could be a good approach also?  but reading over the code definitely makes it feel like there's a circular relationship between `MoabValidationHandler` and its consumers (each expects methods from the other).  i suspect this is what makes it especially hard to understand, and i also think all the above ideas would at least eliminate that issue.

**Comment by justinlittman** [comment]
You might want to consider https://github.com/sul-dlss/preservation_catalog/pull/1294, which consolidates M2C and C2M into a single service class.

**Comment by jmartin-sul** [comment]
i would definitely like to consider #1294, but first i think i'd like to make `MoabValidationHandler` not be a module, so that its relationship to the classes that use it is less confusing.

**Comment by jmartin-sul** [comment]
i can see how #1294 might replace some/much of what `MoabValidationHandler` and a couple of its consumers do, so... whoever picks up this ticket could consider following through on the changes in that PR.  _but_, if we were to use that change, i think we need to wire it into pres cat's audits instead of what pres cat currently uses (`CatalogToMoab`, CompleteMoabHandler`).  i _suspect_ it will be easier (less app and test code churn) to start by just refactoring MVH, but definitely worth giving that PR a look to see if i'm missing something.  it also seems possible that refactoring MVH usage and making it more understandable would also make it easier to wire in the changes in #1294 (as opposed to leaping straight into the #1294 changes).

**Comment by jmartin-sul** [comment]
PR up (#1539).  like @mjgiarlo, i ended up going with a service class instantiated in what used to `include` the old module.

**Comment by mjgiarlo** [comment]
@jmartin-sul will review today.
