### ISSUE TITLE
Investigate version conflict for druid:rs107gm7618 

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_catalog#1285]
This druid has been caught in the preservation production problem from the week of 2019-12-18:

https://argo.stanford.edu/view/druid:rs107gm7618

It is currently stalled in the accessionWF at the preservation-ingest-initiated step. I believe that what happened is:

1. User creates version 5 on 2019-12-16.
2. Prescat is not updated to record existence of version 5
3. User creates another version on 2019-12-18
4. This version is called version 5 when it should be version 6. This could be because prescat still thinks that version 4 is the current version.
5. User tries to send version 5 to preservation core
6. There is a conflict between the version 5 being sent as a new version and the version 5 already on services-disk15

At this point, I am not sure

1. How to resolve the conflict
2. If there should be a version mismatch or other error message surfaced in Argo 

In the past, version mismatches would be surfaced in Argo and the user would be able to manually update the version number. In this case, prescat doesn't see version mismatch because it thinks the current version is 4, so version 5 is the expected version. But the filesystem already has the folder structure for version 5.

More details below from the analysis I've done so far:

The moab is on services-disk15 and has 5 versions:

```
[pres@preservation-catalog-prod-01 rs107gm7618]$ ls -l /services-disk15/sdr2objects/rs/107/gm/7618/rs107gm7618
total 20
drwxrwxr-x 4 pres pres 4096 Aug 17  2018 v0001
drwxrwxr-x 4 pres pres 4096 Dec 10 13:52 v0002
drwxrwxr-x 4 pres pres 4096 Dec 10 14:19 v0003
drwxrwxr-x 4 pres pres 4096 Dec 14 09:06 v0004
drwxrwxr-x 4 pres pres 4096 Dec 16 15:29 v0005
```

Prescat shows only 4 versions:

```=> [#<CompleteMoab:0x0000000007752db0
  id: 1414557,
  version: 4,
  preserved_object_id: 1414549,
  moab_storage_root_id: 14,
  created_at: Tue, 21 Aug 2018 21:54:46 UTC +00:00,
  updated_at: Sat, 14 Dec 2019 17:06:57 UTC +00:00,
  last_moab_validation: Sat, 14 Sep 2019 07:40:08 UTC +00:00,
  last_checksum_validation: Sat, 14 Dec 2019 17:06:57 UTC +00:00,
  size: 227840567,
  status: "ok",
  last_version_audit: Sat, 14 Dec 2019 17:06:57 UTC +00:00,
  last_archive_audit: Thu, 17 Oct 2019 00:05:42 UTC +00:00>]
```

At some point, m2c will come along and update this so that prescat has version 5. I do not think that will fix the problem, but it might be a good idea to wait until that happens.

**Comment by peetucket** [comment]
I'm a bit confused with this one too.  It looks like `preservation-ingest-initiated` step of `accessionWF` is still waiting for its signal that preservation of the new version has started, but never got it.  Which leads me to wonder if simply re-doing `sdr-ingest-transfer` step will get it moving it along again?

**Comment by peetucket** [comment]
And it looks like when the robot `sdr-ingest-transfer` is run, it makes a call to dor-services-app which then invokes a call to create a new `preservationIngestWF` workflow (https://github.com/sul-dlss/dor-services-app/blob/e3da702eb72d439190b1ae4c114231caad9cacb3/app/jobs/start_preservation_workflow_job.rb#L14) and that didn't appear to happen (the last `preservationIngestWF` was 2 days ago)

**Comment by peetucket** [comment]
Though if we were to re-invoke the `sdr-ingest-transfer` robot this would then initiate another transfer of the object to SDR (here: https://github.com/sul-dlss/dor-services-app/blob/master/app/jobs/preserve_job.rb#L14), which may already be done (by the fact the v5 object is already on the service-disk.

**Comment by andrewjbtw** [comment]
I don't think the v5 object being sent matches the v5 object that is already there. I think what's being sent should be v6.

**Comment by peetucket** [comment]
Maybe we need to something like this from dor-services-app (basically the second part of that job after the ingest): 

```    
druid='druid:rs107gm7618'
item = Dor.find(druid)
StartPreservationWorkflowJob.perform_later(druid: druid,
                                               version: item.current_version,
                                               background_job_result: background_job_result)
```

**Comment by peetucket** [comment]
> I don't think the v5 object being sent matches the v5 object that is already there. I think what's being sent should be v6.

The object looks like V5 though?  In versionMetadata and according to the object itself:

```
druid='druid:rs107gm7618'
item = Dor.find(druid)
item.current_version
 => "5"
```

**Comment by andrewjbtw** [comment]
I think in this situation Argo overwrites back into the previous v5. So it's a silent error.

In ```/dor/workspace/rs/107/gm/7618/rs107gm7618``` there's a file called 
```data_EPSG_4326.zip```

But that file is not in any of the preservation versions in the moab.

**Comment by andrewjbtw** [comment]
Oh, that file is shelve only. So maybe these do match?

**Comment by andrewjbtw** [comment]
Never mind, these are definitely different. Compare the events.xml:

On moab v5:

```xml
<?xml version="1.0"?>
<events>
  <event type="open" who="Kimberly A Durante" when="2019-12-10T19:08:15Z">Version 2 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-10T21:52:30Z">Version 2 closed</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-10T21:54:27Z">Version 3 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-10T22:19:09Z">Version 3 closed</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-14T00:14:16Z">Version 4 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-14T17:06:26Z">Version 4 closed</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-16T23:13:27Z">Version 5 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-16T23:28:56Z">Version 5 closed</event>
</events>
```

The version that should be sent from /dor/workspace

```xml
<?xml version="1.0"?>
<events>
  <event type="open" who="Kimberly A Durante" when="2019-12-10T19:08:15Z">Version 2 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-10T21:52:30Z">Version 2 closed</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-10T21:54:27Z">Version 3 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-10T22:19:09Z">Version 3 closed</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-14T00:14:16Z">Version 4 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-14T17:06:26Z">Version 4 closed</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-16T23:13:27Z">Version 5 opened</event>
  <event type="close" who="Kimberly A Durante" when="2019-12-16T23:28:56Z">Version 5 closed</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-16T23:32:13Z">Version 5 opened</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-17T21:22:48Z">Version 5 opened</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-18T19:09:22Z">Version 5 opened</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-18T19:22:43Z">Version 5 opened</event>
  <event type="open" who="Kimberly A Durante" when="2019-12-18T19:25:05Z">Version 5 opened</event>
</events>
```

You can see version 5 being opened repeatedly in the second one.

**Comment by peetucket** [comment]
Prescat now shows version 5 (after the M2C process went through?):

```
PreservedObject.find_by(druid: 'rs107gm7618').complete_moabs
=> [#<CompleteMoab:0x0000000007983440
  id: 1414557,
  version: 5,
  preserved_object_id: 1414549,
  moab_storage_root_id: 14,
  created_at: Tue, 21 Aug 2018 21:54:46 UTC +00:00,
  updated_at: Wed, 18 Dec 2019 22:49:25 UTC +00:00,
  last_moab_validation: Wed, 18 Dec 2019 22:49:25 UTC +00:00,
  last_checksum_validation: Sat, 14 Dec 2019 17:06:57 UTC +00:00,
  size: 274335322,
  status: "ok",
  last_version_audit: Wed, 18 Dec 2019 22:49:25 UTC +00:00,
  last_archive_audit: Thu, 17 Oct 2019 00:05:42 UTC +00:00>]
```

**Comment by andrewjbtw** [comment]
Yes, I think that's what happened. I suspect that if we set sdr-ingest-transfer back to waiting as you suggested above, it will now trigger a version mismatch error. At least, that's what I expect to happen if the robots try to send a version number that already exists.

**Comment by peetucket** [comment]
Could we trying and get ahead of this by manually manipulating the versionMetadata datastream to add the version 6 we expect it to be?  We could also manually add a row in the events to make it clear (though I think that datastream is essentially a log and won't trigger errors if inconsistent).

**Comment by andrewjbtw** [comment]
I think it's worth a shot. It looks like the version 5 name in the moab is also blank so there isn't a previous version 5 name to restore. The only difference between the two versionMetadata files in this case is that one has a line breaks where the other doesn't.

**Comment by peetucket** [comment]
Ok.  Done.  Manually edited `versionMetadata` and `events` DS.  Re-ran the `sdr-ingest-transfer` step. Manually completed the `versioningWF` steps still in waiting.  Object was preserved (appears on service-disk15 now as v0006) and shows as v6 in DOR as well.  Open button is available again.
