### ISSUE TITLE
Get a list of all druids that fail M2C

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/preservation_catalog#1287]
Specifically, from the current M2C run, which ~~is estimated to finish around 1am tomorrow~~ finished on 12/18. ~~That is, this issue is blocked until that run has completed.  @jmartin-sul will update @sul-dlss/infrastructure-team when this run is done.~~ This is no longer blocked.

You should be able to get the druids from the prescat logs. (which are on prescat-02, -03, and -04)

If the number of druidw with errors matches the number of preservationAuditWF errors in argo, yay! <-- if they don't match, investigating might be best as a separate ticket?

Note that validation and catalog updates are NOT done if the object is starting in certain error states, like `checksum invalid`

Ensure all M2C errors are available somewhere for us to address.

**Comment by jmartin-sul** [comment]
whoever takes this may want to make a new separate ticket to figure out how the argo errors related to the errors logged in pres cat.  @jcoyne worried that workflow errors are version specific, and so may disappear upon versioning (or may prevent versioning).

**Comment by jermnelson** [comment]
Hi @jmartin-sul, here is what I found doing some grepping around the servers production logs for 2019-12-17 and 2019-12-18

### preservation-catalog-prod-01
- **INVALID_ARGUMENTS** - 0 found
- **ACTUAL_VERS_GT_DB_OBJ** - 12 found
- **ACTUAL_VERS_LT_DB_OBJ** - 0 found
- **CREATED_NEW_OBJECT** - 501 found
- **DB_OBJ_ALREADY_EXISTS** - 0 found
- **DB_OBJ_DOES_NOT_EXIST**  - 194 found
- **INVALID_MOAB** - 0 found
- **MOAB_FILE_CHECKSUM_MISMATCH** - 0 found

### preservation-catalog-prod-02
- **INVALID_ARGUMENTS** - 0 found
- **ACTUAL_VERS_GT_DB_OBJ** - 0 found
- **ACTUAL_VERS_LT_DB_OBJ** - 0 found
- **DB_OBJ_ALREADY_EXISTS** - 0 found
- **DB_OBJ_DOES_NOT_EXIST** - 0 found
- **INVALID_MOAB** - 0 found
- **MOAB_FILE_CHECKSUM_MISMATCH** - 0 found

### preservation-catalog-prod-03
- **INVALID_ARGUMENTS** - 0 found
- **ACTUAL_VERS_GT_DB_OBJ** - 0 found
- **ACTUAL_VERS_LT_DB_OBJ** - 0 found
- **DB_OBJ_ALREADY_EXISTS** - 0 found
- **DB_OBJ_DOES_NOT_EXIST** - 0 found
- **INVALID_MOAB** - 0 found
- **MOAB_FILE_CHECKSUM_MISMATCH** - 0 found

### preservation-catalog-prod-04
- **INVALID_ARGUMENTS** - 0 found
- **ACTUAL_VERS_GT_DB_OBJ** - 0 found
- **ACTUAL_VERS_LT_DB_OBJ** - 0 found
- **DB_OBJ_ALREADY_EXISTS** - 0 found
- **DB_OBJ_DOES_NOT_EXIST** - 0 found
- **INVALID_MOAB** - 0 found
- **MOAB_FILE_CHECKSUM_MISMATCH** - 0 found

**Comment by ndushay** [comment]
Looking for unhappy `complete_moab` objects in the prescat db:

```
[2] pry(main)> CompleteMoab.where.not(status: 'ok').count
   (482.4ms)  SELECT COUNT(*) FROM "complete_moabs" WHERE "complete_moabs"."status" != $1  [["status", 0]]
=> 675
[3] pry(main)> CompleteMoab.where(status: 'invalid_moab').count
   (1.0ms)  SELECT COUNT(*) FROM "complete_moabs" WHERE "complete_moabs"."status" = $1  [["status", 1]]
=> 0
[4] pry(main)> CompleteMoab.where(status: 'invalid_checksum').count
   (1.8ms)  SELECT COUNT(*) FROM "complete_moabs" WHERE "complete_moabs"."status" = $1  [["status", 2]]
=> 513
[5] pry(main)> CompleteMoab.where(status: 'online_moab_not_found').count
   (3.6ms)  SELECT COUNT(*) FROM "complete_moabs" WHERE "complete_moabs"."status" = $1  [["status", 3]]
=> 0
[6] pry(main)> CompleteMoab.where(status: 'unexpected_version_on_storage').count
   (0.9ms)  SELECT COUNT(*) FROM "complete_moabs" WHERE "complete_moabs"."status" = $1  [["status", 4]]
=> 0
[7] pry(main)> CompleteMoab.where(status: 'validity_unknown').count
   (1.5ms)  SELECT COUNT(*) FROM "complete_moabs" WHERE "complete_moabs"."status" = $1  [["status", 6]]
=> 162
```

**Comment by ndushay** [comment]
Looking at an example object with status `validity_unknown` we see this:

=> #<CompleteMoab:0x000000000721e3a8
 id: 1854120,
 version: 1,
 preserved_object_id: 1854112,
 moab_storage_root_id: 22,
 created_at: Tue, 17 Dec 2019 21:14:15 UTC +00:00,
 updated_at: Fri, 20 Dec 2019 13:14:26 UTC +00:00,
 last_moab_validation: Fri, 20 Dec 2019 13:14:26 UTC +00:00,
 last_checksum_validation: nil,
 size: 1291249193,
 status: "validity_unknown",
 last_version_audit: Fri, 20 Dec 2019 13:14:26 UTC +00:00,
 last_archive_audit: Wed, 18 Dec 2019 09:29:06 UTC +00:00>
[9] pry(main)> CompleteMoab.where(status: 'validity_unknown').first.preserved_object.druid
  CompleteMoab Load (3.3ms)  SELECT "complete_moabs".* FROM "complete_moabs" WHERE "complete_moabs"."status" = $1 ORDER BY "complete_moabs"."id" ASC LIMIT $2  [["status", 6], ["LIMIT", 1]]
  PreservedObject Load (4.0ms)  SELECT "preserved_objects".* FROM "preserved_objects" WHERE "preserved_objects"."id" = $1 LIMIT $2  [["id", 1854112], ["LIMIT", 1]]
=> "bg822jm1141"

Looking at this object in argo, we see that common-accessioning occurred during the pres-robots outage window.

QUESTION:  why didn't this object get corrected by M2C run?

**Comment by julianmorley** [comment]
Does M2C automatically submit CompleteMoabs to CV if they are 'validity_unknown'? I didn't think it did; I thought it just checked o see if they had a record in the database.

**Comment by jmartin-sul** [comment]
@naomi said:
> why do we have any with status "validity_unknown"? <-- checksum validation hasn't happened yet (?)

anything that was created anew by M2C will start in validity unknown (via the call down to `PreservedObjectHandler#check_existence`):  https://github.com/sul-dlss/preservation_catalog/blob/master/app/services/preserved_object_handler.rb#L105

@julianmorley said:
> Does M2C automatically submit CompleteMoabs to CV if they are 'validity_unknown'? I didn't think it did; I thought it just checked o see if they had a record in the database.

yes, when the status changes to validity unknown, an ActiveRecord hook queues for CV:  https://github.com/sul-dlss/preservation_catalog/blob/master/app/models/complete_moab.rb#L19

**Comment by julianmorley** [comment]
@jmartin-sul The implication there is that a new version prompts a full CV of the entire object?

I'm a little concerned that a metadata tweak on a 2TB object prompts an unnecessary CV on 2TBs worth of prior version directories.

**Comment by jermnelson** [comment]
List of Druids that were in the production logs:

[druid-errors.txt](https://github.com/sul-dlss/preservation_catalog/files/3989822/druid-errors.txt)

**Comment by jmartin-sul** [comment]
@julianmorley said
> @jmartin-sul The implication there is that a new version prompts a full CV of the entire object?
>
> I'm a little concerned that a metadata tweak on a 2TB object prompts an unnecessary CV on 2TBs worth of prior version directories.

under the course of normal operation, the pres robots should vouch for checksum validity, pres cat would trust that, and thus that sort of version creation _shouldn't_ trigger CV.  the object will of course get re-CVed every so often due to fixity_ttl expiring, but if the version creation goes as expected, that should cause it to go into validity unknown status.

**Comment by julianmorley** [comment]
@jmartin-sul 
> under the course of normal operation, the pres robots should vouch for checksum validity, pres cat would trust that, and thus that sort of version creation _shouldn't_ trigger CV. the object will of course get re-CVed every so often due to fixity_ttl expiring, but if the version creation goes as expected, that should cause it to go into validity unknown status.

At the risk of driving this convo completely off the rails, pres robots do their checks *after* the version has been moved onto the services-disks, right? They're not doing a CV of the version directory in dor-assembly somewhere, *then* copying it into the services-disks and calling it good?

**Comment by ndushay** [comment]
@julianmorley pres_robots are stupid simple:  they send "create" or "update" to prescat.  prescat then ONLY checks the validity of the thing that has already been put on the storage root by earlier robot steps IF the robots say "this hasn't already been validated" ... but since it always has, the validity of what's on the storage root is NOT checksum validated.

**Comment by julianmorley** [comment]
@ndushay So you're confirming that something-other-than-prescat copies the new version onto the storage root, *checksum validates that new version directory*, and then tells prescat about it?

**Comment by ndushay** [comment]
@julianmorley yes, it's done by the robots utilizing the moab-versioning gem to put the new content in the moab.

**Comment by ndushay** [comment]
I trolled the logs for M2C messages from the affected time period that were for "check_existence" but were NOT "yay! the version matched!" nor were an uninformative debug message using this:

```sh
zgrep check_existence production.log-2019121* | grep -v called | grep -v matches
```
on all four pres-cat-prod boxes that could possibly run the jobs.

I then determined that the ONLY M2C messages of concern to us are the ones like this:

```
production.log-20191219.gz:I, [2019-12-18T17:13:00.523896 #2448]  INFO -- : [ActiveJob] [MoabToCatalogJob] [c3488041-1bf7-42d3-8b06-1bbe23e2ce11] check_existence(pk315qz8697, services-disk20) actual version (2) greater than CompleteMoab db version (1)
```

as any other remaining messages were just informative "M2C found something and fixed it automatically" messages.

I then noticed, looking at these particular log messages, that very close to all of our 513 "invalid_checksum" status CompleteMoab objects (see above for getting database counts for non-ok status)  are on services-disk02.  

This led me to get the following info about invalid_checksum status objects in the prescat db:
- 513 total  invalid_checksum statuses for complete_moabs
    - 506 - services-disk02 [services-disk02-invalid-checksum-druids.txt](https://github.com/sul-dlss/preservation_catalog/files/3990265/services-disk02-invalid-checksum-druids.txt)
    - 1 - services-disk03: `fk847cz0044`
    - 1 - services-disk04: `gh926rx4162`
    - 3 - services-disk08: `"py880rz2144`, `mg599hw5271`, `vq518cf9512`
    - 1 - services-disk10:  `zx284xc2961`
    - 1 - services-disk16:  `fr360kt0172`

**Comment by ndushay** [comment]
I'm closing this as I'm confident we have the correct druids that failed the M2C check.
