### ISSUE TITLE
we need a procedure for resolving invalid_checksum objects [aids storage migration]

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1297]
[m2c-invalid-checksum-druids.txt](https://github.com/sul-dlss/preservation_catalog/files/3990365/m2c-invalid-checksum-druids.txt) - 513 of them

Note that:
- M2C won't do its checks under these circumstances

**Comment by jmartin-sul** [comment]
self-assigning since this feels like it goes with #1324's analysis work, which is in progress (and since all the errors found in that work are checksum validation failures).

**Comment by jmartin-sul** [comment]
i filed a new issue (#1396) more geared towards documenting what we do for the remediations spawned by #1324, so that we can maybe find re-usable patterns and techniques as new errors come up in the future.

closing this one.
