### ISSUE TITLE
should pres cat gate access via JWT (or some sort of API key)?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1298]
issue was raised by @ndushay in https://github.com/sul-dlss/preservation_catalog/pull/1295#issuecomment-568048385

it's a thing we've started doing in other apps that provide APIs, e.g. [dor-services-app](https://github.com/sul-dlss/dor-services-app/search?q=jwt&unscoped_q=jwt).

**Comment by julianmorley** [comment]
Yes. IP-based access control is not considered a best practice; shouldn't implement a new service that doesn't use API keys.

**Comment by julianmorley** [comment]
This is now a high priority issue. See @vivnwong or me for details.
