### ISSUE TITLE
check size of archive zip file(s) upon creation

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1302]
Add a simple check to make sure that the zip that was created (all parts if it's a multi-part zip) is about the same size as the moab version directory from which it was created.  We'd expect the generated zip file(s) to be slightly larger in total than the moab in terms of logical size, since we're not using compression (and so there should be a small amount of additional overhead for the zip file's metadata).

We'd probably want the check to be implemented here, where the zip is created:  https://github.com/sul-dlss/preservation_catalog/blob/d16aafc710af512ad3c8c43590719abbcac4d6ab/app/models/druid_version_zip.rb#L30-L38

Maybe at line 33, the check could become `unless status.success? && zip_size_ok?`, where `zip_size_ok?` is a method that confirms that the zip parts that were generated sum to a value greater than or equal to the logical size of the moab version directory that was zipped.

I'd be inclined to delete the bad zip file(s), raise an error, and let whoever's minding Resque retry the job.

I believe an error raised there would bubble back up to the job:  https://github.com/sul-dlss/preservation_catalog/blob/d16aafc710af512ad3c8c43590719abbcac4d6ab/app/jobs/zipmaker_job.rb#L17

which gets that `create_zip!` method via:  https://github.com/sul-dlss/preservation_catalog/blob/d16aafc710af512ad3c8c43590719abbcac4d6ab/app/jobs/druid_version_job_base.rb#L9

Spawned from investigation of #1194.  This is an idea for a relatively easy sanity check that would catch that issue earlier, though it would not prevent it from happening in the first place (we have ideas as to what might've caused the problem, but have not been able to reproduce it).

**Comment by julianmorley** [comment]
Doesn't prescat start uploading zip parts as they complete? I think that's part of how we ended up with incomplete uploads with parts_count mismatches, and would confound an attempt to do a 'do we have enough zips' check before uploading.

**Comment by julianmorley** [comment]
For comparison, my parts_count audit check gets the size of the Moab version directory on disk, then divides by 10GB to get expected parts_count value. It then checks AWS for that number of zip parts, and checks each zip_part for a correct parts_count value.

**Comment by jmartin-sul** [comment]
> Doesn't prescat start uploading zip parts as they complete? I think that's part of how we ended up with incomplete uploads with parts_count mismatches, and would confound an attempt to do a 'do we have enough zips' check before uploading.

it seems to me that the zip is not delivered until all parts are created, as `#create_zip!` is a synchronous operation that completes before plexing of delivery work is invoked:
* https://github.com/sul-dlss/preservation_catalog/blob/d16aafc710af512ad3c8c43590719abbcac4d6ab/app/jobs/zipmaker_job.rb#L13-L22
* https://github.com/sul-dlss/preservation_catalog/blob/d16aafc710af512ad3c8c43590719abbcac4d6ab/app/models/druid_version_zip.rb#L30-L38
