### ISSUE TITLE
update_version encountered error on fx139bg2406

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1303]
see:
https://argo.stanford.edu/view/fx139bg2406
https://app.honeybadger.io/projects/55564/faults/59421754

`preservation-audit : update_version (actual location: services-disk10; actual version: 4) actual version (4) has unexpected relationship to CompleteMoab db version (4); ERROR!`

**Comment by andrewjbtw** [comment]
This item ran into an error at update-catalog in the preservationIngestWF:

![Screen Shot 2020-01-13 at 9 00 07 AM](https://user-images.githubusercontent.com/8975583/72275658-31f1cd00-35e3-11ea-8388-f1ca55561ebf.png)

I am going to reset that step and see if the next audit passes. Maybe it failed because preservation catalog didn't get updated and/or the item may not have finished ingest into the moab before the audit?

**Comment by andrewjbtw** [comment]
Ok, resetting the step just resulted in another 500 status, so this will need more investigation.

**Comment by andrewjbtw** [comment]
It looks like this item may have the same issue now: https://argo.stanford.edu/view/druid:md061cm9765

**Comment by vivnwong** [comment]
Confirmation from Julian that fx139bg2406 has v4 in the endpoints (confirm that the above error didn't stop the replication step): 

[dlss-jmorley:~/ruby ]$ ./tools.rb fx139bg2406,4
fx139bg2406
  sul-sdr-aws-us-west-2-archive:
    version 1: 
      fx/139/bg/2406/fx139bg2406.v0001.zip
    version 2: 
      fx/139/bg/2406/fx139bg2406.v0002.zip
    version 3: 
      fx/139/bg/2406/fx139bg2406.v0003.zip
    version 4: 
      fx/139/bg/2406/fx139bg2406.v0004.zip
  sul-sdr-aws-us-east-1-archive:
    version 1: 
      fx/139/bg/2406/fx139bg2406.v0001.zip
    version 2: 
      fx/139/bg/2406/fx139bg2406.v0002.zip
    version 3: 
      fx/139/bg/2406/fx139bg2406.v0003.zip
    version 4: 
      fx/139/bg/2406/fx139bg2406.v0004.zip
  sul-sdr-ibm-us-south-1-prod:
    version 1: 
      fx/139/bg/2406/fx139bg2406.v0001.zip
    version 2: 
      fx/139/bg/2406/fx139bg2406.v0002.zip
    version 3: 
      fx/139/bg/2406/fx139bg2406.v0003.zip
    version 4: 
      fx/139/bg/2406/fx139bg2406.v0004.zip

**Comment by mjgiarlo** [comment]
Error message in log: `update_version(fx139bg2406, services-disk10) actual version (4) has unexpected relationship to CompleteMoab db version (4); ERROR!`

**Comment by mjgiarlo** [comment]
@andrewjbtw @jmartin-sul So, it looks like the request coming over from preservation_robots says "update the version to v4", but it appears this object is already at v4:

```
update_version fx139bg2406 called
update_version(fx139bg2406, services-disk10) actual version (4) has unexpected relationship to CompleteMoab db version (4); ERROR!
update_version(fx139bg2406, services-disk10) actual version (4) matches CompleteMoab db version
=> [{:unexpected_version=>"actual version (4) has unexpected relationship to CompleteMoab db version (4); ERROR!"},
 {:version_matches=>"actual version (4) matches CompleteMoab db version"}]
```

I don't know if I can explain this. How does this happen? How should we remediate this? Skip the step? Are there things I should verify first? If this is already written up somewhere, please let me know!

**Comment by andrewjbtw** [comment]
I spent a bunch of time on this a couple of weeks ago and started and ended with pretty much the same questions. Everything looks like it should be fine to me, but it isn't. 

Maybe we should try to pair on this later in the week?

**Comment by mjgiarlo** [comment]
Sounds good to me, @andrewjbtw. I wonder if we can rope @jmartin-sul in as well.

**Comment by jmartin-sul** [comment]
happy to join, @mjgiarlo and @andrewjbtw!

**Comment by jmartin-sul** [comment]
if there's a v4 in the repository, my first instinct would be to see if and how the v4 in stacks/fedora differs from the v4 in preservation.  if there is no v4 in stacks/fedora, then i'd maybe start looking into whether something disappeared from stacks/fedora, whether something somehow accidentally got a version added in preservation, etc.  but i agree, this is perplexing.

**Comment by mjgiarlo** [comment]
This is no longer an active FR issue. @andrewjbtw @jmartin-sul and I paired on this and we marked as completed the failing WF steps after having verified that each affected object was in an OK state. @andrewjbtw will write up documentation for dealing with this in the future and will close the issue at his own discretion.

**Comment by mjgiarlo** [comment]
@andrewjbtw thank you!

**Comment by mjgiarlo** [comment]
Closing now.
