### ISSUE TITLE
Web Interface to Show Audit Results (per root? per druid?)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1320]
Ideally, there would be some sort of web interface on prescat to show current audit results - possibly rendered as a sortable table, with columns such as:

druid, storage root, status, audit errors, last M2C run, last C2M run, last CV run, whatever

related to #1318, #1319

**Comment by jmartin-sul** [comment]
though we probably won't use them exactly as-is, there are some example queries in [db/README.md](https://github.com/sul-dlss/preservation_catalog/tree/master/db#some-useful-activerecord-queries) that might provide a good basis for the queries that'd be used for this implementation.

**Comment by ndushay** [comment]
this is being closed in favor of #1357 and plans in #1363
