### ISSUE TITLE
Create Process to Begin Writing **Newly Accessioned** Objects to New Storage

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1326]
This is about NEWLY ACCESSIONED objects; not about objects that already exist (on an old storage root, or migrated to a new storage root)

- Do we START prescat using new bricks with this?
- or do this after we've migrated an old storage root or two?
- Do we need to do any special validations or audits?
- Do we need to do anything to confirm additional versions work (beyond "just" the first version)?  
- Do we need to do anything to confirm replicating to cloud works?  that we can reconstitute Moabs sent to cloud?  etc.

Actually doing it may be as simple as 
- having new brick ready to go, and 
- following Tony's instructions for adding a new storage root (https://docs.google.com/document/d/1waEsPEYHUNui06XCdwzeMPopWt-wePagKchabDf4XkU/ ).

**Comment by ndushay** [comment]
@tallenaz says we would follow instructions 2-8 here:  https://docs.google.com/document/d/1waEsPEYHUNui06XCdwzeMPopWt-wePagKchabDf4XkU/edit

and it has to be the highest numbered storage root.

Note that we need to address #1376 before we do this *or* not migrate existing Moabs onto the highest numbered storage root.

**Comment by ndushay** [comment]
in response to:  “We would love to write new Moabs to new storage sooner rather than later”

email from Julian 2-14-2020:

> The next storage brick pair can’t go live for new data until we’ve built, validated and deployed the first pair, and got enough comfort that it’s working as expected. Once the first brick pair is live, our next priority is to build the second brick pair for migrated content. After that we can build a third brick pair for new content. As a result of that, I expect new content to go to a brick sometime around the end of April/early May (week 8+).

**Comment by jmartin-sul** [comment]
i think we want an answer on #1392 before starting this

**Comment by aaron-collier** [comment]
Is this actionable now? #1392 has been answered and closed? However I'm unclear on the status of the new storage roots that would need to be available for this.

**Comment by jmartin-sul** [comment]
i think this is actionable, and i suspect that the instructions will end up being "mount the storage on the new brick as an NFS share according to the usual instructions for adding a new storage root" (for which i believe there's a consul doc?).  the meat of the ticket might just be:
- [ ] confirm with @julianmorley that the plan is still to put storage from the new bricks into the list of storage roots, for newly accessioned/versioned content, before old content is cut over to the new storage.
- [ ] confirm with @tallenaz that the docs for adding a new storage root cover this.
- [ ] confirming that the docs for adding a storage root are up to date (e.g. they account for the new tech metadata service, which mounts the storage roots as read-only and uses the moab-versioning gem to find moabs for tech MD analysis).

if you hit any snags, we can pair, or you can kick the ticket back to me to make it more actionable, or whatever seems appropriate.
