### ISSUE TITLE
Create Process to Sunset an Old Storage Root

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1327]
- when is infrastructure ready to sign off?
- when is SDR manager ready to sign off (if needed)?
- when is ops ready to sign off?

storage root 1 will probably need to be handled differently.  see issue #1328

**Comment by justinlittman** [comment]
This process would be after the process for migrating an individual storage root (#1332).

**Comment by jmartin-sul** [comment]
we can't embark on any of the actual sunsetting yet, but i think we can start thinking up the process for it.  will move to the ready column.  if this ticket gets picked up, and work hits a point where we're blocked by inability to test or no storage migrations having happened yet, we can move it back to the backlog.

**Comment by ndushay** [comment]
Note:  an initial discussion about this is currently slated for 2020-02-24.

**Comment by ndushay** [comment]
In response to: “How long after migration can we keep old storage root data around?”

Julian emailed on 2-14-2020:

>6220 content can be kept around until October. 8040 content will need to be cleared off within a week or two of migration; we need the space so the 8040 can receive other content from the 6220.

6220 content is storage roots 2-7 (and 1)
8040 content is storage roots 8-2x

**Comment by jmartin-sul** [comment]
i think the process, in order, is:
- [ ] 1. for a given piece of hardware (i.e. the 6220 or the 8040), we have copied all of its preservation storage root content to a new storage brick.
- [ ] 2. for all of the storage roots on the hardware to be retired:
  - [ ] all of the production preservation_catalog DB records for moabs that have been copied to the new storage hardware have been migrated to point to their new home on the storage brick.  this is done in bulk for each migrated storage root using a `rake` task (see https://github.com/sul-dlss/preservation_catalog/blob/master/.github/ISSUE_TEMPLATE/storage-migration-checklist.md).
  - [ ] infra dev and ops have confirmed, via e.g. checksum validation of all moved moabs (as outlined in the aforementioned checklist) that the copied content landed safely on the new storage, with no degradation compared to the original moabs.
- [ ] 3. our repository manager (@andrewjbtw) is satisfied that the migrated preservation content has landed safely in its new home and that the preservation_catalog records for the migrated moabs have also been properly updated to point to the new storage location.  i assume this confirmation will happen via a combination of discussing the migration attempts with devs/ops, and spot checking results himself, but he can correct or flesh out this part as needed.

added context from @julianmorley via slack:
> We will have a few weeks after 4/24 _[the first production migration weekend]_ before we’ll need to reclaim disks. I’d say the deadline to have this first batch of 12 reclaimed (so: signed off and wiped) is 5/30, which implies a sign-off by mid-May.
>
> The driver is we need ~250TB of space on the 8040 for LOCKSS migrations, starting in June.

@julianmorley says the first round of migrations will be these disks:
* services-disk02
* services-disk03
* services-disk04
* services-disk05
* services-disk06
* services-disk07
* services-disk08
* services-disk09
* services-disk10
* services-disk11
* services-disk12
* services-disk17

there will be a dry run of this on a specifically provisioned migration test instance of preservation_catalog (but connected read-only to actual production storage) on 2020-04-08.  if all goes well with the dry run, the first actual production migration will be the weekend of 2020-04-24.

* meta-ticket for the dry run:  https://github.com/sul-dlss/preservation_catalog/issues/1462

* ticket for retiring the 6220:  
* ticket for retiring the 8040:

**Comment by jmartin-sul** [comment]
i'm going to close this ticket in favor of the more specific tickets linked in the prior comment.
