### ISSUE TITLE
Create Process for Migrating Storage Root 1

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1328]
** We need a way to put this data on a new brick but not bring it into prescat.**
** We need a process for sunsetting OLD storage root 1**

It may be that Julian already has a plan for ^^, and the rest of this ticket can be postponed until after storage migration MVP.

(or perhaps ops has the above covered and this will not be not needed as part of 2020 storage migration MVP?)

For storage root 1:
 - Not in prescat
 - Not Moabs, but bags
 - Not *all* old google books?
    - **do we want to put non "old google book bags" into prescat?**   See text below.
 - Also: Which old google books are here that we are unable to download from google now?

FYI: There are details for one way to convert the bags to Moabs in this document: https://docs.google.com/document/d/1etLnmFK07u2RfPcQcDVBNnOkq53bsdTSbbHTY2gPB38/

(more info in the doc, but here is the bulk of how to convert -- which, if being tackled, might be a separate ticket)

"There is already code in the moab-versioning gem that can create all the missing files (AND presumably adjust signatureCatalog.xml to include versionMetadata.xml).  Then we would have a “deposit bag” that is ready to become an official version in the Moab.  We could essentially run the following ingest robot steps to turn the object’s deposit bag into a Moab version v0001:

- validate-bag - we want to make sure we have all we need to create a proper Moab v0001
- verify-apo - this checks for the APO as a Moab object
- update-moab - this turns the deposit bag into Moab v0001
- update-catalog - this updates the new Preservation Catalog
- Ingest-cleanup - not sure how much of this step we need. “cleans up the ingest workspaces and signals DOR accessioning that Ingest is completed by updating an accessioning WF step.”

"A little bit of script setup would be needed to ensure we use the bag in its current location and to ensure we write v0001 to the correct new location to make these object into valid moabs.  Otherwise, this should be straightforward."

**Comment by justinlittman** [comment]
Per discussion migrating store root 1 will be handled by Ops. No Infra work is required.
