### ISSUE TITLE
Do We Remove Existing Validation Dates In Migration Rake Task?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1329]
when we set a preserved object status to "unknown" as part of the rake task in #1322, will we also want to remove existing validation dates?

- will removing the dates ensure the full validation is run?
- is there any value in keeping the old validation dates?

Pre-req for #1322

**Comment by justinlittman** [comment]
I'd suggest that we should remove the existing validation dates. The validation date refers to validation of the old set of bits on the old storage root and thus is incorrect, as the moab record now refers to the new set of bits on the new storage root, which has not been validated.

The old validation dates will exist in a database backup, should we for some reason need them.

I don't believe that removing the validation date will ensure that CV is run; CV is automatically queued by changing the status.

**Comment by justinlittman** [comment]
Decision is to remove these dates.
