### ISSUE TITLE
test rake task for migrating db from individual old root to new storage root on stage

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1354]
We will probably need to test this a few times, so it *may* be prudent to:

(Note that this should inform the process to migrate an individual root in prod, which is #1332 - the nascent checklist there could inform this ticket and vice versa)

- have a rake task to create fixture data on an existing stage root
     - some objects with clean audit status for CompleteMoab
     - some objects with dirty audit status for CompleteMoab (check in prod db/Argo to see if we have any of these now to be realistic
     - do we need to worry about  replicated zips and so on?
- have a repeatable way (temporary rake task?  script?) to copy all the moabs from one existing storage root on stage to another.
     QUESTION largely for @jmartin-sul:  do we need to have a process for adding new storage bricks to prescat, esp if they are not "last" root?
- try our existing reports for the OLD storage root before running the rake task
    - get reports - are they accurate?  do they help? (e.g. from PR #1347, from code to be written for issues #1318 and #1319)
-  try our existing rake take (from PR #1339) and see if it's complete
    - ensure that moab validation and checksum validation is triggered for object at new location
    - ensure new results are ok
    - get reports AFTER migration (after validation?  do we wait?) - are they accurate?  do they help? 
     - see if prescat is "happy" with new root assignment for the object (not sure what else we need to check)
     - discover what else we need to do for migrating an individual root, and ticket it ...

This list (the above, but improved) may spawn tickets for subtasks.   At a minimum, we need a checklist of what we need to do.

I am suggesting this checklist should be in a wiki page, google doc, or google sheet, rather than in a ticket - we want to be able to have a checklist to follow for each storage root, and an ability to actually check it off...

**Comment by ndushay** [comment]
This is now part of #1377, i would say.

**Comment by jmartin-sul** [comment]
@ndushay said:
> This is now part of #1377, i would say.

i think i'd agree, so i'm going to go ahead and close this.  feel free to open if that was the wrong thing to do.
