### ISSUE TITLE
Send preservationAuditWF events to the event service

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/preservation_catalog#1357]
Currently preservationAuditWF is not used as a workflow, but as a log of problems.  It is not sending the object version, which is now a deprecated call in workflow_service_rails (https://app.honeybadger.io/projects/58890/faults/60031582).  Can we change to use the event service in dor-services-app now?

**Comment by mjgiarlo** [comment]
Yes, let's do this.

**Comment by jmartin-sul** [comment]
splitting this into two tickets.  this ticket is now just about sending events to the event service.  there is a new (currently blocked, slightly ambiguous) ticket for un-coupling from `preservationAuditWF`.  see #1363.

**Comment by ndushay** [comment]
@mjgiarlo is this a dup of #1351  ?

I think we want to send passing AND error audit results to event service.

**Comment by jmartin-sul** [comment]
ah yes, had meant to close one or the other of this and #1351 as a dupe.  but also i agree with @ndushay that the respective scopes of the two tickets differ slightly and that the wider scope of #1351 is what we want to do.

as noted in https://github.com/sul-dlss/preservation_catalog/issues/1363#issuecomment-586012857, de-coupling preservation from workflow service is a bit trickier than just sending events to the event service and somehow exposing audit errors -- we actually do want to block versioning if the preserved object has issues (even if that wasn't part of the original intent of sending errors to WFS).

no preference as to which ticket gets kept open, now that this one has been updated with the relevant info.

my gut feeling without really digging into the code again is that we want to push events from [`AuditResults#report_results`](https://github.com/sul-dlss/preservation_catalog/blob/master/app/services/audit_results.rb#L152-L173) and where ever we manually notify honeybadger.

hopefully whatever work you've put into this so far can be extended to the slightly wider scope w/o too much trouble!
