### ISSUE TITLE
reports: allow user entered info in title of audit_errors report and some general touchups

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1367]
### General Touchups:
- [x] status_details (with an s) for report name and rake task, please
- [x] colons in timestamp are awkward in filename on linux box.  remove or change to hyphen or something (just a `gsub` after iso8601 call on DateTime)
- [ ] ~~can we get rid of trailing comma on each data line easily?~~
- [x] allow user entered string for easier file name differentiation between runs (see below)
- [x] remaining feedback from #1365 that wasn't addressed as part of that PR's revisions (see comments on that PR linking to this issue)

### Current title of output file:

`MoabStorageRoot_fixture_sr1_audit_errors_2020-02-12T21:57:42Z.csv`

Breaking this down:
`MoabStorageRoot` - constant for all reports;  dead space as far as I personally am concerned
`fixture_sr1` - name of moab storage root - awesome, keep
`audit_errors` - what kind of report (audit_errors, druids, druid_details) - awesome, keep
`2020-02-12T21:57:42Z` - timestamp - awesome, keep.

What I would like instead:

`fixture_sr1_audit_errors_myTextHere_2020-02-12T21:57:42Z.csv`

That is, i want to provide an argument in the rake task like this:

```
rake prescat:reports:msr_audit_errors[fixture_sr1, naomi-after-lunch]
```

in order to get this:

`fixture_sr1_audit_errors_naomi-after-lunch_2020-02-12T21:57:42Z.csv`

Why?  because the error details in the db after M2C, C2M and CV checks differ, and I want to easily be able to indicate which ones I will be looking at.

TLDR; 

Examples:

after M2C:
```
druid,previous storage root,current storage root,last checksum validation,last moab validation,status,status details
bj102hs9687,,fixture_sr1,2020-02-12 01:10:56 UTC,2018-07-10 17:05:58 UTC,invalid_checksum,validate_checksums (actual location: fixture_sr1; ) Moab file spec/fixtures/storage_root01/sdr2objects/bj/102/hs/9687/bj102hs9687/v0001/data/metadata/versionMetadata.xml was not found in Moab signature catalog spec/fixtures/storage_root01/sdr2objects/bj/102/hs/9687/bj102hs9687/v0003/manifests/signatureCatalog.xml
bj102hs9688,,fixture_sr1,2019-12-13 12:55:59 UTC,2019-12-13 12:31:41 UTC,unexpected_version_on_storage,
```

status of bj102hs9688 is `unexpected_version_on_storage`, no status details

after C2M:
```
druid,previous storage root,current storage root,last checksum validation,last moab validation,status,status details
bj102hs9687,,fixture_sr1,2020-02-12 01:10:56 UTC,2018-07-10 17:05:58 UTC,invalid_checksum,validate_checksums (actual location: fixture_sr1; ) Moab file spec/fixtures/storage_root01/sdr2objects/bj/102/hs/9687/bj102hs9687/v0001/data/metadata/versionMetadata.xml was not found in Moab signature catalog spec/fixtures/storage_root01/sdr2objects/bj/102/hs/9687/bj102hs9687/v0003/manifests/signatureCatalog.xml
bj102hs9688,,fixture_sr1,2019-12-13 12:55:59 UTC,2019-12-13 12:31:41 UTC,online_moab_not_found,check_catalog_version (actual location: fixture_sr1; actual version: 0) db CompleteMoab (created 2019-12-13T12:31:41Z; last updated 2019-12-13T12:55:59Z) exists but Moab not found && CompleteMoab status changed from unexpected_version_on_storage to online_moab_not_found
```

status of bj102hs9688 is `online_moab_not_found`, with status details

after CV:
```
druid,previous storage root,current storage root,last checksum validation,last moab validation,status,status details
bj102hs9687,,fixture_sr1,2020-02-12 22:04:24 UTC,2018-07-10 17:05:58 UTC,invalid_checksum,validate_checksums (actual location: fixture_sr1; ) Moab file spec/fixtures/storage_root01/sdr2objects/bj/102/hs/9687/bj102hs9687/v0001/data/metadata/versionMetadata.xml was not found in Moab signature catalog spec/fixtures/storage_root01/sdr2objects/bj/102/hs/9687/bj102hs9687/v0003/manifests/signatureCatalog.xml
bj102hs9688,,fixture_sr1,2019-12-13 12:55:59 UTC,2019-12-13 12:31:41 UTC,online_moab_not_found,check_catalog_version (actual location: fixture_sr1; actual version: 0) db CompleteMoab (created 2019-12-13T12:31:41Z; last updated 2019-12-13T12:55:59Z) exists but Moab not found && CompleteMoab status changed from unexpected_version_on_storage to online_moab_not_found
```

bj102hs9688 - same as C2M in this example ...

**Comment by jmartin-sul** [comment]
@ndushay asked:
> can we get rid of trailing comma on each data line easily?

i don't see any extraneous trailing lines in my test CSV output.  perhaps you're seeing this on rows that have a null value for the last column?  if so, i think we want the trailing comma so that we have valid and regular CSV output.  and anyway, we're delegating the CSV writing to the CSV library, and i'd be hesitant to start messing with what it's writing.

if i'm mis-understanding things definitely correct me -- if we actually have totally extraneous trailing commas, i suspect we're building the column list incorrectly or something.

**Comment by ndushay** [comment]
if i see a trailing comma in a report, i'll triple check that it's missing the last field;  I thought I saw a bunch of examples but can't find one now, so I suspect you're correct, John.
