### ISSUE TITLE
explore using github template for cutover checklist

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1378]
Do a partial mockup of github template for cutover weekend checklist;  see if we like it better than using spreadsheet.

**Comment by mjgiarlo** [comment]
@ndushay Hi! Anything left to do for the exploration?

**Comment by ndushay** [comment]
@jmartin-sul - I prefer the github template, personally.  Shall we close this ticket?

**Comment by jmartin-sul** [comment]
> @jmartin-sul - I prefer the github template, personally. Shall we close this ticket?

yup, i like the GH issue template, let's go with that, closing this issue...
