### ISSUE TITLE
ensure none of these write/update prescat storage or database

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1380]
We need to know what processes must be stopped as part of the preservation storage migration.  There are four consumers of the preservation-client gem, per https://github.com/sul-dlss/preservation-client/network/dependents.  We know preservation-robots update preservation storage.  We want to know if any of the other preservation-client consumers update preservation (database or storage):

- argo
- common-accessioning
- dor-services-app

You should be able to figure out how the preservation client is instantiated in the code and where it is used.  Which requests is it making?  If you list those in a comment on this ticket, that should be sufficient.

**Comment by aaron-collier** [comment]
- Argo appears to only read version & checksum
- common-accessioning writes metadata: https://github.com/sul-dlss/common-accessioning/blob/cb2ed9f6112d9c3759cfab661d2c89e87700a078/lib/robots/dor_repo/accession/technical_metadata.rb#L73

**Comment by ndushay** [comment]
actually, "metadata" is a read:   https://github.com/sul-dlss/preservation-client/blob/master/lib/preservation/client/objects.rb#L65-L71

good to be sure, tho!  keep being thorough!

**Comment by ndushay** [comment]
we think we're going to turn off all the ReST API routes during migration weekends ... but we really don't want to mess this up!

**Comment by aaron-collier** [comment]
I'm pretty sure dor-services-app only reads, here: https://github.com/sul-dlss/dor-services-app/blob/4029dd1eab60903cb92a48b74bc83bdabffd0588/app/services/version_service.rb#L116

**Comment by ndushay** [comment]
so, in summary:

- argo: reads version & checksum
- common-accessioning: reads metadata
- dor-services-app: reads current_version in VersionService

Thanks, @aaron-collier !
