### ISSUE TITLE
Investigate order of searching within moab-versioning roots to find objects

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1392]
For preservation storage migration, we need to know this in order to know the constraints of naming new storage roots (the new bricks), the constraints of removing old storage roots from the config file, and the needed ordering of roots in the config file.

This code will be in the moab-versioning gem.

We indicate roots in config files, e.g. https://github.com/sul-dlss/shared_configs/blob/preservation-catalog-prod/config/settings/production.yml or  https://github.com/sul-dlss/shared_configs/blob/preservation_robots_prod/config/environments/prod.yml.

When we migrate storage roots, we want to know:

- does the root getting NEW moabs have to be last in the config file or have the latest lexical order or ??

- does it search for objects root by root by the order in the config?  or by lexical order?  or ??

- can we use '100' as the number for the first new brick?

- will there be a problem if we remove `services-disk11` while keeping `services-disk10` and `services-disk12` (gaps in the lexical/sorting sequence)

**Comment by aaron-collier** [comment]
We reference/crawl the storage roots in two places, essentially the same way:

```
[1] pry(main)> Settings.storage_root_map.default.to_h.values
=> ["/services-disk02",
 "/services-disk03",
 "/services-disk04",
 "/services-disk05",
 "/services-disk06",
 "/services-disk07",
 "/services-disk08",
 "/services-disk09",
 "/services-disk10",
 "/services-disk11",
 "/services-disk12",
 "/services-disk13",
 "/services-disk14",
 "/services-disk15",
 "/services-disk16",
 "/services-disk17",
 "/services-disk18",
 "/services-disk19",
 "/services-disk20",
 "/services-disk21",
 "/services-disk22"]
[2] pry(main)> Settings.storage_root_map['default'].to_h.values
=> ["/services-disk02",
 "/services-disk03",
 "/services-disk04",
 "/services-disk05",
 "/services-disk06",
 "/services-disk07",
 "/services-disk08",
 "/services-disk09",
 "/services-disk10",
 "/services-disk11",
 "/services-disk12",
 "/services-disk13",
 "/services-disk14",
 "/services-disk15",
 "/services-disk16",
 "/services-disk17",
 "/services-disk18",
 "/services-disk19",
 "/services-disk20",
 "/services-disk21",
 "/services-disk22"]
```

This lists then in the order in which they are in the config file.

**Comment by aaron-collier** [comment]
After investigation and experimentation in with @ndushay and I adjusted the order of the storage roots in the shared_configs for preservation_robots (where deposited items get the storage root that should be used) we identified:

- 1: The last storage root in the config is used, unsorted
- 2: no searching
- 3: we can use any naming we wish
- 4: removing storage roots should be of no impact.
