### ISSUE TITLE
document any moab remediation processes that might be re-usable

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1396]
Start a Preservation Catalog wiki page for capturing re-usable moab remediation notes.  These should be investigative procedures and remediation procedures that developers and repository admins can use for approaching preservation objects that fail audits in the future.

To prevent clutter, if a procedure will really only be used once, it might be better to keep it in the issue.

But it may also be a good idea to link remediation issues from the wiki, or at least to try and consistently tag them, for easier searching in the future.

I suspect that most remediations will be unique and hard to fully automate, but I also suspect it will be easier to approach any new remediation if there's some documentation about the types of problems we've encountered and solutions we've used.

**Comment by jmartin-sul** [comment]
i'm not sure using the zenhub blocking connection is the right approach here:  but starting this should be blocked on at least _one_ of the linked issues.

but this could be started as soon as we've closed any of:
* #1324 ([migration MVP] Analyze Existing Audit Errors (old storage roots))
* #1192 (checksum validation failure auditing moab for expunged object fk847cz0044)
* #1394 (extraneous technicalMetadata.xml in a couple moabs on storage root 2?)
* #1393 (extraneous versionMetadata.xml file in v1 of 504 moabs on storage root 2)
* #1395 (preservation copy of vq518cf9512 (service disk 8) has a number of issues)

**Comment by jmartin-sul** [comment]
though it seems likely we'll want to collect documentation from most (maybe all) of the resolutions of those issues.

**Comment by jmartin-sul** [comment]
probably can't quite complete this, but i think we can get started on it now

**Comment by jmartin-sul** [comment]
removed the blocker about re-archiving, but ultimately that should be part of this documentation too

**Comment by ndushay** [comment]
@jmartin-sul if there is further work to be done on this ticket, please ticket separately;   personally, I would be okay just closing this ticket.
