### ISSUE TITLE
qv168mz2031 failed to replicate to aws_s3_west_2

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1404]
resque console's failed jobs queues show one entry for the `s3_us_west_2_delivery_failed` queue at the moment:
```
Worker
    preservation-catalog-prod-04.stanford.edu:21374 on s3_us_west_2_delivery at 4 days ago
    Retry or Remove
Class
    S3WestDeliveryJob (via ActiveJob) 
Arguments

    ---
    job_class: S3WestDeliveryJob
    job_id: 86812047-46db-4cf6-b390-c6433a2438e4
    provider_job_id: 
    queue_name: s3_us_west_2_delivery
    priority: 
    arguments:
    - qv168mz2031
    - 1
    - qv/168/mz/2031/qv168mz2031.v0001.zip
    - checksum_md5: bff429501b2af468e28db87f3c4390d5
      size: 154180499
      parts_count: 1
      zip_cmd: zip -r0X -s 10g /sdr-transfers/qv/168/mz/2031/qv168mz2031.v0001.zip qv168mz2031/v0001
      zip_version: Zip 3.0 (July 5th 2008)
      _aj_symbol_keys:
      - checksum_md5
      - size
      - parts_count
      - zip_cmd
      - zip_version
    executions: 0
    exception_executions: {}
    locale: en
    timezone: UTC
    enqueued_at: '2020-02-21T00:12:55Z'

Exception
    Aws::S3::MultipartUploadError
Error
    multipart upload failed: The provided 'x-amz-content-sha256' header does not match what was computed.
```

it appears that some bits got flipped when sending the zip file over the wire (since amazon didn't compute the same checksum value for the content as the one we provided).

i think the thing to do is to remove the `ZippedMoabVersion` entry (and any associated zip parts) for the endpoint that failed to get the file successfully, and then to trigger replication for the druid again so that pres cat tries to re-create the zip and push it again.  zip should already be gone from zip temp space since error occurred a few days ago.

**Comment by jmartin-sul** [comment]
similar to #1340

**Comment by jmartin-sul** [comment]
the first thing to do is to see what we have noted in pres cat's database, and what we have archived in the cloud at the moment (and thus, whether this is still an issue).  here are some instructions to get started when looking at replication problems:  https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-a-druid-with-replication-errors

if the moabs are fully replicated to all cloud endpoints, we may just have some database cleanup to do.  if everything is replicated and the database looks good, we should be able to close this without further action.

**Comment by aaron-collier** [comment]
Status on all zip parts is OK:

```
=> [
["qv168mz2031", 1, 1, "aws_s3_west_2", "ok", ".zip", 1, 154180499], 
["qv168mz2031", 1, 1, "aws_s3_east_1", "ok", ".zip", 1, 154180499], 
["qv168mz2031", 1, 1, "ibm_us_south", "ok", ".zip", 1, 154180499]]
```

The part shows up on aws_s3_west_2

```
=> [#<Aws::S3::Object:0x0000000007a3c4b8 @bucket_name="sul-sdr-aws-us-west-2-archive", @client=#<Aws::S3::Client>, @data=nil, @key="qv/168/mz/2031/qv168mz2031.v0001.zip", @waiter_block_warned=false>]
[23] pry(main)> zip_parts_s3_objects.each { |zpart| puts "Key = #{zpart.key} Found = #{zpart.exists?}" }
Key = qv/168/mz/2031/qv168mz2031.v0001.zip Found = true
=> [#<Aws::S3::Object:0x0000000007a3c4b8 @bucket_name="sul-sdr-aws-us-west-2-archive", @client=#<Aws::S3::Client>, @data=nil, @key="qv/168/mz/2031/qv168mz2031.v0001.zip", @waiter_block_warned=false>]```

Also verified all parts are on aws_s3_east_1 and ibm_us_south
