### ISSUE TITLE
report prefixed druids to dor-services-client after audit

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_catalog#1414]
**Describe the bug**
Running checksum audits from the rails console in prescat is producing this error:
```
Dor::Services::Client::UnexpectedResponse: Bad Request: 400 ({"errors":
[{"status":"bad_request","detail":"#/components/schemas/Druid pattern 
^druid:[b-df-hjkmnp-tv-z]{2}[0-9]{3}[b-df-hjkmnp-tv-z]{2}[0-9]{4}$ does not match value:
vq518cf9512, example: druid:bc123df4567"}]}) for vq518cf9512
from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.5.0/gems/dor-services-client-4.16.0/lib/dor/services/client/versioned_service.rb:23:in `raise_exception_based_on_response!'
```

**User Impact**
This may be preventing audits from updating the preservationAuditWF

**Steps to Reproduce, if Known**
Run an audit on a druid and you will probably see this error. I've been running 

```Audit::Checksum.validate_druid('vq518cf9512')``` 

and seeing this for a druid I'm remediating.

**Comment by jmartin-sul** [comment]
see also #1388

**Comment by jmartin-sul** [comment]
related HB alert:  https://app.honeybadger.io/projects/54415/faults/61206835
