### ISSUE TITLE
(PC) moab_storage_controller ... becomes what?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#142]
we currently have `catalog_controller` and `moab_storage_controller` 

will we want a single controller, period?
will we want separate controllers to get info on archive objects vs. online moabs?  Or use an arg?  Or get info by the druid only, and return info on all copies, regardless of endpoint?

**Comment by ndushay** [comment]
per discussion 2017-10-3, we believe we will only need one controller.  The *index* action from moab_storage_controller will be made no-op (as it won't be performant until we run it off the db);  the show action needs to migrate to catalog_controller, and needs to use db data, not go out to the  storage_root.

**Comment by ndushay** [comment]
#### GET /catalog/show/:id
Called from 
- Inventory/Audit process
  - "does this online moab object match expectations?"
- Human getting info about object size, version, endpoints, prez policy, etc.

**Comment by SaravShah** [comment]
druid, storage, size, version, when it was checked, how many preservation copies, and endpoints

**Comment by jmartin-sul** [comment]
we seem happy with `CatalogController` as our only controller at the moment.  closing.
