### ISSUE TITLE
re-introduce code coverage reporting and code coverage diff display for builds

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1429]
it appears that #1427's transition from travis to circle resulted in loss of
- [x] code coverage reporting
- [ ] display of code coverage difference between PR build and master.

#### note the lack of code coverage display on PR build results

<img width="770" alt="Screen Shot 2020-03-09 at 10 07 42 AM" src="https://user-images.githubusercontent.com/7741604/76239754-59ce6d00-61ef-11ea-9d71-df16ff5f6a74.png">

#### and complaint about not knowing where to report coverage results

<img width="630" alt="Screen Shot 2020-03-09 at 10 19 21 AM" src="https://user-images.githubusercontent.com/7741604/76239853-7d91b300-61ef-11ea-86e5-eb7f4a82b9d2.png">

possibly related?

**Comment by ndushay** [comment]
we could also go to codeclimate if folks prefer;  I don't care.

**Comment by justinlittman** [comment]
Hmmm ... travis config didn't reference coveralls at all.

**Comment by ndushay** [comment]
probably put the env vars directly into travis service.

**Comment by jmartin-sul** [comment]
so the other thing i was hoping for, per description, was getting the display of coverage back on the checks section for PRs, so we could easily see the test coverage (including any drops) when deciding whether to merge.

reopening and moving back to ready, @ndushay you definitely shouldn't feel obligated to pick the ticket up again if you're otherwise occupied.

i spent about 20 minutes looking into this last night, and it wasn't obvious to me how to make this happen.  but we have it set up on other projects, so will ask as standup discussion topic.

**Comment by jmartin-sul** [comment]
but thanks much for the switch to code climate and the badge updates, @ndushay!

**Comment by ndushay** [comment]
has there been a PR since you set up the github repo to have a webhook to codeclimate?

**Comment by jmartin-sul** [comment]
> has there been a PR since you set up the github repo to have a webhook to codeclimate?

good question:  it seemed to me that the hook was already there, and that my attempt to add it was essentially a no-op.  but i might have that wrong, so we'll see on the next PR that goes up.  it'd be great if that did the trick.  i can mark this `[HOLD]` and put it in backlog, pending the behavior of the next pres cat PR that goes up.

**Comment by jmartin-sul** [comment]
> has there been a PR since you set up the github repo to have a webhook to codeclimate?

there definitely has been now, and it seems that my attempt to add the codeclimate webhook failed to do the trick:
<img width="780" alt="Screen Shot 2020-03-11 at 1 46 12 PM" src="https://user-images.githubusercontent.com/7741604/76462483-ff740e80-639e-11ea-9df7-902ec4f71ced.png">

removing the hold and putting back in ready col...

**Comment by ndushay** [comment]
https://docs.codeclimate.com/docs/github-pull-requests#section-configuring-summary-comments

**Comment by ndushay** [comment]
![image](https://user-images.githubusercontent.com/96775/76466356-bfb02580-63a4-11ea-9616-76390678fbb0.png)

**Comment by jmartin-sul** [comment]
huh, good to know!  i looked on that page, and i wouldn't have expected that option to have an effect on this issue.

ah!  now that i'm reading the docs, i see that "summary comments" doesn't mean what i assumed it did.

anyway, thanks for the fix and the documentation link!

**Comment by ndushay** [comment]
let's hope this really does fix it.
