### ISSUE TITLE
preservationAuditWF not completing properly

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_catalog#1430]
**Describe the bug**
The preservationAuditWF has recently been sending a lot of error messages to Argo with this error:

```
preservation-audit : validate_checksums (actual location: services-disk11; ) db update failed: #<ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out >
```

**User Impact**
Items can't be updated (i.e. versioned) while this is in error. 

If the error is related to an actual audit failure, this is as it should be. But if the error is from a failure of the workflow to get the correct message from prescat, then it can become a blocker for staff needing to work with these objects. 

Additionally, this error makes it difficult to separate the "real" audit failures from the connection timeouts.

**Object(s) In This Error State**
Most of the items where Argo shows audit errors are in this state:
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=preservationAuditWF%3Apreservation-audit%3Aerror

**Expected behavior**
Only an actual audit failure should hold up this workflow.

**Additional context**
This error started showing up very recently, probably towards the end of last week.

**Comment by andrewjbtw** [comment]
One additional note: these all seem to be items that have not been recently modified. New items/reaccessions do not seem to be triggering this error.

**Comment by andrewjbtw** [comment]
One more data point: all of the items with this error appear to be 100 GB or larger. Maybe the audit reporting is timing out because checksum validation takes so much longer with large files?

**Comment by justinlittman** [comment]
After the db connection fix I re-ran https://argo.stanford.edu/view/druid:bf748mt1617 and it succeeded.

@andrewjbtw assigning to you to determine if can be closed.

**Comment by andrewjbtw** [comment]
Do prescat audits only report back to the preservationAuditWF if there's an error? I'm trying to make sure I understand this well enough to verify that it's working. It does look like it's working. I've audited a few druids today without new errors.

**Comment by jmartin-sul** [comment]
here's a honeybadger alert for a DB connection timeout that looks similar, but not exactly the same:

https://app.honeybadger.io/projects/54415/faults/61920561

```
ActiveJob::DeserializationError: Error while trying to deserialize arguments: could not connect to server: Connection timed out Is the server running on host "preservation-catalog-db-prod-01.stanford.edu" (172.20.206.130) and accepting TCP/IP connections on port 5432? 
```

not clear to me whether this is a new issue for a new ticket, or part of this ticket, but i suspect the latter.  happened from `PartReplicationAuditJob` in the alert referenced by this comment.

**Comment by andrewjbtw** [comment]
Another case of a timed-out audit today:

```ruby
[9] pry(main)> Audit::Checksum.validate_druid('wk609yq1382')
I, [2020-04-06T16:03:31.932455 #5978]  INFO -- : 2020-04-06T23:03:31Z CV validate_druid starting for wk609yq1382
W, [2020-04-06T16:18:58.579982 #5978]  WARN -- : No PreservedObject found for wk609yq1382
I, [2020-04-06T16:18:58.580121 #5978]  INFO -- : 2020-04-06T23:18:58Z CV validate_druid ended for wk609yq1382
ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out
from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:686:in `exec_prepared'
Caused by PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out

from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.5.0/gems/activerecord-6.0.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:686:in `exec_prepared'
```

**Comment by andrewjbtw** [comment]
One more instance of this issue, just a few minutes ago:

```ruby
[3] pry(main)> Audit::Checksum.validate_druid('vf742yx0561')
I, [2020-05-26T13:27:10.823325 #686]  INFO -- : 2020-05-26T20:27:10Z CV validate_druid starting for vf742yx0561
W, [2020-05-26T13:42:37.471045 #686]  WARN -- : No PreservedObject found for vf742yx0561
I, [2020-05-26T13:42:37.471271 #686]  INFO -- : 2020-05-26T20:42:37Z CV validate_druid ended for vf742yx0561
ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out

from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.5.0/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:689:in `exec_prepared'
Caused by PG::ConnectionBad: PQconsumeInput() could not receive data from server: Connection timed out

from /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.5.0/gems/activerecord-6.0.3/lib/active_record/connection_adapters/postgresql_adapter.rb:689:in `exec_prepared'
[4] pry(main)> 
```

An audit on the same druid ran a couple of hours ago without a connection time out, so it's definitely not something that happens consistently even on the same druid.
