### ISSUE TITLE
Checksum report fails on accessioned objects, error from preservation catalog API

### ISSUE THREAD

**Issue by oceanofsound** [sul-dlss/preservation_catalog#1434]
**Describe the bug**
When running a checksum report on a set of accessioned objects, the report will error out.

**User Impact**
Users are unable to do checksum comparisons on large sets of objects in the SDR against those on staging servers.

**Object(s) In This Error State**

n/a

Steps to Reproduce, if Known:

Take an example set of objects, i.e. https://argo.stanford.edu/catalog?utf8=%E2%9C%93&q=%22JIRA+%3A+DIGREQ-1585%22

Bulk action --> new bulk action --> checksum report

**Expected behavior**

On the results page, the total objects and success numbers should be identical. Right now, all objects are failing.

**Screenshots**
2020-03-10 16:40:36 UTC Starting ChecksumReportJob for BulkAction 8594
2020-03-10 16:40:36 UTC ChecksumReportJob got error from Preservation Catalog API (Preservation::Client::UnexpectedResponseError): Preservation::Client.http_response got 400 from Preservation at v1/objects/checksums: {"errors":[{"status":"bad_request","detail":"\"Content-Type\" request header must be set to \"application/x-www-form-urlencoded\"."}]}
2020-03-10 16:40:36 UTC Finished ChecksumReportJob for BulkAction 8594

**Additional context**
n/a

**Comment by peetucket** [comment]
Reproducible from the rails console in argo, confirming the call to preservation_catalog is failing:

```
[lyberadmin@argo-prod-01 current]$ bundle exec rails c production
DEPRECATION WARNING: Passing the environment's name as a regular argument is deprecated and will be removed in the next Rails version. Please, use the -e option instead. (called from <main> at bin/rails:6)
Loading production environment (Rails 5.2.4.1)
[1] pry(main)> pids = ['druid:bb000kg4251','druid:bb000zn0114']
=> ["druid:bb000kg4251", "druid:bb000zn0114"]
[2] pry(main)> csv_report = Preservation::Client.objects.checksums(druids: pids)
Preservation::Client::UnexpectedResponseError: Preservation::Client.http_response got 400 from Preservation at v1/objects/checksums: {"errors":[{"status":"bad_request","detail":"\"Content-Type\" request header must be set to \"application/x-www-form-urlencoded\"."}]}
from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/preservation-client-3.1.0/lib/preservation/client/versioned_api_service.rb:74:in `rescue in http_response'
Caused by Faraday::ClientError: the server responded with status 400
from /opt/app/lyberadmin/argo/shared/bundle/ruby/2.6.0/gems/faraday-0.17.3/lib/faraday/response/raise_error.rb:15:in `on_complete'
[3] pry(main)>
```

**Comment by jmartin-sul** [comment]
i suspect that the issue is similar to https://github.com/sul-dlss/preservation_catalog/pull/1424/files and that the fix might be a similar one around here:  https://github.com/sul-dlss/preservation_catalog/blob/master/openapi.yml#L216-L240

**Comment by peetucket** [comment]
@mjgiarlo this seems related to the fix you did here: https://github.com/sul-dlss/preservation_catalog/pull/1424/files 

but implementing that same change for the checksum method in openapi (and updating the tests in the same way) shows test failures still, see #1436 draft PR

just curious if you had any ideas

**Comment by mjgiarlo** [comment]
@peetucket couple things to check quickly.

first I see you may be injecting the content-type header on GET requests in the request specs, but the openapi change you made only affects POST requests (and GET requests shouldn't need/use content-type headers since those are used to specify the format of the request body and GET requests should not have bodies).

second, you are correctly setting the content-type header to JSON for POST requests, but you may also need to call `.to_json` on the `params` hash (instead of passing along `format: :json`), but you might want to verify that the controller wants/prefers that info to come along as a JSON body vs. query arguments. cc: @jmartin-sul

**Comment by peetucket** [comment]
Thanks for the leads.  Getting closer in #1436 ... (and indeed for some reason we allow either GET or POST for that checksums method, though preservation client always sends a post).  Our tests check for both GET or POST currently.  Now down to 3 failures after allowing for that difference and for being explicit about the params being json.  

Also, I believe the `format: json` is the response, not the request, so is fine as is.

**Comment by mjgiarlo** [comment]
@peetucket :speech_balloon: 
> Thanks for the leads. Getting closer in #1436 ... (and indeed for some reason we allow either GET or POST for that checksums method, though preservation client always sends a post). Our tests check for both GET or POST currently. Now down to 2 failures after allowing for that difference and for being explicit about the params being json.

For the two current failures, have you tried byebugging in and spitting out the value of the response body? That should get you the more specific 400 bad request info.

> Also, I believe the `format: json` is the response, not the request, so is fine as is.

Ah, right: that should ask the server for JSON to be returned. Good call.

**Comment by jmartin-sul** [comment]
> and indeed for some reason we allow either GET or POST for that checksums method

the `POST` approach was allowed after some real-world testing:  it's possible to send a `druid` list that's too big for a URL, and so too big to fit in a single `GET` request.  we added ability to `POST` to that route after errors on large-ish checksum jobs in prod.

we suspected that would happen, but `GET` is what you're supposed to do for a request that doesn't try to change state on the server side (if you're being pedantic about your REST interface), so we went with that in the first implementation.

**Comment by peetucket** [comment]
> > and indeed for some reason we allow either GET or POST for that checksums method
> 
> the `POST` approach was allowed after some real-world testing: it's possible to send a `druid` list that's too big for a URL, and so too big to fit in a single `GET` request. we added ability to `POST` to that route after errors requesting large-ish lists of druids for checksum reporting in prod.
> 
> we suspected that would happen, but `GET` is what you're supposed to do for a request that doesn't try to change state on the server side (if you're being pedantic about your REST interface), so we went with that in the first implementation.

Right, forgot about that.  GET is the right verb but POST is needed due to the large amount of data being sent.

**Comment by peetucket** [comment]
Figured out the last couple of test issues - had to do with a parameter being sent as a boolean in the tests instead of a string.  #1436 ready for review now.
