### ISSUE TITLE
Test effect of turning off accessioning robots on Hydrus (stage/test)

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_catalog#1435]
One component of the preservation storage migration will be temporarily turning off the accessioning robots. We should test what effect this may have on the Hydrus interface, which will help us understand the potential service impact for the migration.

To test:

- [ ] Verify that hydrus-test is hooked up all the way through to prescat stage (Andrew to do this)

Once verified that this will be a useful test:

- [ ] stop google books stage from automatically depositing
- [ ] turn off prescat stage
- [ ] turn off preservation robots stage
- [ ] turn off accessioning robots stage
- [ ] Andrew to try to create, edit items in Hydrus

**Comment by andrewjbtw** [comment]
Assigning to myself while I do the initial hydrus testing.

**Comment by peetucket** [comment]
May not be needed given new migration strategy

**Comment by ndushay** [comment]
hydrus is dead.
