### ISSUE TITLE
migration checklist:  to shut down accessioning robots or not?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1439]
assuming we do want to shut down the accessioning robots, flesh out the instructions here with actual step by step instructions:  https://github.com/sul-dlss/preservation_catalog/pull/1438/files#diff-a9539480162943c784e6e055fb34c87eR95-R97

assigning to @andrewjbtw for confirmation.  if it turns out the answer's no, feel free to close.  otherwise, you can assign it to me, and i will either pick it up if free, or move it back to the ready column if i'm not yet able to pick it up.

**Comment by jmartin-sul** [comment]
@andrewjbtw confirmed here:  https://github.com/sul-dlss/preservation_catalog/pull/1438#issuecomment-598290915

un-assigning andrew, i can write instructions.

**Comment by jmartin-sul** [comment]
after much discussion with @andrewjbtw and @ndushay over the last couple weeks, and some discussion w/ the wider infra team, we feel that it's safe to leave the accessioning robots on, while leaving the preservation robots shut down.  the preservation robots should be the only service outside of pres cat that asks pres cat to update itself, and should also be the only service that manipulates moabs in their storage roots -- all other service communication to pres cat should be read-only, which should be safe, since those reads are for things like getting current version, getting preserved file content, etc.  during the period where moabs location is in flux from pres cat's perspective, serving preserved file content might be flakey, but reads to get current version should be safe.

remaining work for this ticket:
- [ ] amend pres cat's REST route disabling migration branch so that it doesn't disable routes for reading from pres cat (but writes for updating the catalog will be left disabled in that branch).
- [ ] update migration checklist accordingly.

during our dry run of the migration in early april, i'd suggest that we try a small accessioning job while pres cat is in this weird read-only state, to prove to ourselves that this will work out ok.  we expect/hope that things will just harmlessly pile up at the `preservationIngestWF`, waiting for pres robots to be re-enabled.  we don't expect any other robots-related errors, but would hope that any we encounter can be resolved by retrying the errored step.  we shall see during the test run.

either way, @andrewjbtw will message to users that accessioning should be halted for the migration weekend, to prevent large jobs from coming through and filling up the DOR workspace.  we feel that we have less control over e.g. self-deposit activity, and are worried about what might happen if people try to use that while accessioning is fully shut off.

corrections welcome if any of that seems wrong.

**Comment by jmartin-sul** [comment]
@andrewjbtw said that he would still like to test the effect on hydrus of shutting down accessioning robots.  we'll try to pair on testing that later this week or early next week.

**Comment by jmartin-sul** [comment]
since i wasn't previously very familiar with the internal workings of the robots in general, and since we seemed a little uncertain last week about whether the accessioning robots might write to pres cat, i tried to go through the accessioning robot documentation and code to reassure myself that they indeed wouldn't be trying to write to preservation.  bread crumbs:

* https://github.com/sul-dlss/common-accessioning/blob/b20b3303c8b4b33b85a7ffaa3dce01e6b023ff47/lib/robots/dor_repo/accession/sdr_ingest_transfer.rb#L11-L13 (`sdr-ingest-transfer` step, calls dor-services-app)
* https://github.com/sul-dlss/dor-services-client/blob/0490d7b33dcb7f5fb8e6a47e5040c5c63bd208b9/lib/dor/services/client/object.rb#L102-L109 (via dor-services-client)
* https://github.com/sul-dlss/dor-services-app/blob/198eac80fec7bba643b3585e05db931a78aad7e7/app/controllers/objects_controller.rb#L92-L98 (which queues a dor-services-app job)
* https://github.com/sul-dlss/dor-services-app/blob/198eac80fec7bba643b3585e05db931a78aad7e7/app/jobs/preserve_job.rb (which transfers the bag for the new moab version to the deposit space and starts the preservation workflow)
  * https://github.com/sul-dlss/dor-services-app/blob/198eac80fec7bba643b3585e05db931a78aad7e7/app/services/sdr_ingest_service.rb (transfer the bag to the deposit space, but doesn't yet write the new moab version to its final destination or update preservation catalog)
  * https://github.com/sul-dlss/dor-services-app/blob/4029dd1eab60903cb92a48b74bc83bdabffd0588/app/jobs/start_preservation_workflow_job.rb (hand off to preservation robots?)
* https://github.com/sul-dlss/preservation_robots/blob/343f39659fca5a0a6b5352219f097abc93a16fa7/lib/robots/sdr_repo/preservation_ingest/transfer_object.rb (pick up `preservationIngestWF` `transfer-object` step: copies the BagIt bag containing files for a new Moab version (or new Moab), which was created by common-accessioning sdr-ingest-transfer robot, to the deposit location for the Moab. -- see preservation_robots README)


i'm still not clear on how common-accessioning robots pick up the `accessionWF` steps and preservation_robots the `preservationIngestWF` steps, but i am somewhat less worried that we've missed anything that writes to preservation outside of the preservation_robots workers that we plan to shut down.  but for both my own edification and for extra certainty, it would be nice if someone more familiar with the workings of the robots could pair with me for a bit to walk me through the parts i'm unclear on.

**Comment by jcoyne** [comment]
@jmartin-sul I'd be happy to help walk you through that. Ping me when you're online.

**Comment by jmartin-sul** [comment]
a couple things i'd missed that helped tie things together (thanks @jcoyne for pairing and giving pointers):
* stuff gets enqueued by this code in workflow-server-rails for workflow step creation:  https://github.com/sul-dlss/workflow-server-rails/blob/09227014a2cbb56e2c434d9bf447892284f7e848/app/services/workflow_creator.rb#L18-L47 (as a result of a call from [`StartPreservationWorkflowJob`, linked above](https://github.com/sul-dlss/dor-services-app/blob/4029dd1eab60903cb92a48b74bc83bdabffd0588/app/jobs/start_preservation_workflow_job.rb), which does indeed hand off to pres robots)
* the resque-pool.yml configs for common-accessioning and preservation_robots instances are what get those codebases to watch the queues they're supposed to watch (they both hook up to the same redis instance, but work different sets of queues)
  * https://github.com/sul-dlss/common-accessioning/blob/master/config/resque-pool.yml
  * https://github.com/sul-dlss/preservation_robots/blob/master/config/resque-pool.yml

**Comment by jmartin-sul** [comment]
#1454 captures the point about testing accessioning during the storage migration dry run.

closing this issue.
