### ISSUE TITLE
schema refactor: change bigint to int for foreign keys in db

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#144]
Spoke with julian and he said it is overkill to have bigint for foreign keys.

Table Name: Endpoints
Column: endpoint_type_id

Table Name: Endpoints_preservation_policies
Column: preservation_policy_id, endpoint_id

Table Name: Preservation Copies
Column: presreved_object_id, endpoint_id, status_id

Table Name: Preserved Object
Column: preservation_policy_id

However, rails default for table id's is BIGINT so if there is any performance issues in using big int vs int we can change... maybe not the most important ticket right now.

Julian - is for changing type to int from big int

**Comment by ndushay** [comment]
Wait for a performance prob before we fix this;  it is rails default for id columns.

**Comment by atz** [comment]
Yeah, no need to deviate from rails defaults on this.
