### ISSUE TITLE
moved Moabs cause preservationIngestWF and preservationAuditWF errors

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_catalog#1447]
**Describe the situation**
As part of the migration of data from SDR1 to current preservation storage (the SDR services disks), Moabs are being moved from storage roots that don't have available space to roots that do have available space. This is being done this way because

1. The druids were created many years ago and are already in use for PURLs displaying JP2s
2. The preservation master TIFs were not migrated at that time
3. In the intervening years the storage roots have filled to a point where the TIFs cannot all be added to the druids in their original locations

The migration workflow was set up last year to follow these steps:

1. Move an existing Moab to a storage root with enough space
2. Accession the preservation files (usually one big tar.gz) to that Moab
3. Update prescat with the new location

However, these new accessions are hitting errors

1. at `update-catalog` in the `preservationIngestWF`, probably because prescat needs to know the new location before this step can be completed
2. at `preservation-audit` in the `preservationAuditWF`, probably again because prescat needs to know about the new location for an audit to pass

In order for the migration to move forward, we need to:

1. Work out how to update prescat so that in-progress items can keep moving through the workflows
2. Determine whether to change the order of the SDR1 migration steps given changes in the preservation system in the time since the SDR1 migration workflow was set up.

**Important additional context**

Items caught in the preservationIngestWF remain on the `/dor` workspace without being cleaned up until accessioning is complete. This puts a higher priority on at least getting items past that workflow step because there is a risk of filling up the `/dor` workspace with in-process migrated content.

**Comment by jmartin-sul** [comment]
discussed w/ andrew.  will do a bit of refactoring to make an existing method for moab migration more accessible for rails console users.  then that can be run manually on a `CompleteMoab` object from rails console before step 1 ("Move an existing Moab to a storage root with enough space") in the procedure outlined above.  or between steps 1 and 2.
