### ISSUE TITLE
document how to expunge a moab and leave an valid moab stub in its place

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1449]
arguably could be covered under #1396, but i wanted to call out this use case specifically, since it's kind of a pain, and since the desired end result is different from other moab remdiations.

useful comments from an issue dealing with the expungement (and initial validation failures due to partial expungement) of a couple of specific moabs:

* https://github.com/sul-dlss/preservation_catalog/issues/1192#issuecomment-589908067
* https://github.com/sul-dlss/preservation_catalog/issues/1192#issuecomment-596769939
* https://github.com/sul-dlss/preservation_catalog/issues/1192#issuecomment-600911329

at a glance, i didn't see this mentioned in those tickets, but i believe some cleanup of workflow service data for the object is needed.

**Comment by jmartin-sul** [comment]
possible locations for this documentation:
* pres cat wiki
* pres cat readme
* consul

i think pres cat wiki would be my vote.

**Comment by jmartin-sul** [comment]
#1396 is the general remediation documentation ticket

**Comment by ndushay** [comment]
@jmartin-sul please close this if no longer needed, or put it into the backlog for this workcycle and in the presnotes for the documentation storytime.

**Comment by andrewjbtw** [comment]
I would close this as there is no longer a possibility of leaving a moab stub following expunge. But we do need an actual, supported, official, non-manual, way to expunge.

**Comment by ndushay** [comment]
I'm closing this.  Andrew - I'm not even sure where a ticket should go for the "actual, supported, official, non-manual, way to expunge an object".  Maybe ... dor-service-app for lack of a better place????
