### ISSUE TITLE
[UBER] storage migration dry-run, 2020-04-08

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1462]
we will do a dry run of the first round of storage migration, on Apr 8, 2020.  the disks to be migrated will be:
* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues/1478)
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues/1477)
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues/1476)
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues/1475)
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues/1474)
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues/1473)
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues/1472)
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues/1471)
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues/1470)
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues/1469)
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues/1467)
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues/1466)

we will spawn a [migration checklist](https://github.com/sul-dlss/preservation_catalog/blob/master/.github/ISSUE_TEMPLATE/storage-migration-checklist.md) ticket for each storage root, which i'll link to this issue.

if the dry run goes well, we'll do the actual production migration for the same disks on 2020-04-24.

**Comment by ndushay** [comment]
## Before HandOff To Ops

#### Final Pre-Cut-Over Reports

* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues/1478)
  - [x] generate final pre-cutover report for objects with error status ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,b4_cutover]```
  - [x] get list of druids on storage root ```RAILS_ENV=production bundle exec rake prescat:reports:msr_druids[storage_root_name,druids_b4]```
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues/1477)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues/1476)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues/1475)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues/1474)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues/1473)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues/1472)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues/1471)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues/1470)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues/1469)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues/1467)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues/1466)
  - [x] generate final pre-cutover report for objects with error status 
  - [x] get list of druids on storage root

#### Tell PresCat About New Storage Root

- [ ] update shared_configs for prescat with the new storage root information

  - [ ] create a shared_configs PR (***to base branch `preservation-catalog-prod`***) that adjusts storage root information.

    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added, and the old storage root entry removed

      ```yml
      storage_root_map:
        default:
          # services-disk02: '/services-disk02' # lines to be removed, left here for illustrative purposes
          # services-disk03: '/services-disk03'
          services-disk04: '/services-disk04'
          <snip>
          services-disk22: '/services-disk22'
      ```
  - [ ] have someone merge shared_configs PR (if possible, see note at top)

- [ ] use capistrano to make prescat aware of new shared_configs

    ```sh
    bundle exec cap prod shared_configs:update
    bundle exec cap prod passenger:restart
    ```

- [ ] if you added a new storage root (the first time migrating data to a particular new storage brick), you will need to add the root to the prescat db (run this from your laptop):

    ```sh
    bundle exec cap prod db_seed
    ```

    (yes, it's `db_seed` via capistrano)

**Comment by ndushay** [comment]
## Just Before Handoff To Ops

#### Migrate DB Moabs to New Storage Roots

For each root being migrated:
```
RAILS_ENV=production bundle exec rake prescat:migrate_storage_root[services-disknn,pres-01]
```

* [services-disk02](https://github.com/sul-dlss/preservation_catalog/issues/1478)
  - [x] migrate objects on storage root in db
* [services-disk03](https://github.com/sul-dlss/preservation_catalog/issues/1477)
  - [ ] migrate objects on storage root in db
* [services-disk04](https://github.com/sul-dlss/preservation_catalog/issues/1476)
  - [ ] migrate objects on storage root in db
* [services-disk05](https://github.com/sul-dlss/preservation_catalog/issues/1475)
  - [ ] migrate objects on storage root in db
* [services-disk06](https://github.com/sul-dlss/preservation_catalog/issues/1474)
  - [ ] migrate objects on storage root in db
* [services-disk07](https://github.com/sul-dlss/preservation_catalog/issues/1473)
  - [ ] migrate objects on storage root in db
* [services-disk08](https://github.com/sul-dlss/preservation_catalog/issues/1472)
  - [ ] migrate objects on storage root in db
* [services-disk09](https://github.com/sul-dlss/preservation_catalog/issues/1471)
  - [ ] migrate objects on storage root in db
* [services-disk10](https://github.com/sul-dlss/preservation_catalog/issues/1470)
  - [ ] migrate objects on storage root in db
* [services-disk11](https://github.com/sul-dlss/preservation_catalog/issues/1469)
  - [ ] migrate objects on storage root in db
* [services-disk12](https://github.com/sul-dlss/preservation_catalog/issues/1467)
  - [ ] migrate objects on storage root in db
* [services-disk17](https://github.com/sul-dlss/preservation_catalog/issues/1466)
  - [ ] migrate objects on storage root in db

**Comment by ndushay** [comment]
### Ops Runs with the Baton

Ops will now perform such tasks as the following:

- final migration of data from old storage root to new
- migrated content moved to final location on new brick (see #1376 )
- apply puppet PR to add new brick to preservation robots and prescat as needed
- unmount the old storage root's NFS volume so that pres cat no longer has access to the contents, leaving empty sdr2objects and deposit directories in the path that previously mounted the storage root contents. (this will make the contents of the old storage invisible to pres cat without deleting the files where they actually reside)
- add resque workers (for CV and M2C to be run on new brick)?
- more ops-y things
- notify us the data is now available in its new home.

**Comment by ndushay** [comment]
## Back to Devs After Ops Says Data Available

### Confirm that the old storage root's NFS volume has been unmounted

The migrated moabs should no longer be visible in the old location (e.g., if migrating off of services-disk02, /services-disk02/sdr2objects should be present, but empty -- its moabs should only be available from the migration's target storage location). This will prevent pres cat from seeing the same moab in two places, which is currently unsupported.

**Comment by ndushay** [comment]
## CV Report After Migration

- [ ] confirm that CV workers for newly migrated objects are running via the resque GUI: https://preservation-catalog-prod-01.stanford.edu/resque/overview
- [ ] possibly Ops has added workers and the other resources they need (CPU?)

Run CV, then generate report.  We will probably overwhelm the workers, so keep an eye out for resque failed jobs and the like

* pres-01:
    - [ ] CV run completed
    - [ ] CV error report run ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,cv_after]```
    - [ ] CV errors manually reviewed - no new errors

**Comment by ndushay** [comment]
## M2C Report After Migration

M2C reports should be run **after** CV reports.

* pres-01:
    - [ ] M2C run completed
    - [ ] M2C error report run ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,m2c_after]```
    - [ ] M2C errors manually reviewed - no new errors

**Comment by ndushay** [comment]
## After Migration Success

### Restore Preservation Catalog Archival Workers, ReST API and weekend crons

- [ ] create a shared_configs PR (***to base branch `preservation-catalog-prod`***) that reverts the worker changes made above, and keeps the new storage root config.

    `config/resque-pool.yml` should look like this:
    ```yml
    c2m: 6
    checksum_validation: 6
    ibm_us_south_delivery: 6
    m2c: 6
    moab_replication_audit: 3
    part_audit_aws_s3_east_1: 3
    part_audit_aws_s3_west_2: 3
    part_audit_ibm_us_south: 3
    results_recorder: 6
    s3_us_east_1_delivery: 6
    s3_us_west_2_delivery: 6
    zip_endpoint_events: 6
    zipmaker: 6
    zips_made: 6
    ```

- [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] deploy `master` branch of preservation_catalog to prod

    ```sh
    bundle exec cap prod deploy
    ```

- [ ] confirm there are archival workers running via the resque GUI: https://preservation-catalog-prod-01.stanford.edu/resque/overview
- [ ] confirm the ReST routes are available (e.g. go to https://preservation-catalog-prod-01.stanford.edu/v1/objects/wr934ny6689)
- [ ] confirm there are weekend cron jobs, especially CV

      Note that cron jobs are deployed on preservation-catalog-prod-02.

      ```sh
      bundle exec cap -z preservation-catalog-prod-02.stanford.edu prod ssh
      crontab -l
      ```

      there should be a line with `validate_expired_checksums!` in it.

- [ ] (Ops) turn on nagios alerts for preservation_catalog prod boxes

### Restore Preservation Robots Workers

- update shared_configs for preservation robots with the new storage root information

  - [ ] create a shared_configs PR (***to base branch `preservation_robots_prod`***) that adjusts storage root information.

    `moab.storage_roots` in `config/environments/prod.yml`  should have the target storage location on the new brick added, and the old storage root entry removed

      ```yml
      moab:
        storage_roots:
          # - '/services-disk02' # lines to be removed, left here for illustrative purposes
          # - '/services-disk03'
          - '/services-disk04'
          <snip>
          - '/services-disk23'
          - '/pres-01'
      ```
  - [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] deploy `master` branch of preservation_robots to use the new shared_configs and to turn the workers back on

    ```sh
    bundle exec cap prod deploy
    ```

  - [ ] confirm your capistrano logs show the shared_configs being updated

  - [ ] confirm there are preservation robots workers available via the resque GUI:  https://robot-console-prod.stanford.edu/workers

- [ ] (Ops) turn on nagios alerts for preservation_robots prod boxes

### Update shared_configs for technical-metadata-service

- [ ] update shared_configs for technical-metadata-service with the new storage root information

- [ ] create a shared_configs PR (***to base branch `dor-techmd-prod`***) that adjusts storage root information.

    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added, and the old storage root entry removed

      ```yml
      storage_root_map:
        default:
          # services-disk02: '/services-disk02' # lines to be removed, left here for illustrative purposes
          # services-disk03: '/services-disk03'
          services-disk04: '/services-disk04'
          <snip>
          services-disk23: '/services-disk23'
          pres-01: '/pres-01'
      ```

  - [ ] deploy `master` branch of technical-metadata-service to use the new shared_configs

    ```sh
    bundle exec cap prod deploy
    ```

  - [ ] confirm your capistrano logs show the shared_configs being updated

**Comment by ndushay** [comment]
## After Cutover Weekend

- [ ] when M2C is done, generate an error report and compare it with the `m2c_b4` error reports for the migrated roots.

- [ ] confirm migrated objects can be updated 

- [ ] confirm new objects are flowing through preservation_robots steps and are being added to preservation_catalog

- [ ] watch for Honeybadger errors from preservation_robots and from preservation_catalog

- [ ] watch for preservationAuditWF errors (via Argo)

**Comment by jmartin-sul** [comment]
i think this is done, and i'll make the last of the edits that came out of this test on #1465.  first real migration is scheduled for this weekend.
