### ISSUE TITLE
MOAB_NOT_FOUND should probably be in the AuditResults::HONEYBADGER_REPORT_CODES list?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1483]
this seems like a serious and unexpected situation.  we update the `status` on the `CompleteMoab` (`complete_moabs` entry) when this is detected, and we log it and send to workflow service and event service, but it appears that we don't proactively send a honeybadger alert.

discovered while working on #1480/#1481.  tried just adding to the list, got some unexpected test failures around unexpected network requests.  likely not a difficult fix, but didn't have the time to chase it down on thurs/fri of last week.

**Comment by jmartin-sul** [comment]
happy to close this if we did this intentionally, and i'm forgetting why

**Comment by andrewjbtw** [comment]
@jmartin-sul will verify if this is still a problem.

**Comment by ndushay** [comment]
Here's what I can think of:

- would we get a MOAB_NOT_FOUND when we're creating the first version of an object, which we wouldn't want to report to honeybadger??
- other situations related to the above case?

Also, is this PR relevant, which is about looking for a moab on a diff disk?   PR #1271

**Comment by jmartin-sul** [comment]
> Here's what I can think of:
> 
>     * would we get a MOAB_NOT_FOUND when we're creating the first version of an object, which we wouldn't want to report to honeybadger??
> 

in that case i think we'd get `CREATED_NEW_OBJECT`:
https://github.com/sul-dlss/preservation_catalog/blob/af8beb95a04a94c549bd3ce178c7623afd9f28a5/app/services/complete_moab_handler.rb#L35-L66

https://github.com/sul-dlss/preservation_catalog/blob/af8beb95a04a94c549bd3ce178c7623afd9f28a5/app/services/complete_moab_handler.rb#L188-L210

i think we'd only get `MOAB_NOT_FOUND` if we were expecting to see it already.

>     * other situations related to the above case?
> 

none i can think of 🤷‍♂️ 

> 
> Also, is this PR relevant, which is about looking for a moab on a diff disk? PR #1271

i think that was the "let C2M detect moved moabs" approach to storage migration.  i could see turning off the `MOAB_NOT_FOUND` code if we went with that approach as-is, but i don't think that was the cause of this.

reasonable conjectures, but i'm guessing it was oversight at this point.
