### ISSUE TITLE
jg493zj2723, xn304xk4491, fz044py4850 - druid replication failures

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1491]
**Describe the bug**
the resque console on pres cat prod indicates some druids have failed to replicate to AWS US West 2.  the druids are:  jg493zj2723, xn304xk4491, fz044py4850.

we should check out the state of things in the DB and in the S3 buckets.  and then we should manually remediate the DB records and re-push the druids through the replication pipeline as needed.

**User Impact**
recoverability of these druids is slightly reduced in the event of disaster, as they have failed to fully replicate to all 3 cloud archive targets.  not super urgent, since they likely replicated correctly to the other two archive endpoints, but definitely something to investigate/remediate.

**Object(s) In This Error State**

- [x] jg493zj2723
- [x] xn304xk4491
- [ ] fz044py4850

**Steps to Reproduce, if Known:**
likely due to some sort of transient network error, or a transient error on the AWS servers.

**Expected behavior**
all versions of all three of the druids have been replicated to all three cloud endpoints without error.

**Screenshots**
n/a, but will include text of resque errors in a comment

**Additional context**
i will clear these errors from the queue.  the associated zip files have likely aged out of the zip temp storage, so retrying the jobs as-is would likely do no good.

**Comment by jmartin-sul** [comment]
resque errors:



    Worker
        preservation-catalog-prod-03.stanford.edu:14303 on s3_us_west_2_delivery at April 11, 2020
        Retry or Remove
    Class
        S3WestDeliveryJob (via ActiveJob) 
    Arguments

        ---
        job_class: S3WestDeliveryJob
        job_id: 9325a24c-1520-42c8-b584-455ca8b94dc1
        provider_job_id: 
        queue_name: s3_us_west_2_delivery
        priority: 
        arguments:
        - jg493zj2723
        - 1
        - jg/493/zj/2723/jg493zj2723.v0001.z07
        - checksum_md5: aeae8cad1138827ec656b7778cc87828
          size: 10737418240
          parts_count: 15
          zip_cmd: zip -r0X -s 10g /sdr-transfers/jg/493/zj/2723/jg493zj2723.v0001.zip jg493zj2723/v0001
          zip_version: Zip 3.0 (July 5th 2008)
          _aj_symbol_keys:
          - checksum_md5
          - size
          - parts_count
          - zip_cmd
          - zip_version
        executions: 0
        exception_executions: {}
        locale: en
        timezone: UTC
        enqueued_at: '2020-04-11T22:55:43Z'

    Exception
        Aws::S3::MultipartUploadError
    Error
        multipart upload failed: The provided 'x-amz-content-sha256' header does not match what was computed. 

    Worker
        preservation-catalog-prod-02.stanford.edu:23486 on s3_us_west_2_delivery at April 10, 2020 
    Class
        S3WestDeliveryJob (via ActiveJob) 
    Arguments

        ---
        job_class: S3WestDeliveryJob
        job_id: 754b68a3-893a-4b90-9e1f-e21aedd0d35a
        provider_job_id: 
        queue_name: s3_us_west_2_delivery
        priority: 
        arguments:
        - xn304xk4491
        - 1
        - xn/304/xk/4491/xn304xk4491.v0001.zip
        - checksum_md5: 45e2ff6572e8517c7434998542d356a2
          size: 2141242534
          parts_count: 1
          zip_cmd: zip -r0X -s 10g /sdr-transfers/xn/304/xk/4491/xn304xk4491.v0001.zip xn304xk4491/v0001
          zip_version: Zip 3.0 (July 5th 2008)
          _aj_symbol_keys:
          - checksum_md5
          - size
          - parts_count
          - zip_cmd
          - zip_version
        executions: 0
        exception_executions: {}
        locale: en
        timezone: UTC
        enqueued_at: '2020-04-10T11:28:48Z'

    Exception
        Aws::S3::MultipartUploadError
    Error
        multipart upload failed: The provided 'x-amz-content-sha256' header does not match what was computed. 

    Worker
        preservation-catalog-prod-03.stanford.edu:4177 on s3_us_west_2_delivery at April 02, 2020 
    Class
        S3WestDeliveryJob (via ActiveJob) 
    Arguments

        ---
        job_class: S3WestDeliveryJob
        job_id: 38fde3be-f6f8-40bb-b034-05392bb438b9
        provider_job_id: 
        queue_name: s3_us_west_2_delivery
        priority: 
        arguments:
        - fz044py4850
        - 1
        - fz/044/py/4850/fz044py4850.v0001.zip
        - checksum_md5: 2327a0a75665ced0219ae81aeb1d74a9
          size: 216243589
          parts_count: 1
          zip_cmd: zip -r0X -s 10g /sdr-transfers/fz/044/py/4850/fz044py4850.v0001.zip fz044py4850/v0001
          zip_version: Zip 3.0 (July 5th 2008)
          _aj_symbol_keys:
          - checksum_md5
          - size
          - parts_count
          - zip_cmd
          - zip_version
        executions: 0
        exception_executions: {}
        locale: en
        timezone: UTC
        enqueued_at: '2020-04-03T04:00:03Z'

    Exception
        Aws::S3::MultipartUploadError
    Error
        multipart upload failed: execution expired

**Comment by jmartin-sul** [comment]
this ticket is done when all of these moab have been fully archived to all 3 cloud endpoints.

relevant wiki page:  https://github.com/sul-dlss/preservation_catalog/wiki/Fixing-an-Incomplete-Moab-Upload

note: devs don't have delete permission on the cloud archives, so you'll have to ask ops to do that deletion, if it's necessary.

**Comment by aaron-collier** [comment]
["jg493zj2723", 2, 1, "aws_s3_west_2", "unreplicated", ".z07", 15, 10737418240]
["xn304xk4491", 1, 1, "aws_s3_west_2", "unreplicated", ".zip", 1, 2141242534]
["fz044py4850", 2, 1, "aws_s3_west_2", "unreplicated", ".zip", 1, 216243589]

Each of the above druids have a single unreplicated zip part.

**Comment by aaron-collier** [comment]
- [ ] We need @julianmorley (or someone else in ops) to verify if the above zip parts are in fact NOT on the storage locations
- [ ] If confirmed that they are missing, remove moab from the location (ops must perform) - please confirm this is correct @jmartin-sul 
- [ ] Follow the instructions here: https://github.com/sul-dlss/preservation_catalog/wiki/Fixing-an-Incomplete-Moab-Upload

The outstanding question is: Should we remove additional moabs if recreating an existing version?

**Comment by aaron-collier** [comment]
Verified that the following parts do not exist on the `aws_s3_west_2` end point.

```
Key = jg/493/zj/2723/jg493zj2723.v0001.z07 Found = false
Key = xn/304/xk/4491/xn304xk4491.v0001.zip Found = false
Key = fz/044/py/4850/fz044py4850.v0001.zip Found = false
```

**Comment by aaron-collier** [comment]
Ops-task created: https://github.com/sul-dlss/operations-tasks/issues/2253

**Comment by julianmorley** [comment]
Deleted the one druid-version that was present in AWS-West-2; the other two druids weren't there at all. I suspect that clearing up the ZMV records might get prescat to re-upload the correct content.

**Comment by ndushay** [comment]
jg493zj2723 is fixed.

```
3.0.0 :043 > druid = 'jg493zj2723'
 => "jg493zj2723" 
3.0.0 :044 > po = PreservedObject.find_by(druid: druid)
 => 
#<PreservedObject:0x0000563cfefbfec8
... 
3.0.0 :045 > zmvs = ZippedMoabVersion.where(preserved_object: po)
 => 
[#<ZippedMoabVersion:0x0000563cfffe6d10
... 
3.0.0 :046 > zmvs.count
 => 6 
3.0.0 :047 > zmvs.each { zps = ZipPart.where(zipped_moab_version: zmvs.first); zps.each { |zp| puts "#{zp.status} - #{zp.last_existence_check}" } }
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:01 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:02 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:03 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
ok - 2023-01-06 15:46:04 UTC
 => 
```

**Comment by ndushay** [comment]
xn304xk4491 is fixed.

```
3.0.0 :049 > druid = 'xn304xk4491'
 => "xn304xk4491" 
3.0.0 :050 > po = PreservedObject.find_by(druid: druid)
 => 
#<PreservedObject:0x0000563cff3daf80
... 
3.0.0 :051 > zmvs = ZippedMoabVersion.where(preserved_object: po)
 => 
[#<ZippedMoabVersion:0x0000563d001d4410
... 
3.0.0 :052 > zmvs.count
 => 3 
3.0.0 :053 > zmvs.each { zps = ZipPart.where(zipped_moab_version: zmvs.first); zps.each { |zp| puts "#{zp.status} - #{zp.last_existence_check}" } }
ok - 2023-01-17 17:28:29 UTC
ok - 2023-01-17 17:28:29 UTC
ok - 2023-01-17 17:28:29 UTC
 => 
```
