### ISSUE TITLE
refactor MoabValidationHandler module

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1494]
per #1487
> Everyone seems to find this difficult to work with, myself included sometimes, and I was the one who originally refactored code into this module. I don't want to copy this logic back out into the various consumers, but feedback seems to be that a more traditional inheritance relationship, or some other form of composition, would be more intelligible than the module mixin.

some possible approaches:
* turn it into a parent class that takes needed things in constructor, modify the classes that currently `include` it extend it instead.
  * along those lines: turn it into a class where subclass is expected to define some methods, and the default method implementations raise error if unimplemented.  this feels a little too java-ish and a little too close to the current (confusing) implementation, but it's a possibility to consider.
* service object that takes needed things in constructor, classes that currently `include` the module would have an instance of the service class instead
* other ideas?

i think i'm leaning toward the parent class idea, but would love to hear other ideas or discuss further if someone else wants to pick this up.  the service class thing could be a good approach also?  but reading over the code definitely makes it feel like there's a circular relationship between `MoabValidationHandler` and its consumers (each expects methods from the other).  i suspect this is what makes it especially hard to understand, and i also think all the above ideas would at least eliminate that issue.

as always, happy to pair on this if someone else picks it up.

**Comment by jmartin-sul** [comment]
#1493 should happen first

**Comment by jmartin-sul** [comment]
see also @mjgiarlo's excellent writeup on #1276 (forgot that existed, sorry for the duplicate).

i'd suggest that whoever picks this up pick up the other one too, and close whichever ticket seems less useful/informative as a dupe.

**Comment by aaron-collier** [comment]
Moved the comment from here into #1276 and closing this as dupe.
