### ISSUE TITLE
Prescat not replicating all druid-versions to endpoints

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#1499]
**Describe the bug**
prescat seems to not be processing all druid-versions that it should. When a druid-version is impacted, it appears that it does not replicate to *any* endpoint and this replication failure is not remediated by any follow-up audit processes.

This started out with a 5 druid-versions not being replicated on/around Feb 25th, then the number of impacted d-v grew by a handful a day over the next 2 months until it reached 197 druid-versions today. I manually submitted these d-v to prescat (zipmaker) for replication and they seem to be going through now, so this implies that our regular sweeps to verify replication  aren't working as expected.

**User Impact**
We're not preserving druids we expect to be preserved.
[missing-druid-versions.txt](https://github.com/sul-dlss/preservation_catalog/files/4524653/missing-druid-versions.txt)

No idea how to reproduce; this is just observed behavior over the last 2-ish months.

**Comment by julianmorley** [comment]
Aha! These may be Ben Specials. Eyeballing a couple of them I see that they have been moved from disk 5 to disk 11.

**Comment by aaron-collier** [comment]
@julianmorley do you think this ticket is still valid?

**Comment by jmartin-sul** [comment]
this is a more open ended investigation ticket.  the first step might be to pair to discuss how to go about diagnosing the problem.  we could at least see whether all the affected druids listed in the description are in fact parker objects that have been moved around manually, and/or whether they fit some other pattern.

**Comment by ndushay** [comment]
I'm closing this.  We have Catalog-to-Archive audit that will find problems with replication, and we're confident our current code does replicate to all endpoints.  Plus, this ticet is 2 1/2 years old with no recent info.
