### ISSUE TITLE
proxy: Wowza prod upgrade

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#15]

**Comment by tallenaz** [comment]
Upgrade is applied to dev/stage. Before rolling it out to prod, we will schedule some testing.

**Comment by tingulfsen** [comment]
See sul-dlss/media#144, which is a blocker.

**Comment by ndushay** [comment]
We booted @tingulfsen off the team, so this ticket can be recreated by him in the location of his choice.
