### ISSUE TITLE
switch from Dir.chdir in Zipmaker, to using chdir param in Open3.capture2e

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1519]
per https://github.com/sul-dlss/preservation_catalog/issues/1487#issuecomment-621309175:

>     Make the following, tiny patch (HT @justinlittman: [sul-dlss/google-books#529](https://github.com/sul-dlss/google-books/pull/529)). From:
> 
> 
> ```ruby
>     Dir.chdir(work_dir.to_s) do
>       combined, status = Open3.capture2e(zip_command)
>       raise "zipmaker failure #{combined}" unless status.success?
>     end
> ```
> 
> to:
> 
> ```ruby
>     combined, status = Open3.capture2e(zip_command, chdir: work_dir.to_s)
>     raise "zipmaker failure #{combined}" unless status.success?
> ```

this should be the only instance of this usage in pres cat.  it's not threadsafe, but the alternate approach @mjgiarlo describes is.  switching to that approach will help pave the way for switching over to sidekiq from resque (see the top level description of the issue linked above).

question:  is there a good way to document that we want to avoid `Dir.chdir` going forward?  a thread safety section in the readme if we switch from resque to sidekiq?

**Comment by mjgiarlo** [comment]
@jmartin-sul :speech_balloon: 
> 
> question: is there a good way to document that we want to avoid `Dir.chdir` going forward? a thread safety section in the readme if we switch from resque to sidekiq?

maybe a new section in the devplaybook entry re: background jobs? with some specific gotchas to avoid? README here works too if just prescat-focused

**Comment by jmartin-sul** [comment]
@mjgiarlo 💬 

> @jmartin-sul 💬
> 
> > question: is there a good way to document that we want to avoid `Dir.chdir` going forward? a thread safety section in the readme if we switch from resque to sidekiq?
> 
> maybe a new section in the devplaybook entry re: background jobs? with some specific gotchas to avoid? README here works too if just prescat-focused

good call, i like that approach.
