### ISSUE TITLE
update replication errors investigation wiki page in light of part audit class refactoring

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1542]
minor updates to https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-a-druid-with-replication-errors based on changes resulting from:  https://github.com/sul-dlss/preservation_catalog/issues/1496

likely just some class name updates?

**Comment by ndushay** [comment]
I'm closing this as we have revamped our wikis
