### ISSUE TITLE
consolidate repeated ibm_provider_spec.rb and aws_provider_spec.rb code into a single shared example

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1561]
most of the code in these two files is very similar, and we expect the two classes being tested to behave very similarly.

parameterize the differences into a `shared_examples_s3_provider.rb` file and replace the existing test file contents with an invocation of the new shared examples, using the correct parameters for expectations around that specific provider.

**Comment by jcoyne** [comment]
I really dislike shared tests because they are much harder to reason about. I love to see code optimized, but tests as stupid as possible. Making changes like this can cause the code to be less approachable.

**Comment by justinlittman** [comment]
Oh good, it is not only me. Maybe it is lack of practice with them but I find them much more difficult to understand.

**Comment by jmartin-sul** [comment]
> I really dislike shared tests because they are much harder to reason about. I love to see code optimized, but tests as stupid as possible. Making changes like this can cause the code to be less approachable.

totally fair point.  i don't find shared examples so bad in this regard, but i can understand how others might, and i totally agree with the goal of keeping tests stupid.

still, i'd really like to reduce the opportunity for unintentional drift between these two sets of tests, which are mostly the same.

@jcoyne, do you have any suggestions for doing that without shared examples?

the test files in question are fairly short, so as much as i try to avoid the need for comments like "don't let this thing drift from that thing", maybe that's sufficient for what we want here.
