### ISSUE TITLE
load balance the preservation catalog REST API VM

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1562]
see discussion in slack:  https://stanfordlib.slack.com/archives/G6K8R3VBK/p1590781771485400

the tasks needed to do this, in order:
- [ ] 1. put the load balancer in place _(ops task)_
- [ ] 2. to start, point the load balancer to preservation-catalog-[stage|prod]-01 _(ops task)_
- [ ] 3. update shared_configs for all services that talk to pres cat to use the load balancer, instead of talking to -01 VM directly _(dev task)_
  - but allow services to keep talking directly to -01 till all pres cat API consuming services have had configs updated
- [ ] 4. _after_ everything has been re-deployed with updated configs, restrict access to the pres cat -01 VMs so that all traffic must go through the load balancer. _(ops task)_
- [ ] 5. add a second pres cat REST API VM behind the load balancer.  i'm inclined to number this after the existing VMs, to minimize other config churn, but am grudgingly open to re-numbering the worker and redis VMs if that's greatly preferable for some reason.

the following shell alias may be useful in searching shared_configs for consumers of the pres cat API:
```sh
# courtesy of @mjgiarlo
# Find unique git branches that match a search string
function branchgrep {
    for commit in $(git grep -li --no-color "$@" $(git rev-list --all) | cut -d: -f1 | sort | uniq)
    do
        git branch -r --contains $commit
    done | sort | uniq
}
```

make sure to pull the latest shared_configs before running that locally.  the string to search for would be `preservation_catalog:` (so `branchgrep 'preservation_catalog:'`), which should be the name of the settings section where the pres cat host and access token are provided.  it appears at first glance from running this locally that we need to update:
* argo
* common-accessioning
* dor-services-app
* preservation_robots

**Comment by jmartin-sul** [comment]
marked as part of the pres cat storage migration epic because this work helps that indirectly (this makes the CentOS 7 upgrade easier by possibly eliminating downtime for it, and the CentOS 7 upgrade makes the storage migration easier).

**Comment by jmartin-sul** [comment]
there may actually already be a pres cat load balancer in place, so steps 1 & 2 may be done.  @julianmorley?

**Comment by julianmorley** [comment]
This got spiked by an internal discussion on how best / when to use the UIT hardware loadbalancer. The TL;DR is that we have many API services that either currently use the UIT HWLB, or would benefit from it, but we're using public IPs and transiting firewall boundaries to do so (up to 50% bandwidth hit). UIT is functionally 'out' of public IPs, so it's undesirable for us to use up what is left for traffic that can, and should, use non-routable IP endpoints. But the HWLB doesn't currently provide non-routable endpoint IPs.

So ideally, we'd either:
* Get UIT to add a non-routable IP net to the HWLB for us, and migrate our services endpoints to that IP space, or
* Do something else for load-balancing internal apps that just need RESTful API endpoints

Either approach would take more than a few weeks to set up, so getting Pres API loadbalanced isn't a quick, easy win.

**Comment by jmartin-sul** [comment]
> Either approach would take more than a few weeks to set up, so getting Pres API loadbalanced isn't a quick, easy win.

bummer.

it does seem likely that we still want to do this, for pres cat specifically and probably for other API apps in general, even if it won't help us avoid downtime in the very near future for the CentOS upgrades to pres cat and pres robots.

does this have any chance of happening eventually?  should i leave this ticket open?  file something more general in ops tasks?  close it and forget about it?  something else?

**Comment by ndushay** [comment]
@jmartin-sul @tallenaz has this been done?  Do we have a prescat lb?  If so, please close ticket.

**Comment by tallenaz** [comment]
Yes, this is done.
