### ISSUE TITLE
Investigate why CompleteMoab by_storage_root cannot embed .by_druid

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss/preservation_catalog#1571]
**Describe the bug**
In reviewing of PR #1568, @mjgiarlo in this [comment](https://github.com/sul-dlss/preservation_catalog/pull/1568/files#r437542151), asked about making `by_storage_root` a single call instead of chaining it to the `by_druid` scope to better reflect the code's intention. After experimenting with a single `by_storage_root` scope with two parameters, **druid** and **storage_root** and then first calling the `by_druid` scope or by copying the code used `by_druid` scope, always returned an empty relation. 

**User Impact**
A description of the impact of this bug on, e.g. accessioning throughput or your own work or long term preservation.

na/a

**Comment by ndushay** [comment]
I'm closing this ticket.  @mjgiarlo if that's wrong, please re-open
