### ISSUE TITLE
okcomputer:  check sdr-transfers for available space, fail check if usage over 80%

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1610]
let's make this a separate check from `feature-zip_storage`.

see request from @julianmorley on #1603 (we should just automate this instead of babysitting manually).

also, this check should be optional for machines with an -01 hostname (which are web boxes, and which don't mount `/sdr-transfers`, since only the worker boxes need to  create zip files from moabs for archiving).

**Comment by mjgiarlo** [comment]
Do we want this as an OKComputer check, a Nagios check, or both? (A bunch of projects do this via Nagios check is the only reason I ask. Either will be an improvement over what we have now?)

**Comment by jmartin-sul** [comment]
ah, if existing the pattern is to do this entirely via nagios, i'm fine with that approach instead, in which case we could just file an ops ticket in place of this, i guess?

**Comment by mjgiarlo** [comment]
Yep, file an ops ticket or write up a puppet PR. Happy to pair on the latter, but equally happy for the former. :smile:

**Comment by jmartin-sul** [comment]
ops ticket filed, closing this one.  see https://github.com/sul-dlss/operations-tasks/issues/2282
