### ISSUE TITLE
updating openapi_parser past 0.11.x breaks build

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1626]
**Describe the bug**

test suite broke both locally and on CI as follows when the openapi_parser gem was brought to 0.12.1:

```
Failures:

  1) ObjectsController GET #file when no id param when id param is empty returns 400 error
     Failure/Error: expect(response).to have_http_status(:bad_request)
       expected the response to have status code :bad_request (400) but it was :not_found (404)
     # ./spec/requests/objects_controller_file_spec.rb:83:in `block (5 levels) in <top (required)>'
     # ./spec/support/live_s3.rb:10:in `block (2 levels) in <top (required)>'

  2) ObjectsController POST #content_diff when druid empty returns 400 response
     Failure/Error: expect(response).to have_http_status(:bad_request)
       expected the response to have status code :bad_request (400) but it was :not_found (404)
     # ./spec/requests/objects_controller_content_diff_spec.rb:140:in `block (4 levels) in <top (required)>'
     # ./spec/support/live_s3.rb:10:in `block (2 levels) in <top (required)>'

Finished in 34.69 seconds (files took 5.7 seconds to load)
1084 examples, 2 failures, 7 pending

Failed examples:

rspec ./spec/requests/objects_controller_file_spec.rb:81 # ObjectsController GET #file when no id param when id param is empty returns 400 error
rspec ./spec/requests/objects_controller_content_diff_spec.rb:136 # ObjectsController POST #content_diff when druid empty returns 400 response

Randomized with seed 18320
```

see https://github.com/sul-dlss/preservation_catalog/pull/1625/commits/88aab346854a4abbfe7ad014a0843d755aa39f63 and https://app.circleci.com/pipelines/github/sul-dlss/preservation_catalog/357/workflows/afc4201a-35ac-444f-b2d6-9c94450d6807/jobs/557

pinning back to 0.11.x seems to fix the build, but we should figure out how to unpin this gem.

**User Impact**

nothing at present, though this issue could prevent useful future dep updates if allowed to linger.

**Object(s) In This Error State**

n/a

Steps to Reproduce, if Known:

upgrade openapi_parser gem and run rspec

**Expected behavior**

test suite passes on latest version of dependencies

**Screenshots**

n/a, see text of error above

**Additional context**

none

**Comment by jcoyne** [comment]
I think this is because of this change upstream: https://github.com/ota42y/openapi_parser/pull/84

and I think this is a good change.  

The failing tests are here:
https://github.com/sul-dlss/preservation_catalog/blob/master/spec/requests/objects_controller_file_spec.rb#L82

and
https://github.com/sul-dlss/preservation_catalog/blob/master/spec/requests/objects_controller_content_diff_spec.rb#L137

and because the id is a blank string, it's is asking for a path that matches no pattern in the openapi.yml, thus the 404.

**Comment by jmartin-sul** [comment]
ha, yeah, i was just looking through the openapi_parser commits in the diff between 0.11.2 and 0.12.1 and circling the same thing, though my suspicion was this one:  https://github.com/ota42y/openapi_parser/commit/b8bac7770ec8f9b9a18f6252fcf3d50d30c03dd5

anyway, yeah, i agree, this seems like a reasonable change.  400 and 404 both seem like similarly reasonable error codes (i say having not put too much thought into it yet), so i'm happy to update the test.  i was just perplexed that this gem was breaking things, and wanted to try and figure out why.

**Comment by jmartin-sul** [comment]
actually, on very slightly more thought, i think i liked it better when it was 400 (because to me `''` feels more like `'foo'` than it does a non-existent druid of the right format, and `'foo'` is a 400 as opposed to a 404, which i think is right).  but it doesn't feel worth the effort to me to go against openapi_parser for this quibble, and its request validation is generally very valuable, so sure, why not, will still change the test.

interested in why 404 might be a more appropriate response code, in case i'm not thinking of something.

**Comment by jcoyne** [comment]
They are now looking for `/foo/{bar}` where `{bar}` represents something (and not an empty string). Since we don't allow an empty string to be a valid identifier, 404 seems like the right code in this choice.

**Comment by jmartin-sul** [comment]
yeah, i mean, i don't think it makes a material difference for us since we're the only consumers and we're not acting on the response codes that finely.  but the fact that empty string isn't a valid identifier is the part that made me think 400 -- if only because it's a bit more informative, in that it tells the client that they're asking for something we don't support, as opposed to something that could maybe exist.  404 makes it seem (to me at least) like the issue might be server-side, whereas 400 is a stronger assertion that the client is doing something wrong and should've known better 😆 

at any rate, i already acquiesced 🙂, and the fix is green:  https://github.com/sul-dlss/preservation_catalog/pull/1625/files

**Comment by jcoyne** [comment]
Yeah, I suppose you could leave a bug report on openapi_parser.
