### ISSUE TITLE
preservation services are having trouble interacting reliably with Ceph backed storage

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1633]
**Describe the bug**

The clearest symptom is that a preservation_robots worker will write a new version of a Moab, and some time after it finishes, another process will have trouble reading content or file system metadata from one or more files in the Moab version.  By far the most trouble has cropped up with the `ZipmakerJob` -- either the zip binary will throw an error when it's unable to add a file from the Moab version to the zip it's creating for replication, or a sanity check on size after zip creation (see #1302, #1540) will fail with an access denied error.  Occasionally, an API call to pres cat from pres robots will fail because pres cat won't be able to fully read the contents of the Moab it's being asked about.  Very occasionally, we've seen pres robots be unable to read the contents of a Moab version.  Will show example errors in the comments below.

@julianmorley and @andrewjbtw have also scripted up some automated checks that proactively look for files on the Ceph backed preservation mounts, to look for issues when listing file system attributes, since we've noticed inability to resolve file system attributes or permissions issues reading the files at all for files that trigger pres cat and pres robots errors.  Examples of that output below also.

Filing this in pres cat repo since that's the codebase that experiences this error the most.  But it seems to involve the interplay of preservation_robots writing Moab content (possibly due to our particular usage of hardlinking), preservation_catalog and preservation_robots reading Moab content, and something to do with Ceph and its MDS (metadata service) configuration.

**User Impact**

We experience unpredictable failures in `ZipmakerJob`, which requires babysitting and manual intervention to assure that all our content is replicated to all endpoints, and when preservation_robots run into errors or have to be throttled to prevent errors from cropping up, accessioning can slow down in general, and/or stall for specific objects that encounter errors.  This problem has required pausing some automated accessioning, and has required us to ask for more pauses in human accessioning than initially asked for in prep for the recent storage migration weekend (see #1559).

**Object(s) In This Error State**

There are 1420 `zipmaker_failed` entries at the moment.  In a comment below, I'll post a ruby snippet for programmatically capturing the relevant info (druid, version, etc) so as to not need to copy it all out of the paginated list in Resque's web console.

**Steps to Reproduce, if Known**

Not sure exactly yet.  We just know that pres robots will write a Moab version, and subsequent processes that attempt to read the content are sometimes unexpectedly unable to.  We suspect stale MDS cache or stale locks, further explanation in comments below.

**Expected behavior**

Once a pres robots worker is done writing a Moab version, other processes on the same VM or other VMs should be able to read that content if they have the Ceph backed preservation storage root mounted.

**Comment by jmartin-sul** [comment]
example errors

* https://app.honeybadger.io/projects/54415/faults/65917465 (pres cat)
```
RuntimeError: zip size (76085588) is smaller than the moab size (76087581)! zipmaker failure 	zip warning: name not matched: qc601wk9177/v0001/manifests/versionAdditions.xml
	zip warning: name not matched: qc601wk9177/v0001/data/content/checksum.md5
	zip warning: name not matched: qc601wk9177/v0001/data/content/36105037959694-gb-txt.zip
	zip warning: name not matched: qc601wk9177/v0001/data/content/STANFORD_36105037959694.xml
	zip warning: name not matched: qc601wk9177/v0001/data/metadata/contentMetadata.xml
	zip warning: name not matched: qc601wk9177/v0001/data/metadata/descMetadata.xml
	zip warning: name not matched: qc601wk9177/v0001/data/metadata/relationshipMetadata.xml
	zip warning: name not matched: qc601wk9177/v0001/data/metadata/workflows.xml
	zip warning: name not matched: qc601wk9177/v0001/data/metadata/provenanceMetadata.xml
  adding: qc601wk9177/v0001/ (stored 0%)
  adding: qc601wk9177/v0001/manifests/ (stored 0%)
  adding: qc601wk9177/v0001/manifests/signatureCatalog.xml (stored 0%)
  adding: qc601wk9177/v0001/manifests/manifestInventory.xml (stored 0%)
```

* https://app.honeybadger.io/projects/54415/faults/65802347 (pres cat)
```
RuntimeError: zipmaker failure   adding: tz225vm7482/v0001/ (stored 0%)
  adding: tz225vm7482/v0001/manifests/ (stored 0%)
  adding: tz225vm7482/v0001/manifests/versionAdditions.xml
zip warning: Permission denied
	zip warning: could not open for reading: tz225vm7482/v0001/manifests/versionAdditions.xml
  adding: tz225vm7482/v0001/manifests/signatureCatalog.xml (stored 0%)
```

* https://app.honeybadger.io/projects/55564/faults/68167965 (pres robots)
```
Errno::EACCES: Permission denied @ rb_file_s_size - /pres-03/sdr2objects/nn/446/gc/7625/nn446gc7625/v0001/data/metadata/contentMetadata.xml
```
* https://app.honeybadger.io/projects/55564/faults/53287088 (pres robots)
```
Robots::SdrRepo::PreservationIngest::ItemError: Error transferring bag (via dor_services@dor-services-prod.stanford.edu) for druid:wf977yb8633: Shell command failed: [ssh dor_services@dor-services-prod.stanford.edu "tar -C /dor/export/ --dereference -cf - wf977yb8633 " | tar -C /pres-03/deposit -xf -] caused by <STDERR = tar: wf977yb8633: Cannot mkdir: Permission denied
tar: wf977yb8633: Cannot mkdir: Permission denied
tar: wf977yb8633/bagit.txt: Cannot open: No such file or directory
tar: wf977yb8633: Cannot mkdir: Permission denied
tar: wf977yb8633/versionInventory.xml: Cannot open: No such file or directory
tar: wf977yb8633: Cannot mkdir: Permission denied
```


here's an example of what a file looks like when `ls`ed from the command line while its in a state where processes on the VM can't read the content and/or metadata properly:
```
bf/590/jh/9879/bf590jh9879/v0001/data/metadata:
ls: cannot access bf/590/jh/9879/bf590jh9879/v0001/data/metadata/identityMetadata.xml: Permission denied
ls: cannot access bf/590/jh/9879/bf590jh9879/v0001/data/metadata/descMetadata.xml: Permission denied
ls: cannot access bf/590/jh/9879/bf590jh9879/v0001/data/metadata/provenanceMetadata.xml: Permission denied
ls: cannot access bf/590/jh/9879/bf590jh9879/v0001/data/metadata/rightsMetadata.xml: Permission denied
ls: cannot access bf/590/jh/9879/bf590jh9879/v0001/data/metadata/versionMetadata.xml: Permission denied
total 21
-rw-rw-r-- 1 pres pres 16239 Sep 30 16:11 contentMetadata.xml
-????????? ? ?    ?        ?            ? descMetadata.xml
-????????? ? ?    ?        ?            ? identityMetadata.xml
-????????? ? ?    ?        ?            ? provenanceMetadata.xml
-rw-rw-r-- 1 pres pres   458 Sep 30 16:11 relationshipMetadata.xml
-????????? ? ?    ?        ?            ? rightsMetadata.xml
-????????? ? ?    ?        ?            ? versionMetadata.xml
-rw-rw-r-- 1 pres pres  4312 Sep 30 16:11 workflows.xml
```

**Comment by jmartin-sul** [comment]
a couple of points in the pres robots code that we currently think are important:

* pres robots `update_moab` calls moab-versioning's [`StorageObject#ingest_bag`](https://github.com/sul-dlss/moab-versioning/blob/9e24a35624b0c54c94a0386e1de7cbf52cf5b0d3/lib/moab/storage_object.rb#L62-L78) method to transfer from deposit to sdr2objects:  https://github.com/sul-dlss/preservation_robots/blob/fb5ebfbe06a70ac555e319be44abdaacd40aa2e8/lib/robots/sdr_repo/preservation_ingest/update_moab.rb#L22-L30
  * `StorageObjectVersion#ingest_bag_data` does the actual work (via another couple helper methods) of actually ingesting the files to be preserved from the deposit bag to the new Moab version:  https://github.com/sul-dlss/moab-versioning/blob/9e24a35624b0c54c94a0386e1de7cbf52cf5b0d3/lib/moab/storage_object_version.rb#L141-L180
* pres robots `complete_ingest` removes the deposit bag once the new moab version has been created:  https://github.com/sul-dlss/preservation_robots/blob/f45a19c78ab3ae7646f4210e21c22ec1991947a5/lib/robots/sdr_repo/preservation_ingest/complete_ingest.rb#L23-L28

**Comment by jmartin-sul** [comment]
other observations:
* when we notice the error rate going up for a particular MDS instance serving a particular client VM (client being e.g. pres cat reading files from a Moab pres robots updated, _or_, less frequently pres robots reading/writing Moab contents in prep for creating a new version), restarting that MDS instance usually helps.
* @julianmorley observes that once we start getting bad/incomplete data for a file from a particular MDS instance, we don't start getting good metadata/data for/from it till the MDS instance is restarted.
* we've been seeing `zipmaker` errors like this for a few weeks, since the second storage migration (#1558), but they spiked this past monday (2020-09-28) evening and tuesday morning.  there were around 350 zipmaker errors as of monday morning due to Ceph read issues, and right now there are 1420.
* we haven't had any new read errors encountered by pres cat or pres robots since around 13:17 tues 2020-09-29.  we were able to tamp down the spike in errors by a combination of the following, and we're not entirely sure what was most helpful:
  * adding an artificial 60 second delay right before pres robots calls `update_catalog` to notifiy pres cat that a new Moab version has been created.  we suspect this gives time for MDS instances to become consistent after a pres robots worker finishes writing?  see https://github.com/sul-dlss/preservation_robots/pull/269 and https://github.com/sul-dlss/preservation_robots/pull/270
  * adding an artificial 60 second delay at the start of `ZipmakerJob` before attempting to create the zip for replication.  same thinking as pres robots delay.  see https://github.com/sul-dlss/preservation_catalog/pull/1631 and https://github.com/sul-dlss/preservation_catalog/pull/1632
  * greatly reducing the number of pres robots workers (10, down to 1, back up to 3).  see https://github.com/sul-dlss/preservation_robots/pull/271 and https://github.com/sul-dlss/preservation_robots/pull/272

@julianmorley's initial suspicions were:
* maybe we're putting too much write load on Ceph for our current configuration, and the MDS servers can't stay up to date as well as we'd expect.
* maybe we're putting too much write load on Ceph for our current configuration, and write locks from pres robots aren't being given up quickly enough, blocking pres cat from reading files the pres robots worker is actually done writing.  or, the other way around, pres robots can't read something it just updated (e.g. when something is rapidly versioned multiple times) because pres cat has a read lockj on that Moab version, e.g. because it's creating a zip for cloud replication.

_but_ he's found a new

**Comment by jmartin-sul** [comment]
things we'd like to try.  these are not necessarily mutually exclusive, and it's likely some or all of these should spawn new tickets, possibly in other repos:
- [ ] recursively `stat` the contents of the new Moab version dir after the `rmtree` in `complete_ingest` (**pres robots**)
- [ ] recursively `stat` the contents of the Moab version dir to be zipped before calling `create_zip!` in `ZipmakerJob`.  we think/hope this will trigger the same issue as the after the fact directory sizing to sanity check the newly created zip, but up front, before we attempt to create the zip (**pres cat**)
  - side note:  it's disconcerting that the zip binary will sometimes silently make a zip that's missing files it's supposed to have, and that we only catch this because we know the uncompressed zip should be slightly larger than the total file size being zipped, in terms of logical size, because of the addition of a bit of metadata about the zipped content.
- [ ] if the zip size check _does_ determine that the zip is bad because it's not large enough to contain all the expected content, delete the bad zip.  this will make it easier to retry the failed `zipmaker` job without either manually cleaning up busted zip files, or waiting for the regular zip cache cleaning process to clean the zip up (zip file currently expires when it hasn't been accessed in a week, i.e. `atime` more than 7 days old, iirc). (**pres cat**)
- [ ] revisit the `sleep` based delay mechanism in pres robots `update_catalog`, with an eye towards excising it entirely (**pres robots**)
- [ ] revisit the `sleep` based delay mechanism in pres cat `ZipmakerJob`, with an eye towards excising it entirely (**pres cat**)
- [ ] if we determine we need to have retries or a delayed start for any of our pres cat jobs, explore the following (**pres cat**):
  - [ ] sidekiq.  this would require we vet our code and dependencies for thread safety.  we'd have to look for things like class vars and other thread unsafe implementation techniques in pres cat and its dependencies.  for whatever reason, i'm esp worried about moab-versioning, which i don't think was written w/ thread safety in mind, and which may cache things in class vars.  also the sidekiq wiki claims the aws-s3 gem isn't thread safe, and that would likely be a dealbreaker for pres cat, because of the delivery workers.  resque spawns a process per worker, so this isn't a concern with resque workers.
    - [ ] sidekiq has the advantages of a built in retry mechanism, more efficient use of resources/less overhead compared to resque, and seeming like the emerging departmental preference for job management going forward.
  - [ ] plugins for resque that add scheduling and retry functionality
    - resque-retry:  https://github.com/lantins/resque-retry
    - resque-scheduler:  https://github.com/resque/resque-scheduler
  - [ ] the retries gem, but i would vote for avoiding this, as it's only a slightly better version of the `sleep` above.  in particular, we'd want to avoid long retry delays, to avoid tying up worker threads (or processes, if we switch to sidekiq) by making them look busy when they're actually idle, backing off and waiting to retry.

**Comment by julianmorley** [comment]
Some additional context/data:
* So far, when a file displays this behavior (no metadata / permission denied on an `ls`), it has always been resolved by restarting (actually failing over to a backup) the MDS instance.
* We have copied/rsync'd over 1 PB of data into Ceph and successfully CV'd it without seeing this issue, which is more evidence that this is related to our use of hard links, and supports the notion that if we swapped to a `cp` based method of moving from `deposit` to `sdr2objects` the issue would probably be resolved.

**Comment by jmartin-sul** [comment]
two more random observations:
* the tail end of the CV from this past weekend's storage migration (`services-disk21` through `services-disk26` to `pres-03`) ran into, iirc, just over 500 occurrences of the sort of file read issue `ZipmakerJob` has run into.  all failures succeeded on the first retry (triggered manually from resque console).  also CV finished super fast compared to the last two migrations (60ish hours instead of a week or two).  we migrated a comparable amount of content to the prior two, right?
* we suspect that the switch to having newly accessioned content land on ceph backed storage led to the issue occurring more frequently, if only because it meant we were using ceph storage a lot more (activity is typically higher on the storage root that gets new moabs).

**Comment by jmartin-sul** [comment]
closing, since i believe all of the remaining work has been captured in other smaller tickets that reference this one.
