### ISSUE TITLE
C2M weekly audit conflicts with robots update_catalog step (in progress?)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1634]
**Describe the bug**

We have had a number of occurrences of C2M running (currently kicked off Thurs night/early Friday morning) while a bunch of objects are going through accessioning.   The problem seems to be a sort of race condition:

- when pres robots update_catalog step is in progress (https://github.com/sul-dlss/preservation_robots/blob/master/lib/robots/sdr_repo/preservation_ingest/update_catalog.rb), it is trying to add a new version to the object in prescat, 

WHILE

- when C2M is running, (https://github.com/sul-dlss/preservation_catalog/blob/master/app/lib/audit/catalog_to_moab.rb), it is trying to verify the version in the catalog is what is on disk.

This can land us in the soup:

![image](https://user-images.githubusercontent.com/96775/94957264-50199900-04a2-11eb-88d5-78237bf037d8.png)

Note the same number of object have errored in both workflows.  :-(

![image](https://user-images.githubusercontent.com/96775/94957368-7b03ed00-04a2-11eb-94b2-0a39181921f6.png)

These also show up in Honeybadger:

pres robots:

![image](https://user-images.githubusercontent.com/96775/94957486-b0a8d600-04a2-11eb-93d9-0ef288d25368.png)

The most recent occurrence was this morning:
https://app.honeybadger.io/projects/55564/faults/68322527  (6,882 occurrences)

But it happened the previous 2 weeks as well:
https://app.honeybadger.io/projects/55564/faults/59562582 (roughly 30 occurrences last week and 900 the week before)

**Comment by andrewjbtw** [comment]
When this has happened in the past, I've followed this remediation plan:

1. Run preservation audit from prescat to make sure the moabs are ok. This will flip the status from "unexpected version" to "ok" if the audits pass.
2. Make sure the version numbers shown in Argo match the version numbers for the moabs. 
3. Set update-catalog to completed manually
4. Watch the items complete accessioning

**Comment by vivnwong** [comment]
This issue touches many parts of the preservation code and the reason of the failure is unknown. Move this out of the the first responder queue. This may be better to address in a maintenance workcycle.

**Comment by jmartin-sul** [comment]
@andrewjbtw's theory, as posted to slack friday morning:

> * my new theory on the update-catalog is this
> * item made into moab with update-moab
> * item is _queued_ for `update-catalog`
> * meanwhile … M2C [_or C2M_] finds the moab
> * preservation audit says “unexpected version!” [_but then updates the catalog to the version seen on disk_]
> * item comes off the queue for `update-catalog`
> * prescat says “what’s going on here?” [_in response to the pres robot `update-catalog` API request_]
> * so you see errors in preservationAudit and preservationIngest [_set by pres cat when responding with an error to the late pres robots `update-catalog` request_]

bracketed notes and some emphasis/formatting are @jmartin-sul's.

There are two broad categories of fix that I can think of off-hand, but we should discuss as a team.  I'm not wild about either of these ideas:
1. When looking at a specific druid, pres cat asks pres robots whether that druid is queued for processing.
  - advantages
    - keeps things event driven, keeps us biased towards updating the catalog based on known events.
  - disadvantages
    - introduces a circular dependency in terms of network API calls between pres cat and pres robots.  currently, pres robots call pres cat, but not vice versa (pres robots has no API available to other apps over the network).
    - i'm not sure if redis supports this sort of query across the queue in a performant way.
2. If a pres robots worker says to `update-catalog` with a version it just added to a Moab, and it's the version pres cat has in the catalog, respond with a non-`500` http code (`200`?  some other `2xx` that indicates the resource already exists?).  Still send a honeybadger alert?  This is unusual, but now a known condition, and I think there's a good chance we'd ignore the alerts anyway.
  - advantages
    - simpler, avoids circular dependency
  - disadvantages
    - reduces strictness of expectations around update calls from pres robots to pres cat.  allows more opportunity for a bug in pres robots update to overwrite existing info about a preserved version of something, without a scary alert.

actually, a 2b.:
- Similar to 2, above, but pres robots sends as one of its request params a hash of `manifestInventory.xml` from the Moab version it's calling `update-catalog` on.  If pres cat sees that it has that Moab version already, calculate a hash of `manifestInventory.xml` for that Moab version.  If it matches the one sent by pres robots, all good, respond with a `200`, maybe log a warning and/or send a clearly info/non-scary HB message.
  - advantages
    - avoids circular dependency
    - gives assurance that pres robots worker really was trying to tell pres cat about the exact content it was already aware of.  we get this assurance is because `manifestInventory.xml` has signatures (checksums and sizes) for all the other manifest files in the moab version, and one of those manifest files is `signatureCatalog.xml`, which has signatures for all content files in that version and prior versions.
    - probably no more complex than option 1 above
    - should be performant:  the file to be checksummed is typically a few hundred kB at most.
  - disadvantages
    - more complex than option 2 above
    - would require touching the dreaded `CompleteMoabHandler` in pres cat 😄, though i think this is a pretty approachable thing to have to do with it.


Now that I've thought it through a bit more, i actually like option 2b.  but would still love feedback for other approaches or refinements to any of the above.

**Comment by jmartin-sul** [comment]
There are two broad categories of fix that I can think of off-hand, but we should discuss as a team.  I'm not wild about either of these ideas:
1. When looking at a specific druid, pres cat asks pres robots whether that druid is queued for processing.
  - advantages
    - keeps things event driven, keeps us biased towards updating the catalog based on known events.
  - disadvantages
    - introduces a circular dependency in terms of network API calls between pres cat and pres robots.  currently, pres robots call pres cat, but not vice versa (pres robots has no API available to other apps over the network).
    - i'm not sure if redis supports this sort of query across the queue in a performant way.
2. If a pres robots worker says to `update-catalog` with a version it just added to a Moab, and it's the version pres cat has in the catalog, respond with a non-`500` http code (`200`?  some other `2xx` that indicates the resource already exists?).  Still send a honeybadger alert?  This is unusual, but now a known condition, and I think there's a good chance we'd ignore the alerts anyway.
  - advantages
    - simpler, avoids circular dependency
  - disadvantages
    - reduces strictness of expectations around update calls from pres robots to pres cat.  allows more opportunity for a bug in pres robots update to overwrite existing info about a preserved version of something, without a scary alert.

Actually, idea 2b.:
- Similar to 2, above, but pres robots worker sends as one of its request params a hash of `manifestInventory.xml` from the Moab version it's calling `update-catalog` on.  If pres cat sees that it has that Moab version already, calculate a hash of `manifestInventory.xml` for that Moab version.  If it matches the one sent by pres robots, all good, respond with a `200`, maybe log a warning and/or send a clearly info/non-scary HB message.
  - advantages
    - avoids circular service dependency
    - gives assurance that the pres robots worker really was trying to tell pres cat about the exact content pres cat was already aware of.  we get this assurance is because `manifestInventory.xml` has signatures (checksums and sizes) for all the other manifest files in the moab version ([example](https://github.com/sul-dlss/preservation_catalog/tree/34755248115348bce3e0de97cd45dde3a2ba053f/spec/fixtures/storage_root01/sdr2objects/bj/102/hs/9687/bj102hs9687/v0003/manifests/manifestInventory.xml)), and one of those manifest files is `signatureCatalog.xml`, which has signatures for all content files in that version and prior versions.  through that chain of signatures, we can have pretty good assurance that pres robots and pres cat are in agreement about the content in question.
    - probably no more complex than option 1 above
    - should be performant:  the file to be checksummed is typically a few kB.
  - disadvantages
    - more complex than option 2 above
    - would require touching the dreaded `CompleteMoabHandler` in pres cat 😄, though i think this is a relatively approachable thing to have to do with it.


Now that I've thought it through a bit more, I actually like option 2b.  But would still love feedback, whether other approaches or refinements to any of the above.

**Comment by ndushay** [comment]
Has this been addressed by allocating workers to specific queues?

**Comment by ndushay** [comment]
I believe this is no longer a problem since the most recent comment is 2020;  closing the ticket.
