### ISSUE TITLE
zipmaker job: delete zips that fail file size check

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1637]
TO DO: if the zip size check determines that the zip is bad (because it's not large enough to contain all the expected content), delete the bad zip. 

WHY: This will make it easier to retry the failed zipmaker job without either manually cleaning up busted zip files, or waiting for the regular zip cache cleaning process to clean the zip up (zip file currently expires when it hasn't been accessed in a week, i.e. a time more than 7 days old, iirc).

**Comment by jmartin-sul** [comment]
i've done part of this work -- i've implemented the app code change in https://github.com/sul-dlss/preservation_catalog/pull/1644, but the work still needs a new test.  happy to pair if someone else wants to pick this up to finish it off.
