### ISSUE TITLE
prescat resque - zipmaker* failed jobs cleanup - need to restart failed jobs AND clean up this queue

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1638]
NOTE:  as of 2020-10-05, there is a plan to retry the entire failed zipmaker jobs queue and delete the existing failed jobs and see if we can vastly reduce the list currently showing.   This is awaiting Julian to finish some work on a script he is writing; once he gives the ok, we will proceed.  Nevertheless, this is an ongoing problem that needs a solution. 

GOAL:  make it possible to look at zipmaker** failed queue and see current errors only.  

https://preservation-catalog-prod-01.stanford.edu/resque/failed/zipmaker_failed  current shows 1281 failed zipmaker jobs.  These failures date from August 2020.  In fact, they dated from July 2020, but I manually removed some:

![image](https://user-images.githubusercontent.com/96775/95126210-f1a32380-070a-11eb-8d26-7350fe8bf424.png)

IDEAS:
- make it FR job to manually restart these, empty queue, and look for repeaters???
- automagically retry failed jobs and remove them from the failed queue (@jmartin-sul thought about these; no credit to me)
    - switch to sidekiq?  Concerns below***
    - plugins for resque that add scheduling and retry functionality
        - resque-retry: https://github.com/lantins/resque-retry
        - resque-scheduler: https://github.com/resque/resque-scheduler
    - retries gem - poor choice.  not maintained, no gradual backoff, manual management of failure queue, etc.

** maybe apply to any of the prescat resque queues?  

*** this would require we vet our code and dependencies for thread safety. we'd have to look for things like class vars and other thread unsafe implementation techniques in pres cat and its dependencies. for whatever reason, i'm esp worried about moab-versioning, which i don't think was written w/ thread safety in mind, and which may cache things in class vars. also the sidekiq wiki claims the aws-s3 gem isn't thread safe, and that would likely be a dealbreaker for pres cat, because of the delivery workers. resque spawns a process per worker, so this isn't a concern with resque workers.

**Comment by ndushay** [comment]
If we have to hand code (i would hope not!), here's a little info:

![image](https://user-images.githubusercontent.com/96775/95142179-f7f3c880-0727-11eb-9ff1-9c04fdf163f3.png)

**Comment by jmartin-sul** [comment]
here's some code for examining failures and finding bad zip files:

```ruby
# there should be well under 2000 errors, but check the web console to make sure there aren't, and that this captures everything
# https://preservation-catalog-prod-01.stanford.edu/resque/overview
max_failures_to_dump = 2000
failure_queue_name = 'zipmaker_failed'
puts 'not showing all failures!' unless Resque::Failure.count(failure_queue_name) < max_failures_to_dump
zipmaker_failures = Resque::Failure.all(0, max_failures_to_dump, failure_queue_name).map do |failure|
  {
    failed_at: failure['failed_at'],
    args: failure['payload']['args'].map { |arg| arg.slice('queue_name', 'job_class', 'arguments') },
    exception: failure['exception'],
    error: failure['error'],
    worker: failure['worker'],
    queue: failure['queue'],
  }
end ; nil

File.open(File.join(Rails.root, 'log', "zipmaker_failure_capture_#{Time.now.utc.iso8601.to_s}.log"), 'w') { |file| file.write(zipmaker_failures) }

# just the ZipmakerJob args:  druid, version, storage_location -- e.g.: ["hw812nt2613", 2, "/pres-01/sdr2objects"]
zipmaker_failure_arg_lists = zipmaker_failures.map { |failure| failure[:args][0]['arguments'] } ; nil
zm_druid_version_zips = zipmaker_failure_arg_lists.map { |args| DruidVersionZip.new(args[0], args[1], args[2]) } ; nil
bad_druid_version_zips = zm_druid_version_zips.map do |dvz|
  if File.exist?(dvz.file_path)
    if dvz.send(:zip_size_ok?)
      puts "ok: zip exists at #{dvz.file_path}, but size is ok"
      nil
    else
      puts "ERROR: zip exists at #{dvz.file_path} but is smaller than moab version"
      dvz
    end
  else
    nil
  end
end ; nil
```

**Comment by jmartin-sul** [comment]
i believe the specific failures for which this ticket was filed have been addressed.

for future issues, i've added a wiki entry to help first responders who haven't encountered this issue before: https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-a-failed-zipmaker-job
