### ISSUE TITLE
ChecksumValidator should handle Nokogiri parse errors gracefully

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1696]
⚠️ _warning_ ⚠️ -- it doesn't matter whether this happens before or after #1697, just make sure both aren't being worked at the same time, because then one or more developers will likely be in for a painful rebase.

**Describe the bug**
If Nokogiri runs into an unexpected parsing error, say an empty XML file, it will crash `ChecksumValidator` in such a way that `ChecksumValidator` will not update the `CompleteMoab#status` to `invalid_checksum`.  In the usual situation, where `CheckumValidator` is being run by `ChecksumValidationJob`, the job will fail, land will and in the `checksum_validation_failed` queue.  Even if the Moab fails checksum validation, the job should succeed from the perspective of Resque's job management, and the error should be reported by marking `status` and sending a honeybadger alert, as happens with most situations where `ChecksumValidator` detects an error in the Moab.

https://app.honeybadger.io/projects/54415/faults/79310268
https://github.com/sul-dlss/preservation_catalog/blob/80bcd90c54d8d40edbf14c177f4c53d88b89ca9e/app/services/checksum_validator.rb#L187

```
[PROJECT_ROOT]/app/services/checksum_validator.rb:187 :in `latest_signature_catalog_entries`
  # @return [Array<SignatureCatalogEntry>]
  def latest_signature_catalog_entries
    @latest_signature_catalog_entries ||= latest_moab_version.signature_catalog.entries
  rescue Errno::ENOENT, NoMethodError # e.g. latest_moab_version.signature_catalog is nil (signatureCatalog.xml does not exist)
    results.add_result(AuditResults::SIGNATURE_CATALOG_NOT_IN_MOAB, signature_catalog_path: latest_signature_catalog_path)
[PROJECT_ROOT]/app/services/checksum_validator.rb:194 :in `paths_from_signature_catalog`
[PROJECT_ROOT]/app/services/checksum_validator.rb:208 :in `signature_catalog_has_file?`
[PROJECT_ROOT]/app/services/checksum_validator.rb:204 :in `validate_against_signature_catalog`
[PROJECT_ROOT]/app/services/checksum_validator.rb:104 :in `block in flag_unexpected_data_files`
[PROJECT_ROOT]/app/services/checksum_validator.rb:104 :in `each`
[PROJECT_ROOT]/app/services/checksum_validator.rb:104 :in `flag_unexpected_data_files`
[PROJECT_ROOT]/app/services/checksum_validator.rb:81 :in `validate_signature_catalog`
[PROJECT_ROOT]/app/services/checksum_validator.rb:33 :in `validate_checksums`
[PROJECT_ROOT]/app/jobs/checksum_validation_job.rb:14 :in `perform` 
```

**User Impact**

Some Moabs that are corrupt will have incorrect status, usually `ok`, and the issue with the Moab will not be easily queryable.  The only indication of a problem is a cryptic entry in the Resque failure queue.  This might lead to a false sense of security about the integrity of some of our preservation objects.

**Object(s) In This Error State**

at present:
* yq896mc2480
* yg880zm4762
* cq580gn5234
* ym971gq9293

**Steps to Reproduce, if Known**

run `ChecksumValidator` on a `CompleteMoab` record for a Moab in preservation storage that has an empty or otherwise unparsable XML manifest file (e.g. a zero-length `signatureCatalog.xml`).

For example, as of 2021-05-19 on prod:
```ruby
ChecksumValidator.new(CompleteMoab.by_druid('yq896mc2480').take).validate_checksums
```

will reproduce the bad behavior.

**Expected behavior**

`ChecksumValidator` marks the `CompleteMoab#status` as `invalid_checksum`, as it would with any other validation failure.  It does not result in the method call crashing, or a failed Resque job if invoked from `ChecksumValidationJob`.

**Screenshots**

<img width="1290" alt="Screen Shot 2021-05-19 at 3 23 14 PM" src="https://user-images.githubusercontent.com/7741604/118892708-276dd480-b8b6-11eb-97af-1283d79fbb8e.png">

**Additional context**

see #1695 for more background info and possibly useful scripting.

**Comment by ndushay** [comment]
There's already a pattern for handling this sort of parsing error somewhere in the code ...

**Comment by jmartin-sul** [comment]
ah!  i just noticed that the error is coming from the error handling 🤦 

so the error is being raised from an example of the existing error handling:
https://github.com/sul-dlss/preservation_catalog/blob/2dc297dd416f5264902fabb919805cac666a26db/app/services/checksum_validator.rb#L185-L191

in general the error handling seems to assume `latest_signature_catalog_path` will not error.

so, maybe just add some limited error handling here?  https://github.com/sul-dlss/preservation_catalog/blob/2dc297dd416f5264902fabb919805cac666a26db/app/services/checksum_validator.rb#L181-L183

**Comment by jmartin-sul** [comment]
Looking at the full stack trace, the error is happening here:

```
storage_object_version.rb 132 signature_catalog(...)
[GEM_ROOT]/gems/moab-versioning-4.4.1/lib/moab/storage_object_version.rb:132:in `signature_catalog'
  def signature_catalog
    if version_id > 0
      SignatureCatalog.read_xml_file(@version_pathname.join('manifests'))
    else
          SignatureCatalog.new(:digital_object_id => @storage_object.digital_object_id)

  checksum_validator.rb 187 latest_signature_catalog_entries(...)
  [PROJECT_ROOT]/app/services/checksum_validator.rb:187:in `latest_signature_catalog_entries'

# @return [Array<SignatureCatalogEntry>]
def latest_signature_catalog_entries
  @latest_signature_catalog_entries ||= latest_moab_version.signature_catalog.entries
rescue Errno::ENOENT, NoMethodError # e.g. latest_moab_version.signature_catalog is nil (signatureCatalog.xml does not exist)
  results.add_result(AuditResults::SIGNATURE_CATALOG_NOT_IN_MOAB, signature_catalog_path: latest_signature_catalog_path)
```

So, for a targeted fix, I _think_ I'd be inclined to `rescue Nokogiri::XML::SyntaxError` in either `latest_signature_catalog_entries` or `paths_from_signature_catalog`.  Probably `latest_signature_catalog_entries`, and as a separate rescue from the `rescue Errno::ENOENT, NoMethodError` on line 188.  Possibly with a new result code?  e.g. `AuditResults::SIGNATURE_CATALOG_UNPARSABLE`.

For testing, we could just add a small new Moab fixture with a garbage signature catalog, and test that running `#valdite_checksums` on it determines that the Moab is invalid, without raising.  At present, https://argo.stanford.edu/view/yg880zm4762 (the druid from the HB alert) still fits the bill.  In case it gets remediated, I'll attach a copy here (zipped, because github doesn't like xml files).

[signatureCatalog_corrupted.zip](https://github.com/sul-dlss/preservation_catalog/files/6534597/signatureCatalog_corrupted.zip)
.
