### ISSUE TITLE
make it possible to checksum validate a Moab without having to reference preservation catalog's database

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1697]
⚠️ _warning_ ⚠️ -- it doesn't matter whether this happens before or after #1696, just make sure both aren't being worked at the same time, because then one or more developers will likely be in for a painful rebase.

see #1691 for more context.

Hopefully it isn't _too_ difficult to do this by slightly refactoring and generalizing `ChecksumValidator` so that it can take a druid and a storage location, or even just a path to a Moab, and do all the same checksum validation it currently does, without having to look at or update the database.  It should make results available to the caller.  While it would be convenient to point `ChecksumValidator` at any purported Moab folder in any location, for practical purposes for now, it is safe to assume that the Moab in question at least resides in the known storage roots in a Moab directory tree (since we are still validating content being updated by the usual pres robots process).

I'm happy to pair on implementation ideas if that's helpful, and also jotted down some thoughts around implementation here:  https://github.com/sul-dlss/preservation_catalog/issues/1691#issuecomment-841437740

Maybe it _should_ mark the `CompleteMoab#status` as `invalid_checksum` if there is an entry in the catalog already, but it _shouldn't_ create an entry anew, or update anything else (including `#version`)?  Not sure, warrants further discussion.  Would be fine to err on the side of being naive and not updating at all.  Another option would be to set the `PreservedObject#robot_versioning_allowed` flag to `false` if there is already a `PreservedObject` record.

**Comment by ndushay** [comment]
We came up with a way to do this with Julian's help with a script against only moab-validation gem;   

We also want to make this an automatic part of preservation workflow, which is ticketed separately.

**Comment by jmartin-sul** [comment]
> We also want to make this an automatic part of preservation workflow, which is ticketed separately.

just to clarify:  this is the first ticket in that set of tickets.

at the end of the day, the important part for this ticket is that we end up with some checksum validation code that can be invoked from the job that'll be implemented by #1698.

as discussed in FR handoff this morning, it'd be fine, functionally, to call the aforementioned script code we got from julian.

but, i personally think it'd be preferable, time permitting, to modify the existing `ChecksumValidator` class.  having two separate CV classes seems less than ideal from a maintenance perspective, especially since people new to this codebase already find parts of it confusing.

if it looks like i'm wrong about refactoring `ChecksumValdiator` making for more readable code, or if there just isn't time to do it that way, i'd have no objection to just making a new class out of julian's script (see [moab-versioning readme](https://github.com/sul-dlss/moab-versioning/#soup-to-nuts-example-of-validating-a-druid-at-stanford) for script).
