### ISSUE TITLE
prescat failing okcomputer status check

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1702]
We have at least one druid that hasn't had a C2M (Catalog-to-Moab) or a CV (Checksum Validation) in over 2 weeks.

```
feature-version-audit-window-check: FAILED CompleteMoab#last_version_audit older than 2021-05-10 23:46:52 UTC
```

![image](https://user-images.githubusercontent.com/96775/119531464-cbcd9c00-bd38-11eb-9d9d-895d39d99c35.png)

If this is no longer true, close this ticket.

If it is still true:

1.  ensure all the cron jobs are on (as of May 25, 2021, they are)
2.  do db query to find out if this is one druid, a handful or many of them
3.  try manually running C2M and CV on one of the druids -- any errors?  (check honeybadger and logs)
3a.  ticket errors?
3b.  if no errors, get a list of offending druids, and run them (?)

**Comment by jcoyne** [comment]
I just asked ops to open this endpoint up to VPN (like we have for all other projects).

**Comment by peetucket** [comment]
This is an older issue and that check is no longer failing.  Closing for now.
