### ISSUE TITLE
(PC) storage_dir helper method would be nice

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#171]
turns out there are a number of places already in the codebase where we do the following to get the path where druid trees live under a particular storage root:
```ruby
storage_dir = File.join(storage_root, Settings.moab.storage_trunk)
```

we could write a helper method like the following to cut down on that repetition:
```ruby
def storage_dir(storage_root)
  File.join(storage_root, Settings.moab.storage_trunk)
end
```

**Comment by tingulfsen** [comment]
It seems like we only do this in one or two places in the code at this time. So I'll close this ticket and just leave this for now.
