### ISSUE TITLE
create a method for cleaning up catalog entries for replication failures

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1748]
for context, this is the current manual process, which doesn't really scale past more than a few druids at a time:  https://github.com/sul-dlss/preservation_catalog/wiki/Cleaning-up-delivery-failures

see also #1733 (this issue describes the meat of the code for the remediation approach described there -- it'd be nice to have it as a properly tested method, so that it can be called from the rails console, and so that we don't have too much important remediation code in an untested rake task)

I think the new method belongs in a new service class, maybe something like `CatalogRemediator#delete_failed_replication_records!`?  It might require some helper methods?  Or maybe not, up to the implementer.

The goal of the method is to take a druid and version, and for that druid/version combo, delete from the database any `ZippedMoabVersion`s (and any child `ZipPart`s for such ZMVs) for which replication to the ZMV's particular cloud endpoint did not fully succeed.  Additionally, I think we should refrain from cleaning up any ZMVs younger than `zip_cache_expiry_time`, to avoid things that might be retriable.  Note that `zip_cache_expiry_time` is specified in minutes in a format that can be fed easily to the `find` command, e.g.

`zip_cache_expiry_time: '+10080' # this is UNIX `find` speak for "greater than seven days"`

Very roughly, I think this method does something like:
* given a druid and version, query for all such `ZippedMoabVersion`s (ZMVs hang off `PreservedObject`, which has the druid, see schema here: https://github.com/sul-dlss/preservation_catalog/tree/main/db)
* for each ZMV older than `zip_cache_expiry_time`, do what `PartReplicationAuditJob` does, and call the two methods it calls in its ZMV loop:  https://github.com/sul-dlss/preservation_catalog/blob/a213649bf733557731f20d7f21c2cb9eacfb63e2/app/jobs/part_replication_audit_job.rb#L17-L18 (this will require instantiating and passing in an `AuditResults` instance, which i think should probably be instantiated anew for each ZMV; it might also be nice to log the results)
* if the ZMV that was just checked has any errors in the audit results (or if it has no child parts), and it's old enough, remove that `ZippedMoabVersion` and its child `ZipPart`s, if any.
* it's probably best to do the deletion for each ZMV (and its child ZPs) in a transaction.  however, the audit code will reach out to the cloud to check for presence of the expected zip parts (assuming it doesn't detect a problem just by looking at the DB entries), so it's probably best not to wrap the audit calls in a transaction (or at least, i don't see much benefit since we're already filtering for things that should be too told to be in flux, and even a few quick network calls inside a DB transaction seems like it should be avoided if possible).
* return the version number and endpoint name for each ZMV that was removed

We can figure out a way to cause some delivery failures or create some bad DB records for testing on QA or stage.

Totally happy to pair on this, and would be interested in feedback on the suggested approach.  Definitely open to other ideas.  The approach I describe above is sort of an amalgam of the above linked wiki entry and the approach described in 2 on [this comment](https://github.com/sul-dlss/preservation_catalog/issues/1733#issuecomment-900730705).  One thing that comment suggests is a size check on the zip parts, basically an audit version of what `ZipMaker` currently does to confirm that the size of the zip it creates is consistent with the size of the moab version in our on prem storage roots (since we might've made some bad uploads before `ZipMaker` had that check added).  Now that I realize we can just reuse some existing audit code in this new method, I think we should just let the size check happen in the audit code we're calling (e.g. `check_child_zip_part_attributes`?), and I'd implement that new size check under the already filed ticket #1742.

**Comment by jmartin-sul** [comment]
might also be good to set `check_unreplicated_parts` to true when calling `check_replicated_zipped_moab_version` in the method we're writing for this issue.

**Comment by julianmorley** [comment]
I'd have a slight preference for having the method work on druid,version rather than druid. Can always be wrapped into another class to handle an entire druid, but a feel a more atomic approach would be more efficient. When I've found issues it's been with a specific druid,version and I don't see value in doing an audit (esp. with cloud checks) against the entire druid when I already know where the problem is.

**Comment by jmartin-sul** [comment]
updated the description to be about dealing with druid/version (as opposed to a whole druid), following some discussion with @julianmorley and some pairing with @mjgiarlo.
