### ISSUE TITLE
(MV)   verify Moab contains only a sequential set of ‘version’ subdirs

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#175]
Contains only a sequential set of ‘version’ subdirs, starting at v0001

connects #177
connects to #179
connects to #178

**Comment by jmartin-sul** [comment]
this might ultimately belong in the moab-versioning gem, because it's about checking characteristics of a moab directory on disk

**Comment by jmartin-sul** [comment]
this ticket gets closed when the call is in place in preservation catalog.

for the moab-versioning part, spawn a separate ticket and PR in the moab-versioning gem.  this ticket will require upgrading to the version of moab-versioning that includes the desired call, and making the call in PC.
