### ISSUE TITLE
(M2C) (MV) verify Each version directory contains only data and manifests subdirs

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#176]
Each version directory contains only data and manifests subdirs
connects to #177 
connects to #175
connects to #179
connects to #178

**Comment by ndushay** [comment]
It's possible moab-versioning  moab/storage_object_version #verify_xxx would help with this???   or storage_object methods?

**Comment by jmartin-sul** [comment]
this ticket gets closed when the call is in place in preservation catalog.

for the moab-versioning part, spawn a separate ticket and PR in the moab-versioning gem.  this ticket will require upgrading to the version of moab-versioning that includes the desired call, and making the call in PC.
