### ISSUE TITLE
(MV) #create_with_validation

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#177]
That it does not contain any ‘nested’ Moabs (a complete Moab object dir placed inside the dir of another Moab, a result of bad initial file copy/move).

**Comment by SaravShah** [comment]
Something to check for ```bj/102/hs/9687/bj102hs9687/v0004/bj/102/hs/9687/ba12fhs1447/```

**Comment by SaravShah** [comment]
the easiest check is to just confirm there are only /manifests and /data directories under each version dir, and that there are only /content and /metadata dirs under /data. No other directories anywhere else.

**Comment by jmartin-sul** [comment]
this might ultimately belong in the moab-versioning gem, because it's about checking characteristics of a moab directory on disk

**Comment by jmartin-sul** [comment]
this ticket gets closed when the call is in place in preservation catalog.

for the moab-versioning part, spawn a separate ticket and PR in the moab-versioning gem.  this ticket will require upgrading to the version of moab-versioning that includes the desired call, and making the call in PC.

**Comment by tallenaz** [comment]
Related to sul-dlss/moab-versioning/issues/63

**Comment by ndushay** [comment]
See #279 -- please put this "hook up MV/D2D validation" code into pohandler.create_with_validation
