### ISSUE TITLE
(MV)  verify each manifest subdir contains manifestInventory.xml and signatureCatalog.xml

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#178]
Each /version/manifest subdir contains at least a manifestInventory.xml file and a signatureCatalog.xml file (without these, it is impossible to perform checksum validation).

connects #177

**Comment by ndushay** [comment]
It's possible moab-versioning  moab/storage_object_version #verify_manifest_inventory would help with this???

**Comment by jmartin-sul** [comment]
this might ultimately belong in the moab-versioning gem, because it's about checking characteristics of a moab directory on disk
