### ISSUE TITLE
zip temp space pruning is a bit too aggressive

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1782]
**Describe the bug**
@mjgiarlo noticed that the script for cleaning up empty dirs in the zip temp space is likely too aggressive, and is deleting the root directory of the temp space if the temp space is entirely empty.  see https://github.com/sul-dlss/preservation_catalog/blob/bdc2df54aa9f48d0bdb142c0464eed6858dfecd6/lib/tasks/prescat.rake#L14-L17

**User Impact**
on prod and stage, this is essentially a non-issue, because there is enough activity that the temp space is never fully empty, and so the root of the zip temp storage never gets removed.  on low activity envs like QA, this can lead to the unexpected disappearance of the zip temp space.

**Object(s) In This Error State**

N/A

**Steps to Reproduce, if Known:**

allow the zip temp empty dir cleaner to run while there are no zips in the specified zip transfer dir (defined by `Settings.zip_storage`).

**Expected behavior**

root zip temp dir (`Settings.zip_storage`) never gets deleted.

**Screenshots**

N/A

**Additional context**

discovered after the cron job for temp space cleanup was enabled in https://github.com/sul-dlss/preservation_catalog/pull/1775

**Comment by jmartin-sul** [comment]
iirc `find` has a minimum depth option?  maybe adding that flag with the appropriate value that would suffice?

**Comment by mjgiarlo** [comment]
@jmartin-sul `-mindepth 1` ought to suffice as long as we're not concerned about files clogging up the root dir. I assume files aren't put in the root dir?

**Comment by jmartin-sul** [comment]
> @jmartin-sul `-mindepth 1` ought to suffice as long as we're not concerned about files clogging up the root dir. I assume files aren't put in the root dir?

sorry, forgot to reply to this yesterday, but that's correct:  everything in the zip temp space should be contained in a druid tree, so there should be no files loose in the root of the zip temp dir.
