### ISSUE TITLE
prod deployment hangs on resque-pool hotswap step

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1783]
**Describe the bug**
starting with @aaron-collier running dependency updates last week, we noticed that when deploying the app to production, the deployment process will hang on the resque-pool hotswap step (where the workers are restarted).  if the resque pool hotswap cap task is run alone against prod, it will hang too.

other observations:
* this doesn't seem to happen for stage or QA
* this wasn't happening until last week
* it does seem that the app is successfully deployed, and the worker pools successfully restarted (e.g. you can see a new resque pool master process with a start time stamp from right after deployment was started).  but something must hang before the hotswap invocation returns.  or something.

**User Impact**

nothing direct, this just makes deployment more of a pain for devs (as the deployment must be cancelled out of using `^C` once it's apparent the process is hung, and then the dev should probably go check that things were deployed and restarted correctly).  it makes it hard to include pres cat in the bulk deployments for weekly dependency updates (because it'll hang subsequent deployments that happen to fall after it, i.e. any project with a name lexically greater than `preservation_catalog`).

**Object(s) In This Error State**

N/A

**Steps to Reproduce, if Known:**

`cap deploy` or run the `resque:pool:hotswap` task for prod

**Expected behavior**

resque pool hotswap doesn't hang, and returns in a timely manner on success or error

**Screenshots**

n/a

**Additional context**

n/a

**Comment by peetucket** [comment]
If you control-c out of the hung resque-pool swap process and want to manually complete the deployment steps that were missed by capistrano (after confirming that the worker counts look ok and that there are no stale workers to deal with):

```
cap prod deploy:cleanup
cap prod honeybadger:deploy
cap prod deploy:log_revision
```

**Comment by peetucket** [comment]
Note: `deploy:log_revision` seems to hang with run manually

**Comment by jmartin-sul** [comment]
I did some debugging on this last week, which stalled out since I was out sick part of Friday.  What I've found so far:

could use some pairing on further troubleshooting resque-pool restart thing and seeing the command
* `bundle exec resque-pool --daemon --hot-swap --environment production` runs fine from a login shell on the box
* but it hangs when run via `cap` (or even when run slightly more directly by invoking on VM using `ssh pres@ ...` from laptop)
* though the `hotswap`, and in @peetucket's testing the `deploy:log_revision`, commands seems like only victims of that, and only on prod:  none of this seems to happen on QA or stage, which both allow cap deployment of pres cat with no trouble
* one other thing of note:  the qa/stage/prod pres cat environments all use different operating systems, and prod is the only one on ubuntu ATM.

**Comment by jmartin-sul** [comment]
note:  pre-assembly devopsdocs has info on how to check whether there are stale workers in a resque-pool instance:  https://github.com/sul-dlss/DevOpsDocs/blob/master/projects/pre-assembly/operations-concerns.md#stop-unresponsive-workers-workers-with-jobs-that-are-taking-too-long-and-zombie-workers

**Comment by jmartin-sul** [comment]
@mjgiarlo says: "I tried tweaking the cap task to print out more diagnostic information and it did so just fine.  it's just something about that hot swap operation executed via cap?  Like, it can invoke bundle exec resque-pool --help just fine."

**Comment by peetucket** [comment]
Has anyone tried to see what happens if we invoke the command manually on the server that cap is executing?  I would assume the issue is not necessarily capistrano, but rather the hot swap operation command (whatever that is).

**Comment by jmartin-sul** [comment]
> Has anyone tried to see what happens if we invoke the command manually on the server that cap is executing? I would assume the issue is not necessarily capistrano, but rather the hot swap operation command (whatever that is).

surprisingly, that seems to work fine, tested that and ran into no problems, noted above, i think

**Comment by jmartin-sul** [comment]
the extra weird part to me was that running the command over ssh indicated that it returned, and then something else caused the cap command to hang mysteriously after that, see end of this comment: https://github.com/sul-dlss/preservation_catalog/issues/1783#issuecomment-1016863245

**Comment by jmartin-sul** [comment]
@edsu ran across this resque-pool issue, which may be relevant:  https://github.com/nevans/resque-pool/issues/107

**Comment by edsu** [comment]
It's a longshot but perhaps changing the QUIT to a INT over in [dlss-capistrano](https://github.com/sul-dlss/dlss-capistrano/blob/c5a04066115a1317e81361bafd52f96c0b5aff12/lib/dlss/capistrano/resque_pool/tasks/resque_pool.rake#L53) might help?

**Comment by ndushay** [comment]
- We tried using `INT` and `TERM` instead of `QUIT` and the result was the same -- the command executes fine on prod and stage but the ssh connection hangs for prod only.

- We found this: https://askubuntu.com/questions/1343677/ssh-terminal-always-freezes-after-2minutes-of-inactivity so I sent the following to ops channel:

>Hi ops - we are investigating a weird difference between prescat-prod worker boxes and prescat-stage worker box.   When we run a capistrano command to spin up our resque workers, the command executes just fine, but the ssh connection to the prod box hangs, while that analogous ssh connection to the stage box does NOT hang.  The command itself can be run just fine on the box, too.  It’s just the ssh for prod never gets the “I’m done” signal.   Might there be some firewall difference or puppet difference that could explain this?
