### ISSUE TITLE
(M2C)  verify druid in manifest matches directory tree

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#179]
identify the most recent version, and positively identify the druid (read most recent manifestInventory.xml for objectId; match against druidtree path - i.e. does the path /aa/123/bb/1234/aa123bb1234 really contain a Moab object of the druid aa123bb1234? ).

connects #177

**Comment by jmartin-sul** [comment]
this might ultimately belong in the moab-versioning gem, because it's about checking characteristics of a moab directory on disk

**Comment by jmartin-sul** [comment]
this ticket gets closed when the call is in place in preservation catalog.

for the moab-versioning part, spawn a separate ticket and PR in the moab-versioning gem.  this ticket will require upgrading to the version of moab-versioning that includes the desired call, and making the call in PC.

**Comment by tallenaz** [comment]
Related to sul-dlss/moab-versioning#71

**Comment by tallenaz** [comment]
`moab-versioning` v2.5.0, which includes D2D check, is released. Once https://github.com/sul-dlss/preservation_catalog/pull/291 is merged, we can make the call in PC.
