### ISSUE TITLE
upgrade resque gem

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1793]
currently `resque` is pinned to 1.x, but as @mjgiarlo and @edsu observe, the last release in that line was from 2017 (around the time of pres cat's inception):

resque's [release history](https://rubygems.org/gems/resque/):
* 2.2.1 - March 27, 2022 (98.5 KB)
* 2.2.0 - November 04, 2021 (94.5 KB)
* 2.1.0 - August 10, 2021 (94.5 KB)
* 2.0.0 - November 06, 2018 (96 KB)
* 1.27.4 - April 15, 2017 (96 KB) _(what pres cat is currently using, released a few months before this repo was started in aug 2017)_
* 1.27.3 - April 10, 2017 (96 KB)

we should:
- [ ] look at the release notes to see if there's any cause for concern about breaking changes
- [ ] right after dependency updates are tagged for the week, do the upgrade on `main`, including any tweaks we know we'll need to make up front for resque 2.x compatibility (hopefully none?)
- [ ] deploy to stage and test by
  - [ ] using infra integration tests, esp `create_preassembly_image_spec.rb`, which checks for replication of a two version object
  - [ ] manually running some audit jobs (e.g. checksum validation, replication audit)
  - [ ] letting it run for the week, running all the audits on all the updated/created druids (post upgrade deployment) that friday.
- [ ] if testing looks good, leave it in `main`, and alert e.g. @andrewjbtw just to be extra safe (so he's on the lookout for any odd worker behavior or stalled accessioning).  if we discover inexplicable gaps in replication or failure of audits to run or things like that, we can roll back the change and investigate.

**Comment by jmartin-sul** [comment]
> > relevant discussion of a deprecation warning we're seeing (which would still be an issue even if we upgraded Resque, if i'm understanding this issue correctly): [resque/resque#1794](https://github.com/resque/resque/issues/1794)
> 
> Yea I can confirm this - I'm using Resque 2.2.0 and still getting the warning. Were you able to find a solution? Thanks!

@varun43in nope, we have yet to upgrade, and haven't yet tried to work around the issue.

i suspect that if no one beats us to it, we'll look at submitting a patch back to resque?  hoping someone beats us to it though, as i'm not sure any of us have done work in the resque gem before.  i haven't dug into what a fix might take, and my familiarity with the internals of resque is a bit spotty.

i can also imagine us just pinning the indirect redis dependency for a bit, if it comes to that.

**Comment by ndushay** [comment]
technically not blocked but pointless if we switch to sidekiq

**Comment by justinlittman** [comment]
Closing this because we're not going to do the work. Rather, we'll be switching to sidekiq.
