### ISSUE TITLE
fix up wiki entry about replication troubleshooting and cleanup

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1809]
in light of the work done here: https://github.com/sul-dlss/preservation_catalog/pull/1750

and the schema modifications of summer 2020 (having `ZippedMoabVersion` hang off `PreservedObject` instead of `CompleteMoab`).

these pages in particular:
- [ ] https://github.com/sul-dlss/preservation_catalog/wiki/Cleaning-up-delivery-failures
- [x] https://github.com/sul-dlss/preservation_catalog/wiki/Fixing-an-Incomplete-Moab-Upload

@jmartin-sul is happy to pair on this if someone else picks it up.

**Comment by ndushay** [comment]
Closing this ticket, as we have the newly organized and edited wiki, and the page not yet updated is now a Legacy page.
