### ISSUE TITLE
[BLOCKED by switching to sidekiq] Redis.current= Deprecation warning

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/preservation_catalog#1819]
**Describe the bug**
`Redis.current=` is deprecated and will be removed in 5.0. (called from: /Users/jcoyne85/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/redis-namespace-1.8.1/lib/redis/namespace.rb:245:in `initialize')

See https://github.com/resque/redis-namespace/issues/189

This will block our upgrade to the redis gem 5.0

**Comment by ndushay** [comment]
technically not blocked but pointless if we switch to sidekiq

**Comment by jmartin-sul** [comment]
made moot by #1984
