### ISSUE TITLE
make ResultsRecorderJob more resilient

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1860]
`ResultsRecorderJob` potentially does two different things that involve a network connection to another service, either of which could fail independently.

The first is a set of queries to find the `unreplicated` zip part for the given druid/version/zip part, and then update it to `ok` if found.  In practice, this rarely if ever fails, except for when it's already run successfully, because then there's no `unreplicated` zip part to find (so the `find_by!` throws `ActiveRecord::RecordNotFound` ` Couldn't find ZipPart with [WHERE "zip_parts"."zipped_moab_version_id" = $1 AND "zip_parts"."suffix" = $2 AND "zip_parts"."status" = $3]`).  See [here](https://github.com/sul-dlss/preservation_catalog/blob/c023c714adcb6868123d72d147eb9666b2b4592e/app/jobs/results_recorder_job.rb#L28-L29) and [here](https://github.com/sul-dlss/preservation_catalog/blob/c023c714adcb6868123d72d147eb9666b2b4592e/app/jobs/results_recorder_job.rb#L15-L21).

The other, if the first operation is successful _and_ the success makes for the complete replication of the druid version in question to the cloud endpoint in question, is to emit an event to DSA indicating that the druid version was replicated successfully (e.g. v2 of bc123df4567 was successfully replicated to AWS east).  See [here](https://github.com/sul-dlss/preservation_catalog/blob/c023c714adcb6868123d72d147eb9666b2b4592e/app/jobs/results_recorder_job.rb#L32).  Because of intermittent local internal network flakiness, and/or DSA unavailability because of Fedora load, these event service calls tend to fail 10s or 100s of times per month.  Because of the non-idempotence of the first operation, retrying the job on this failure results in its erroring out with the above described `RecordNotFound` exception.  This basically results in us dumping errors like that and forgoing the event reporting for the druid/version/endpoint combos that hit this DSA connection blip.  To remediate the job failures, we'd have to hand-create the DSA events.  This seems like more trouble than it's worth, because if a replication event is missing on an object in Argo, we can always run replication audit on it in pres cat to find its current status.

THERE WERE 3 options for fixing this, but we have chosen this one:

Split out the event reporting into a separate job that `ResultsRecorderJob` hands off to where it currently uses dor-services-client directly.  I think that would mean just splitting [this code](https://github.com/sul-dlss/preservation_catalog/blob/c023c714adcb6868123d72d147eb9666b2b4592e/app/jobs/results_recorder_job.rb#L72-L82) into its own new job and calling `perform_later` on that job in place of the code that was factored out into the new job.  This would also require updating the diagram in [app/jobs/README.md](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md) (hopefully straight-forward, there's a link to the lucidchart project that was used to generate the current image file).  May also require updating `spec/jobs/integration_spec.rb` and `results_recorder_job_spec.rb`.

If you'd like to see the other possible options, they should be in the edit history for this description comment.

`ResultsRecorderJob` errors show up in [`zip_endpoint_events_failed`](https://preservation-catalog-web-prod-01.stanford.edu/resque/failed/zip_endpoint_events_failed)

See also:
https://app.honeybadger.io/projects/54415/faults/79834140
https://app.honeybadger.io/projects/54415/faults/82830079

**Comment by ndushay** [comment]
@jmartin-sul what is the "question" on this ticket?  I would say if we are going to switch to sidekiq, option 2 is the one for us.

**Comment by jmartin-sul** [comment]
> @jmartin-sul what is the "question" on this ticket? I would say if we are going to switch to sidekiq, option 2 is the one for us.

i think the question was just "which option?"

option 2 sounds fine to me.  i don't think sidekiq precludes option 1, but i would agree that option 2 is the better choice in a world where the default behavior is to automate retries, esp since the desired exponential back-off is the default sidekiq behavior.  and option 2 feels "most correct" ™️ of the 3 anyway.

will amend issue description and drop the "question" label.

**Comment by ndushay** [comment]
The action for this ticket is to implement option 2 from above.

**Comment by justinlittman** [comment]
Based on discussion with @ndushay and @jmartin-sul, going to turn event creation into an async call instead of the current sync call to DSA. This is consistent with https://sul-dlss-labs.github.io/infrastructure-adrs/records/0010/#event-logging

**Comment by ndushay** [comment]
@justinlittman is this WIP?  Should you assign yourself to this ticket and move it to in progress column?
