### ISSUE TITLE
wiki: create sidebar link for restarting failed job

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1868]
- [ ] Include all the below  (possibly combine with zip size 0 content thingy)
- [ ] add link to new content in sidebar (troubleshooting section) from home page
- [ ] replace the stuff in devopsdocs with link to new wiki page
- [ ] remove similar content elsewhere in the wiki (possibly linking to new page)

## From DevOpsDocs

1. Find the failed job:  https://preservation-catalog-web-prod-01.stanford.edu/resque/failed
- Retry a single failed job: You can got to a single job by clicking on the link for a queue, and then you will see the individual jobs.  You can then hover over a job to see a retry link towards the upper right of the individual job block.
- Retry a single queue's failed jobs:  from https://preservation-catalog-web-prod-01.stanford.edu/resque/failed, click on a link for a queue.  You will see a link in the upper right to retry all the queue's failed jobs.
- Retry all failed jobs:  You probably don't want to do this -- there are often old failed jobs we don't want to retry.  But if you do, there's a link in the upper right at https://preservation-catalog-web-prod-01.stanford.edu/resque/failed

**Comment by jmartin-sul** [comment]
automatic retries were introduced by the [switch to sidekiq](#1984)
