### ISSUE TITLE
port "create_bag.rb" script over to a prescat server

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_catalog#1871]
There's a script called `create_bag.rb` that's used to perform SDRGET requests (requests to retrieve data from SDR). The script is located here:
https://github.com/sul-dlss/preservation_robots/blob/main/bin/create_bag.rb

For what I think are historical reasons, that script was ported to preservation_robots around 2019. It came from a decommissioned server that was turned off around the time I started in 2019. I think it would be safer to put it on one of the prescat boxes because those mount the preservation system read-only. As far as I know, the script does not need write access to preservation.

Putting this script on a prescat box would reduce the amount of times I have to `ssh` into preservation-robots, which I think will be better for all of us. I want to reduce how often I use a login with write access to preservation as much as possible.

**What the script does**

I run that script against a list of druids in a text file and supply a target directory, and then it creates a set of subdirectories in that target directory that uses the BagIt format, one subdirectory for each druid. It doesn't actually copy any files and instead relies on symlinks to where the files are in preservation.

Typical usage is:

`ruby create_bag.rb /tmp/sdrget/sdrget-folder/druids.txt /tmp/sdrget/sdrget-folder/`

I then copy the files (following the symlinks) from the `/tmp/sdrget/sdrget-folder` to the destination that the requestor asked for (shared mount, Google Drive, Globus, etc.).

I'd also be ok with creating a different way to fill these retrieval requests, but the this script has been covering the basic requirements for years. These requests are primarily for large number of file and/or large amounts of data (in the TB range), so any alternative would need to be able to handle that.

**Comment by edsu** [comment]
@andrewjbtw would you like `create_bag.rb` removed from preservation_robots once it is ported?
