### ISSUE TITLE
EPIC: Preservation Replication Jobs - automate retries

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1880]
Sidekiq preferred, since we use it elsewhere already.

- make ResultsRecordJob more resilient

If Sidekiq:
- everything must be thread-safe.
- replace job locking via resque. 

If not Sidekiq:
- could be resque-retry gem

See https://docs.google.com/document/d/13eI6_Y1ZnkBEoaBNIPY_886McIPkGSfb119wuFoTI-Y/edit#heading=h.yglxk38a1j3i  for more info

**Comment by jmartin-sul** [comment]
see also https://github.com/sul-dlss/preservation_catalog/issues/1860 (which should likely block this ticket)

**Comment by ndushay** [comment]
@jmartin-sul this is an Epic ticket, and should not be marked as blocked.  Thanks for the info, will address the blocking as needed on the board.

**Comment by jmartin-sul** [comment]
> @jmartin-sul this is an Epic ticket, and should not be marked as blocked. Thanks for the info, will address the blocking as needed on the board.

ah good point, sorry!

**Comment by jmartin-sul** [comment]
automated by #1984
