### ISSUE TITLE
[refactor] Extract job locking code to a separate subclass

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/preservation_catalog#1899]
Currently the locking applies to all children of ApplicationJob.  In the future we may add new jobs that do not need this locking behavior, and we may inherit it by default without knowing we are doing so.  This is just about making the locking code explicitly opt-in rather than getting it by default. This will help readers of the code understand that there is some non-default code happening.

**Comment by ndushay** [comment]
@justinlittman not sure if this is something you want to tackle as part of your work?
