### ISSUE TITLE
schema refinement questions, semantics for existing catalog fields

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#191]
some random questions we came up with while working on #183:
* should `preservation_copies` have a `size` column?  we're using `size` as a way to know size consumed on a particular disk, so it'd seem to make more sense on a pres copy, which represents a concrete instance of an object on an endpoint, as opposed to a `PreservedObject`, which is the abstract records for all the preservation copies on various endpoints for a given druid.
  * likewise, should `preserved_objects` have a size col?  by the above logic, i now sort of think this is a column we should remove from that table (and the corresponding AR model).
* should we be setting `preservation_copies.last_checked_on_storage` when creating a pres copy for the first time?  i'd guess yes.  and probably should when updating it after an inventory or fixity check?
* should we get rid of `preservation_copies.last_audited`?  is this col superseded by the more granular `last_checked_on_storage` and `last_checksum_validation` columns?  or does it have a distinct use of its own?
* is it worth adding a compound unique constraint on `preservation_copies` for the combo of `preserved_object_id`, `endpoint_id`, and `current_version`?  will a particular version of a particular druid ever have more than one instance on a given endpoint?  

i figure this is a catch all discussion/investigation ticket, and we can spawn implementation tickets if/as needed

**Comment by ndushay** [comment]
I agree with your assessments. My votes are:
- size should live with preservation_copies, not with preserved_object
- yes, set last_checked_on_storage when creating pres_copy 
- yes, use more granular dates and remove the generic
- yes, add compound unique constraint

**Comment by atz** [comment]
Way outdated now, so closing.
