### ISSUE TITLE
Question: Is there a continued need for the audit workflow

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/preservation_catalog#1921]
This is a question for @andrewjbtw 

Now that we are recording the audit results in the events and in honeybadger, must we continue to use the audit workflow?  A workflow doesn't seem like a good fit here as no "work" happens.

https://github.com/sul-dlss/preservation_catalog/blob/e0363bca31079f3a435e42567bb0ca46242f9591/app/services/audit_results.rb#L159-L160

**Comment by jmartin-sul** [comment]
fwiw, we've always reported to HB, even before the event service.  and i think i recall there being some desire to have a failed audit prevent further versioning, which is a good fit for workflow service, though that was a happy accident and not an original goal of sending errors to WFS (which was just an easy way to expose audit issues in argo -- we thought it'd be easier than properly indexing the audit errors into solr, but i think we ended up realizing we were wrong about that).

regardless, certainly worth re-considering, and definitely a question for @andrewjbtw

**Comment by andrewjbtw** [comment]
There were two reasons we kept the audit workflow the last time this came up:

1. There's no other way to get a current picture of current items that have failed an audit.
2. There's no other way to block further accessioning of an item that's failed an audit. Without the workflow, you could open a new version of an item that failed audit. It would probably still stall somewhere in accessioning, but it would be harder to deal with than if accessioning never began.

If we can find alternative ways to meet those two needs - know what's in a an audit failure state and prevent creating new versions until an item passes audit - we can take away the workflow.

**Comment by jcoyne** [comment]
I was unaware of the case where a failing audit blocks further accessioning.  I see this is effective in Argo, but do the other avenues of accessioning are respect this?

**Comment by andrewjbtw** [comment]
I believe it causes the "is this openable?" check to say "no" but I haven't tried to version an object in this state recently.

**Comment by jcoyne** [comment]
Andrew is correct. It is needed for that use case.
