### ISSUE TITLE
Investigate PresCat OK computer failure

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/preservation_catalog#1933]
The `FeatureVersionAuditWindowCheck` is currently failing with a date that seems too old: https://preservation-catalog-web-prod-02.stanford.edu/status/feature-version-audit-window-check

The check is marked OPTIONAL.

**Comment by peetucket** [comment]
Everything should be checksumed at minimum every 90 days, an m2c and c2m job should be run at least once a month (one of the 1st and the other on the 15th via cron: https://github.com/sul-dlss/preservation_catalog/blob/main/config/schedule.rb#L8-L19)

Recent change to that schedule: https://github.com/sul-dlss/preservation_catalog/pull/1895

From John in Slack (https://stanfordlib.slack.com/archives/C09M7P91R/p1661965845294219)

```
queries i ran:
[13] pry(main)> CompleteMoab.pluck('MIN(last_checksum_validation)')
=> [2022-04-04 08:15:57.448649 UTC]
```

```
something like what the okcomputer check is doing:
[1] pry(main)> clause = 21.days.ago
=> Wed, 10 Aug 2022 17:02:04.975181322 UTC +00:00
[2] pry(main)> CompleteMoab.least_recent_version_audit(clause).first
=> #<CompleteMoab:0x0000555db854aba8
 id: 1,
 version: 9,
 preserved_object_id: 1,
 moab_storage_root_id: 25,
 created_at: Thu, 18 Jan 2018 18:56:07.785254000 UTC +00:00,
 updated_at: Fri, 01 Jul 2022 18:00:30.754842000 UTC +00:00,
 last_moab_validation: Sun, 15 May 2022 08:01:30.735288000 UTC +00:00,
 last_checksum_validation: Sun, 15 May 2022 08:01:30.569237000 UTC +00:00,
 size: 11110101,
 status: "ok",
 last_version_audit: Fri, 01 Jul 2022 18:00:30.748787000 UTC +00:00,
 status_details: "validate_checksums (actual location: pres-01; actual version: 9) checksum(s) match",
 from_moab_storage_root_id: nil>
```

```
slightly worrisome:
[3] pry(main)> CompleteMoab.pluck('MIN(last_version_audit)')
=> [2022-07-01 18:00:30.210009 UTC]
```

```
would expect that to be more like august 15 or so, when the last C2M run should've gone?
[13] pry(main)> CompleteMoab.pluck('MIN(last_checksum_validation)')
=> [2022-04-04 08:15:57.448649 UTC]
would expect that to be more like mid to late may

we do lots of logging around audits, and the queries that cron jobs use to queue the validation work should be built into the models and tested, so hopefully this shouldn't be hard to troubleshoot.  as naomi says, the cron jobs that queue things for audit are configured via whenever gem.
```

**Comment by peetucket** [comment]
The cron jobs on `preservation-catalog-prod-02` seem to be scheduled just fine and the `schedule.rb` seems fine too.  There are error log files for each job timestamped at the expected dates as if the jobs had run and have no entries.   There are no output log files though with those timestamps (the most recent log file output for the M2C and C2M jobs have older timestamps).  Nothing obvious in honeybadger.  

Potential tasks:

- [ ] look at the M2C on the 1st and see if jobs are getting queued and run: https://preservation-catalog-web-prod-01.stanford.edu/resque/queues/m2c
- [ ] look at the C2M resque on the 15th and see if jobs are getting queued and run: https://preservation-catalog-web-prod-01.stanford.edu/resque/queues/c2m
- [ ] try to run these jobs manually at some point (though in a way they don't overlap)?
- [ ] look at the job logic and maybe try it on a single druid to see if it works as expected

**Comment by ndushay** [comment]
See #1939 as related ?

**Comment by justinlittman** [comment]
This OK computer check is currently passing, so closing. If it re-occurs, this ticket can be re-opened.
