### ISSUE TITLE
even out checksum validation and replication audit load over time by queueing a block of the least recently checked druids every day

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1939]
### Problem

When lots of objects have very proximate values for `complete_moabs.last_checksum_validation` or `preserved_objects.last_archive_audit`, they'll all exceed the TTL for those values during the same week, and will all be queued for checksum validation or cloud replication audit (respectively) together the same week.  This can lead to situations where we run checksum validation or cloud archive audit on a significant portion of our catalog some weeks, and not much of our catalog on other weeks.  This is suboptimal, because it's generally nice to have even and predictable load for disk IO intensive operations (checksum validation) and network IO intensive operations (replication audit).

### Solution

After some discussion on Slack (see `#dlss-preservation-dev`, week of 2022-09-19), we've settled on the following approach, which at a high level, tries to process whatever percentage of the catalog per day is needed to keep all the validation timestamps within the configured expiry time:
* on a daily basis, queue the least recently audited `daily_check_count` druids.
  * for replication audit `daily_check_count = PreservedObject.count / (PreservationPolicy.default_policy.archive_ttl / (60*60*24))`
  * for checksum validation `daily_check_count = CompleteMoab.count / (PreservationPolicy.default_policy.fixity_ttl / (60*60*24))`
  * some assumptions made by those formulae
    * `_ttl` values are in seconds, hence the conversion to days
    * We don't care about policies besides default policy, because it's the only policy that exists at the moment.  Because we haven't used policies in the 4+ years that pres cat has been running, the team has started discussing removing the functionality altogether, which would simplify the DB schema and some queries, though this needs further discussion and ticketing (pres cat maintenance analysis is on deck for next work cycle).  Using this approach on a per-policy basis certainly isn't impossible, but it is more complicated, and has no practical benefit at the moment.  Additionally, even if we were to start using additional preservation policies with shorter TTL values (which would require feature development to automate, or manual database futzing to apply retroactively as a one-off), this naive approach should still be an improvement on the current situation.  (If we got rid of `PreservationPolicy`, I assume the TTL values would just become config values)

Since TTL is currently 90 days, that means we'd queue the oldest 1/90th of `PreservedObject`s for archive audit, and the oldest 1/90th of `CompleteMoab`s for checksum validation.  As of a few minutes ago, that's 52875 druids/day for each.

So, e.g., you could add a class method to `CompleteMoab` like
```ruby
def self.daily_check_count
  CompleteMoab.count / (PreservationPolicy.default_policy.fixity_ttl / (60*60*24))
end
```

and a cron job to `schedule.rb` like
```ruby
every :day, at: '9am', , roles: [:queue_populator] do
  set :output, standard: nil, error: 'log/cv-err.log'
  runner 'CompleteMoab.order(last_checksum_validation: :asc).limit(CompleteMoab.daily_check_count).find_each(&:validate_checksums!)
end
```

and then similarly for archive audit, but a class method on `PreservedObject` for `daily_check_count`
```ruby
def self.daily_check_count
  PreservedObject.count / (PreservationPolicy.default_policy.fixity_ttl / (60*60*24))
end
```

and a cron job similar to the above (but calling `audit_moab_version_replication!` instead of `validate_checksums!`, querying `PreservedObject` instead of `CompleteMoab`, ordering by `last_archive_audit` instead of `last_checksum_validation`, and logging to `log/c2a-err.log` instead of `cv-err.log`).

and then we'd leave in place the existing weekly audit jobs that queue everything that's expired.  hopefully they'll be queueing a very small number of stragglers per week.

**Comment by julianmorley** [comment]
I'd suggest that the daily cron start after 8PM daily. It's OK (nay, desirable!) for it to run thru the night, and this means it's less likely to conflict with any local daily traffic that might be working its way thru the system.
