### ISSUE TITLE
refactor??   classes with more than 100 lines ?? (i.e. with respect to SOLID principles)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1951]
`find app -name '*.rb' | xargs wc -l | sort`

```
      57 app/models/moab_storage_root.rb
      63 app/jobs/plexer_job.rb
      63 app/lib/audit/moab_to_catalog.rb
      64 app/controllers/application_controller.rb
      67 app/services/reporters/base_reporter.rb
      71 app/controllers/catalog_controller.rb
      72 app/services/catalog_remediator.rb
      75 app/models/druid_version_zip_part.rb
      76 app/models/zip_endpoint.rb
      77 app/models/preserved_object.rb
      84 app/services/reporters/event_service_reporter.rb
      86 app/jobs/results_recorder_job.rb
      94 app/lib/audit/catalog_to_moab.rb
      97 app/lib/preservation_catalog/s3_audit.rb
     102 app/services/reporters/audit_workflow_reporter.rb
     119 app/services/moab_storage_root_reporter.rb
     119 app/services/moab_validator.rb
     121 app/jobs/validate_moab_job.rb
     127 app/jobs/concerns/unique_job.rb
--- # ripe for refactoring below this line ???  SOLID as a guide? ---
     140 app/models/complete_moab.rb
     175 app/controllers/objects_controller.rb
     199 app/services/audit_results.rb
     220 app/models/druid_version_zip.rb
     232 app/services/checksum_validator.rb
     355 app/services/complete_moab_handler.rb
```

**Comment by edsu** [comment]
I think we want to be careful not to split up one large class into a many different shorter ones because having long classes is a "bad thing". Having many different classes and abstractions to keep open in your editor, and your head, can also make for hard to understand code, especially if the abstraction's only purpose is to be short.

**Comment by ndushay** [comment]
> I think we want to be careful not to split up one large class into a many different shorter ones because having long classes is a "bad thing". Having many different classes and abstractions to keep open in your editor, and your head, can also make for hard to understand code, especially if the abstraction's only purpose is to be short.

I agree completely, Ed.  I should have added that SOLID principles (or some other set of principles) are more important than class length.

**Comment by ndushay** [comment]
Much improved!

----
     101 app/services/audit/catalog_to_moab.rb
     102 app/services/reporters/audit_workflow_reporter.rb
     117 app/jobs/validate_moab_job.rb
     119 app/services/moab_storage_root_reporter.rb
     123 app/helpers/dashboard_catalog_helper.rb
     132 app/jobs/concerns/unique_job.rb
     137 app/models/complete_moab.rb
     146 app/services/complete_moab_service/base.rb
     161 app/controllers/objects_controller.rb
     164 app/models/audit_results.rb
     220 app/models/druid_version_zip.rb
     294 app/services/checksum_validator.rb

Closing this.
