### ISSUE TITLE
Diagram the overall architecture of preservation catalog

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1959]
questions:
- [ ] where does this live?  README.md?  a wiki page?
- [ ] what's the right level of granularity and what do we highlight?  classes?  internal services?  areas of functionality?  connections with other services?
- [ ] do we treat the things that already have their own diagrams (i.e. the replication pipeline in [app/jobs/README.md](https://github.com/sul-dlss/preservation_catalog/blob/main/app/jobs/README.md), the schema diagram in [db/README.md](https://github.com/sul-dlss/preservation_catalog/blob/main/db/README.md))
- [ ] what tool should we use?  @edsu points out that [Mermaid](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) might be a good fit, since the diagram can be described directly in a Markdown file without linking to an external SVG.  another option might be LucidChart, for which Stanford has a site license.  Also, the Google Docs drawing/diagramming tool.
- [ ] how does this fit in with the overall SDR current state architecture diagram?  e.g. https://docs.google.com/drawings/d/1jAy5BRlC5l4HZprHXyrM1KTa_dLSbjveniBik9U6WMY/edit

**Comment by ndushay** [comment]
team discussion - we decided to close this;  we have the db diagram in https://github.com/sul-dlss/preservation_catalog/tree/main/db

also covered somewhat by SDR diagram.
