### ISSUE TITLE
(M2C)  refactor how we use %{addl}

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#196]
some new uses of %{addl} should maybe be %{obj_class_name} (actually, this prob requires assuming addl will be a hash w/ named params, since var name addl is expected by helper methods result_code_msg and result_hash)

**Comment by ndushay** [comment]
@SaravShah can you provide a little more context:  which class?  and is this in PC code base?

**Comment by SaravShah** [comment]
Yeah so when John and I were pairing on separating the create and update methods from preserved_object_handler.rb we figured that instead of using the %{addl} variable we should use something more descriptive like %{obj_class_name} for some of the response code messages.  However not all of the use cases for %{addl} were object class names, like in the case of  ``` result_hash(INVALID_ARGUMENTS, errors.full_messages) ``` so not sure if we should do anything with this.

**Comment by ndushay** [comment]
closing this;  will revisit if it becomes important -- probably in a new ticket
