### ISSUE TITLE
refactor(?):  remove preservation_policy db table

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1961]
From [maint/tech debt storytime discussion Wed 10/19](https://docs.google.com/document/d/1vTv9ySljSgJ-zcrH2ZztDpdUtnVCxe_hgfZnIehkPGs/edit#heading=h.a6kqlslw7c5o):

We only have one preservation policy;   reducing the complexity of the db schema and of the code associated with the table will redux complexity.

Note: in order:
- [ ] remove code referencing the table (maybe reference a class with the info instead?)
- [ ] remove the table

**Comment by andrewjbtw** [comment]
What are/were preservation policies?
