### ISSUE TITLE
design/prototype Dashboard to visually represent "it's working" or "it's broken"

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1962]
From  [maint/tech debt storytime discussion Wed 10/19](https://docs.google.com/document/d/1vTv9ySljSgJ-zcrH2ZztDpdUtnVCxe_hgfZnIehkPGs/edit#heading=h.a6kqlslw7c5o):

Preservation system:

- What are metrics ?
- What does success look like?
- How can we have a visual representation of “yes it's working” or “no, it’s not working” for this complex system?
    - Would like an improvement over Honeybadger alerts.

- There are dashboards for google books and for techmd service.
- See the [Wiki page](https://github.com/sul-dlss/preservation_catalog/wiki/Notes-from-Preservation-Catalog-knowledge-transfer) that includes, "What might a user want to do manually?":
- Lots of useful queries in [DB readme](https://github.com/sul-dlss/preservation_catalog/blob/main/db/README.md)
    - Query the catalog to see what state a particular object or set of objects is in
    - how many objects are in a given state for a given storage root, 
    - how many objects are in a given state for a given replication endpoint, etc.
     - Integrity check individual objects, lists of objects, objects on a given storage root, etc.

@jmartin-sul will talk to Astrid and to Andrew about this.

-----
Motivation:   preservation has lots of pieces that all have to fit together:  cron jobs, code bases, background jobs, robots, prescat, external services, etc.  It’s a big, complex ecosystem that is unfamiliar to some.

-----
Exploratory prototype code is also welcome, but don't get too attached to it.

**Comment by ndushay** [comment]
random thoughts of what might be useful:
- number of objects in prescat
- number of object versions preserved
- sizes of above - total, per object
- unresolved replication errors, possibly by s3 endpoint
- grouped info for each s3 endpoint 
  - number of objects at each s3 endpoint
  - number of files at each s3 endpoint (bigger than 10G is split into chunks)
- for each audit type
  - most recent audit
  - number of objects with audit errors
  - ...
- next cron job to be run???
- anything about preservation robots?  (query workflow server for step counts, step counts per druid??)

**Comment by ndushay** [comment]
More ideas:
- okcomputer checks?
- See the [Wiki page](https://github.com/sul-dlss/preservation_catalog/wiki/Notes-from-Preservation-Catalog-knowledge-transfer) that includes, "What might a user want to do manually?":
- Lots of useful queries in [DB readme](https://github.com/sul-dlss/preservation_catalog/blob/main/db/README.md)
    - Query the catalog to see what state a particular object or set of objects is in
    - how many objects are in a given state for a given storage root, 
    - how many objects are in a given state for a given replication endpoint, etc.
     - Integrity check individual objects, lists of objects, objects on a given storage root, etc.

**Comment by edsu** [comment]
I spent a bit of time looking at the types of errors in the Wiki and did a bit of [blue sky] thinking about what a dashboard could look like. I was thinking that clicking on the DRUID IDs, or looking up a DRUID ,would go to a detail page about that object from the perspective of PresCat which I have not designed yet. This is just meant to be generative for discussion. It was also my first time trying to use Figma.

![Desktop - 1](https://user-images.githubusercontent.com/33829/197799754-a2a940d1-5e47-492b-b13b-7c0897148cd9.png)

**Comment by ndushay** [comment]
@edsu there is an API call to get info about a particular druid;  not sure if adding an html format to that would be useful?  In any case, it's not "dashboard" ...   just wondering about usage.

**Comment by edsu** [comment]
@ndushay Yes, I was imagining that the interface would potentially involve some API calls if it was implemented? What did you mean by the second part: "In any case..." ?

**Comment by ndushay** [comment]
I was suggesting that the html forms to submit druids to get info might not be on the dash board page itself.  But whatevs.
