### ISSUE TITLE
refactor complete_moab_handler to reduce complexity

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1964]
From  [maint/tech debt storytime discussion Wed 10/19](https://docs.google.com/document/d/1vTv9ySljSgJ-zcrH2ZztDpdUtnVCxe_hgfZnIehkPGs/edit#heading=h.a6kqlslw7c5o):

`complete_moab_handler` is the biggest class at 355 lines.  It also has 5 of the largest spec files.  See notes.

JLitt suggests that someone just pick the refactor ticket, start refactoring, and see if they get to something better / throw it out to the team for review.

- The class name itself doesn’t make clear what it does.
- This is the longest class, and the specs for this class were broken up, to some extent by method:
    - check_existence - 605 line spec
        - An overview: 
           ![image](https://user-images.githubusercontent.com/96775/196817949-85848cc1-4004-447d-9a4a-dab958dccb8c.png)
    - confirm_version - 276 line spec
    - create - 225 line spec
    - update_version 754 line spec
    - with a shared_examples spec file of 469 lines
  

One idea:  refactor the 4 actions above into their own services.  If that seems like a good approach, try it for one action, and see how it goes.  Feel free to separately ticket other pieces.

**Comment by justinlittman** [comment]
8 PRs later, I'm declaring victory.
