### ISSUE TITLE
refactor AuditResults class

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1965]
From  [maint/tech debt storytime discussion Wed 10/19](https://docs.google.com/document/d/1vTv9ySljSgJ-zcrH2ZztDpdUtnVCxe_hgfZnIehkPGs/edit#heading=h.a6kqlslw7c5o):

This is one of our 5 biggest classes:

![image](https://user-images.githubusercontent.com/96775/196819005-45688a96-4771-4711-b79e-9b17a25e23ae.png)

John already has some ideas for refactors / rethinking of how this is done, but feel free to branch out on your own ...

**Comment by ndushay** [comment]
@justinlittman are there any useful thoughts in #1955

**Comment by justinlittman** [comment]
Thanks for referencing #1155. I'd suggest that switching to error lists is a significant functionality change and not a plain-old refactoring.  Thoughts @jmartin-sul ?

**Comment by jmartin-sul** [comment]
> Thanks for referencing #1155. I'd suggest that switching to error lists is a significant functionality change and not a plain-old refactoring. Thoughts @jmartin-sul ?

i would agree -- while there's definitely interplay between result list reporting and the setting of status codes (or the updating of error lists if we make that switch), i think they're kinda sorta orthogonal.  my gut feeling is that the switch to error lists might slightly change what events are recorded in a result list, or maybe not... but won't significantly change the idea that we want to capture a list of highlights from an update or audit that get logged or sent to the event service (or to HB or workflow service).
