### ISSUE TITLE
Create "Getting Started with Preservation" document

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#1971]
create a basic intro document for understanding the preservation system:

 -what is prescat
- how and why do we replicate to cloud
  - which cloud services
- how and why do we audit
  - which audits do we run
- what is moab version and why do we use it (could be 2 sentences and a link to the paper in code4lib journal)
- what do pres robots do

See also: https://github.com/sul-dlss/preservation_catalog/wiki/Notes-from-Preservation-Catalog-knowledge-transfer#preservation-catalog-introduction

link to diagram from #1959

**Comment by edsu** [comment]
I like this idea, especially if it can fit up front in the README rather than being a separate document or Wiki page. I think a "What is PresCat" rather than a "Getting Started" is a helpful framing. What services does PresCat perform in the SDR, and how does it work?

**Comment by justinlittman** [comment]
Here is the use case: When a future first responder has to take a look at a pres issue and can't remember what a "complete moab" is or what the "catalog to moab" job does.

**Comment by ndushay** [comment]
I think maybe a bunch of stuff on the current README could become wiki pages or separate `.md` pages.  I think our README should be:

- how to run tests
- getting started

we also need to split out a glossary of terms -- a lot of them are in the DB readme.

The dashboard should help, too.   It's very very early in development right now, but:

![image](https://user-images.githubusercontent.com/96775/197404549-e8ce0040-d5fb-43e1-8f90-7f5756af8684.png)

**Comment by edsu** [comment]
Does it make sense to port some of the description of PresCat in [the wiki](https://github.com/sul-dlss/preservation_catalog/wiki/Notes-from-Preservation-Catalog-knowledge-transfer#preservation-catalog-introduction) to the README?

**Comment by ndushay** [comment]
> Does it make sense to port some of the description of PresCat in [the wiki](https://github.com/sul-dlss/preservation_catalog/wiki/Notes-from-Preservation-Catalog-knowledge-transfer#preservation-catalog-introduction) to the README?

I think this is a good question for realtime discussion.  Post standup, or maybe storytime:  what do we want out of prescat documentation.

**Comment by ndushay** [comment]
@edsu - I thought you were doing this?

**Comment by edsu** [comment]
I didn't want to wait for me to come back from vacation if someone felt inspired :-)
