### ISSUE TITLE
Dashboard: Audit Status:  Each error condition should link to appropriate details

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#2004]
e.g. In this image, the Catalog to Archive Status error badge should be a link to information about the error and how to fix it.

![image](https://user-images.githubusercontent.com/96775/199277620-597cfc41-8447-4d7a-af0a-ef825632bf25.png)

**Comment by mjgiarlo** [comment]
@ndushay This appears to be blocked no longer. Do you think this can/should move to Ready now?

**Comment by ndushay** [comment]
This ticket about the dashboard is old and I am closing it.
