### ISSUE TITLE
Consider restructuring replication

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/preservation_catalog#2007]
Currently, replication is split across multiple jobs. A failure in a job can be difficult to correct because it may require touching the DB and/or repeating other jobs.

For this ticket, we will propose restructuring replication. In particular, we will consider an approach that uses a single job per druids and version and that job will be retriable. Steps within the job that have already been completed, e.g., creating a zip or replicating to an endpoint, will not be repeated.

In addition to normal replication, cases to be considered include:
* Two versions created in rapid succession.
* Adding an additional endpoint for already replicated druids and versions.

**Comment by justinlittman** [comment]
Next step for this ticket is for @jmartin-sul to flesh out a proposal, answering question like whether/which data in the db can be used to determine the state of replication.

Presumably the new replication job would be in its own queue with its own dedicated workers (and other jobs would be in their own queues), so I think we should still have adequate control over resource allocation. (The proposed approach to Sidekiq will give use Resque-like control over worker allocation. However, it's not one-to-one since Resque is process based and Sidekiq is a combination of process and thread based.)

**Comment by ndushay** [comment]
@jmartin-sul is this something for you, or something for a storytime?

**Comment by mjgiarlo** [comment]
In light of @justinlittman's and @ndushay's questions above, it seems like we need some guidance from @jmartin-sul to unblock and clarify what's needed for this ticket to move to Ready.

**Comment by ndushay** [comment]
@justinlittman I think we kind of discussed this last week - that grouping the replication jobs into one job is way more complex than doing it for the audits, and probably not worth it.   I don't remember the reasons -- something something retriability of jobs by sidekiq, perhaps?

If you agree, maybe this ticket can be closed.

**Comment by justinlittman** [comment]
Yes, that was @jmartin-sul 's conclusion.
