### ISSUE TITLE
README:  include some info about how to run the web app locally w foreman

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#2031]
#2025 switched us to using Foreman, so a pointer to use `bin/dev` instead of `rails s` in the README would be helpful.

**Comment by edsu** [comment]
@ndushay it seems to me like the current docs are oriented towards getting a development up and running with Docker, so running `bin/dev` (which invoked foreman) isn't really needed?

**Comment by edsu** [comment]
Actually I take it back, it looks like the `Dockerfile` copies the application source files to the container once during the `docker compose build app` and isn't really suitable for live development, unless you want to keep rebuilding the image.
