### ISSUE TITLE
Make DruidVersionZip.zip_split_size into a setting

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#2037]
This should really be in the config/settings.yml file instead of being hardcoded, no?  (check with John)

```ruby
# @return [String] the option included with "zip -s"
  def zip_split_size
    '10g'
  end
```

**Comment by justinlittman** [comment]
Why? If we don't vary it between environments (or for that matter ever change it), then the clearest and most concise location is directly in the code where it is used.

**Comment by julianmorley** [comment]
If we distributed this code to others, then absolutely be a setting. But we don't, and we don't want to change it by accident, so I'm on team JLitt here.

**Comment by ndushay** [comment]
I had to dig through a lot of code to find it, is why.
