### ISSUE TITLE
`DruidVersionZip` and `DruidVersionZipPart` models go in `Replication` namespace within "models" dir

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#2065]
from storytime 2022-11-21

"druid_version_zip and druid_version_zip_part: put in Replication namespace. They are not ActiveRecord models."

(Replication namespace in models directory, I believe)

**Comment by justinlittman** [comment]
Maybe I'm mistaken, but I thought the suggestion was to put them in a replication namespace within models (since they are models).
