### ISSUE TITLE
Log names should match job names whatever they are logging for

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/preservation_catalog#2071]
Once all of the refactoring / renaming as settled down, change the log names so that they reflect what they are logging.

currently we have some logs "c2m", "cv", etc.

Also ensure the logs are being rotated to long term storage (?)

**Comment by mjgiarlo** [comment]
@justinlittman @jmartin-sul Are there particular refactorings / renamings that you'd call out as blocking? I'd like to reflect those relationships in the board so it's clearer when this can move to Ready. Thanks!
