### ISSUE TITLE
First pass at addressing replication errors + providing missing interstitial documentation

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#2081]
from storytime 11-28-2002:

We want to
- address existing production replication errors
- address documentation(?) gap in how to resolve those errors

What John would do to fix these errors:

 (explained in this [comment](https://github.com/sul-dlss/preservation_catalog/issues/1733#issuecomment-1071061148)):

1. Identify errored druids (using dashboard)
2. Run rake task on identified druids so it can clean up DB records
3. Take list of druid versions it spits out, give to ops for cloud cleanup
4. Once ops has cleaned up, trigger replication on the druid list
5. In rails console, run PreservedObject.create_zipped_moab_versions!

Next Steps, more or less framed as an FR duty:

- [ ] “Leslie” runs through the above steps to fix production errors  (John to advise as needed) and takes notes
- [ ]  “Leslie” creates documentation that “Leslie” would need if they had to do this in 6 months, and/or if John and “Leslie” are both hit by a truck.  A wiki page would be good, but could be a google doc ...
- [ ]  “Leslie” either creates a ticket or does the work of 
    - [ ] putting a link in the wiki sidebar* troubleshooting section  (just do this, please) to this new documentation
    - [ ] putting a link in an appropriate place in the dashboard to this new documentation 

@edsu is FR next week, and he is willing to take on the role of "Leslie"

* 
![image](https://user-images.githubusercontent.com/96775/204406996-34a67254-ddd2-4b40-a656-d73ce0b404f0.png)

**Comment by edsu** [comment]
On @jmartin-sul's advice I added a section about extracting druids from Honeybadger alerts to this wiki page:

https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-failed-Resque-Jobs

We will need to revisit that documentation to remove mention of using Resque since it is no longer being used in prescat.

**Comment by edsu** [comment]
The section on getting Druids from HB was moved to https://github.com/sul-dlss/preservation_catalog/wiki/Investigating-a-druid-with-replication-errors#getting-a-list-of-druids which isn't specific to Resque.

**Comment by edsu** [comment]
After talking with @jmartin-sul before the break I think that we are leaning towards creating Rake tasks and other utilities to help deal with any problems that remain after making tasks retry and put less into HB for FRs to respond to? Therefor I propose closing this ticket.

**Comment by ndushay** [comment]
I'm not ready to close this yet as I think some of us as FR would NOT know at this time what to do in order to address replication.  We have a bunch of the work done, but it's not yet something an FR would be able to figure out on their own, I don't think.

Hypothetically, if we wanted the FR to reduce anything "red" in the dashboard:

![image](https://user-images.githubusercontent.com/96775/210676435-da0a306c-97dc-49da-baf6-477830ba2c92.png)

We have to know where to look to start, etc.

For what it's worth, @justinlittman and I, and then John and I discussed a need to reorganize/revise the prescat wikis and part of that will be about figuring out where this sort of missing information should go, and getting it there in a way that it can be easily found by FRs.   Some of this is individual wiki revision, and some of it is something else.

I think JLitt may have taken the task of setting up a storytime re: Prescat wiki but I think he's perhaps going to propose a specific course to take rather than have a free-for-all discussion.

**Comment by edsu** [comment]
Ok, I'm going to put this back into ready then since I wasn't part of the conversation and it sounds like other people are going to push it forward.

**Comment by edsu** [comment]
Ok, I'm going to put this back into ready then since I wasn't part of the conversation and it sounds like other people are going to push it forward.

**Comment by ndushay** [comment]
@justinlittman I'm assigning this ticket to you as you have been working on remediating replication errors.   

I think the main remaining points are:
1.  do we have the code bits to do what we need?
2.  do we have the documentation for the FR to be able to do what is needed to address problems?
3.  have we removed obsolete and confusing documentation about this?

**Comment by justinlittman** [comment]
The only outstanding bit is https://github.com/sul-dlss/preservation_catalog/issues/2171. Since this is ticketed separately, I'm going to close this.
