### ISSUE TITLE
Monitor Ceph upgrade process

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/preservation_catalog#2085]
Ceph storage will be [upgraded by Ops](https://github.com/sul-dlss/operations-tasks/issues/3015) on December 4, 2022. 

This upgrade will test a process of pausing, not stopping, preservation robots and not shutting down preservation catalog.

Plan for this upgrade:
1) @andrewjbtw has confirmed that any possible multi-TB deposits coming to preservation have already completed.
2) @jmartin-sul will turn off Google Books on Friday, 12/2.
3) @julianmorley will run the Ceph upgrade starting at 8AM Pacific on 12/4. See [operations-task ticket](https://github.com/sul-dlss/operations-tasks/issues/3015) for details and link to runbook. The upgrade is projected to take 6-8 hours. @jmartin-sul will be available for any questions that may arise.
4) @edsu as FR will turn Google Books back on, on Monday morning, 12/5.

Google Books proceeding through the preservation workflow will be a test of the upgrade success.

**Comment by ndushay** [comment]
@edsu assigned this to you as you have the last step.  When you feel good about Ceph upgrade, you can close this (or check with John and close it)
