### ISSUE TITLE
dashboard UI:  some tables bleed off the right side of the browser window

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#2124]
Note the table on the right is off the page:

![image](https://user-images.githubusercontent.com/96775/208004737-aea6b605-1361-401c-ab21-a9f1c47096e6.png)

vs

![image](https://user-images.githubusercontent.com/96775/208004793-2429b04e-1226-433d-8dc1-efcb9b898a2d.png)

Same for replication files:

![image](https://user-images.githubusercontent.com/96775/208004862-38da9d8f-90b3-4ccc-bf0d-1ed2c262a139.png)

**Comment by justinlittman** [comment]
Good news, bad news.

The good news is that I think the problem is that a `container` class is missing on the outer-most `<div>`.

The bad news is that the layout doesn't flow correctly.
![image](https://user-images.githubusercontent.com/588335/208104369-66f74c43-0bfd-4be3-b1b5-4e5322b915cc.png)
