### ISSUE TITLE
why does **Endpoint** have default_storage_root_endpoint_type method?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#215]
why isn't this in EndpointType  as  default_endpoint_type ??

At miminum, it might be good to add a comment in the code as I may not be the only one confused.

**Comment by jmartin-sul** [comment]
comment seems like a good idea.  in this case, it's not a default `EndpointType` across all `EndpointType`s, but a default `EndpointType` among the storage root (i.e. online `EndpointType`s), which is a thing that only `Endpoint` cares about at the moment, for seeding purposes.

i have no objection to that living under `EndpointType` instead, just wanted to make the clarification that it's not an overall default, just a default for a specific subset of `Endpoint[Type]`s.
