### ISSUE TITLE
Create replication flow wiki page

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/preservation_catalog#2162]
Remove the replication flow section of the dashboard and create a wiki page. This new page should be added to the "About PresCat" section of the sidebar and linked to from the dashboard.

https://preservation-catalog-web-prod-01.stanford.edu/dashboard/replication_flow

**Comment by ndushay** [comment]
FYI, this is how it currently looks in dashboard;  it doesnt have to be a table in the wiki -- but the information on what triggers each step, etc, should be skimmablew.

![image](https://user-images.githubusercontent.com/96775/211415147-3e29ca09-f571-4408-a220-e49f439161f0.png)

**Comment by ndushay** [comment]
@justinlittman @jmartin-sul I sent you both slack messages re: my hope to replace the OLD wiki page https://github.com/sul-dlss/preservation_catalog/wiki/Replication-flow with my NEW wiki page  https://github.com/sul-dlss/preservation_catalog/wiki/Replication-Flow-WIP.   Let me know what you think.

**Comment by justinlittman** [comment]
Completely support

**Comment by jmartin-sul** [comment]
also support
