### ISSUE TITLE
Silence openapi_parser deprecation

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#2198]
Not so much a bug, but a noisy deprecation warning.

Cron daemon frequently emails the following message from pres@preservation-catalog-prod-04
```
[DEPRECATION] openapi_parser will default to strict reference validation from next version. Pass config `strict_reference_validation: true` (or false, if you must) to quiet this warning.
```

The deprecation warning comes from, for example:
```
/bin/bash -l -c 'cd /opt/app/pres/preservation_catalog/releases/20230201185452 && RAILS_ENV=production bundle exec rake prescat:cache_cleaner:stale_files --silent >> /var/log/preservation_catalog/zip_cache_cleanup.log'
```

**Comment by jmartin-sul** [comment]
stumbled on this issue when searching to see if there was an existing issue for or similar to something i'm about to file.  i think this is fixed?  searching outlook, the most recent notice i see like this is from feb 7 of this year, and looking doing a `git blame config/application.rb` makes it seem like the suggested config option was added by commit 4e2307514.

@tallenaz i'm gonna close this, but feel free to reopen if you think that's wrong.
