### ISSUE TITLE
(PC) consider turning the `statuses` table and `Status` model into a Rails enum on `PreservationCopy`

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#228]
in our first pass at the schema, the `status` field on `PreservationCopy` was a text field.  @julianmorley was concerned that searching on this column wouldn't be performant, since text searches are more expensive than integer searches, even on indexed columns.  as such, we made the `status` col on pres copy a foreign key to a `statuses` table that holds the status text.  currently, status text is defined in the settings file, from which entries in the `statuses` table are seeded (using a method in the `Status` model).

this is getting unwieldy:  the code is aware of various statuses, and refers to them by name.  it seems unlikely that we'll add more columns to the `statuses` table, and it seems unlikely that users will add entries to the `status` settings without the code being made aware of those entries (unlike, say, endpoints, or endpoint types, or other things that might feel sort of like enums, but where there are multiple columns associated with each entry, and where the application code isn't necessarily aware of each specific entry by name in a way that's hardcoded like we're doing with status stuff).

as such, i'd propose that `status` should actually be a rails `enum`:
http://api.rubyonrails.org/v5.1/classes/ActiveRecord/Enum.html

underneath (in the DB), this will actually be an integer column (as it is right now since it's a FK to an ID in another table), and so it should still obviate julian's performance worry.  active record will do the translation that lets us refer to status by a human readable ruby symbol, as well as providing some other magical rails conveniences.

broadly, the reasons i could see to not make this change would be:
* there are actually more columns that are going to go in the `statuses` table/on the `Status` model.
  * can anyone actually think of any?
* we'll have user defined statuses that the code can work with, but that the code isn't aware of by name.
  * that sounds much more extensible and state machine-y than what we're planning on doing.
* there's some performance problem i'm not considering
  * though i'd actually think a plain int col would be more performant than a FK int col that needs to do a join.

so yeah... i vote that we do what this ticket suggests.  happy to be told i'm missing something.  i don't think the migration will be terrible:  we're still at a point where we can just build up the catalog from scratch again (and i think we're expecting to do that another time or two).  so i don't think we need to write a data migration, just a schema migration.  i think that migration is roughly:
* `preservation_copies.status_id` col gets dropped, replaced by `preservation_copies.status`, which is a plain `integer`, and not a `bigint`.
* `statuses` table gets dropped.
* `Status` model gets removed.
* `PreservationCopy` model gets an enum field called `status`, which has explicitly defined integer mappings to its status symbols (so more statuses can be safely added later).
  * `PreservationCopy` gets some new tests for its new enum (maybe some ported from the old `status_spec`, maybe not, not sure).
* other stuff that references the `Status` model gets cleaned up to use the enum (e.g `Status` seeding call gets dropped from rake db seed code, stuff that sets status on pres copy just uses the enum instead of querying for the relevant `Status` object).

**Comment by jmartin-sul** [comment]
julian says :+1: to making this a rails enum

**Comment by ndushay** [comment]
We also want the result of this work to avoid doing db lookups for status or preservation policy for each moab as it is being processed.

**Comment by jmartin-sul** [comment]
i believe policy will not become an enum... though it is constant-ish in behavior, i think it should remain it's own table, because:
* it has multiple columns (not just a name identifying it, with all relevant logic in code)
* polices are referenced by multiple other tables/obj types (preserved objects reference the policy ID that applies to them, endpoints reference the preservation policies they implement via the `endpoints_preservation_policies` intermediary table)
* policies have logic that we'd prefer to configure via settings instead of code changes (a `_ttl` value feels very much like a setting we might want to tune somewhat regularly, compared to a status type, which the code likely has to be more tightly coupled too, since we're not building the ability to define some arbitrary configurable state machine).

but, since we don't expect policies to change often, i do think they're amenable to memoization a la #347.  maybe we should reopen 347 for pres policies?  or file a similar new issue?  i would propose that we also flush the memoized values whenever new pres policies are created/loaded from the configs (which should be rare).  if we found that we were doing that sort of memoization regularly, maybe we should explore `ActiveSupport::Memoizable` or `Memoist` as per @SaravShah's comment here: https://github.com/sul-dlss/preservation_catalog/pull/351#pullrequestreview-79350425

**Comment by ndushay** [comment]
Just data from old logs:

From logs, this could save maybe 1-2ms per #create call?

```D, [2017-11-23T12:15:19.487354 #19661] DEBUG -- :   Status Load (0.8ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."status_text" = $1 LIMIT $2  [["status_text", "ok"], ["LIMIT", 1]]
...
D, [2017-11-23T12:15:30.117925 #19661] DEBUG -- :   Status Load (1.1ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."status_text" = $1 LIMIT $2  [["status_text", "ok"], ["LIMIT", 1]]
...
D, [2017-11-23T12:26:39.501242 #19661] DEBUG -- :   Status Load (0.7ms)  SELECT  "statuses".* FROM "statuses" WHERE "statuses"."status_text" = $1 LIMIT $2  [["status_text", "ok"], ["LIMIT", 1]]```

**Comment by julianmorley** [comment]
Yeah, definitely. This is almost precisely what I was worried about, way back when (a select * on status, grepping for a text value...).
