### ISSUE TITLE
[QA only] replication success events aren't reaching the DSA event log

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#2291]
**Describe the bug**
The integration tests that check for successful completion of cloud replication (`preassembly_reaccessioning_spec.rb` and `preassembly_hfs_accessioning_spec.rb`) fail when checking to see whether the expected events show up in the DSA event log.  But when looking in the pres cat DB, even after running replication audit, I can see that both versions of the object created by the integration test are actually replicated to all 3 cloud endpoints.  For example: https://argo-qa.stanford.edu/view/mg327cx0173

Thankfully, this does not seem to be a problem in prod or stage.

I have not dug in to see whether the issue is with pres cat talking to RabbitMQ (the dor-event-client uses Rabbit as a high availability intermediary since we used to get intermittent dropped direct calls to DSA), RabbitMQ's message handling (our least likely suspect), or Rabbit talking to DSA.

I didn't see any Honeybadger alerts that seemed related to this (in particular, none in pres cat).

**User Impact**

This makes it harder for Argo users to see what's been successfully replicated at a glance, and makes it harder for our integration test suite to determine the health/bugginess of a particular deployment to QA.

**Object(s) In This Error State**

https://argo-qa.stanford.edu/view/mg327cx0173

Steps to Reproduce, if Known:
* run one of the above mentioned integration tests, watch it fail, examine the druid (run `PreservedObject#audit_moab_version_replication!` for the druid and confirm that the correct `ZippedMoabVersion`s and `ZipPart`s entries exist for it in an `ok` status; then confirm that the events for replication of each version to each cloud endpoint are missing from the DSA event log for the druid).

**Expected behavior**
There is an event in the event log for each successful replication of a druid version to a cloud endpoint.

**Screenshots**
n/a

**Additional context**
none i can think of

**Comment by justinlittman** [comment]
Occasionally apps lose their bindings to Rabbit:
<img width="679" alt="image" src="https://github.com/sul-dlss/preservation_catalog/assets/588335/a6376a3a-0bde-48c4-976b-7eaf5e2c614a">

Which can be fixed with `RAILS_ENV=production bin/rake rabbitmq:setup`:
<img width="694" alt="image" src="https://github.com/sul-dlss/preservation_catalog/assets/588335/5d73b22d-637e-4b85-a1ce-f7401c0a2369">

Seems like a good candidate for an OK Computer check?

**Comment by jmartin-sul** [comment]
nice find @justinlittman!  and agree, good candidate for an okcomputer check.

**Comment by peetucket** [comment]
Is this were you looked to see if the `sdr.objects.event` exchange was bound to `dsa.create-event` ?  https://sul-rabbit-qa.stanford.edu/#/exchanges/workflow/sdr.objects.event  

To me it looks like it is, but the integration tests in QA are failing in the same way.

**Comment by peetucket** [comment]
Tests still failing in QA: 

```
SDR_ENV=qa be rspec ./spec/features/preassembly_reaccessioning_spec.rb:47
SDR_ENV=qa be rspec ./spec/features/preassembly_hfs_accessioning_spec.rb:35
```

**Comment by justinlittman** [comment]
I fixed this by deleting the event queues and exchange from the rabbitmq admin interface and regenerating using the rake task in DSA.
