### ISSUE TITLE
Resync cloud copies for db586ns4974

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/preservation_catalog#2294]
Per request, druid db586ns4974 has been emptied of content files. All previously stored cloud copies should be resynced to the current state of the druid. All 42 versions that existed prior to the file deletion have been modified. 

Note that I will be making additional versions because this item needs to be republished with a "tombstone page", as items that have DOIs need to resolve to a landing page even if the content is no longer available. That means I'll be editing descriptive metadata. But I think those new versions will get synced correctly.

**Comment by justinlittman** [comment]
Here's the zip for the deletion.
[db586ns4974.csv](https://github.com/sul-dlss/preservation_catalog/files/14694628/db586ns4974.csv)

**Comment by justinlittman** [comment]
Done.
