### ISSUE TITLE
workflow-archiver prod problem mop up

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#230]
- [x] @tallenaz will do timeline writeup for post-mortem
- [x] will transcribe "necessary steps" from whiteboard and put here (prob @tallenaz)

**Comment by tallenaz** [comment]
- workflow-archiver
  - [ ] cut release v1.3.1 against the merged hotfix PR
- workflow-archiver-job
  - [ ] issue a PR against the deployable branch
  - [ ] cut release v1.3.1 against the merged PR that includes workflow-archiver v1.3.1
  - [ ]  deploy v1.3.1
- surface to infrastructure team mgmt
  - [ ] for workflow-archiver, get upgrades in master into a deployable version (v2.x), make sure it has tests
  - [ ] for workflow-archiver-job, get a release into prod that uses v2.x of workflow-archiver, and with tests
