### ISSUE TITLE
(PC) grep the code for TODO and FIXME comments, disposition them appropriately

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#242]
disposition those statements as needed (i.e., do, fix, or ticket for the backlog).

we should maybe do this periodically, but it feels to me like we can't close this till we're close to the end of the work cycle, since more of these will likely be added as our work continues.

**Comment by ndushay** [comment]
#  if it's already done, or is now moot, remove comment.
#  if it's really easy, just do it.
#  look to see if there is already a ticket.  if there isn't, make one if it's worthy.

**Comment by atz** [comment]
See also: any mention of "shameless green"

**Comment by ndushay** [comment]
I'm closing this ticket -- there are 8 FIXMEs and 11 TODOs (case insensitive) and that seems reasonable for a code base of this size.
