### ISSUE TITLE
(PC) #confirm_version - hook up #create

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#257]
#confirm_version doesn't call the #create method if the druid is unknown to the catalog, the logic is there but we need to hook it up.  
If druid is unknown to catalog 
- run MV from moab versioning gem
- run D2D
- call (PC) #create and ALERT appropriately

Morphed to: #check_existence method should call #create_with_validation

Connects to #284

**Comment by ndushay** [comment]
Note the job in lib/audit  is currently set up to call #create.   Perhaps the handler.confirm_version should do this, and take a boolean "create_if_missing" arg?

**Comment by SaravShah** [comment]
Things to discuss with team:
- Do we want po_handler#confirm_version to call #create OR do we want M2C check (from lib/audit) to call #create.

**Comment by ndushay** [comment]
this ticket is morphed to be part of check_existence method.
