### ISSUE TITLE
(PC) update_version needs to be endpoint aware (Moab vs Archived)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#264]
possibly covered by storage_dir argument to pohandler.initialize().   

@jmartin-sul -- does that mean this ticket is already done?

**Comment by ndushay** [comment]
I believe we are now set up to finish implementing #262 (or to close it, if we don't want to worry about archival preserved_copy objects yet) ??  @jmartin-sul

**Comment by jmartin-sul** [comment]
@ndushay: yup, that sounds right to me
