### ISSUE TITLE
(SPC) Seed Preservation Catalog checklist

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#269]
See
- Storage Validation to production checklist: https://docs.google.com/document/d/137htAn4gK-v26jh7CILmWz2d-2ekPwvRD8WToafb-Yo
- ?? Audit Requirements ??  https://docs.google.com/document/d/1QdsQyR40l6_ykcibJ4OxxFCs1-KiGmdTzzpw0J2Telg
- To production overall checklist: https://docs.google.com/document/d/1oi9KmIKY0t6zVE7ACiIyOB4V-vQqTExGneFdFsth3Vs

**Comment by tallenaz** [comment]
ready for review: https://docs.google.com/document/d/1lZNmsAqVddUkjxpNlVo-2WE2IrMuUNs0rXPR_jsdE_g/edit

**Comment by ndushay** [comment]
I did some pretty big edits - I hope you're okay with them.  If you can get sign off from everyone, we can close this ticket and mark xxx unblocked.

**Comment by SaravShah** [comment]
This looks good to me
