### ISSUE TITLE
prov.log turned off in shared_configs until Christina has cycles to ensure it doesn't use up lots of disk space

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#276]
prov.log filled up the remaining space in the logging partition, preventing further logging from happening.  i truncated it, since i figured we'd likely not be looking at the data it contained for the catalog seeding run that started on saturday evening.  luckily, the inability to write to the log didn't prevent further catalog building:  things seem to be proceeding just fine in the absence of the ability to write to prov.log (though... maybe that's not actually desirable?  might warrant some discussion.).

@tallenaz says @cmh2166 is working on a way to have the logs shipped off pretty much immediately, to prevent them from filling the log partition.

since there's a feature flag controlling whether the prov.log is used, we could turn that flag off for now if we decide the current logging is untenable (though i'd think we'd want some working version of it enabled in prod).

**Comment by ndushay** [comment]
Begin forwarded message:

From: Naomi Dushay <ndushay@stanford.edu>
Subject: prov.log on preservation-catalog machines
Date: November 13, 2017 at 1:14:01 PM PST
To: Christina Marie Harlow <cmharlow@stanford.edu>
Cc: Johnathan Martin <suntzu@stanford.edu>, Anthony M Zanella <azanella@stanford.edu>

Hi Christina,

We ran into this “problem” when seeding the catalog:

> prov.log filled up the remaining space in the logging partition, preventing further logging from happening. i truncated it, since i figured we'd likely not be looking at the data it contained for the catalog seeding run that started on saturday evening. luckily, the inability to write to the log didn't prevent further catalog building: things seem to be proceeding just fine in the absence of the ability to write to prov.log (though... maybe that's not actually desirable? might warrant some discussion.).
>@tallenaz says @cmh2166 is working on a way to have the logs shipped off pretty much immediately, to prevent them from filling the log partition.

>since there's a feature flag controlling whether the prov.log is used, we could turn that flag off for now if we decide the current logging is untenable (though i'd think we'd want some working version of it enabled in prod).


Can we do some of the following (or other ideas);
- determine if what we are logging for prov.log is useful
- reduce the amount of logging
- ship the logs off immediately so they don’t fill the log partition
- turn off the prov.log feature for now

…

https://github.com/sul-dlss/preservation_catalog/issues/276

Thanks,
Naomi

**Comment by ndushay** [comment]
assigning this ticket to @cmh2166 and @tallenaz as I think they may already be working on it?

**Comment by ndushay** [comment]
Begin forwarded message:

From: Christina Marie Harlow <cmharlow@stanford.edu>
Subject: Re: prov.log on preservation-catalog machines
Date: November 13, 2017 at 5:52:30 PM PST
To: Naomi Dushay <ndushay@stanford.edu>
Cc: Johnathan Martin <suntzu@stanford.edu>, Anthony M Zanella <azanella@stanford.edu>

Hi Naomi, Tony, Jon-

Tony, feel free to delete / remove logs for space needs. I’m trying to get back to this but sdr3 fell in my way.

I can move this up my priority list for, I hope, an agent / stream producer solution this week, after getting some clarity on infra options from Julian on weds.

Happy to talk in person about it too, perhaps after the daily sdr3 design meeting from 2-3.

Sorry!
C

Christina Harlow

**Comment by ndushay** [comment]
Current decision is to turn this logging off until Christina has time to work on it further.  This should be reflected in our shared_configs for -stage and prod.

**Comment by jmartin-sul** [comment]
@ndushay:  yup, there are currently two open PRs in shared_configs to that effect
