### ISSUE TITLE
actually use pres copy last_audited, last_checked_on_storage, last_checksum_validation fields

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#278]
we aren't doing checksum validation yet in our code, but we could be setting `last_audited` and `last_checked_on_storage` in `POH#confirm_version` etc.

**Comment by jmartin-sul** [comment]
if you pick this up, you might want to spawn individual tickets for `POH#confirm_version`, `#create`, and `#update_version`.

**Comment by jmartin-sul** [comment]
see #286 for more detailed behavioral requirements

**Comment by ndushay** [comment]
closing in favor of #288, #287, #286
