### ISSUE TITLE
(PC) what should we do for performance testing?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#290]
the easiest thing would probably be to just use newrelic.

other options, should we want more detail or more target detail than newrelic provides:
* with argo reindexing, when we needed to tune performance we added some configurable performance logging on its indexing code:
  * https://github.com/sul-dlss/argo/blob/master/config/settings.yml#L42
  * https://github.com/sul-dlss/argo/blob/master/config/settings.yml#L55-L69
  * https://github.com/sul-dlss/argo/blob/master/app/jobs/local_indexing_job.rb
  * https://github.com/sul-dlss/argo/blob/master/lib/profiler.rb
  * https://github.com/sul-dlss/argo/blob/master/lib/indexer.rb
* a quick and dirty performance testing branch that ports some of our old PC perf testing code, without the intention of ever using that branch in prod
* there will likely be some basic DB stats in the logs per operation, but i think we’d need to do some log parsing for them to be useful at all, which is also work (or maybe someone in ops who’s fluent in whatever log analysis tool we have could make sense of them for us, or show us how to use that tool ourselves)

we're not sure how much of new relic’s magic `just works` for rake tasks (which is what the seeding is called from, as opposed to being called from a controller, which is what newrelic seemed to specialize in profiling, last i used newrelic).

**Comment by ndushay** [comment]
@jmartin-sul @tallenaz  is this ticket addressed elsewhere now?

**Comment by jmartin-sul** [comment]
i think PR #306 is addressing this?
