### ISSUE TITLE
(SPC) do a catalog seeding run on a small storage root with profiling enabled

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#317]
we'd like to make sure the profiling output file isn't enormous (and that profiling doesn't cause intractable slowdown) before possibly running it on the full set of storage roots.

this should give us some performance data about seeding in general, and about our validation code in particular, now that that's wired up.

if profiling does add a ton of overhead, profiling on what feels like a representative subset of the storage roots might be the way to go.  which should be possible by just temporarily listing a subset of the storage roots in the settings file when seeding gets kicked off.

i think we're planning to do this on stage?

other TODOs
* truncate the old logs first since we probably won't look at their contents again, and they're taking up useful space.
* turn off prov logging so that space doesn't fill up again and prevent the profiler output from saving.

**Comment by ndushay** [comment]
We also want to get some info on validation:
- what % of objects fail MV
- what are the failures, collated?  (do they all fail on the same check?  2 diff checks?  all manor of checks?)
- how much resource does it take to do validation?
  - when it fully passes
  - when it fails right away

Current code is wired to seed with MV for version 2.5.1 of the gem (some checks missing, but enough written to get some data)

**Comment by jmartin-sul** [comment]
this was about 3X faster on disk 11 than the prior seeding run was.

| Storage root |  start time  |    end time    | elapsed time | number of moabs | avg moab size (in MB) |
|:------------:| ------------:|---------------:|-------------:|----------------:|----------------------:|
| 11 | 2017-11-15 02:08:32 | 2017-11-15 02:23:12 | 00:14:40 | 9,122 | 313 |


* 8288 moabs ended up with the `invalid_moab` status
* 834 ended up being `ok`

i'm pretty sure the profiling isn't granular enough to differentiate resources used when validation passes vs when validation fails.  even with very detailed (and high overhead) callgrind profiling (instead of the flat profiler output), i'm not sure we'd be able to get that info without running profiling separately on a batch of objects that we know will fail validation, and then on a batch that we know will pass (i.e. different profiling runs).  which is certainly not impossible to setup, but would take some work (do a run and find out which ones pass vs fail, record those druids, contrive a run that only operated on the set you're interested in at any given time).

here are the top resource users based on the profiling done in this run:
```
Measure Mode: wall_time
Thread ID: 17379360
Fiber ID: 36756740
Total: 880.629244
Sort by: self_time

 %self      total      self      wait     child     calls  name
 36.17    318.532   318.532     0.000     0.000   488412   <Module::FileTest>#directory?

 19.88    175.124   175.087     0.000     0.037   214012   <Class::Dir>#open

  6.87     60.484    60.484     0.000     0.000   100360   PG::Connection#async_exec
      called from:
          ActiveSupport::Concurrency::ShareLock#yield_shares (/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/activesu
pport-5.1.4/lib/active_support/concurrency/share_lock.rb:169)

  3.48     30.659    30.659     0.000     0.000    36850   <Class::File>#directory?

  1.24     10.941    10.941     0.000     0.000      834   IO#eof?
      called from:
          <Class::Nokogiri::XML::Document>#empty_doc? (/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/nokogiri-1.8.1/
lib/nokogiri/xml/document.rb:271)

  0.62      5.458     5.458     0.000     0.000   516068   <Class::File>#lstat

  0.59      5.211     5.211     0.000     0.000   369596   <Module::FileTest>#size

  0.44      7.808     3.916     0.000     3.891   739003   ActiveRecord::QueryMethods#default_value_for
      defined at:
          /opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/relation/query_methods.
rb:1180
      called from:
          ActiveRecord::QueryMethods#get_value (/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib
/active_record/relation/query_methods.rb:922)

  0.42      3.664     3.664     0.000     0.000  8767833   Symbol#===
      called from:
          ERB::Compiler#compile_stag (/usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/erb.rb:632)
          ActiveRecord::QueryMethods#default_value_for (/opt/app/pres/preservation_catalog/shared/bundle/ruby/2.4.0/gems/activerecord-5
.1.4/lib/active_record/relation/query_methods.rb:1180)
```

**Comment by jmartin-sul** [comment]
> what are the failures, collated? (do they all fail on the same check? 2 diff checks? all manor of checks?)

unfortunately, we're not logging the specific validation errors.  see #325.

**Comment by jmartin-sul** [comment]
closing this one.  we'll collect more info under #326.
