### ISSUE TITLE
better tests for CompleteMoabHandler transactionality?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#324]
i was thinking of adding a basic test of the private method `POH#with_active_record_transaction_and_rescue`.

or not, if others don't think that's worthwhile (i.e. if the tests added for PR #322 are comprehensive enough).

this ticket assume PR #322 gets merged in something pretty close to its current form as of this ticket being created.

follow up:

at @ndushay's suggestion, we'd like to add a test for each of:
* create
* create_after_validation
* update_version
* update_version_after_validation (doesn't exist yet)
* confirm_version

proving that they roll back when they are supposed to? Or maybe proving that they use [with_active_record_transaction_and_rescue]?

**Comment by ndushay** [comment]
I don't mind tests against private methods;  our true objective is to prove transactions roll back when they are supposed to, and if testing the private method simplifies that task, it's fine with me.

**Comment by ndushay** [comment]
So the rollback test needed is essentially:  when we have a failure when trying to update the second object ... then the rollback is correct, resetting the first object back to its original?

**Comment by jmartin-sul** [comment]
@ndushay: yup, that's my understanding of what a worthwhile test of rollback should be doing.

so a combination of testing the private method and testing that the other methods call the private method would probably suffice.  that and the tests we have for rollback with `create` and `confirm_version` feel like they'd cover a nice range of modular unit tests and slightly more integration-y tests.

i'm a little unsure how to do a good job of testing that the private method gets called properly by the update methods, but that maybe a little pairing/brainstorming could get us past that (or maybe it's obvious and i'm just missing it, i've just always found it tricky to test whether something that takes a block is getting the right block).

**Comment by atz** [comment]
If we just used AR built-in transactionality (e.g. pass a block to `create` that builds associated objects), then we only need test the resulting logic and not the internals.  Overall, we should avoid rolling our own transactions as much as possible.

**Comment by ndushay** [comment]
@jmartin-sul I'm closing this one - it's over 4 years old, and I think the former CompleteMoabHandler had great test coverage.
