### ISSUE TITLE
(SPC) do another tiny seeding run (disk 9)  with validation errors logged

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#326]
once sul-dlss/moab-versioning#92 is merged and a new moab-versioning version is released, and once PC is updated to use that release of MV, we should do another seeding run on stage with profiling.

might also be nice to get #325 in before another run?  anything else anyone can think of that'd block this?

since the run we just did for #317 was surprisingly speedy, i'm inclined to just do all the storage roots.

**Comment by ndushay** [comment]
Do tiny root 11
When satisfied, do root 8

See also to production checklist for seeding.

**Comment by ndushay** [comment]
@SaravShah no - i was originally wrong:  disk 8!  do disk 8!!!

**Comment by ndushay** [comment]
done, results documented in wiki and promulgated
