### ISSUE TITLE
ship prod logs off to afs or elk

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#358]
we need to long term retain logs from perservation-catalog-prod.   "/opt/app/pres/preservation_catalog/shared/log/production.log-20171118.gz"  etc.

**Comment by julianmorley** [comment]
Strong vote for 'not AFS'; it's going away, security's a pain, etc etc. If necessary we can create a separate NFS volume for logs and put them all there.

**Comment by cmh2166** [comment]
Need to differentiate here application logs (sure, just ship wherever) and the prov / rails instrumentation logs being then transformed for a proto-prov database. Two different data sources / contexts / needs.

**Comment by tallenaz** [comment]
Creating a separate ticket for shipping the `prov.log` to aws. Action item here is to ship `production.log` to aws.

**Comment by tallenaz** [comment]
Found out that rails logs were not shipping to afs at all, connected to sul-dlss/operations-tasks#1582
