### ISSUE TITLE
PreservedCopy has duplicate statuses for checksum validation failure

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#372]
PreservedCopy status enum needs some love:

1.  'expected_vers_not_found_on_storage' is too long.  How about:
  `unexpected_version_in_catalog` ?   or `unexpected_version_on_storage` ?

2.  we have:

- INVALID_MOAB_STATUS = 'invalid_moab'.freeze  # <-- moab validation failed
- INVALID_CHECKSUM_STATUS = 'invalid_checksum'.freeze  # <-- checksum validation failed
- FIXITY_CHECK_FAILED_STATUS = 'fixity_check_failed'.freeze # <-- duplicate of the above?  before we wanted to get more specific?

Note that these changes could imply a migration is needed.

Note that a big migration of the data itself might be not worth it and we should just wipe, re-seed, and move on.

**Comment by ndushay** [comment]
I prefer `INVALID_CHECKSUM_STATUS`

**Comment by jmartin-sul** [comment]
* i'd agree about dropping `FIXITY_CHECK_FAILED_STATUS` as a dupe of `INVALID_CHECKSUM_STATUS`
* no objection to renaming `expected_vers_not_found_on_storage` to `unexpected_version_on_storage`.  not that much shorter but i think it reads a little better while communicating the same thing.
* > Note that a big migration of the data itself might be not worth it and we should just wipe, re-seed, and move on.
  * i think the only thing we'd have to migrate is `expected_vers_not_found_on_storage`, which we might not even have any entries for?  but it'd also be one of the simplest types of data migrations you can do, and so maybe good practice/exposure for that part of active record (but also very much *not* critical path at the moment).

**Comment by jmartin-sul** [comment]
currently, nothing on prod has `EXPECTED_VERS_NOT_FOUND_ON_STORAGE_STATUS`:
```ruby
[12] pry(main)> PreservedCopy.joins(:preserved_object, :endpoint).where(status: PreservedCopy::EXPECTED_VERS_NOT_FOUND_ON_STORAGE_STATUS).count
=> 0
[15] pry(main)> PreservedCopy.joins(:preserved_object, :endpoint).where(status: PreservedCopy::OK_STATUS).count
=> 1192819
```

so, i think no migration needed.

oh, actually, i just realized:  definitely no migration needed.  what's in the DB is an integer code, which won't change.  the human readable string is mapped to the integer code, and ActiveRecord magic takes care of letting the caller use the string as if it were the int code in the DB.  so yeah, this should be no trouble.
