### ISSUE TITLE
(PC) #confirm_version timestamp update

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#384]
PC and PO update timestamps...they are done with
-  create_with_validation (already done in plain create method, timestamp info in ticket #288)
-  calls update_version_with_validation (timestamp info already in ticket #287)

**Comment by tallenaz** [comment]
It looks like this will already happen: https://github.com/sul-dlss/preservation_catalog/blob/e3470ef43b1cdc4d3a95861a713c0ace4f8940a0/app/services/preserved_object_handler.rb#L210

Briefly, it will happen if `confirm_online_version` calls `update_preserved_copy_version_etc`, which calls `update_pc_validation_timestamps`

The PR for that change hasn't been merged yet, so keeping this open for now.
