### ISSUE TITLE
SPRINT 9 DEMO 12-15-17

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#386]
### (M2C) Moab to Catalog Existence Check - Coded
https://stanfordlib.slack.com/files/U6KTP6UUV/F8D1EPNDA/m2c_existence_path.jpg

**Comment by SaravShah** [comment]
[Uploading M2C existence path.jpg...]

**Comment by SaravShah** [comment]
![M2C existence path.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/599c9d9bc8d74502f8bc1d65/125516c66e82c728ace21e0d46c5c6b963879ba09cfdba4da758b08428522f316546b3397f8fe62bab0021435a5647a81550574cfeaadb7df4b03c708c5e0fbc833f0d7cd42103eee9dc4be05ce36ade0d97bcae8b44cae93824e48b8d4b371b0d1e8bfe4f78.jpg)

**Comment by ndushay** [comment]
Done:   https://www.youtube.com/watch?v=tfovRjZUCL4
