### ISSUE TITLE
prevent callers from reusing a PreservedObjectHandler instance

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#388]
per @ndushay's comment here https://github.com/sul-dlss/preservation_catalog/pull/369#discussion_r155154002 :
> it's abnormal to re-use a pohandler object

as a nicety, we could have POH instances store a boolean flag (e.g. `has_been_used`), with that flag initialized to `false`.  it'd get set to `true` upon the first call to a POH method that does updating/validation.  such methods would also check the flag before doing anything, and if the flag is `true`, an exception warning against that usage could be raised.

**Comment by ndushay** [comment]
I'm in favor of closing this ticket.  John?

**Comment by jmartin-sul** [comment]
no objection
