### ISSUE TITLE
(CV) checksum validation:  where should checksum computation code live?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#39]
This might 
- already be in an existing gem (sul-dlss or other)
- already be in moab-versioning
- already be in preservation core robots
- checksum code in other sul-dlss code bases (github search for sha-1, sha1, md5, sha256 ...)

because it is clearly computed somewhere to go in moab xml files

it might make sense to have a fixity gem, as we expect to use this:
- audit process
- creating the checksums (ingest process for new version)
- moab-versioning gem when creating moab wrapper
- ... ?

SOOO - task is to 
- find existing code in sul-dlss
- consider if it should be its own gem
- write the code needed by audit process (perhaps just the new gem?)

moab expects these 3 checksums:
- md5
-sha-1
-sha256

This task is done when it is clear what code should be called by audit process.

Spawn programming tickets as encounter:
- new gem:  create github repo and then add to waffle and write tickets on that repo
  - document which other code bases should be refactored to use the new gem
- exisiting non-sul-dlss gem:
  - document which other code bases should be refactored to use the new gem
- existing code - document what code to use
- possibly share shocking info on ALL the spots where we do this differently (consul page?  email to dlss?  ...)  (you won't believe #5)

**Comment by ndushay** [comment]
https://github.com/sul-dlss/moab-versioning/blob/master/lib/moab/file_signature.rb#L144-L163  seems to be the code doing the work in moab-versioning

**Comment by ndushay** [comment]
See #96
See sul-dlss/moab-versioning#53

**Comment by ndushay** [comment]
for preservation work, expected consumer are:
- audit functionality
- archive  functionality
- recovery functionality

**Comment by tingulfsen** [comment]
I believe that we almost agreed today on creating some checksum code for sharing within the druid-tools gem.

**Comment by ndushay** [comment]
i wouldn't put it there.  I would either make it easy to use chcksum code in moab-versioning, or I would make a tiny gem.

**Comment by jmartin-sul** [comment]
we may be able to get most of what we want by using `Moab::StorageObject#verify_object_storage`.  it appears that it doesn't calculate checksums for the files listed in signatureCatalog, but it appears to do the other auditing we want.

@SaravShah will do a bit more exploration and testing to see what we'd need to modify in moab-versioning, or what calls we can steal from there to use in preservation catalog.

we should also compare the way `Moab::StorageObject#verify_object_storage` operates to the decision tree we drew to map out how we thought checksum auditing should work.

i pushed the test code from this afternoon's pairing to this branch:  https://github.com/sul-dlss/preservation_catalog/compare/checksum-validation-testing?expand=1

this is the call hierarchy through which checksums are re-calculated for what's on disk, to be used in comparing what's on disk to what's expected after parsing `manifestInventory.xml`:
* `StorageObject#verify_object_storage` call stack is as follows, FileSignature#signature_from_file is what does the checksum re-calc
* result of `FileGroup#inventory_from_directory`, which finds file list and checksums for what's actually on disk, is compared to `StorageObjectVersion#file_inventory('manifests')` result, which gets file list and checksums from manifest file.
```ruby
# all classes below is in the Moab namespace (from moab-versioning gem)
StorageObject#verify_object_storage
  StorageObjectVersion#verify_version_storage
    StorageObjectVersion#verify_manifest_inventory
      FileInventory#inventory_from_directory
        FileGroup#group_from_directory
          FileGroup#harvest_directory
            FileGroup#add_physical_file
              FileSignature#normalized_signature
                FileSignature#signature_from_file
```

**Comment by jmartin-sul** [comment]
useful link from moab-versioning wiki:  https://github.com/sul-dlss/moab-versioning/wiki/Class-Relationships-(Conceptual)

**Comment by jmartin-sul** [comment]
see also #518 and #521
