### ISSUE TITLE
(PC) uber-ticket: Update DOR workflow with audit error findings

### ISSUE THREAD

**Issue by LynnMcRae** [sul-dlss/preservation_catalog#402]
It is highly desirable to have audit error findings discoverable in Argo. We can use a passive workflow (one that has no robots that exists to record status information) to record such errors via the workflow services API described at 

https://consul.stanford.edu/display/DOR/DOR+services#DORservices-workflow_updateThis 

automatically provides the information to Argo indexing and display and obviates the need for additional special calls or new Argo screen work.

**Comment by ndushay** [comment]
So basically, when Audit checking code encounters errors, then it needs to use the dor services workflow API to report errors on individual objects.   This workflow status will then be visible (and indexed) in Argo.

@LynnMcRae @blalbrit  would we start with something like

- `preservationWF` with steps such 
    - `moab_validation` (which would be empty or in specific error)
    - `M2C_existence_check` (ditto)
    - `C2M_existence_check` (ditto)
