### ISSUE TITLE
make more shared_examples out of repetitious pohandler specs

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#416]
make more shared_examples out of repetitious specs

**Comment by atz** [comment]
Similarly:
- make better code to make better tests
- use factories more
- use better OO

**Comment by jmartin-sul** [comment]
closing this for now -- after the ticket was filed, some things were moved to shared_examples, and if we discover more opportunity for test consolidation, we can open a new and more specific ticket.
