### ISSUE TITLE
(M2C) Define dor WF and its DOR object for preservation

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#420]
do this on STAGE at first
first pass at steps:

- start  (required)
- moab-valid
- M2C-exist-check
- C2M-exist-check

- [x] on stage
- [x] on prod

**Comment by ndushay** [comment]
done on Stage;  @SaravShah is doing writeup of what was needed (should become consul page or ???);  still need to do on prod, once we know what the workflows should be

**Comment by ndushay** [comment]
`vt769hj9598` currently has this for `workflowDefinition` datastream:

```xml
<?xml version="1.0"?>
<workflow-def id="preservationWF" repository="dor">
  <process name="start" sequence="1" skip-queue="true" status="completed">
    <label>Initiate preservation workflow</label>
  </process>
  <process name="moab-valid" sequence="2" skip-queue="true">
    <prereq>start</prereq>
    <label>Report Moab validation errors</label>
  </process>
  <process name="M2C-check-exist" sequence="3" skip-queue="true">
    <prereq>start</prereq>
    <label>Report Moab to Catalog existence check errors</label>
  </process>
  <process name="C2M-check-exist" sequence="4" skip-queue="true">
    <prereq>start</prereq>
    <label>Report Catalog to Moab existence check errors</label>
  </process>
</workflow-def>
```

**Comment by ndushay** [comment]
See object for latest workflowDefinition.

**Comment by LynnMcRae** [comment]
Workflow definition copied to production DOR

**Comment by LynnMcRae** [comment]
Reopened briefly to indicate a field decision to rename the workflow to preservationAuditWF. This has been reflected in the stage and prod definitions
