### ISSUE TITLE
CompleteMoabHandler#check_exist refactor - it's shameful green, really.

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#425]
One approach: 
- create small private methods that can be used by both confirm_online_version and check_existence 
- create private method with some of logic in public check_existence method.
...

orig ticket:
-------
For discussion of the issue, see https://github.com/sul-dlss/preservation_catalog/pull/423#discussion_r157289371

The code to extract is here: https://github.com/sul-dlss/preservation_catalog/blob/7b89f23b27cac88c9498356d2e9219550c3043d9/app/services/preserved_object_handler.rb#L68-L109

The proposed new helper method name is `check_online_existence`

**Comment by ndushay** [comment]
🙀   🙀   🙀  I'm not sure if this is the best refactor, esp given changes in PR #432.   🙀   🙀   🙀

**Comment by jmartin-sul** [comment]
see also #366

**Comment by ndushay** [comment]
@jmartin-sul I'm closing this as it is 5 years old, and I think it has been addressed by recent refactors.
