### ISSUE TITLE
audit_results: use symbols instead of ints for error codes

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#428]
this will make logs more readable and grep-able, as well as debugging specs, etc.

**Comment by ndushay** [comment]
It will require re-seeding the database, I imagine.

**Comment by tallenaz** [comment]
This might allow us to refactor some specs, for example in https://github.com/sul-dlss/preservation_catalog/blob/68aec714d26a3e49286e5985cf8fa60e646851aa/spec/services/preserved_object_handler_results_spec.rb#L145-L156
