### ISSUE TITLE
(C2M) pres_copy with VALIDITY_UNKNOWN_STATUS becomes OK_STATUS how?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#433]
How do we expect any VALIDITY_UNKNOWN_STATUS objects to get validated and set to OK_STATUS ?  

Is this part of C2M?   and/or update_version_after_validation when something gets a new version via a robot?

Objects are assigned VALIDITY_UNKNOWN_STATUS when they are created without moab validation.

**Comment by ndushay** [comment]
See also #443

**Comment by ndushay** [comment]
@jmartin-sul is this a dup?  Or is it also part of C2M?

**Comment by jmartin-sul** [comment]
at first glance i actually figured this was being asked in the context of M2C, but either way, i believe it should get taken care of by PR #456.  previously i don't think that we were dealing with that status at all?  that's my recollection, and seems to be what this ticket is saying.  like if something was in `VALIDITY_UNKNOWN_STATUS`, and it never got versioned or was never subject to some event that'd force re-validation, would the status have ever gotten updated?

but as of #456, anything that's not in `OK_STATUS` gets its status set based on what's on disk when `check_existence` or `confirm_version` sees the moab.  so the first M2C check on the moab should straighten things out.
