### ISSUE TITLE
(M2C) more audit timestamp granularity

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#434]
we discovered that we might want to differentiate between `last_checked_on_storage` use cases to a couple more granular things like `last_moab_validation` and `last_version_audit`.

surfaced by PR #432.

**Comment by ndushay** [comment]
this requires both a migration and code changes.  :-)

It is possible we could also drop last_audited and just use the specific fields, too ...

**Comment by jmartin-sul** [comment]
i would be ok with ditching `last_audited` until we saw there was a need for it (e.g. performance problems checking across the audit fields, having to write the same query repeatedly across all those same fields, etc).
