### ISSUE TITLE
proxy: document how to create a dor WF object in SDR (link in comments)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#448]
There is a google doc in progress based on the experiences of Naomi and Sarav and ...

Tommy intends to massage this document and put it on consul, and then make each of the potentially "obvious" github code bases that might expect this document have a link to the consul doc in a github wiki, if not the README

**Comment by SaravShah** [comment]
https://consul.stanford.edu/display/chimera/DOR+Workflow+objects

**Comment by ndushay** [comment]
@LynnMcRae actually, YOU should close this issue when you are done making it clear the google doc is not the right source of info ... either by deleting it or putting a disclaimer in it.

**Comment by LynnMcRae** [comment]
Tommy is giving it a trial run and I will close the ticket after his report and any adjustments.

**Comment by LynnMcRae** [comment]
Edits complete and approved
