### ISSUE TITLE
(PC) Refactoring poh to pull out methods that only deals with PreservedCopy model

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#470]
- Move specifc code that deals with PreservedCopy in the poh to the model so C2M and M2C can easily use it

**Comment by jmartin-sul** [comment]
@SaravShah and i looked around POH, but nothing jumped out at us as easy things to move over.  e.g. `update_preserved_copy_version_etc` and `update_pc_audit_timestamps` are both short and only concerned with `PreservedCopy`, but they also both deal with POH specific things (`ran_moab_validation?`, `handler_results`).
