### ISSUE TITLE
(M2C) run M2C "continuously" against all storage roots

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#471]
questions:
* what's the mechanism?  cron job via whenever gem?
* should we add a lock file (or similar, e.g. flag in the DB) indicating that `check_existence` is already running on a particular root, so that the cron jobs don't step on one another if they run long?  seems safest to shard by endpoint and not have multiple jobs crawling the same endpoint simultaneously.

**Comment by ndushay** [comment]
newest thoughts include running it in parallel with a separate process running for each storage root and possibly just using a cron to do it every XXX, depending on the time needed for the storage root that takes the longest.

**Comment by jmartin-sul** [comment]
this got implemented as described in #647, and then was reworked to use queues in #1065.
