### ISSUE TITLE
(C2M) run C2M "continuously" against the least recently checked catalog entries

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#472]
questions:
* what's the mechanism?  cron job via whenever gem?
* should we add a lock file (or similar, e.g. flag in the DB) indicating that C2M `check_existence` is already running, so that the cron jobs don't step on one another and pick up the same list of least-recently-checked objects if they run long?

**Comment by ndushay** [comment]
current plan, in #648, is to run every other week via cron (whenever).

after that, we may do any of the following:
- run all the roots in parallell, effectively starting a job that runs the rake task for a single storage root ... for each of the storage roots.
    - determine the longest time needed for any storage root, and possibly run cron every XXX depending on that interval. 
- switch to using redis to kick off C2M for individual druids

**Comment by jmartin-sul** [comment]
implemented per #648, then re-worked to use queues in #1062
