### ISSUE TITLE
Add tests to show wfclass doesn't send error if there were no errors

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#474]
- If there is no error code in:

` WORKFLOW_REPORT_CODES = [
    ARG_VERSION_LESS_THAN_DB_OBJECT,
    DB_UPDATE_FAILED,
    OBJECT_ALREADY_EXISTS,
    OBJECT_DOES_NOT_EXIST,
    UNEXPECTED_VERSION,
    PC_PO_VERSION_MISMATCH
  ].freeze `

make sure no message is sent to Argo.

(Should be caught by the `return if candidate_workflow_results.empty?`  in `report_errors_to_workflows`)

**Comment by ndushay** [comment]
This bug is fixed, but there aren't tests for it yet.

**Comment by SaravShah** [comment]
handled in PR #530
