### ISSUE TITLE
(C2M) write check_version_on_dir specs to test ordering of sql result pres_copies

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#476]
Connects to #460

Will become testable with further work on `check_catalog_version`s updating of timestamps

**Comment by ndushay** [comment]
Per today's discussion, check that scope in PreservedCopy DOES respect order.

**Comment by tallenaz** [comment]
This will be the path forward: for c2m `check_version_on_dir`, replace `find_each` with `each`, and pass in a `limit` param to feed to a `.limit` call on the invoked scope. That param should come from settings, set to 1000. Then, write a wrapper method around `check_version_on_dir` to invoke it, and have the wrapper check that there are no more `least_recent_version_audit` results via a `count` called on it. Write the appropriate specs.
