### ISSUE TITLE
(M2C) ensure last_checked_b4_date is in the correct format

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#485]
In check_version_on_dir, we need to ensure that last_checked_b4_date is in the format needed.

Possibly, this check should be done first in any method with the argument, or possibly it should always fall through to check_version_on_dir method to do the testing.

Note we might want to accept certain incorrect formats and convert them, rather than reject all but the format we ultimately want.

**Comment by ndushay** [comment]
from README:  `It should be in the format 2018-01-22 22:54:48 UTC.`   EW!!!!    I would like it to at least take:

- `2018-01-22 22:54:48 UTC`
- `2018-01-22T22:54:48Z`
and maybe even:
- `2018-01-22T18:54:48`  <-- local time, which will be converted to UTC (?)

**Comment by ndushay** [comment]
Note there are 2 places in the code tagged for this -- not clear if we only want to check date format in the one place or not.

There are no skipped tests for this, but I'm confident tests will be created for this.

**Comment by ndushay** [comment]
May want to use ActiveRecord validations for this (see PreservedObjectHandler)

**Comment by tallenaz** [comment]
We're setting up `least_recent_version_audit`as a scope on PreservedCopy, and there, the date is/will be passed in as a lambda. Since we're unsure of how "acceptable" it would be to validate the date inside the lamba block, let's make that date check the caller's responsibility.
