### ISSUE TITLE
CompleteMoab: add/cleanup comments, validation refinement

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#490]
a small chunk of CompleteMoab model cleanup:
* method param comments should use `@param` notation (see `upd_audstamps_version_size`)
* we should indicate that the validation time stamp fields indicate the last time validation was run at all, as opposed to the last time the object was found to actually be valid.
* **we should probably validate the timestamp fields as timestamps using AR validations?**

**Comment by ndushay** [comment]
AR validations are most useful for incoming parameters (e.g. from a person)

**Comment by ndushay** [comment]
Clarification:
- PC *model* should put validation constraints on timestamp fields.
- PC  *model* would get comments per above (e.g. "last_version_audit" gets a comment `# last time the version was audited, not last time it succeeded)

**Comment by ndushay** [comment]
@jmartin-sul if the two below are still true, can you please make them into separate tickets and stick 'em in the ready column?

1. we should indicate that the validation time stamp fields indicate the last time validation was run at all, as opposed to the last time the object was found to actually be valid. -- I think this would be good -- put it where?  In soon-to-be-written audit documentation  https://github.com/sul-dlss/preservation_catalog/issues/2010  ?

3. **we should probably validate the timestamp fields as timestamps using AR validations?** -- this is done by db/rails magic, as it is a datetime type, no?

**Comment by ndushay** [comment]
@jmartin-sul if you agree with my last comment, I think this can be closed.
