### ISSUE TITLE
(WF) Documentation for zeroing out all the Pres-audit workflow errors

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#494]
Documentation for resetting all of the errors in lyberservices-test.

**Comment by LynnMcRae** [comment]
I used this task to illustrate the canonical steps one uses when remediating workflow data in general directly in the database.  All it requires is good basic SQL skills and a client you are comfortable using. 

See https://consul.stanford.edu/display/chimera/Workflow+database+and+data+model
