### ISSUE TITLE
Need to set storage_trunk on a per storage_root basis for replication

### ISSUE THREAD

**Issue by julianmorley** [sul-dlss/preservation_catalog#503]
In settings.yaml, I need to be able to set this:

```moab:
  storage_roots:
    fixture_sr1: 'spec/fixtures/storage_root01'
      storage_trunk: '/my_custom_trunk'
```
Use case:
storage_trunk, as implemented, is a global variable that is appended to all storage roots. We can't assume that this is always the case. For example, I may have a druid tree that starts at: /sf5-sdr/sdr2objects/druids and another one that starts at /sf6-sdr/sdr_services_01/smpl. If storage_trunk is global, there's no way to ingest these two sources as it presumes the last directories(s) immediately before the druidtree will always be the same for all sources.

**Comment by ndushay** [comment]
As currently implemented, the only time storage_trunk comes into play is with moabs;  we are unaware of a problem.  Closing this.
