### ISSUE TITLE
(R) where shall we store checksums for replication?

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#504]
When talking through the SWAG for replication, the topic of generating multiple shas for an object on a filesystem came up. 

Question (possibly for a future storytime): where would this filesystem live?

**Comment by ndushay** [comment]
Given that we need to store the checksum for the most recent manifestInventory.xml file … someplace … Tony raised some concerns about where this should live.  
  - “local” disk on the VM with preservation catalog?  What if we shard PC on multiple VMs?   
  - NFS mounted disk?  Which one? Where?
  - …

**Comment by ndushay** [comment]
Email update:

>>From: Naomi Dushay
>>Date: Thursday, January 25, 2018 at 6:22 PM
>>Subject: Questions for next story time
>>
>> ... <snip> ...
>>
>>1. Where to Store Checksums:  Given that we need to store the checksum for the most recent signatureCatalog.xml file … someplace … Tony raised some concerns about where this should live.  
>>  - “local” disk on the VM with preservation catalog?  What if we shard PC on multiple VMs?   
>>  - NFS mounted disk?  Which one? Where?
>>  - …
>
>From: Julian Morley 
>Date: Thursday, January 25, 2018 at 9:08 PM
>
>There’s only *one* set of checksums that we have to store, and that’s the checksums of the archive zip files. It’d be nice to do signatureCatalog.xml too, but, honestly, not critical path. 
>
>I shall provide an NFS volume, around 5TB in size, that can be used to both store these checksums and provide scratch space for archive zip creation. The single largest set of zips we’ll need to make will be around 2TB (! ouch) so that’ll more than cover us. The vast majority of zips will be < 1GB.
>
>I suggest - for expediency and to just get it done - that we store the checksums of the zip files in a druid-tree, in this transfer NFS volume. We will also be attaching these checksums to each zip that we upload, as metadata.
>
>Why as files in a druid tree? Because we can send it up to AWS super easy, find files we’re looking for with filesystem utilities, and we can always get fancy with it later.

**Comment by ndushay** [comment]
Email update, part 2:

>>From: Naomi Dushay
>>Date: Thursday, January 25, 2018 at 6:22 PM
>>Subject: Questions for next story time
>>
>> ... <snip> ...
>>
>>1. Where to Store Checksums:   
>> ... <snip> ...
>>
>>   (Will it actually be the right choice to pick a ‘temporary’ storage that may be long lived vs. coming up with the minimum TCR we possibly can?)
>>  - …
>
>From: Julian Morley 
>Date: Thursday, January 25, 2018 at 9:08 PM
>
>... <snip> ...
>Yes. I really, really, really want us to just get critical path functionality working here, and I know for sure that we can easily loop back on this later, and that it’d be another few days or week+ of work to create a TCR (even a MVP) and get it working. We truly don’t need that. Just talking about how we’ll talk to it, what sort of tests it needs, where it’ll run… ugh. -1 votes.
>

**Comment by ndushay** [comment]
from Slack:

[1:36 PM]
Naomi Dushay @jmorley so is it the case that at this time, we ONLY will be storing checksums for REPLICATION;   for checksum validation of online Moabs, we will have NO EXTERNALLY STORED checksums/
[1:36 PM]
Julian Morley Yup.
[1:36 PM]
Naomi Dushay i would say if we've encountered no errors on stage or prod as yet, then we can leave stage populated with only the small disks
[1:36 PM]
Julian Morley Checksums of zips only. Not checksums of manifestInventory.xml

**Comment by jmartin-sul** [comment]
we should investigate whether TCR is done enough to make TCR the path of least resistance.  we have a simple schema and rails app which may be close to accommodating our needs, and we may already have at least a stage VM up and running for TCR.

**Comment by jmartin-sul** [comment]
i am going to close this in favor of #673, which points back to the discussion here.
