### ISSUE TITLE
(M2C) Update wiki stats with seed and m2c information

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#506]
- Look on prod through the logs to see what information on seeding we can find. ( Some logs might have been deleted)
- M2C is currently running see if there is any information we can use in the logs. (ran with profiler)

**Comment by ndushay** [comment]
See also #568 -- can we make a chart that is easier to update and that makes it easier to compare stats from diff runs?

**Comment by ndushay** [comment]
Seeding info has been put in https://docs.google.com/spreadsheets/d/1Xvk02asCm75lj5eCOrruhT0i9T8r8kHpUYjoEvLKbqM

**Comment by ndushay** [comment]
M2C stats from prod, given logs available at this time, put in https://docs.google.com/spreadsheets/d/1Xvk02asCm75lj5eCOrruhT0i9T8r8kHpUYjoEvLKbqM
