### ISSUE TITLE
(C2M) Add additional information to the ONLINE_MOAB_DOES_NOT_EXIST error code (blocked by #528)

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#509]
Ask @julianmorley and @blalbrit  to see if there is any preference for what additional information we should send like..... 
~~- endpoint directory - unless it is already in the message prefix~~ done with #555
- preservedcopy version in catalog?
- updated_at or created_at timestamps??

**Comment by ndushay** [comment]
Maybe we should be sending this info for ALL workflow errors

**Comment by ndushay** [comment]
@blalbrit says he would like all of the above info.
