### ISSUE TITLE
(CV) generate checksums for all files in moab

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#518]
This code MIGHT best be located in moab-versioning gem (vs. checksum-validation class in PC).  It is a piece of doing checksum validation for a moab.  If it does not live there, then it is blocked by #511.

Given a moab object:

- glob or otherwise step through each file 
    - generate appropriate checksum (per chosen algorithm) for the file
    - store in a hash? (key: full file path/name relative to moab;  value: the checksum for the file)

Currently thinking we build this structure on demand for the specific hash requested: MD5, SHA-1, or SHA-256.

When we do the comparisons with the manifestInventory.xml file's data for each version (#521), we will likely build the key for the above hash either from `/fileInventory/fileGroup[dataSource]` + `/fileInventory/fileGroup/file/fileSignature/fileInstance[path]`  or perhaps moab-versioning gem will have a handy way to get the info we need with some manifest_inventory objects ...

sample from `manifestInventory.xml` file:

```xml
<fileInventory type="manifests" objectId="druid:bj102hs9687" versionId="2" inventoryDatetime="2013-06-18T19:19:47Z" fileCount="4" byteCount="18646" blockCount="20">
  <fileGroup groupId="manifests" dataSource="/services-disk02/sdr2objects/bj/102/hs/9687/bj102hs9687/v0002/manifests" fileCount="4" byteCount="18646" blockCount="20">
    <file>
      <fileSignature size="5813" md5="ad240598fa89aacc49172c0a518aff1c" sha1="6986954ad36510a0c03e8609a02d3d201bcbb3ec" sha256="037662ca9845706524eb44557ad0ffbc23a09e536d6eaedb02f64b72781cdabe"/>
      <fileInstance path="fileInventoryDifference.xml" datetime="2013-06-18T19:19:47Z"/>
    </file>
```

**Comment by tallenaz** [comment]
```ruby
sigcat_path = "spec/fixtures/storage_root01/moab_storage_trunk/bj/102/hs/9687/bj102hs9687/v0001/manifests/signatureCatalog.xml"
sigcat_file = File.open(sigcat_path)
Moab::SignatureCatalog.parse(sigcat_file.read)
```

**Comment by jmartin-sul** [comment]
see also #521 and #522
