### ISSUE TITLE
(C2M) *IFF* we need to do ReST call, then migrate code to app/services

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#523]
*IF* there is a need for C2M to be called by druid, then `lib/audit/catalog_to_moab.check_catalog_version` method should be migrated.

In other words, just that method, and whatever it needs, would probably go in `app/services/catalog_to_moab` or `app/services/preservation_copy_service` or some such class.

**Comment by atz** [comment]
already under `app/lib` now
