### ISSUE TITLE
(C2M) add order clause in find_each loop of SQL query

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#537]
Copied from #519 

"one slightly annoying thing i did notice when playing around with this stuff in the console:
```ruby
[5] pry(main)> PreservedCopy.by_endpoint_name('fixture_sr1').fixity_check_expired.find_each { |x| p x }
Scoped order is ignored, it's forced to be batch order.
  PreservedCopy Load (1.2ms)  SELECT  "preserved_copies".* FROM "preserved_copies" INNER JOIN "endpoints" ON "endpoints"."id" = "preserved_copies"."endpoint_id" INNER JOIN preserved_objects ON preserved_objects.id = preserved_object_id INNER JOIN preservation_policies ON preservation_policies.id = preserved_objects.preservation_policy_id AND extract(day from (CURRENT_TIMESTAMP - last_checksum_validation)*86400) > fixity_ttl OR last_checksum_validation IS NULL WHERE "endpoints"."endpoint_name" = $1 ORDER BY "preserved_copies"."id" ASC LIMIT $2  [["endpoint_name", "fixture_sr1"], ["LIMIT", 1000]]
#<PreservedCopy id: 1, version: 3, preserved_object_id: 1, endpoint_id: 1, created_at: "2017-12-13 20:19:49", updated_at: "2018-01-29 20:50:44", last_moab_validation: "2017-12-13 20:19:48", last_checksum_validation: nil, size: 2012695, status: "ok", last_version_audit: nil>
#<PreservedCopy id: 2, version: 3, preserved_object_id: 2, endpoint_id: 1, created_at: "2017-12-13 20:19:49", updated_at: "2017-12-13 20:19:49", last_moab_validation: "2017-12-13 20:19:49", last_checksum_validation: nil, size: 277588, status: "ok", last_version_audit: nil>
#<PreservedCopy id: 3, version: 2, preserved_object_id: 3, endpoint_id: 1, created_at: "2017-12-13 20:19:49", updated_at: "2017-12-13 20:19:49", last_moab_validation: "2017-12-13 20:19:49", last_checksum_validation: nil, size: 6570668, status: "ok", last_version_audit: nil>
=> nil
```

which indicates to me that we might want to move the ordering clause to the `find_each`, or have it in both places since some callers of the scope might want it, or something.  would be happy to ticket that consideration as follow on work.  doesn't seem essential to getting this PR merged.

* an ActiveRecord relation represents a query that can be run, but constructing it doesn't automatically run the query -- the query only gets run when the result set needs to be retrieved, e.g. when invoking something like `#find_each`, `#first`, `#all`, or `#count` on the relation)."

**Comment by ndushay** [comment]
hahahah - good luck with THIS, @tallenaz !

Actually, this ticket has morphed, because we cannot do an ordering on `fine_each` or `in_batches`.   So instead, we will:
- use the SQL scope (@azanella will write a TEST to ensure that ordering is respected in the results returned from the scope)
- use limit explicitly to get a reasonable number of records per batch
    - limit will be set in shared_configs, and will likely default to 1000 ?
- use `.each` on the batch to preserve the ordering

Wheee!

**Comment by tallenaz** [comment]
The discussion on #519 indicates the above approach, and once that gets merged, this can be closed.
