### ISSUE TITLE
(C2M) clean up catalog_version < moab_version case in CatalogToMoab#check_catalog_version

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#540]
currently, `CatalogToMoab#check_catalog_version` calls out to `PreservedObjectHandler#update_version_after_validation`:
https://github.com/sul-dlss/preservation_catalog/blob/dc43a2da1cbe65daadb045053955af8b07d8e8cb/lib/audit/catalog_to_moab.rb#L76-L92

but it might be nice to instead call the relevant underlying code directly.  as the name implies, `update_version_after_validation` does moab validation, and if the moab is valid, it calls `#update_online_version` with `OK_STATUS`.  that updates audit timestamps, updates status on the preserved copy, and updates current version, after checking that the version seen on disk is greater than the version in the catalog:
https://github.com/sul-dlss/preservation_catalog/blob/dc43a2da1cbe65daadb045053955af8b07d8e8cb/app/services/preserved_object_handler.rb#L226-L237

but once #526 is merged, `C2M#check_catalog_version` will already be validating the moab on disk and updating the status accordingly, and we already know that the version seen on disk is greater than the version in the catalog.  we'd also cut down on a bit of duplicate logging.  i think the relevant chunk of code to steal from `POH#update_online_version` would be:
```ruby
        pres_copy.upd_audstamps_version_size(ran_moab_validation?, incoming_version, incoming_size)
        pres_copy.save!
        pres_object.current_version = incoming_version
        pres_object.save!
```

this will break one test in catalog_to_moab_instance_spec.rb that just makes sure `POH#update_version_after_validation` gets called.  presumably we'll want to test the expected behavior in place of that test.

we'd also want to add transactionality to C2M if we implemented this ticket (though really we want to do that anyway, see #).

filing this was initially spurred by difficulty testing the situation where `C2M#check_catalog_version` sees a newer version on disk and moab validation fails, but there was actually a nice way to mock the validation failure that we use elsewhere that made that situation easy to test afterall.  still felt worth capturing, since it'd be a slightly more efficient implementation.

definitely not high priority.

**Comment by ndushay** [comment]
@jmartin-sul did this ticket become obsolete with the PR you ultimately submitted for status stuff (#526)?  If so, please close.

**Comment by ndushay** [comment]
@jmartin-sul is this still needed, or can it be closed?
