### ISSUE TITLE
(PC) Trigger a workflow error in prod, to make sure workflow error reporting is working

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#548]
Keep track of an error in a druid on prod so we can make sure workflow is hooked up correctly.
Either C2M or M2C should pick up on this error

**Comment by tallenaz** [comment]
About to run C2M in prod against the following change:

```ruby
[14] pry(main)> wf_test_druid = PreservedObject.find_by(druid: 'zz136kw6853')
=> #<PreservedObject:0x0000000004769e00
 id: 895902,
 druid: "zz136kw6853",
 current_version: 666,
 created_at: Mon, 22 Jan 2018 14:57:28 UTC +00:00,
 updated_at: Mon, 12 Feb 2018 22:11:36 UTC +00:00,
 preservation_policy_id: 1>
[15] pry(main)> wf_test_druid.current_version
=> 666
[16] pry(main)> wf_test_druid.preserved_copies.first.version
=> 3
[17] pry(main)> 
```

**Comment by tallenaz** [comment]
looks like it got skipped in c2m?
```
I, [2018-02-14T17:37:23.162006 #5264]  INFO -- : check_catalog_version(zz242kj3639, services-disk11) actual version (3) matches PreservedCopy db version
I, [2018-02-14T17:37:23.251088 #5264]  INFO -- : check_catalog_version(zz328dm9979, services-disk11) actual version (1) matches PreservedCopy db version
```

**Comment by ndushay** [comment]
what happened in prod?   no logs, no argo error ... huh?????

**Comment by ndushay** [comment]
I can assert we are now reporting errors in production, via running M2C on disk 14!!!

#### errors showing in workflows

![reported-errors-for-wf-in-prod](https://user-images.githubusercontent.com/96775/36456861-eb80e732-165b-11e8-8d3f-4b91d8a354bb.png)

#### Single record

![reported-error-in-prod](https://user-images.githubusercontent.com/96775/36456860-eb69ab62-165b-11e8-9fb8-884e30370286.png)
