### ISSUE TITLE
(CV) fixture data with updated Moab content file

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#553]
We need a publically sharable, small Moab that has a content file that gets updated in a later version.   (We have examples for metadata files and manifest files, but not for *updated* content files).  

We would also like a small, publically shareable Moab with a new content file added to a later version.

the druids will be sufficient for us to do the rest.

**Comment by LynnMcRae** [comment]
Object https://argo.stanford.edu/view/druid:zt762qn7564 had a .tiff replacement in v3 and a word doc added in v5 ... can this one object serve both needs?

**Comment by LynnMcRae** [comment]
Just an added file for this one, in v5 -- https://argo.stanford.edu/view/druid:ch092bc0660

**Comment by LynnMcRae** [comment]
And just a replaced file in v7 -- https://argo.stanford.edu/view/druid:nn063td4500

**Comment by ndushay** [comment]
Lynn, please verify:
- these are public objects (i.e. we could add to git repo)
- they are all in stage

**Comment by LynnMcRae** [comment]
These three files are all accessioned/ingested in stage:

druid:zt762qn7564 - prod store14, test store02, size 466 KB
druid:ch092bc0660 - prod store14, test store02, size 490 KB
druid:nn063td4500 - prod store02, test store02, size 281 MB

**Comment by ndushay** [comment]
Keeping this handy in needs review;  objects will probably be used by #613, #614, #615

**Comment by ndushay** [comment]
closing this ticket;  have linked to it from all relevant tickets.
