### ISSUE TITLE
(CV) trigger CV errors to ensure we like error handling (blocked by CV)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#561]
If specs and/or running on stage does NOT produce errors, change a db / objects as necessary to trigger errors.

Note "if SPECS" -- if we can do it with specs, I'm fine with that.

e.g.
- computed checksum doesn't match
- checksum missing
- can't parse manifest xml
- file is missing from manifest xml
- file is missing from directory

Note:
- ensure errors will be sent to workflows (?  probably can trust auditresults class ...)
- give Ben a headsup if sending bogus errors

**Comment by SaravShah** [comment]
Need to ask Lynn or Ben to intentionally mess up one of the druids

**Comment by ndushay** [comment]
possibly address by running prod on storage root 2

**Comment by ndushay** [comment]
I'm closing this - we've triggered errors in prod, and we have specs for our errors.
