### ISSUE TITLE
(CV) run CV on prod for  root 5-15 for errors and timings

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#564]
As of 2018-04-17, the focus is on running each root in order to get errors.  We also want the timings, but we really really want to do some checksum validation on all those Moabs that have been minding their own business for years.

For each root below:
- run CV on one of the prod boxes
- put the stats into the spreadsheet
- note how many errors (and maybe bring to Ben's attention?)

- [x] root 2 (all 3 checksums)
- [x] root 3 (all 3 checksums)
- [x] root 4
- [x] root 5
- [x] root 6
- [x] root 7
- [x] root 8
- [x] root 9
- [x] root 10
- [x] root 11
- [x] root 12
- [x] root 13
- [x] root 14
- [x] root 15

**Comment by ndushay** [comment]
This can be broken into individual tickets for each root, if that's easier ...

**Comment by SaravShah** [comment]
Google sheets  has been updated as well.
