### ISSUE TITLE
(CV) rename methods in Checksum class to not be so duplicative

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#572]
For example, 
``` 
def self.checksum_validate_disk(last_checked_b4, endpoint, algorithm="MD5")
  end 
```

can be
``` 
def self.validate_disk
 ```

**Comment by ndushay** [comment]
The above approach sounds good.  However, keep in mind that naming is hard and sometimes what makes sense to one is confusing to another.

**Comment by ndushay** [comment]
Marking this high priority, as it is low effort, high value.
