### ISSUE TITLE
add ok_computer to preservation catalog

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#574]
(high priority in that this should happen before we go to prod)

we should probably have some status checks that nagios can look at.  what i can think of to start:
* are the service disks available?
* is postgres available?
* is workflow services available?

bonus stuff:
* figure out something about current audit throughput?  alert if below some threshold?  is that overkill?

**Comment by jmartin-sul** [comment]
see also #569 (i don't think this is a dupe of that, as i imagine there's devops stuff (puppet?) to do for the nagios hookup, as well as ok computer stuff, so nagios has something to look at)

**Comment by tallenaz** [comment]
Thanks! We've got the mounts monitored from elsewhere, and the others are solid suggestions.

**Comment by atz** [comment]
Borrowing from `sul_pub` and other projects, we can check pretty easily to ensure:
- certain tables are non-empty and 
- certain tables have added or updated rows during a defined interval.  

These are more specific than "got database connection".  Can we define what tables we might want to use those queries on?

**Comment by atz** [comment]
I think checking that `endpoints` is non-empty makes sense, for example (otherwise the app is fundamentally misconfigured).  @jmartin-sul: Naomi suggests maybe you would have insight as to what other tables might be worth checking under either condition.

**Comment by jmartin-sul** [comment]
tables to check for non-emptiness:
* `endpoints`
  * `endpoint_types`?  `endpoints` has an FK constraint on it, so `endpoints` entries imply that there are `endpoint_types` entries, so maybe that's unnecessary.
* `preservation_policies` (needed to create pres objects)
* `endpoints_preservation_policies`?  an endpoint should implement one or more preservation policies, according to our model.  but we don't really pay attention to pres policies at the moment, and our first pass might just be that everything is on every endpoint.  (the idea is that an endpoint is associated with one or more pres policies, and that a pres object should have its pres copies replicated to each endpoint associated with the pres object's pres policy -- but our first pass is likely that everything just lives everywhere, essentially hardcoding what we've been thinking of as the "default" pres policy).

i'm tempted to say `preserved_copies`, because the window where the catalog will know of no pres copies should be pretty small, but maybe that's overkill.

re: the thing i said in the issue description about:
> figure out something about current audit throughput? alert if below some threshold? is that overkill?

i think i was imagining an alert if the oldest `last_version_audit`/`last_checksum_validation`/`last_moab_validation` value in the catalog is too old.  but i'm not sure what the threshold is, and i imagine it's pretty different for each of those validations (e.g. `last_version_audit` and `last_moab_validation` should probably be a threshold of days, whereas `last_checksum_validation` might be more like 3 to 6 months).

**Comment by atz** [comment]
Can definitely have different checks.  I'll code up a conservative check for the initial version and we can tune or expand from there.
