### ISSUE TITLE
(C2M) (CV) what is "optimal" batch size?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#577]
in #547:

>running c2m on a bigger root (4) with sql limit at 10,000 took about an hour less than with the limit set at just 1,000

limit (batch size) set to 1,000:  4 hours
set to 10,000:  3 hours

There may be a sweet spot bigger or smaller than 10,000.

Anticipated factors:
- does it matter if we're running CV vs. C2M in terms of batch size?  Or is the "optimal" size the same for both?   
    - if not, we can make distinct config setting for C2M vs CV
- does it matter if there is more processing to do (e.g.  C2M does NOT match version found on disk ...)

**Comment by jmartin-sul** [comment]
N/A now that we've moved to an async queue architecture instead of a synchronous job that iterates over all audit candidates sequentially in batches.
