### ISSUE TITLE
(CV) lib/audit/checksum.rb implement .validate_disk (hook up to checksum_validator)

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#595]
- Checksum.validate_disk need to be coded to  connect to ChecksumValidator class

- "We could put in the timestamp code and so on analogous to M2C / C2M checks now??" - from Naomi

**Comment by jmartin-sul** [comment]
> "We could put in the timestamp code and so on analogous to M2C / C2M checks now??"
  -- @ndushay 

maybe the stdout and log statements that say "started running"/"finished running"?
