### ISSUE TITLE
stats: for each root, get object size data

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#599]
Ideally, we'd like a histogram of object sizes for each root, but the super easy thing is a SQL query that gets the largest object for each root.  Try re-purposing one of the M2C or C2M rails console sql queries for this.

Could even make a new "worksheet" for some stats here:

https://docs.google.com/spreadsheets/d/1Xvk02asCm75lj5eCOrruhT0i9T8r8kHpUYjoEvLKbqM

**Comment by tallenaz** [comment]
```ruby
PreservedCopy.joins(:preserved_object, :endpoint).group('endpoints.storage_location', 'preserved_copies.size').order('endpoints.storage_location asc, preserved_copies.size asc').pluck('endpoints.storage_location, preserved_copies.size')
```

**Comment by tallenaz** [comment]
Added `max size (MB)` row to the google doc and filled it in for each root with values from 

```ruby
Endpoint.joins(:preserved_copies).group(:endpoint_name).order('endpoint_name asc').pluck(:endpoint_name, 'min(preserved_copies.created_at)', 'max(preserved_copies.created_at)', '(max(preserved_copies.created_at)-min(preserved_copies.created_at))', 'count(preserved_copies.id)', 'avg(preserved_copies.version)', 'max(preserved_copies.size)')
```
