### ISSUE TITLE
(PC) notify product owners of deployment to -stage and -prod (blocked by #32)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#6]
One possibility is to set up honeybadger with a slack integration to dlss-infrastructure channel for -stage and -prod deploys ....

obviously, need VMs to deploy to first, so blocked by sul-dlss/preservation2017#35

**Comment by ndushay** [comment]
blocked by #32 (add honeybadger)

**Comment by tallenaz** [comment]
added a slack integration to honeybadger -- it's currently configured to only notify the `dlss-preservation-dev` slack channel only when deploying to stage or prod
