### ISSUE TITLE
(IR) need moab deposit bag with public permissions for validate-bag tests

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#601]
Where can I get a bag of files ready to be deposited in a moab object?
(a bag that will validate)

It would be great if the content files were tiny.

Or maybe I'll just have to grow my own using the moab-versioning bagger class, as does dor-services/lib/dor/services/sdr-ingest-service.rb

------
the first 5 pages of this druid is being used as an example deposit bag in old preservation robot code:  https://argo.stanford.edu/view/druid:jq937jp0017

https://github.com/sul-dlss/sdr-preservation-core/tree/master/spec/fixtures/deposit/jq937jp0017

druid:jq937jp0017 is a google scanned book, which was all that existed when preservation core was first built. It’s public domain and fully viewable via Google Books (https://goo.gl/cCdjjK) so likely not a problem, but maybe not ideal that we put their images out in the git repository. I’ll look for a more modern example of a public object, maybe catch one live in the /export directory.
Google Books
The Poetry of Robert Burns
https://books.google.com/books/content?id=haczAQAAMAAJ&printsec=frontcover&img=1&zoom=1&edge=curl&imgtk=AFLRE73e0rdmurpYzyvuYcYUtz_lmJ_fYVCzx0z3TtKvCPL-2ApQqGYncxL_JQImjT-KJYA7SbxF6z7SONsbP4HWJ62qnZZ-_SB-R_dQxxEHLgTPlyB9zihGgMWgJQjF1K8QIM2QZi2s

Benjamin Albritton [6:41 AM]
@Naomi Dushay - that is Google Books data and is not okay for inclusion in a public github repo. I would recommend anything that is in SDR and licensed as public domain (https://argo.stanford.edu/catalog?all=true&f%5Buse_license_machine_ssi%5D%5B%5D=pdm) or any of the Walters Art Museum objects (https://argo.stanford.edu/catalog?all=true&f%5Bnonhydrus_collection_title_ssim%5D%5B%5D=Walters+Manuscripts)

**Comment by LynnMcRae** [comment]
I assume you want/need a v1 bag for a new Moab, not an update to an existing MOAB

**Comment by ndushay** [comment]
I'll happily take either or one of each.

**Comment by LynnMcRae** [comment]
ok good, that will make it easier to catch a live one midstream. I'm still targeting one with both metadata and content.

**Comment by ndushay** [comment]
I just grabbed cr123dt0367 which is just metadata.  Is this okay?

```xml
<?xml version="1.0"?>
<rightsMetadata>
  <access type="discover">
    <machine>
      <world/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world rule="no-download"/>
    </machine>
  </access>
  <use>
    <human type="useAndReproduction">The materials are open for research use and may be used freely for non-commercial purposes with an attribution. For commercial permission requests, please contact the Stanford University Archives (universityarchives@stanford.edu).</human>
  </use>
  <copyright>
    <human>Copyright (c) The Board of Trustees of the Leland Stanford Junior University. All rights reserved.</human>
  </copyright>
</rightsMetadata>
```

**Comment by ndushay** [comment]
and yes, having some content would also be good.

**Comment by ndushay** [comment]
similarly, xm152jw3650

**Comment by ndushay** [comment]
with the 2 etd example bags (xm152jw3650, hh446py3579) I have content.  Both are version 1.

With some records from Kahn, which are metadata only, I have later versions.

Perhaps this is enough.  I will know more  as I write tests.

What is potentially missing:
- a bag with an UPDATE to a content file

**Comment by LynnMcRae** [comment]
Attached is a zipped up v2 bag for a public maps object, 827 KB, from the SDR /deposit directory, with content being added. This is the form you are looking for?
[yx086st8953.zip](https://github.com/sul-dlss/preservation_catalog/files/1777035/yx086st8953.zip)

**Comment by ndushay** [comment]
I do believe I have what I need.
