### ISSUE TITLE
SPRINT 14 DEMO

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#602]

**Comment by SaravShah** [comment]
### Checksum Validation
- [ ] finish coding CV
- [ ] run on **_STAGE_** (probably only a few roots)
       - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with CV code
        - [ ] perf data in wiki / google chart (#568)
- [ ] deploy to and run on **_PROD_**
    - [ ]  run against all storage roots except first one (old format Moabs)
        - [ ] performance data captured
             - [ ] satisfied with performance
        - [ ] satisfied with CV code
        - [ ] perf data in wiki / google chart (#568)
