### ISSUE TITLE
(CV) do we use file sizes in our fixity checks?  should we?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#603]
does the moab-versioning code that preservation_catalog uses compare file sizes along with checksums when it validates manifestInventory.xml?

in general, when doing manInv and sigCat checksum comparisons, do we also want to verify that file size is the same?  if it's easy to implement, it seems like an inexpensive way to get further peace of mind that a checksum validation is trustworthy.

**Comment by ndushay** [comment]
I'm pretty sure the answer is no - moab-versioning does not use size.  But I would like someone else to confirm this.

**Comment by jmartin-sul** [comment]
turns out size _is_ already used in the moab-versioning fixity comparison code, see #1553 and #1520
