### ISSUE TITLE
(M2C) ensure we have tests for 4 cases of valid moabs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#613]
single version:
- metadata only
- metadata + content

subsequent version:
- metadata only
- metadata + content

If this brings to mind some additional tests for invalid objects, go for it.  (e.g. invalid content in subsequent version)

possible test data inspired by sul-dlss/preservation_catalog#553

**Comment by SaravShah** [comment]
i don't understand this ticket... closing
