### ISSUE TITLE
(CV) code tweaks for running CV on mult roots?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#619]
Do we want to turn off non-CV functionality of preservation_catalog on the instances split off for CV per volume processing?

If yes:
- need to implement feature flags for M2C, C2M
    - especially for ReST calls

If no:
 - so a M2C or C2M check would also be required to be in parallel ...
    - ensure rake task will fire off process(es) on all implicated VMs
    - or possibly we'd just manually fire off / use cron to do in parallel
    - or possibly wire up with capistrano (possibly see SearchWorks or exhibits or stacks capistrano)
           - something about error messages on multiple machines

**Comment by atz** [comment]
I think further clarity is needed for this ticket to be actionable.

**Comment by jmartin-sul** [comment]
closing for now, need to figure out how we're scheduling CV, M2C, C2M in general.  will reopen or recreate when needed
