### ISSUE TITLE
(M2C) Rake task to run single druid

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#623]
- Update README w/ usage info
- Add rake task that allows for druid input

**Comment by ndushay** [comment]
a ReST call would be even better!  (separate ticket?)  See also #339?

**Comment by SaravShah** [comment]
#630 ticket for rest call

**Comment by SaravShah** [comment]
F2F discussion on 3/19/17 No need for rake task w/ M2C
