### ISSUE TITLE
(C2M) Rake task to run single druid

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#624]
- Update README w/ usage info
- Add rake task that allows for druid input

**Comment by ndushay** [comment]
a ReST call would be even better!  (separate ticket?)

**Comment by SaravShah** [comment]
#629

**Comment by atz** [comment]
This is just:
```ruby
Audit::CatalogToMoab.new(complete_moab, storage_dir).check_catalog_version
```
Anybody can do that on the console. `storage_dir` is a `MoabStorageRoot#storage_location` value.

Definitely do NOT need a rake task.  Since the REST call is separately ticketed (twice?), closing this one.
