### ISSUE TITLE
(CV) graph of  object sizes on storage roots

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#626]
Right now we only record the largest object per storage root at https://docs.google.com/spreadsheets/d/1Xvk02asCm75lj5eCOrruhT0i9T8r8kHpUYjoEvLKbqM/edit#gid=1523168050

Can we generate a simple(ish) histogram of the largest, say, 5 objects per storage root?

Or the largest, 100th largest, 200th largest, etc?   

SQL  should be easy if we can sort on size cheaply (or even expensively, i suppose - it's not going to be done often).   Or we can index on size ...

**Comment by ndushay** [comment]
![image](https://user-images.githubusercontent.com/96775/37692477-2694d38a-2c76-11e8-8995-82cbcd37ba1d.png)

is in https://docs.google.com/spreadsheets/d/1Xvk02asCm75lj5eCOrruhT0i9T8r8kHpUYjoEvLKbqM

SQL used is https://github.com/sul-dlss/preservation_catalog/wiki/SQL-queries-for-stats

**Comment by ndushay** [comment]
Better:

![image](https://user-images.githubusercontent.com/96775/37692563-caad1c5c-2c76-11e8-8973-0601fef45943.png)
