### ISSUE TITLE
deploy updated CV code to prod, run on single manually updated druid to see if manual update fixes problem

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/preservation_catalog#636]
For a subset of objects in the repository, v001 of the object predated the use of the versionMetadata datastream. These 554 objects (all ETDs) do not have a versionMetadata.xml file. These objects are currently showing as errors in the auditWF. Even when later versions have been added to these objects with the expected versionMetadata.xml file, the v001 folder is still failing the audit and, therefore, the objects are failing the audit as well.

These objects are not, in fact, in error - at the time they were deposited to SDR2, they were representative of the model.

The list of objects is here: https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=preservationAuditWF%3Apreservation-audit%3Aerror

There are probably several different approaches to getting past this reported error. Whitelisting those objects would be one approach. Loosening the requirement for a must-have for versionMD would be another - changing to should-have. Probably other options as well - this ticket is not prescribing the technical solution.

@SaravShah  - @julianmorley suggested that I tag you on this. Happy to discuss further or clarify in any way needed. Set this as a "bug" because it is reporting errors on legitimate objects - happy to retag if there's a more appropriate way of describing this ticket.

**Comment by SaravShah** [comment]
Keep an eye on zd335yg6884 when we re-run CV on prod.
Expecting no errors. ( VersionMetadata from version 1 was not found on Moab signature catalog version 3.

**Comment by ndushay** [comment]
@blalbrit if you're good with this, you can close this ticket.
