### ISSUE TITLE
(CV) only compute and compare MD5 checksum, not all

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#642]
Given the slooooow performance of doing CV, it seems sensible to only compute and compare a single checksum, not all present for a given file.

@julianmorley will let us know, but I'm guessing we can do either MD5 or sha256 as our single checksum.

**Comment by ndushay** [comment]
should this be configurable?

**Comment by atz** [comment]
@ndushay says make sure to hit both `ManifestInventory` and `SignatureCatalog`

**Comment by jmartin-sul** [comment]
clarification via slack and in person conversation, from @LynnMcRae and @julianmorley:
> Hi, I [Lynn] chatted with Julian and confirmed what I suspected. An MD5-only check is to confirm the integrity of our current data, When actual fixity checking cycles are introduced — the leisurely background check every 6 onths or so —  it should use a minimum of 2 checksums, at this point almost certainly MD5 and SHA256. So a configuration of choices will serve us well going forward.

**Comment by jmartin-sul** [comment]
see also #663
