### ISSUE TITLE
(PC) API Documentation

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#659]
- PC ReST Calls
- possibly use swagger lines
- https://www.sitepoint.com/do-the-right-thing-and-document-your-rails-api-with-swagger/
- https://coderwall.com/p/bjk3pa/documenting-rails-based-rest-api-using-swagger-ui

**Comment by aredshaw** [comment]
Are you using REST APIs? If so, I might be able to help.
I would need to know the base path and endpoints.
Also, a list of possible methods and parameters.
And of course an API Key if one is required.

**Comment by ndushay** [comment]
closing this in favor of #1216
