### ISSUE TITLE
(R) spin up resque/redis infrastructure for archive/replication service

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#665]
do we need separate ones for stage vs prod?   Or do we have stage queues and prod queues on the same instance?

**Comment by tallenaz** [comment]
RITM00040677 submitted to connect the stage worker to storage roots

**Comment by tallenaz** [comment]
- There's a machine available (preservation-worker-stage) ready to deploy to now if needed. 

Side note based on today's discussion about naming machines:

- There are a couple of better named stage machines that are waiting on UIT to hook up to the storage roots. After that they'll need shared_configs updates and a db import. I'm optimistic that we will have these up next week, and then prod machines shortly after.

**Comment by atz** [comment]
Note: on `preservation-robots1-stage.stanford.edu`, an old crontab entry was still present with:
```
... ROBOT_ENVIRONMENT=production bundle exec rake robots:verify ...
```
This conflicted with the otherwise identical entry w/ `ROBOT_ENVIRONMENT=stage` and the jobs would collide trying to write to the same log files.

I deleted the old entry, but it is something to look out for in the future.

**Comment by atz** [comment]
On robots stage, currently 8196 `Redis::CannotConnectError` messages across `sdr_preservationIngestWF_*.log` files.  Presumably those would get resolved when we get actual infrastructure setup.

**Comment by atz** [comment]
Note: in #712, I already take care of adding Redis to our Travis build.

**Comment by tallenaz** [comment]
`preservation-catalog-stage-02` and `prod-03` are set up with redis.
