### ISSUE TITLE
(PC) Should we disable or keep CSRF enabled?

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#667]
- Quick team discussion on whether we can CSRF disabled or enabled in PC
- When i was making a POST Request to `/catalog` w/ the given parameters i was getting blocked w/ this message:
`Can't verify CSRF token authenticity`

**Comment by atz** [comment]
We don't have any HTML/JS pages, right?  I don't think we need to worry about cross-site request forgery with a JSON API, since there literally is no browser involved.

**Comment by SaravShah** [comment]
Yep. So i can disable it then?

**Comment by atz** [comment]
Right.
