### ISSUE TITLE
(R) explicit API for s3 actions?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#674]
Current notion is that there will be an archive service class in pres_cat that will ultimately implement:
- Exists?  (sends druid, version) (returns metadata)
- Upload? (sends file, MD5, etc)  (returns MD5)

not currently critical path (i.e. postpone impl):
- Delete
- Download

**Comment by jmartin-sul** [comment]
has this ticket been superseded by #710, and other more granular tickets?  or is it something different?  or something we should keep open as a higher level umbrella ticket?

**Comment by ndushay** [comment]
I think this ticket is possibly defunct, although I expect there will be some desire for an explicit, documented API to come out of our replication work ...
