### ISSUE TITLE
(R) set up resque to serve as zip creation queue to avoid duplication

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#677]
(Not sure if we need a "stage" redis/resque" instance, or just "stage" queues on the prod instance ...)

There is a way to use a resque extension to do this; we don't need to roll our own write locks or what have you; we can configure a redis queue to be blocking and have the worker's first step be "does this file already exist?"

https://github.com/defunkt/resque-lock

**Comment by atz** [comment]
Treating the question of stage instances/queues as separate, the locking behavior was accomplished in #723.  I recommend splitting out a ticket for stage infrastructure and closing this one.

**Comment by ndushay** [comment]
I'm ok with closing this ticket.  @atz @tallenaz does one of you want to make a new ticket for stage infrastructure?

**Comment by tallenaz** [comment]
#708 is 'Spin up VM's for resque workers' exists. Are there requirements above and beyond that?

**Comment by jmartin-sul** [comment]
since the queues are set up, the locking behavior is set up, the spinning up of VMs is ticketed (done?), and the other implementation details we know of for the various workers are ticketed... i think i'm going to close this.

@atz, @tallenaz, feel free to reopen if this is still useful.
