### ISSUE TITLE
(M2C) (SPC) rake tasks to fire off PC seed and M2C check

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#68]
Allows us to:
- seed the (prod) db
- run it from cron
...

- [ ] actually run the task on storage_root
   - if errors, write separate tickets

**Comment by ndushay** [comment]
consider ways to run it per storage root, and for combos?   Just via settings.yml???

**Comment by jmartin-sul** [comment]
blocked by #183
blocked by #158
blocked by #201

**Comment by jmartin-sul** [comment]
per @ndushay's comment above ("consider ways to run it per storage root, and for combos? Just via settings.yml???"), this might not strictly be blocked by #158, in that we might not always want the rake task to do all the storage roots.  but completing this issue requires at least deciding what we want to do on that front.

all the roots sequentially seems like a fine first pass to me, but we should discuss as a team when it comes time to implement this.
