### ISSUE TITLE
(CV) deploy pres_cat to prod (for single checksum)

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#680]
pres_cat master branch now has code for CV doing a single checksum computation;  we need to deploy master to our prod boxes and start 2 more roots running (one for each prod VM)

**Comment by SaravShah** [comment]
disk02 is currently running on Prod, and disk 03 is currently running on Prod-A

**Comment by SaravShah** [comment]
disk 05 currently running on Prod and disk 06 running on Prod A
