### ISSUE TITLE
Add storage disk 15 to pres VMs / configs

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#684]
This needs to be added:

- [x] puppet - for pres catalog stage (?)
- [x] puppet - pres catalog prod (?)
- [x] puppet - for pres_robots_prod
- [x] shared_configs for pres catalog stage ?
- [x] shared_configs for pres catalog prod ?
- [x] shared_configs for pres_robots_stage
- [x] shared_configs for pres_robots_prod

**Comment by tallenaz** [comment]
All puppet and shared_configs PRs merged and updated on the servers -- we didn't need a shared_configs PR for pres_robots_stage, since it isn't mounting the new disk.
