### ISSUE TITLE
should we use alias, or alias_method?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#686]
this suggests `alias_method`:
https://blog.bigbinary.com/2012/01/08/alias-vs-alias-method.html

but rubocop complains about using `alias_method` in the way we're using `alias` (`Style/Alias: Use alias instead of alias_method in a class body.`).  i'm not sure what the reasoning is and whether we should add an exception for that rule, or if we should do the `alias_method` invocation through a class method as is done in that blog post.  but the argument of the blog post that `alias_method` is more amenable to class extension resonates, since we are using inheritance in this part of the code (the `alias` was to make it easier to factor out some common code).

alternatively, it wouldn't be too hard to normalize the naming even more, thus obviating the need to `alias` in the first place.  maybe that'd be the better option.  all the code that needs the alias is under our control (and in this codebase).

**Comment by jmartin-sul** [comment]
spawned by https://github.com/sul-dlss/preservation_catalog/pull/664#discussion_r182566926

**Comment by atz** [comment]
Doesn't matter as long as either form is used correctly in the given context.
