### ISSUE TITLE
improve tests that are declared by looping over relevant statuses

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#687]
e.g.:
https://github.com/sul-dlss/preservation_catalog/pull/664/files/0313ed6af566a40779434be2ef1f3b96fad1eb48#diff-9026c3558879e082f1d2ec053628c30f

though we have this pattern in a few places.

ideas for improvement, not necessarily mutually exclusive:
* `PreservedCopy` class provides a set of all possible statuses, and then we could just subtract from that set as needed (e.g. `PreservedCopy.all_statuses - PreservedCopy::OK_STATUS` or similar produces the list you care about if you want all the statuses other than OK).
* more use of shared examples (and then do `it_behaves_like` for each status).  this is probably more readable than what we do now (both in the code and in test failures on the console).  it'd also be more reusable as new functionality that should do the same thing gets added (it was a lot easier to do similar tests on `PreservedObjectHandler` code since we already make liberal use of shared specs there, including for status related stuff).

**Comment by jmartin-sul** [comment]
spawned by https://github.com/sul-dlss/preservation_catalog/pull/664#discussion_r182567898

**Comment by jmartin-sul** [comment]
marking this blocked until we discuss the idea as a team and reach some consensus

**Comment by atz** [comment]
Model classes already provide a set of all statuses via the enum, automatically.  See, e.g. 
```ruby
ZippedMoabVersion.statuses
=> {"ok"=>0, "unreplicated"=>1, "archive_not_found"=>2, "invalid_checksum"=>3}
```

Testing every method with every permutation of status seems like an overkill approach.  We do have shared examples and we do test statuses in the places they are important so I would probably close this or ask for better targeting to make it actionable.

Link to example no longer exists, btw.

**Comment by ndushay** [comment]
@jmartin-sul I'm closing this one.  The concept will resurface again if it still matters, probably as a PR.
