### ISSUE TITLE
(CV) Stats Analysis - why did MD5 alone  take longer than all 3 for CV

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#696]
On Stage

Computing MD5, SHA1, and SHA256 for disk 04 took 3 days 20 hours.

Only computing MD5 for disk 04, took 4 days 6 hours.

What happened here?

https://docs.google.com/spreadsheets/d/1Xvk02asCm75lj5eCOrruhT0i9T8r8kHpUYjoEvLKbqM/edit#gid=1062981440

**Comment by ndushay** [comment]
Some theories:
- io contention on nfs mount
- weird network glitches
- cosmic ray

**Comment by SaravShah** [comment]
CV moved to queues now,....shouldnt be a problem
