### ISSUE TITLE
(CV, M2C, C2M) wire up audit checks to queues

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#703]
as a "phase two" improvement, we've discussed an alternate approach to continuously running C2M, M2C, and CV:
- keep the query that determines what to check
- instead of looping over the things to check when the query runs and checking them at that time, just get the list of druids and put them on a queue of things to CV/M2C/C2M check (one queue per type of check).
- wire up the methods that do the auditing as workers that listen to the aforementioned queues (a CV worker class, an M2C worker class, a C2M worker class).

benefits of this switch:
- makes it easier to monitor progress and backlog on these checks.
- keeps you from scheduling a long running rake task on cron:  the cron'ed task would be the query to populate the queue, which should run quickly, and the workers can chip away at the queue as needed.
- makes it easy to have multiple machines doing a given check (e.g. CV) without having to segregate machines to checking specific endpoints (the queue will de-duplicate requests for a given druid, and one worker will pick up a given druid at a time, so the queue should keep multiple workers from working the same druid simultaneously).  so the approach proposed in this ticket is slightly easier to scale than the "rake task does everything" approach.

**Comment by jmartin-sul** [comment]
this is very much a backlog ticket for now.

when we do get to this, the thing to do might be to spawn a ticket for each of the checks to port to the new approach.  port one of the checks, get it working, then port the rest of the checks (seems like that'd give us a pattern to work off of, since they should be fairly similar to one another).

**Comment by ndushay** [comment]
See also #612

**Comment by SaravShah** [comment]
done. all three have been moved to queues
