### ISSUE TITLE
(R) ensure worker VM is only one processing queues

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#704]
We want to ensure that only the worker VM(s) are actually processing queues (not ReST VMs

**Comment by jmartin-sul** [comment]
this may be more fleshed out by both #712 and #708.  without running a rake task to start the workers watching the queue, the VM won't actually do any work against the queue (hence, a box won't do work against the queues by virtue of having the worker code deployed there, if the rake task to start the workers isn't also called).

closing as a dupe.  of course feel free to reopen if i'm wrong about that.
