### ISSUE TITLE
(R) Spin up VM's for resque workers

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#708]
- decide which workers we want to allocate to what VM's
- how many?
- which we want to separate
- Julian had some ideas about different Endpoint delivery workers on different boxes for better bandwidth usage

**Comment by jmartin-sul** [comment]
these will be the VMs that actually run the rake task that makes the resque workers listen to the queues (e.g. `QUEUES=zipmaker,zips_made rake resque:work`, per @atz's comment on the pers slack channel).

**Comment by atz** [comment]
Logically, they would require configuration to talk to the common Resque instance.
