### ISSUE TITLE
(R) AWS Endpoint Delivery Worker

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#710]
- introduce AWS ruby lib
- use same mount or similar mount as Zip Maker to retrieve zip file needed to replicate
- Does Zip file exist on endpoint?
- if no, replicate (aws lib stuff)

- if yes, make sure checksum matches the one you have.

(Make sure we can get whole checksum and not the etag checksum)

- if checksum matches then send a success message
- if checksum does not match then....??????

**Comment by atz** [comment]
Per slack conversation, we agreed to use the conventional AWS environmental variables to configure `aws-sdk-s3`.  

Waiting on test credentials from @julianmorley.
