### ISSUE TITLE
(PC) ReST calls hooked up for CONFIRM_VERSION M2C functionality

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#72]
blocked by #65

- [ ] hook up controller to model method from #65
- [ ] document ReST call per #71
  - endpoint
  - expected args
  - return codes
  - expected output
  - expected side effect

**Comment by ndushay** [comment]
See https://docs.google.com/document/d/1_ejJE0Ve1gEezQWFnqJAsl1FI4rpREW9lSL0ZSbD62U for documentaiton

**Comment by ndushay** [comment]
based on that doc, the args for "update" and "create" would be:
- druid
- latest version
- object size
- storage_root (or archive endpoint)
- calling process (?  inventory|ingest)  ??  less confident here

**Comment by jmartin-sul** [comment]
possibly/tangentially related to #443?

**Comment by jmartin-sul** [comment]
i believe the robots have ReST calls for the create/update functionality they need.  closing this.
