### ISSUE TITLE
(IR) remove objects with druid: prefix in prod

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#722]
created some objects in prod that have a druid name of `druid:xx000xx0000` 
need to remove those prefix 

John: i'm not sure what the exact syntax is for AR and PG (and it's been a while since i've done it in oracle), but it should be pretty easy to search for pres objects that start with the `druid:` prefix, and update them programmatically.... we could even do it as a proper AR migration in a PR, and make it happen by deploying (instead of just going cowboy on the rails console on prod)

**Comment by jmartin-sul** [comment]
* [ ] query to find druids with 'druid:' prefix
* [ ] loop to normalize (prob don't need transaction, just get through what you can?)
* [ ] simple test (create some bad druids, run clean-up, show query returns zero results after cleanup)
* [ ] migration calls normalize method
