### ISSUE TITLE
(PC)  rspec tests are ordered - maybe make them work in random order?

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#724]
when running `be rspec --order random` we get a lot of failed tests.

**Comment by SaravShah** [comment]
i dont think so. i think backlog is fine ?

**Comment by ndushay** [comment]
See also #728

**Comment by atz** [comment]
Random order reveals where tests side-effect each other, which affects the reproducibility and validity of the tests.  For example, renaming a test file (thereby changing it's sort order position) should not spontaneously cause the tests to fail, but order dependence creates just that scenario.  

An author can intentionally construct tests w/ cascading side effects, but they cannot plausibly maintain it is more readable and maintainable than isolated atomic tests.  In particular, it is not helpful to any subsequent author of tests who is now tasked with understanding complex, invisible and inherited state from **unrelated** examples.

**Comment by atz** [comment]
Sometimes `--order=random` still passes, but sometimes it fails with, e.g. `257` errors.   A lot of them are ` WebMock::NetConnectNotAllowedError` when trying to connect to `sul-lyberservices-test.stanford.edu`.   There is intelligence built-in to `rspec` for identifying which minimum set of tests are order-entangled.

**Comment by atz** [comment]
Got it down to `20` with `--order=random --seed=1485`, then let `--bisect` crunch away on it.  It repeatedly runs  smaller and smaller groups of tests (like binary search) until it finds the smallest order dependent entanglement.  

Final output:
```
Bisect complete! Reduced necessary non-failing examples from 765 to 1 in 2 minutes 31.5 seconds.

The minimal reproduction command is:
  rspec ./spec/controllers/catalog_controller_spec.rb[1:1:3:1,1:1:3:2,1:1:4:1,1:1:4:2,1:2:4:1,1:2:4:2,1:2:5:1,1:2:5:2,1:2:6:1,1:2:6:2,1:2:7] ./spec/services/preserved_object_handler_create_spec.rb[1:1:3,1:1:5:1:1,1:1:5:1:2,1:1:5:2,1:2:6:1,1:2:6:2,1:2:6:3:1:1,1:2:6:3:1:2,1:2:6:3:2] ./spec/services/workflow_errors_reporter_spec.rb[1:1:1] --order=random --seed=1485
```

So there it is: 3 things that are side-effecting each other.

**Comment by atz** [comment]
In `workflow_errors_reporter_spec`, the interaction is obvious, because it does:
```ruby
Settings.workflow_services_url = 'https://sul-lyberservices-test.stanford.edu/workflow/'
```
instead of 
```ruby
Allow(Settings).to receive(workflow_services_url).and_return(...)
```
So the assigned value sticks around across examples.

**Comment by atz** [comment]
The numbers are basically levels of nested blocks.  `1:1:3` is "First describe/context's First describe subblock's Third example"
