### ISSUE TITLE
Remove large fixture objects from git repo history

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#74]
The upload speed from home is killing me.  

Now that Lynn found us some wonderful small objects, I want us to purge the beasts from our git repo and its history.

This explains how -- we're not removing sensitive data but we will be removing data from non-recent commits, so it applies
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by ndushay** [comment]
https://rtyley.github.io/bfg-repo-cleaner/

**Comment by atz** [comment]
Doesn't seem like this is a problem currently (e.g. CI is still reasonably fast).  Maybe the purge was already accomplished?
