### ISSUE TITLE
okcomputer/nagios updates for replication, etc.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#758]
We want to be sure okcomputer checks are appropriate for Preservation Catalog as we finish this preservation work cycle.'

See below, but maybe
- queue depth
- errors?
- ???

**Comment by tallenaz** [comment]
The redis profile in puppet automatically spins up a check in nagios for a reasonable threshold of redis memory usage.

**Comment by ndushay** [comment]
that's cool about redis;  wondering if we need any other checks (zip-making transfer drive mounted?  database response to plexer query?  etc.)

**Comment by ndushay** [comment]
a way to monitor/alert on queue depth, errors ...

**Comment by ndushay** [comment]
Note we also want nagios alerts for things that require human attention.
