### ISSUE TITLE
Travis Live S3 tests can collide during highly simultaneous builds

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#777]
### Background:
- The code that tests live S3 integration does a `put` and a `get` of an object to a test bucket.
- The same S3 object (key) is being targeted (to minimize junk sprawl/cost)
- To defend against a stale object still passing the test when `put` is actually failing, a timestamp is put in the metadata, and checked upon retrieval.

### Problem:
If two Travis builds hit the same test time (well, specifically, if the second test `put` hits before the first's `get`, but at a different clock second -- technically could appear "before" because different systems have different clocks), then the test will fail, because the value that was written to the object doesn't match upon retrieval.

### Possible Directions:
- Change granularity of timestamp to, say, hour.  On the whole, CI would still detect if `put` started silently failing (but not immediately).  The frequency of near-simultaneity/collision/failure would be 1/3600th what it is now.  
- **Use different object (key) every time.  To avoid inducing unnecessary costs, we would have to build more assiduous object cleanup or S3 configuration on the bucket to do cleanup automatically.** **<-- this is the chosen solution**
- Finish getting rspec to run in `random` order.  For a fragment of a ~2 second test in a ~4 min run, that would seem to reduce collision likelihood by >120x.
- Limit number of concurrent Travis builds to 1.

**Comment by atz** [comment]
If we can get the bucket to be self-cleaning, that seems like the strongest move (and protects against any other tests we write or operations we perform manually).

**Comment by ndushay** [comment]
endgoal is to have a worm bucket for production (can write but not delete);  so we want the test bucket to be like prod.   

- generate a unique druid for the test (pres team)
- configure test bucket to delete objects after 24 hours (ops)
