### ISSUE TITLE
plan formal handoff of audit and replication monitoring

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#780]
Once pres phase 1 code is nearly complete, there needs to be a formal decision about who will monitor auditing errors and replication errors.

We will also need to figure out which resources are needed to address these errors, and how the resources will be obtained/allocated.

Putting this in a ticket for now, but this is not the complete agenda for handoff -- just a piece of it.

**Comment by jmartin-sul** [comment]
i believe we just had this meeting at 2 this afternoon?  @SaravShah and @tallenaz have some action items (document application/postgres/resque shutdown and restart procedures, add today's slack conversation about replication queries to wiki, postgres archiving approach, etc -- they can hopefully add here or ticket that stuff elsewhere as needed).

**Comment by tallenaz** [comment]
- [x] Update docs on how to shutdown the catalog cleanly
- [ ] Set up postgres backups
- [ ] Put redis on its own machine
- [ ] Tune cores and RAM on worker machines
