### ISSUE TITLE
code for audit checking archive only copies - no moab content

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#781]
that is, the google books use case.  We should have archival copies replicated, but the Moab is either a placeholder with no real content or doesn't exist at all.

These object should not create problems with M2C, C2M, CV, etc.

Thinking is that there a valid moab, but the only content (if any) is a name-as-text file or some such.

Julian says:  M2C check should make sure the archived copies mentioned in the stub ... actually exist ... in this case.   This is a form of an archival copy to catalog validation.

(more discussion is warranted, to be sure)

**Comment by atz** [comment]
We generally agree that we aren't actually talking about M2C itself necessary, just some regular check that includes these objects.

**Comment by ndushay** [comment]
I'm closing this - I don't think we encounter this case (it hasn't come up in 4 years) and it's not worth keeping this ticket open and having to backlog groom it over and over.
