### ISSUE TITLE
(R) who/what should be notified of a druid's replication results?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#785]
We need to know 
- who is likely to want to know
- how they want this info (e.g. in argo?  email?  interpretive dance?)
-  which consumers to hook up to pub-sub results queue

We need to create a pub/sub queue, potentially, depending on whether there will be actual consumers.  (note:  redis is not a good choice for pub/sub queue)

**Comment by atz** [comment]
Currently, nobody outside the application itself is involved, pub/sub queue is not (yet) required.  We intentionally punted interfacing from Argo out of scope.  

If we get to the point of doing some aggregate reporting, it would be based on DB queries (around `preserved_copies`).  No need to do any work on that now.
