### ISSUE TITLE
(R) store zip's MD5 & create info in pres_cat db

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#787]
The zips have MD5 checksum, which needs to be stored in the db (just merged a PR with this change to schema).  How the zip is created needs to be documented;  in the db it is "create info";  we also send it as metadata in the S3 call.

Zipmaker can pass checksum to other workers, but eventually one of them needs to store the checksums.

Plexer is our choice of worker to write MD5 & create-info b/c:
- it's already talking to db
- it's not resource intensive (not making zip, not sending zip across network)

Create Info:  what do we need?  (question for storytime!)
JSON:
- actually command sent to shell
- OS version
- zip version
- zip compilation info
- VM / system info
- size (in which case, #800 may be a dupe of this)

**Comment by atz** [comment]
From storytime meeting, we only need:
- zip command and 
- 1-liner representation of zip version (no compilation flags, OPTS, or sysinfo)
- size

Related question: determine size limits on S3 metadata field.

**Comment by atz** [comment]
Depends on #707
