### ISSUE TITLE
update DB schema diagram

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#792]
schema's in flux for a bit, so we might want to wait till things settle before doing this, so we're not churning unnecessarily.

see also #772 & #759

**Comment by jmartin-sul** [comment]
document the difference between storage roots and archive endpoints, per #888 (which is closed due to inacuracy, now that the data model has been refactored and storage roots are represented by a different class/table than archive endpoints).

**Comment by SaravShah** [comment]
Started working on in the db/README about the Key
