### ISSUE TITLE
drop PreservedCopy#update_status method

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#801]
due to some other refactoring, there's now only one place in the code that calls `PreservedCopy#update_status`:
https://github.com/sul-dlss/preservation_catalog/blob/1863f60b6727da9589755452fe7561aa23ce2fde/app/services/moab_validation_handler.rb#L53-L59

and `PreservedCopy#update_status` does a combo of things we no longer fully take advantage of:  it only updates the status and runs the block if the incoming status is actually different:
https://github.com/sul-dlss/preservation_catalog/blob/1863f60b6727da9589755452fe7561aa23ce2fde/app/models/preserved_copy.rb#L82-L86

it used to be that we'd ask if the object was `.changed?` in `PreservedObjectHandler`, and we'd add an AuditResult just for that.  and we didn't want to trigger that when setting the status hadn't actually changed the value (but was set blindly because that was the simplest way to write the code).  even with that check, we found that result code too noisy, so we ditched it.  thus, we should also be able to drop this expectation from the couple places that ask about `changed?`, since that's only done in the specs now:
https://github.com/sul-dlss/preservation_catalog/blob/1863f60b6727da9589755452fe7561aa23ce2fde/spec/models/preserved_copy_spec.rb#L171-L185

and then `MoabValidationHandler#update_status` could be modified to `results.add_result(AuditResults::PC_STATUS_CHANGED, ...) if preserved_copy.status_changed?` (after setting).  or it could become:
```ruby
return unless new_status != preserved_copy.status
preserved_copy.status = new_status
results.add_result(AuditResults::PC_STATUS_CHANGED ...)
```

whatever actually gets us the desired behavior of only adding that result code if the status is different.

**Comment by atz** [comment]
The only `update_status` method currently is a different one on `MoabValidationHandler`.  Closing.
