### ISSUE TITLE
if we keep the EndpointType model, we should make its endpoint_class field an int enum

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#805]
currently it uses a string, which is slightly unconventional, and not officially supported (though it is tested in rails 5, and works for now).

the steps to turn it into an int are:
* migration
  * create shadow col in DB (`endpoint_class_string` as a `string` type)
  * copy current `enpoint_class` value to `endpoint_class_string`
  * drop the old `endpoint_class` col
  * recreate `endpoint_class` as an `int` col
  * populate `endpoint_class` with integer translation of `endpoint_class_string`, e.g. `1` for `'online'` and `2` for `'archive'`
  * give 'endpoint_class' non-null constraint, index as unique
  * drop `endpoint_class_string` col
* app & spec code
  * update the `EndpointType` model code so that lists the new int values as the `enum` translations.
  * make its specs look more like e.g. the `PreservedCopy#status` specs, since that is a more conventional int field.

ALTERNATIVELY:  we might consider dropping the `EndpointType` model and table entirely, and just make `endpoint_type` an enum on `Endpoint`.  we should decide once and for all (or at least fairly indefinitely) whether or not to do that, since we should do one of the other, so as not to waste too much effort.

either way, we can punt on this for a while, `EndpointType` as a separate table with a string `endpoint_class` enum isn't killing us, it's just a rough edge.

**Comment by ndushay** [comment]
isn't this done?  And *was* there a migration written?  I do not recall.

**Comment by jmartin-sul** [comment]
it is currently a string enum, because that was easier to implement (there was a migration in that PR, but it was just to add some indexes:  https://github.com/sul-dlss/preservation_catalog/pull/804/files#diff-871ef1341c249026cae9cc3f296b0448

not high priority, because it works in rails 5, and is tested.  but rails, for whatever reason, doesn't want to officially support non-integer enums, so it's slightly precarious in the long term to keep the string enums.

https://bibwild.wordpress.com/2016/09/06/rails5-and-earlier-activerecordenum-supports-strings-in-db/
https://github.com/sul-dlss/preservation_catalog/blob/926030fd2a95631834f439f7234023b3fff5ad74/app/models/endpoint_type.rb#L4-L10

**Comment by jmartin-sul** [comment]
`EndpointType` is gone, so this is obsolete (see #954)
