### ISSUE TITLE
(C2A) audit check(s) for replicated objects; does replicated object exist? and match the MD5?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#813]
probably will spawn mult tickets:

- for each archival pres_copy in the catalog, does the replicated object exist?  (also match the MD5?)
    - scaffolding described below
    - aws call would live with the worker

**Comment by SaravShah** [comment]
discussed in story time (https://docs.google.com/document/d/10HMhTMWlZaM1DJChFr2r3coOVDZKe0EDAH8PPumb-2E/edit#heading=h.67jvdjt99u6g)

**Comment by ndushay** [comment]
can we do this with a queue?  please?

**Comment by tallenaz** [comment]
- Worker class
- Perform method
- Stub for where the worker is called
