### ISSUE TITLE
Document Ben/Julian-compatible interface to kickoff replication (ActiveRecord queries etc to queue objects for replication)

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#820]
We will need to confirm capabilities for manually starting replication for a given druid/version (separate from the bulk jobs)

If using the `rails console` is sufficient, this boils down to:
```ruby
ZipmakerJob.perform_now(druid, version)
```
In that case, just document usage in README (or wiki, whatever).  Otherwise, write some kind of wrapper rake task and document that.

**Comment by atz** [comment]
@ndushay IMO, literally not blocked by anything, since this is an interface/documentation ticket.  Even if we are unhappy w/ preservation execution behavior, it is perfectly fine to document what our interface is (or should be).

**Comment by ndushay** [comment]
what I meant was we might as well wait to document it until after we're sure we've got the kinks worked out with some smoke tests, etc.

**Comment by atz** [comment]
We've since established he prefers to use console over rake tasks, so I consider this something we could document now.  No new rake task is needed.

I might pursue one refinement, specifically adding a `PreservedCopy#preserve!` convenience method that invokes `ZipmakerJob` as above. It would be trivial to implement, but equally trivial to update the docs if they are written against the code we have now.

**Comment by ndushay** [comment]
could be github wiki pages that Repo Admin and Devops Ops Concerns docs can refer to...
- how to run various checks on single druid
- what to do for certain errors
- how to see if system looks ok  (e.g queue health, object health, robot health)
- ...

**Comment by jmartin-sul** [comment]
paired w/ @jermnelson, first pass at the AR code for replicating, per @julianmorley's request in slack:
> sending zipmaker only druids that prescat doesn't think are replicated to us-west-2, limited to druids < 10G, limit 10K druids

```ruby
moab_size_limit = 10_000_000_000
result_limit = 10_000
CompleteMoab.where.not(
  id: ZipEndpoint.find_by!(endpoint_name: 'aws_s3_west_2').zipped_moab_versions.select(:complete_moab_id)
).where("size < ?", moab_size_limit).limit(result_limit).find_each(&:create_zipped_moab_versions!)
```

**Comment by jmartin-sul** [comment]
further explanation: the `create_zipped_moab_versions!` call in the example ruby code above will create the `ZippedMoabVersion` records in the DB that will represent the things we're shipping off to the cloud.  a hook on the `ZippedMoabVersion` model will then initiate the replication process by invoking the zip maker job.

**Comment by jmartin-sul** [comment]
did a bit of testing just now, and saw it queue for replication as expected (with a `result_limit` of one, so just a single moab at a time).
