### ISSUE TITLE
rake task to run list of druids through audit checks

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#821]
We want to be able to run a list of druids through audit checks - firing off a rake task manually for 80 or 400 druids is no fun.

- [x] m2c
- [x] cv

**Comment by ndushay** [comment]
Also, talk to ben - consider if there should be a piece of this that clears the workflows error so it no longer appears in argo.  (Could be a separate ticket.)

**Comment by SaravShah** [comment]
created #827 per Naomi's comment above.
