### ISSUE TITLE
we can probably easily provide ReST calls to replace sdr-services-app

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#826]
Note:   if assessing this takes more than 1 hour, stop.

is argo the only consumer of this (via dor-services-app)?  what else (if anything) do we actually use this for?

we know for sure that argo asks preservation for the current version of a moab, so that it can determine the next version number to use when opening a new version (via ReST call to dor-services-app, via ReST call to sdr-services-app).

if we decide to put this functionality in preservation_catalog, we should instantiate a moab-versioning object and use it to ask for the current version on disk (or run M2C on the druid to make sure the catalog is up to date).  either way, since we expect there to be situations where the catalog lags the state of the disk (e.g. dropped requests from ingest robots), we should use the state of the disk, and not the contents of the catalog, since this particular request requires an accurate response.

**Comment by jmartin-sul** [comment]
additional motivation for doing this:  besides possibly simplifying things and retiring old code, sdr-services-app currently runs on physical hardware which ops would like to decommission.

**Comment by jmartin-sul** [comment]
this ticket is for investigation.  should be timeboxed to an hour or two?  and then maybe we can spawn new tickets as needed if we decide to move forward.

**Comment by ndushay** [comment]
This app seems to be providing a web-service to get information from Moabs.  I see no reason why we couldn't add the actually used ReST calls to preservation_catalog to replace sdr-services.

In typical indirection and conflation of services, dor-services gem has `lib/dor/utils/sdr_client.rb` which has methods:

- `get_content_diff`: receives a fileInventoryDifferences report between POSTed contentMetadata and that in the specified version (could be subset of files:  all|preserve|publish|shelve) -- calculated with moab-versioning gem
      - this one is *definitely used* -- see below for `cm-inv-diff`
- `current_version`: returns the current version from a Moab via moab-versioning gem
- `get_sdr_metadata`: retrieves specified "metadata" file from the Moab via moab-versioning gem
- `get_signature_catalog`: retrieves the latest signatureCatalog.xml from the Moab via moab-versioning gem
- `get_preserved_file_content`: retrieves a specific content file from a particular version of the Moab via moab-versioning gem
   
The above are a subset of the ReST API exposed by sdr-services-app ... but I'm not even sure if we are using all of the above.



- `cm-inv-diff` used by (https://github.com/search?q=org%3Asul-dlss+%22cm-inv-diff%22&type=Code)
    - dor-services-app (routes and sdr-controller) (sul-dlss/dor-services-app/blob/master/app/controllers/sdr_controller.rb#L2-L18, sul-dlss/dor-services-app/blob/master/config/routes.rb#L8)
    - dor-services (Sdr::Client.get_content_diff  (sul-dlss/dor-services/blob/master/lib/dor/utils/sdr_client.rb#L37-L48) ... used by
        - dor_services
            - itemizable (from SDR3 research:)
                - Flag file for passing to Stacks if the File has changed & should be released
                - Flag file for passing to Preservation if the File has changed & should be preserved
            - shelvable (from SDR3 research:)
                 - Move to stacks after checking rights, access, and if file differences exist
            - technical_metadata_service.get_content_diff
            - manual_integration.rb

**Comment by ndushay** [comment]
note that dor-services sdr::client is only used per above.  (https://github.com/search?q=org%3Asul-dlss+%22sdr%3A%3Aclient%22&type=Code)

**Comment by ndushay** [comment]
- what is using sdr-services-app directly?
- what is using sdr-controller routes in dor-services-app?

**Comment by julianmorley** [comment]
This is an awesome ticket. Per today's retro, this would be a good task for a future maintenance cycle - to create a stand-alone 'Moab Versioning' API service.

**Comment by ndushay** [comment]
closing this.  See https://github.com/sul-dlss/sdr-services-app/issues/37
