### ISSUE TITLE
(PC) When status is changed to OK_STATUS set preservationAuditWF to "completed"

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#827]
- Once we change a preserved_copy status to `OK_STATUS`, we need to remove the preservationAuditWF error. 
- So, clear the workflows error so it no longer appears in argo

**Comment by SaravShah** [comment]
Make sure once this is coded that it is hooked up to the rake tasks.  (Naomi is pretty fuzzy right now ... so would putting it in the code as John suggests above just cover everything for us?)

**Comment by SaravShah** [comment]
Change to `OK_STATUS` happens in `MoabValidationhandler`

**Comment by ndushay** [comment]
ensure that pohandler create, update;  m2c, c2m, and cv all reset workflow step to completed when we reset to ok.
