### ISSUE TITLE
Cut production S3 credentials

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#831]
We need the following credentials (AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY), in priority order:
- us-west-2 PROD
- us-east-1 TEST
- us-east-1 PROD

**Comment by atz** [comment]
Note: we need to retain these creds in some place accessible to devs (e.g. puppet or shared_configs).

**Comment by tallenaz** [comment]
@julianmorley I'm happy to cut these credentials, but don't know how. Can you provide some documentation?

**Comment by julianmorley** [comment]
prod credentials have been placed on prod-01; see slack channel for details.

**Comment by atz** [comment]
Still need test credentials

**Comment by julianmorley** [comment]
test creds and bucket for us-east-1 cut. See Slack for more details.
