### ISSUE TITLE
should C2M and M2C (and CV?) write to their own logs, not Rails log?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#858]
Basically - do we want to have to grep out the results of C2M, M2C and CV checks from the Rails production.log or do we want these messages in logs specific to those jobs?

The logs, as they stand, are merely the output from the rake tasks.   Should they at least be renamed if we're going to keep them like that?  See #857

**Comment by atz** [comment]
To implement this, we would just replace the class-level delegation of the logger with a method supplying a class-specific `Logger`

**Comment by atz** [comment]
If we move C2M and M2C to queues, this problem is essentially obviated.

**Comment by ndushay** [comment]
We currently write audit results to rails log, regardless of whether they are called from queue or rake task:

https://github.com/sul-dlss/preservation_catalog/blob/master/app/services/audit_results.rb#L124

And I'm suggesting that we keep doing this logging, but we do it to a purposed logger for the check being run.

Thus, I'm reopening this, as the individual check for an individual moab/db record will still be writing to a log .. and it will be MUCH better if that is a purposed log for the check rather than the generic rails log.

**Comment by tallenaz** [comment]
Do we want separate logs for each check, for example, a 'check_existence.log' for 'check_existence', etc., or do we want to send reports for this check to a more general log, for example, sending the 'check_existence' and 'confirm_version' results to an `m2c.log`?

**Comment by ndushay** [comment]
I would think separate for each. 

If we were using one log, perhaps "moab-audit.log" would be a better name?  or something generic like that, pertaining to moabs vs replicated copies?
