### ISSUE TITLE
(CV) (rake tasks) to populate CV queue (blocked by #867) (blocked by storytime) - or not due to using queues

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#868]
#867 will allow CV to be run via queue.  This ticket is about the rake task(s) to populate the CV queue.  

repurpose (or base it on) current rake task(s) to run CV:
- for all druids, all volumes
- for single volume
- for list of druids
- for single druid

**Comment by ndushay** [comment]
Not necessarily a rake task if there's a clean way to get it associated with one class (model or other), can use rails runner?

**Comment by SaravShah** [comment]
Check with Julian, and may have to change Fixity TTL
