### ISSUE TITLE
Replace "profile" rake tasks and methods w/ dynamic code

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#869]
We shouldn't have one-off "profile" logic in rake tasks (e.g. shadow tasks or argument triggers), or shadow methods in classes that are "regular_method_profiled".  

We should have a single piece of dynamic code (in `Profiler`) that accepts (optional filename and) block to be profiled.  This satisfies all the methods current and future methods that need to do profiling.

As for the rake tasks that invoke them, we should just use a rake `rule`, aka a dynamic namespace.  `rake my_task_profile` would land on the rule, it parses the name, strips the `_profile` off, and passes a block to the dynamic Profiler described above invoking the base task (w/ the same arguments).  This makes **any** rake task profile-ready and remove a bunch of copy-pasta.

**Comment by atz** [comment]
Note: most of the "profile" code becomes irrelevant if we move the underlying functional role to asynchronous workers.

**Comment by atz** [comment]
C2M moved to async in #1062

**Comment by SaravShah** [comment]
not using profiler anymore
