### ISSUE TITLE
(R) wire things up to create zipped_moab_version entries and kick off the replication

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#886]
see  #812 for different implementation options, #989 for only replicating 'ok' status

upon creating or updating a complete_moab, we should:
* call `PreservedObject#create_archive_preserved_copies` for the version we want to replicate (`PreservedObject` will be instantiated with the relevant druid already).
* call zipmaker worker on the druid/version combo in question.

this presumes that the archive endpoints we want to replicate to have already been added to the DB (see #877).

**Comment by jmartin-sul** [comment]
https://github.com/sul-dlss/preservation_catalog/issues/790#issuecomment-392935734
> For now:
>
>    Internal job checks (C2A) - analogous to C2M, regularly queries for things that should be replicated and makes sure they have been, things that we think have been replicated and makes sure that they’re still out there in good condition.
>     A hook on IngestWorkflow - robot says object has been updated or created, kick off replication (create pres copies and submit event to Zipmaker worker queue)
>
> We don't have other callers/consumers in scope currently.

**Comment by atz** [comment]
#1010 handles the latter bullet point via an `after_create` hook.  That leaves only `create_archive_preserved_copies` to worry about.

**Comment by jmartin-sul** [comment]
i believe this is closed by #1010
