### ISSUE TITLE
(R) Maybe Endpoint#delivery_class enum should be String to int mapping?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#890]
instead of class to int mapping?  the rails magic doesn't work quite as well as we'd like on the class values, so maybe we're not playing within the expected bounds of rails enum machinery?

see:
https://github.com/sul-dlss/preservation_catalog/pull/887#discussion_r195542494
https://github.com/sul-dlss/preservation_catalog/pull/887#discussion_r195583395

@jmartin-sul said:
> i didn't expect [to need] the extra indirection of referring to the enum mapping, but when i just set [delivery_class] equal to `endpoint_config.delivery_class.constantize`, i got this error in the specs:

> ```
> ActiveRecord::StatementInvalid:
>   PG::InvalidTextRepresentation: ERROR:  invalid input syntax for integer: "S3WestDeliveryJob"
>   : INSERT INTO "endpoints" ("endpoint_name", "created_at", "updated_at", "endpoint_node", "storage_location", "endpoint_type_id", "delivery_class") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"
> ```

@atz replied:
> I get the same behavior. Your way is fine. The idea of having actual classes as the enum keys is probably subverting some of the rails internals. Like we definitely can't use the enum to do endpoint.(::S3WestDeliveryJob)! the same way we can do pres_copy.ok!.

> Maybe we should have strings in the enum and a wrapping getter that does the constantize? I think that would make the guts work more conventionally. But not a huge deal to me, since we will only ever be setting this value in one place.

**Comment by ndushay** [comment]
this has been addressed with database refactor
