### ISSUE TITLE
deployment: db_seed should be run after shared configs are updated (blocks #892)

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#891]
trickiness:  the `db_seed` task rightfully runs after the `deploy:migrate` task.  the `shared_configs:update` runs before `deploy:restart`.

but regardless, `db_seed` needs to run on the latest configs.

i would personally not be that bothered by needing to run `db:seed` manually as needed, since shared_configs updates which add new endpoints and such should be rare.  but maybe someone with more capistrano-fu can come up with a way to do this properly and automatically.

**Comment by atz** [comment]
Alternatively, maybe this isn't a good way to control data state.
