### ISSUE TITLE
(R) create archive endpoints on prod

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#892]
Note:  do #891 first.

analogous to #877.   should just require new shared_configs entries, and a deployment (so that shared_configs gets updated and seeding is run, though seeding will have to be run manually after deployment if #891 hasn't been fixed yet).  capturing in preservation_catalog repo instead of shared_configs so that it shows up on our waffle board.

**Comment by tallenaz** [comment]
shared_configs merged and updated on prod
