### ISSUE TITLE
(R) archival pres_copies need to be status ok after replication

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#902]
After we successfully replicated a druid version, checking cia the awscli….the status for the preserved_copy object is still `unreplicated`. Should we turn it to `ok` or `replicated`?

Code probably needs to be added into ResultsRecorder worker?

**Comment by atz** [comment]
Code already exists, already is tested, and does `pc.ok!` on an archive PC, so it is unclear what is considered missing.

**Comment by ndushay** [comment]
When results_recorder worker is running, this works!  Yay!
