### ISSUE TITLE
Monitor Queue Depth/Significant Queue growth

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#906]
Investigate how to do this;  hook up nagios to do it for our prod queues?

**Comment by tallenaz** [comment]
dor-indexing-app has an okcomputer check for queue depth: https://github.com/sul-dlss/dor_indexing_app/blob/master/config/initializers/okcomputer.rb#L39-L41

**Comment by atz** [comment]
that app seems to rely on a queue size URL which is unnecessary for us

**Comment by tallenaz** [comment]
https://stackoverflow.com/questions/11235318/programmatically-get-the-number-of-jobs-in-a-resque-queue

If we can decide on how deep is too deep, we could set up some okcomputer check on that figure.

**Comment by tallenaz** [comment]
https://www.rubydoc.info/gems/okcomputer/0.4.0/OKComputer/ResqueBackedUpCheck

**Comment by tallenaz** [comment]
App code is in. Puppet code is waiting for the queues to be started in prod.

**Comment by tallenaz** [comment]
Right now, we're starting the workers manually. Maybe we want to have capistrano do this? Looks like `capistrano-resque` has the functionality to:

```
set :workers, { "my_queue_name" => 2 } # where 2 is num of workers
```
