### ISSUE TITLE
(R) manually replicate prod object to endpoints and confirm it works

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#910]
Shake the kinks out of any config issues, basically.

**Comment by tallenaz** [comment]
Reminder to myself to document in the wiki how to do this with named profiles once the shakedown is done.

**Comment by tallenaz** [comment]
With `resque-pool` up, the following approach (https://github.com/sul-dlss/preservation_catalog/compare/resque-pool-env?expand=1) works: in the east and west worker perform methods, set ENV['AWS_PROFILE'] and ENV['AWS_BUCKET_NAME'] to the named profile and bucket you need. I'll go ahead and investigate a couple of different approaches and update this comment with the results.

**Comment by tallenaz** [comment]
```
Enqueued ZipmakerJob (Job ID: a28a81b6-ab1c-4537-93d6-c8e8cb8d5147) to Resque(zipmaker) with arguments: "df124xg4452", 5
Enqueued ZipmakerJob (Job ID: ce764183-9728-46fc-b905-d2621cd7181e) to Resque(zipmaker) with arguments: "df129rv7046", 8
Enqueued ZipmakerJob (Job ID: 602fc4c3-6d50-4625-a894-7f94d7820c2c) to Resque(zipmaker) with arguments: "df132kf6273", 7
Enqueued ZipmakerJob (Job ID: 022538ec-7c40-4a8d-ad29-d13cb12848d4) to Resque(zipmaker) with arguments: "df132yv1318", 7
Enqueued ZipmakerJob (Job ID: 0b0e3292-0d4f-498f-a107-0bc0a900be2b) to Resque(zipmaker) with arguments: "df136tz0092", 7
```

All objects replicated successfully to both endpoints.
