### ISSUE TITLE
confirm workflows errors cleared by C2M, M2C

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#912]
basically, we deployed #827 and we want to ensure it works in production:

find some objects with a bad status, run a check for the druid (or disk) and see if the error count in workflows goes down.

**Comment by ndushay** [comment]
Plan is to implement #914, and then run copies with "validity_unknown" on disk 15 through CV.

**Comment by ndushay** [comment]
Note:  this doesn't work for "validity_unknown" from robot creation because those don't have workflow errors -- they are erroneously being set to that status instead of "ok" without any workflow-errors.  (#817 will fix what status the robots assign)

Currently trying to get a workflow error from a C2M check so this can be tested.

**Comment by jmartin-sul** [comment]
a couple updates:
- CV is the check to run, because only it does all the checks (i.e., M2C and C2M can only set status to `validity_unknown`, not `ok`)
- we think this should be implemented, and can be tested by running CV on a single object which currently has a preservation workflow error.

**Comment by SaravShah** [comment]
CV successfully clears the workflow error, if checksums match.
