### ISSUE TITLE
Split PC models for online and archive

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#927]
Our uses and expectations for "online" and "archive" `PreservedCopy` records have diverged and introduced query complexity where we typically only want one kind or the other.  We should migrate to having different models for each.

General consensus:
- Create new model (like `ArchivePreservedCopy`) for archive PCs
- Migrate any archive data out of `preserved_copies` to the new table
- Rename `PreservedCopy` model (and table) to something like `MoabPreservedCopy` for online
- Tailor models to each case (e.g. validations, replication triggers)

Design considerations:
- In the new `ArchivePreservedCopy`, should it `belongs_to :moab_preserved_copy` rather than the PO directly?  That seems to match our process for creating the rows and our query logic based on online PC timestamps.
- Do we want to split the `Endpoint` model similarly for online/archive types also?  Separation would make strict validation very easy, and misaligning data (online PC getting an archive endpoint) impossible.  I don't think that there is much commonality between a locally mounted network disk and a remote host we pay thousands of dollars to implement a given protocol, authentication, etc.

**Comment by jmartin-sul** [comment]
can also maybe get rid of `Endpoint` `#to_h`and `#to_s` and use the defaults?

other decisions after talking F2F w/ @atz:
* `MoabPreservedCopy` will replace `PreservedCopy` and will still belong to `PreservedObject`. 
  * each `ArchivePreservedCopy` instance will belong to the `MoabPreservedCopy` instance which triggered its creation.
    * each `ArchivePreservedCopy` will have 1 or more `ArchivePreservedCopyPart` objects.  each `Part` represents a chunk of a zip archive for a particular druid version living on a specific cloud endpoint.  this is because we split archive zips into 10 GB chunks.
      * maybe the checksums can live on the parts instead of in their own table?  or at least reference the parts?

**Comment by atz** [comment]
Right, I think `zip_checksums` **must** `belong_to` the parts

**Comment by atz** [comment]
Different constraints:
- MPC unique by druid, i.e. PO (?)
- APC unique by druid/version/endpoint.  Whichever model APC belongs_to (APC or PO) is the stand-in for druid in terms of DB uniqueness.
