### ISSUE TITLE
Process Monitoring (resque, redis, ??)

### ISSUE THREAD

**Issue by atz** [sul-dlss/preservation_catalog#934]
Establish process monitoring for resque and redis, using a tool like eye, god, runit, monit, etc.

This is not about application performance or errors, it is just about ensuring necessary components are up.

**Comment by tallenaz** [comment]
The worker machines have an init.d script that will bring them up on reboot. Remaining tasks here:

- [ ] set up the desired resque-pool config in shared_configs
- [ ] add okcomputer check for whether resque is up
- [ ] modify docs since we don't have to kick off workers manually anymore
