### ISSUE TITLE
(R) metadata - is there a better way to consolidate documentation?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#961]
Currently metadata has 6 possible fields;  4 are required;  the only documentation about this, besides code, is in yard doc.  That yard doc is in at least 2 places -- application_job and plexer_job.  

Does it make sense to document this in only one place?  Does it make sense to indicate required params (as yard only allows "@option")?

Are we getting to the point of using a class instead of a hash for the arg, where the class is based on Hash, with an enum list of keys and required keys?   This would allow us to encapsulate the documentation in one place.

**Comment by ndushay** [comment]
@atz says, in not quite exactly related context:

>No, you can always refer from one piece of yard to another rather than copy it, like:
```ruby
@see OtherClass#method
```
>And you cannot pass an arbitrary class as an argument to a Job, because it has to have >serialization and deserialization built in (since that is what allows asynchronicity), so the >proposed class is incompatible with the required use.

**Comment by atz** [comment]
Closing as not requiring further action.
