### ISSUE TITLE
(R) refactor:  arg helper methods instead of, e.g.  job.arguments.fourth

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#962]
code currently has this, for example:
in PlexerJob:
```
before_enqueue { |job| job.zip_info_check!(job.arguments.fourth)
```

But knowing that the fourth arg is "metadata" is a bit magical, as is knowing what we are passing to zip_info_check (not readily apparent from above).  So in job classes that use position in this way, we can add well named helper methods to clarify:

```ruby
def metadata_arg(args)
  args.fourth
end
```

Note that we're not sure if this could just be:

```ruby
def metadata_arg
    job.arguments.fourth
end
```

Note:  look through all the job classes for this pattern (job.arguments.second;  job.arguments.xxx)

**Comment by jmartin-sul** [comment]
reopening in light of @ndushay's comment https://github.com/sul-dlss/preservation_catalog/pull/995#issuecomment-405724493

**Comment by SaravShah** [comment]
thanks john!

**Comment by atz** [comment]
As I commented in the original PR where this was raised, this idea is misguided based on the timing of serialization/deserialization and what is available to a given callback.  The only way to accomplish it is through the misdirection of handing a method *all* the arguments and having it return, one as in #995 (IMO, introducing more code surface to be tested and not improving clarity at all).  

Recommend ticket should be closed.

**Comment by atz** [comment]
To be clear, `job.arguments.first` (*et al.*) is literally the style used by `ActiveJob` documentation of their callbacks:
https://api.rubyonrails.org/classes/ActiveJob/Callbacks/ClassMethods.html#method-i-before_perform

So it is highly conventional to find code like that in the wild (or in our other projects).  I can go into detail about the constraints that contribute to that usage (note: specific to callbacks in jobs), but the main this is that it is commonplace and should be expected.
