### ISSUE TITLE
(R) plexer job skipped spec

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#963]
Write this one:

```ruby
    it 'ensures archive_preserved_copy_part exists with status unreplicated before queueing for delivery' do
      skip('need test for ensuring part exists with status unreplicated')
    end
```

Note that the test following "adds ArchivedPreeservedCopyPart ..." is somewhat related.

**Comment by SaravShah** [comment]
don't need to test zip_part status here because the delivery worker never touches the database. It does not care what the status of the zip_part is.
