### ISSUE TITLE
(R) get rid of ZipChecksum model/zip_checksums table

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#970]
i believe this has been superseded by `ArchivePreservedCopyPart`, which has checksum info?  if so, zip_checksums is now obsolete/confusing.

**Comment by tallenaz** [comment]
This looks fairly straightforward -- the only other place zip_checksums are called that I find is in `ReplicatedFileCheckJob`, and it is possible to get at checksums there through the new class.
