### ISSUE TITLE
(C2A) refactor and incorporate archived_preserved_copies and parts

### ISSUE THREAD

**Issue by SaravShah** [sul-dlss/preservation_catalog#973]
Currently using old db/schema.rb dealing with only preserved_copies. Need to refactor to use archive preserved copies and copy_parts

**Comment by tallenaz** [comment]
From #974: "The hitch is that zip_checksums were used by ReplicatedFileCheckJob#stored_checksums. We can now get at the stored checksums for a "complete moab" (formerly PreservedCopy) via the archived_preserved_copies and their subsequent parts. However, the spec for stored_checksums is throwing a false positive."
