### ISSUE TITLE
can we do bounds-checking in the ArchiveEndpoint.which_need_archive_copy scope?

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#983]
per this review comment i left on the #958:
> @SaravShah had suggested trying to work some bounds checking into the query, so that it doesn't return results for versions greater than the current version of the preserved object. i'd like to try to do that, but it's not immediately clear to me what the query would be, so i have a slight preference for getting [PR #958] merged and trying to do that as follow-on work.
>
> if we did do that bounds checking in [the] query, it might or might not obviate the need for it in `PreservedCopy#create_archive_preserved_copies!`... i still sorta like the idea of failing noisily if an out of bounds version is given to that method, but i don't feel super-strongly about that.

**Comment by atz** [comment]
@jmartin-sul is this actionable?  not sure that it is salient anymore
