### ISSUE TITLE
(R) only replicate CompleteMoab if status is ok

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#989]
so `invalid_moab`, `invalid_checksum`, `validity_unknown`, and `unexpected_version_on_storage` moabs should *NOT* be replicated to cloud endpoints.  they should be remediated and set to `ok` before being allowed to replicate.

**Comment by atz** [comment]
Is this a fair piece of logic in PC/CompleteMoab:
```ruby
  def replicatable?
    persisted? && valid? && %w[ok unreplicated replicated_copy_not_found].include?(status)
  end
```
