### ISSUE TITLE
pohandler: extract method for ternary operator status

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/preservation_catalog#991]
This code:

```
new_status = (checksums_validated ? PreservedCopy::OK_STATUS : PreservedCopy::VALIDITY_UNKNOWN_STATUS)
```

is repeated a few times in pohandler.  Can it be extracted to a method with a clarifying name?  Something like

```
def new_status(checksums_validated)
   checksums_validated ? PreservedCopy::OK_STATUS : PreservedCopy::VALIDITY_UNKNOWN_STATUS
end
```

and would it make the code easier to understand and/or easier to maintain to do so?

**Comment by atz** [comment]
Doesn't seem like any payoff since the decisive part is the boolean being passed in.
