### ISSUE TITLE
correct zip command parameter

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/preservation_catalog#992]
command is `zip -vr0X -sv -s 10g /sdr-transfers/bb/827/rw/7443/bb827rw7443.v0001.zip bb827rw7443/v0001` but the last parameter needs to be the full `services-disk11/sdr2objects/.....` path. This shows up, for example, in the worker metadata like so

```
I, [2018-07-16T15:38:41.192627 #26900]  INFO -- : [ActiveJob] [PlexerJob] [2d3f685d-d6d6-4381-af99-3f2a444e0de9] Performing PlexerJob (Job ID: 2d3f685d-d6d6-4381-af99-3f2a444e0de9) from Resque(zips_made) with arguments: "bb827rw7443", 2, "bb/827/rw/7443/bb827rw7443.v0002.zip", {:checksum_md5=>"7932510ad46105520f6c5626fc252cfc", :size=>60808, :parts_count=>1, :zip_cmd=>"zip -vr0X -sv -s 64k /sdr-transfers/bb/827/rw/7443/bb827rw7443.v0002.zip bb827rw7443/v0002", :zip_version=>"Zip 3.0 (July 5th 2008)"}

```

note `:zip_cmd`

**Comment by atz** [comment]
This issue seems confused.  It doesn't need to be the full path ever, and different machines can have the zip transfers directory mounted in different ways, so including the full path introduces conflict.

**Comment by atz** [comment]
What is the motivation here?

**Comment by SaravShah** [comment]
We tried to replicate a 30gb object in parts, and everytime the object would replicate in 1 part. The zip wouldn't split unless we provided the full path.

**Comment by atz** [comment]
That behavior doesn't seem to be related to path.  If `zip` can write one file to the relative path, it can write many.  The size option for chunking is `-s 10g` or `-s 64k` in your latter example.

**Comment by SaravShah** [comment]
Working as expected.
